monitoring_services::PduMonitor
using monitoring_services::PduMonitor::string = std::string
using monitoring_services::PduMonitor::PeriodicCall = perfect_timing::PeriodicCall
using monitoring_services::PduMonitor::Timeout = perfect_timing::Timeout
using monitoring_services::PduMonitor::Logger = ara::log::Logger
using monitoring_services::PduMonitor::RefWrap = std::reference_wrapper<PduMonitor>
std::unique_ptr<PeriodicCall> monitoring_services::PduMonitor::m_pPeriodicCall
Member variable storing a PeriodicCall instance.
uint16_t monitoring_services::PduMonitor::m_PduId
string monitoring_services::PduMonitor::m_PduName
unsigned long long monitoring_services::PduMonitor::m_PduReceivedCounter
unsigned long long monitoring_services::PduMonitor::m_PduProcessedCounter
Referenced by Stop.
unsigned long long monitoring_services::PduMonitor::m_lastPrintedPduReceivedCounter
unsigned long long monitoring_services::PduMonitor::m_lastPrintedPduProcessedCounter
unsigned long long monitoring_services::PduMonitor::m_shortPrintPduReceivedCounter
unsigned long long monitoring_services::PduMonitor::m_shortPrintPduProcessedCounter
Referenced by Stop.
std::map<uint16_t,RefWrap> monitoring_services::PduMonitor::s_instMap
std::unique_ptr<PeriodicCall> monitoring_services::PduMonitor::s_pPeriodicCall
std::unique_ptr<PeriodicCall> monitoring_services::PduMonitor::m_PrintNames
monitoring_services::PduMonitor::PduMonitor(uint16_t id, uint32_t milliSec=10000)
id Pdu Id to monitor milliSec intervall in milliseconds in which the Pdu is monitored Traceability Design Decision - No requirements linked. Constructor to monitor a specific Pdu in a defined millisecond intervall Call Sequence PduMonitor_Constructor !include plantuml/SQD_PduMonitor.plantuml!0
monitoring_services::PduMonitor::PduMonitor()
Traceability Design Decision - No requirements linked. Default constructor
monitoring_services::PduMonitor::~PduMonitor()
Traceability Design Decision - No requirements linked. Default destructor Call Sequence PduMonitor_Destructor !include plantuml/SQD_PduMonitor.plantuml!1
monitoring_services::PduMonitor::PduMonitor(PduMonitor &&)
RValue reference of type PduMonitor Traceability Design Decision - No requirements linked. Constructor for use with universal reference
monitoring_services::PduMonitor::PduMonitor(const PduMonitor &)=delete
const reference of type PduMonitor Traceability Design Decision - No requirements linked. Deleted constructor for const reference usage
PduMonitor & monitoring_services::PduMonitor::operator=(PduMonitor &&)
RValue reference of type PduMonitor LValue reference of type PduMonitor Traceability Design Decision - No requirements linked. Copy operator for universal reference to simple reference assignment
PduMonitor& monitoring_services::PduMonitor::operator=(const PduMonitor &)=delete
const reference of type PduMonitor Traceability Design Decision - No requirements linked. Deleted copy assignment operator for const simple references
void monitoring_services::PduMonitor::OnPduReceived()
defined in header to make it inline
Traceability Design Decision - No requirements linked. Helper function updates the PduReceivedCounter Test MethodTEST_PDUMONITOR_IMPL_8(): Checks the GetPduReceivedCounter and GetPduProcessedCounter methods
Referenced by TEST_PDUMONITOR_IMPL_6.
void monitoring_services::PduMonitor::OnPduProcessed()
defined in header to make it inline
Traceability Design Decision - No requirements linked. Helper function updates the PduProcessedCounter Test MethodTEST_PDUMONITOR_IMPL_8(): Checks the GetPduReceivedCounter and GetPduProcessedCounter methods
long long monitoring_services::PduMonitor::GetPduReceivedCounter()
defined in header to make it inline
PduReceivedCounter Traceability Design Decision - No requirements linked. Helper function to get the PduReceivedCounter Test MethodTEST_PDUMONITOR_IMPL_8(): Checks the GetPduReceivedCounter and GetPduProcessedCounter methods
long long monitoring_services::PduMonitor::GetPduProcessedCounter()
defined in header to make it inline
PduProcessedCounter Traceability Design Decision - No requirements linked. Helper function to get the PduProcessedCounter Test MethodTEST_PDUMONITOR_IMPL_8(): Checks the GetPduReceivedCounter and GetPduProcessedCounter methods
std::string monitoring_services::PduMonitor::GetLogs()
Test MethodTEST_PDUMONITOR_IMPL_3(): GetLogs method calculates the received and processed counter values and then log the messages related to the PDU Id, Received and Processed counters. TEST_PDUMONITOR_IMPL_4(): printLogs method calls the GetLogs method. Traceability Design Decision - No requirements linked. Helper function calculates the received and processed counter values and logs the messages related to the PDU Id, Received and Processed counters.
References GetLogger.
std::string monitoring_services::PduMonitor::GetShortLog()
Test MethodTEST_PDUMONITOR_IMPL_5(): GetShortLog method calculates the received counter and if it is not zero then the processed counter and percent is calculated. TEST_PDUMONITOR_IMPL_6(): printAllLogs method calls the GetShortLog method and messages are logged accordingly. Traceability Design Decision - No requirements linked. Helper function calculates the received counter and if it is not zero, the processed counter and percentage is calculated
References GetLogger.
void monitoring_services::PduMonitor::PrintLogs()
Test MethodTEST_PDUMONITOR_IMPL_4(): printLogs method calls the GetLogs method. Traceability Design Decision - No requirements linked. Helper function calls the GetLogs method
Referenced by TEST_PDUMONITOR_IMPL_6.
void monitoring_services::PduMonitor::Start()
Traceability Design Decision - No requirements linked. Helper function starts Pdu monitoring
void monitoring_services::PduMonitor::Stop()
Traceability Design Decision - No requirements linked. Helper function stops Pdu monitoring
References m_PduProcessedCounter, m_shortPrintPduProcessedCounter.
std::string monitoring_services::PduMonitor::ThreeDigitsToString(int)
Convert function to insert a number with 3 digits to a string.
int the number to convert to a string output string for pretty readable name with leading '0's Test MethodTEST_PDUMONITOR_IMPL_1(): Converts a number with 3 digits to a string. Traceability Design Decision - No requirements linked. Helper function converts a number with 3 digits to a string
std::string monitoring_services::PduMonitor::FourDigitsToString(int)
Convert function to insert a number with 4 digits to a string.
int the number to convert to a string output string for pretty readable name with leading '0's Test MethodTEST_PDUMONITOR_IMPL_2(): Converts a number with 4 digits to a string Traceability Design Decision - No requirements linked. Helper function converts a number with 4 digits to a string
void monitoring_services::PduMonitor::PrintAllLogs()
Test MethodTEST_PDUMONITOR_IMPL_6(): printAllLogs method calls the GetShortLog method and messages are logged accordingly. Traceability Design Decision - No requirements linked. Helper function calls the GetShortLog method and messages are logged accordingly Call Sequence PduMonitor_PrintAllLogs !include plantuml/SQD_PduMonitor.plantuml!2
Referenced by TEST_PDUMONITOR_IMPL_6.
void monitoring_services::PduMonitor::PrintPduNames()
Test MethodTEST_PDUMONITOR_IMPL_7(): PrintPduNames method prints the Pdu names with the respective Pdu Ids. Traceability Design Decision - No requirements linked. Helper function prints the Pdu names with the respective Pdu Ids Call Sequence PduMonitor_PrintPduNames !include plantuml/SQD_PduMonitor.plantuml!3
ara::log::Logger & monitoring_services::PduMonitor::GetLogger()
Returns reference to static Logger instance Traceability Design Decision - No requirements linked. Static reference to instance of Logger class
Referenced by GetLogs, GetShortLog.