CsH_KeyLearning.h
Std_ReturnType FFBSKCUebertragung(const uint8 *rawFFBSKC)
Server function for FFB_SKC Learning process triggered by WFS This function is called by RTE from WFS and leads to learning (storing) the FFB_SKC in the ICAS1 NvM. Prior to storing the FFB_SKC-related data, all obsolete data must be cleared. reentrant No context task thread safe No multicore safe No synchronous Function triggered by WFS N/A rawFFBSKC - pointer of FFB_SKC Std_ReturnType retval - RTE Status for evaluated operation. Globalsu8_FFBSKCUebertragungResp - Response of FFBSKC Key learning process Input->Output-CorrelationInput data determines RTE Status return value. Call Sequence Test MethodSWATT unit test TEST_FFBSKCUebertragung TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_568 SWR_ICAS1_L3_CRY_332 SWR_ICAS1_L3_CRY_335 SWR_ICAS1_L3_CRY_336 SWR_ICAS1_L3_CRY_337 SWR_ICAS1_L3_CRY_338 SWR_ICAS1_L3_CRY_322 SWR_ICAS1_L3_CRY_521 SWR_ICAS1_L3_CRY_343 Server function for FFB_SKC Learning process triggered by WFS Please find detail information in header file.
References CsH_Clear_StanbyRAM_FFBSKC, CsH_Clear_StanbyRAM_FfbData, u8_FFBSKCUebertragungResp, b_FFBSKCUebertragungReq.
Referenced by TEST_FFBSKCUebertragung.
Std_ReturnType FFBDatenUebertragung(boolean bFFBSchluesselNr1, boolean bFFBSchluesselNr2, boolean bFFBSchluesselNr3, boolean bFFBSchluesselNr4, boolean bFFBSchluesselNr5, boolean bFFBSchluesselNr6, boolean bFFBSchluesselNr7, boolean bFFBSchluesselNr8, const uint8 *rawFFBDatenPaket1, const uint8 *rawFFBDatenPaket2, const uint8 *rawFFBDatenPaket3, const uint8 *rawFFBDatenPaket4, const uint8 *rawFFBDatenPaket5, const uint8 *rawFFBDatenPaket6, const uint8 *rawFFBDatenPaket7, const uint8 *rawFFBDatenPaket8)
Server function for FFB Key Learning process triggered by WFS. This function is called by RTE from WFS right after FFB_SKC learning process has succesfully ended. This function leads to learning (storing) data such as TransponderIDs or Rolling Code Counters (WCZ) in the ICAS1 NvM for all the FFB Keys received from WFS. Prior to storing the FFB_SKC-related data, all obsolete FFB Keys' data must be cleared and new Key data must be positively evaluated. This evaluation is executed sequentially for all the keys. After successful evaluation, CsH stores the data in NVM, forwards the Transponder IDs to SAM for RF filtering purposes and propagates the WCZ data to FDH SWC. reentrant No context task thread safe No multicore safe No synchronous Function triggered by WFS. N/A boolean bFFBSchluesselNr1/2/3/4/5/6/7/8 - indicates availability of the Key data (so called Learning Crypt) for specific key number. [in] pointer of rawFFBDatenPaket1/2/3/4/5/6/7/8 array - - Learning Crypt that contains all the Key related data such as the TransponderID or Rolling Code Counter. Std_ReturnType retval - RTE Status for evaluated operation. Globalsu8_FFBDatenUebertragungResp - Response of FFBDaten Key learning process b_FFBDatenUebertragungReq - Flag used to start FFBDaten Key learning process bFFBSchluessel - Boolean Array denoting indexes of learned keys Input->Output-CorrelationInput data determines RTE Status return value. Call Sequence Test MethodTEST_FFBDatenUebertragung TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_346 SWR_ICAS1_L3_CRY_388 SWR_ICAS1_L3_CRY_393 SWR_ICAS1_L3_CRY_533 SWR_ICAS1_L3_CRY_563 SWR_ICAS1_L3_CRY_691 SWR_ICAS1_L3_CRY_692 SWR_ICAS1_L3_CRY_693 SWR_ICAS1_L3_CRY_694 SWR_ICAS1_L3_CRY_702 SWR_ICAS1_L3_CRY_704 SWR_ICAS1_L3_CRY_705 SWR_ICAS1_L3_CRY_707 SWR_ICAS1_L3_CRY_339 SWR_ICAS1_L3_CRY_480 SWR_ICAS1_L3_CRY_381 SWR_ICAS1_L3_CRY_386 SWR_ICAS1_L3_CRY_389 SWR_ICAS1_L3_CRY_391 SWR_ICAS1_L3_CRY_733 Server function for FFB_SKC Learning process triggered by WFS Please find detail information in header file.
References u8_FFBDatenUebertragungResp, NUMBER_OF_KEYS_RECEIVED, bFFBSchluessel, b_FFBDatenUebertragungReq, checkAllDataPointers, FrequencyCheck, WCZ_LENGTH, sendTransponderIDtoSam.
Referenced by TEST_FFBDatenUebertragung.
void evFFBDataExchangeResp(uint8 saveWCZStatus)
This function returns a status of storing the Rolling Code Counter by FDH which is part of the FFB Data Learning process. This function is called by FFBDataHandler reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous FFB Data Learning Process started N/A uint8 saveWCZStatus - status of the Rolling Code Counter storage by FDH void GlobalsalreadyReSendWCZtoFDH - Boolean value denoting if Rolling Code Counter has already been sent to FDH Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_evFFBDataExchangeResp TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_735 SWR_ICAS1_L3_CRY_736 This function returns a status of storing the Rolling Code Counter by FDH which is part of the FFB Data Learning process. Please find detail information in header file.
References WCZ_TRANSFER_OK, WCZ_TRANSFER_N_OK, alreadyReSendWCZtoFDH, WCZ_TRANSFER_PENDING.
Referenced by TEST_evFFBDataExchangeResp.
boolean CSH_getFFBSKCFlag(void)
Getter Function for FFBSKC Validation Flag This function is called by UHF - Returns boolean value reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by UHF Master SWC N/A void boolean FFB SKC Validation flag GlobalsStandby_CsH_FfbSkc - FFB SKC variables stored in Standby RAM Input->Output-CorrelationFFB SKC Validation flag gets provided via RTE to UHF Master Call Sequence Test MethodSWATT unit test TEST_CSH_getFFBSKCFlag TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function to extract Validation Flag. Getter Function for FFBSKC Validation Flag Please find detail information in header file.
References Standby_CsH_FfbSkc.
Referenced by TEST_CSH_getFFBSKCFlag.
boolean CSH_getFFBDataFlag(void)
Getter Function for FFBData Validation Flag This function is called by UHF - Returns boolean value reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by UHF Master SWC N/A void boolean FFB Data Validation flag GlobalsStandby_CsH_FfbData - FFB Data variables stored in Standby RAM Input->Output-CorrelationFFB Data Validation flag gets provided via RTE to UHF Master Call Sequence Test MethodSWATT unit test TEST_CSH_getFFBDataFlag TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function to extract Validation Flag. Getter Function for FFBData Validation Flag Please find detail information in header file.
References Standby_CsH_FfbData.
Referenced by TEST_CSH_getFFBDataFlag.
Std_ReturnType evCheckTransponderID(uint8 KeyIndex, const uint8 *ReceivedTransponderID)
This function checks if the TransponderID stored in the Standby RAM for the key number is the same as received in ReceivedTransponderID This function is called by FFBDataHandler and the arguments come from the UHF frame for given key numeber. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous This function is called by FFB Data Handler N/A uint8 KeyIndex - position, where the key number is located located (key number = KeyIndex - 1) [in] pointer of ReceivedTransponderID - pointer to the array containing TransponderID for given key number Std_ReturnType retval - RTE Status for evaluated operation. GlobalsStandby_CsH_FfbData - FFB Data variables stored in Standby RAM Input->Output-CorrelationResult of the check is provided to FDH. Call Sequence Test MethodSWATT unit test TEST_evCheckTransponderID TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function checking the TransponderID. This function checks if the TransponderID stored in the Standby RAM for the key number is the same as received in ReceivedTransponderID Please find detail information in header file.
References Standby_CsH_FfbData.
Referenced by TEST_evCheckTransponderID.
Std_ReturnType evFindSlotNumber(const uint8 *ReceivedTransponderID, uint8 *slotNumber)
This function is used to provide the Key index of the key with given TransponderID This function is called by UHF Master reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by UHF Master N/A pointer of ReceivedTransponderID - TransponderID of the searched key [in] pointer of slotNumber - position of the key number Std_ReturnType retval - RTE Status for evaluated operation. GlobalsStandby_CsH_FfbData - FFB Data variables stored in Standby RAM Input->Output-CorrelationKey index of the key with given TransponderID provided to UHF Master. Call Sequence Test MethodSWATT unit test TEST_evFindSlotNumber TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function providing the Key index. This function is used to provide the Key index of the key with given TransponderID Please find detail information in header file.
References NUMBER_OF_KEYS_RECEIVED, Standby_CsH_FfbData.
Referenced by TEST_evFindSlotNumber.
void CsH_KeyHandler_Cyclic(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Checks if FFBDaten Key or FFBSKFC flag has been set and performs key learning process. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globalsnone Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_CsH_KeyHandler_Cyclic TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_725 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References b_FFBSKCUebertragungReq, FFBSKCUebertragung_WFS_Response, b_FFBDatenUebertragungReq, FFBDatenUebertragungResp_WFS_Response, alreadyReSendWCZtoFDH, Resend_WCZ_to_FDH, CSH_SetDTC_035819_IfKeysNotLearned, vnumUHFKanalkonfiguration.
Referenced by TEST_CsH_KeyHandler_Cyclic, CsH_TaskCyclicEvent.
void CsH_KeyHandler_Init(void)
CsH init function called by scheduler. On Entrance checks if Standby RAM for CsH has previously been initialized. If not function updates Standby RAM data for FFBSKC and FFBData. Called by scheduler once on each EnterRun. reentrant No context task thread safe Yes multicore safe No - All APIs needs to be called from the same core synchronous System after wake up/reset, in EnterRUN. N/A void void GlobalsbIsCsH_Stanby_Initializated - Standby RAM Initialization Flag Input->Output-CorrelationIf Standby RAM hadn't been previously initialized - CsH performs initialization with data for FFB SKC and FFB Data Call Sequence Test MethodSWATT unit test TEST_CsH_InitVarFunc TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: component init function to be called by scheduler. CsH init function called by scheduler. Please find detail information in header file.
References bIsCsH_Stanby_Initializated, CsH_Update_StanbyRAM_FFBSKC, CsH_Update_StanbyRAM_FfbData.
Referenced by TEST_CsH_KeyHandler_Init, CsH_InitVarFunc.