CsH_CryptoOperations.h
void CsH_Call_Ev_StCryptoKY_evCalcChallengeResp(void)
Event function of the CsH module. The function provides the response to Kessy for Challenge Generation request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the result of challenge generation to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCalcChallengeResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsrawChallengeResult - Buffer used for a raw Challenge generation numCalcChallengeStatus - Status of a raw Challenge generation Input->Output-CorrelationResult of challenge generation gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCalcChallengeResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_554
References rawChallengeResult, numCalcChallengeStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCalcChallengeResp.
void CsH_Call_Ev_StCryptoKY_evCalcSignatureResp(void)
Event function of the CsH module. The function provides the response to Kessy for Signature Calculation request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the result of Signature calculation to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCalcSignatureResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsrawSignatureResult - Buffer for a Signature Check result numCalcSignatureStatus - Status of a Signature Check result Input->Output-CorrelationResult of Signature calculation gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCalcSignatureResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_409
References rawSignatureResult, numCalcSignatureStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCalcSignatureResp.
void CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp(void)
Event function of the CsH module. The function provides the response to Kessy for Checking the RSAD Signature request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the result of checking RSAD Signature to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCheckRSADSignatureResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsbRSASignatureValid - Boolean value denoting RSAD Signature validness numCheckRSASignatureStatus - Status of a RSAD Signature Check result Input->Output-CorrelationResult of checking RSAD Signature gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_539
References bRSASignatureValid, numCheckRSASignatureStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp.
void CsH_Call_Ev_StCryptoKY_evCheckSignatureResp(void)
Event function of the CsH module. The function provides the response to Kessy for Checking the Signature request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the Status of checking Signature to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCheckSignatureResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsbSignatureValid - Boolean value denoting Signature validness numCheckSignatureStatus - Status of a Signature Check result Input->Output-CorrelationStatus of checking Signature gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCheckSignatureResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_401
References bSignatureValid, numCheckSignatureStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCheckSignatureResp.
void CsH_Call_Ev_StCryptoKY_evEncryptResp(void)
Event function of the CsH module. The function provides the response to Kessy for Encryption request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the Response for data encryption request to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evEncryptResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void Globalsu8rawEncryptResult - Buffer for the Encryption Process Result numrawEncryptStatus - Status for data encryption request Input->Output-CorrelationStatus of data encryption request gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evEncryptResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_544
References u8rawEncryptResult, numrawEncryptStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evEncryptResp.
Std_ReturnType evEncryptReq(const uint8 *rawInputData, uint8 enSKC, const uint8 *rawKey)
This is the server function for handling the Encryption request from Kessy The function triggers the encryption of the rawInputData over the CSM (Crypto Stack) using the selected cryptographical key type (either FFB_SKC, RSAD_SKC or rawKey value). The result of the encryption is stored in the u8rawEncryptResult buffer. Afterwards, Kessy receives the encryption result over the KessyEventMngr. reentrant No context task thread safe No multicore safe No synchronous Function called by Kessy component lib N/A uint8* rawInputData - pointer to the data to encrypt [in] uint8 enSKC - enum denoting the selected cryptographical key type [in] uint8* rawKey - pointer to data containing rawKey, being the one of the cryptographical key type Std_ReturnType retval - RTE Status for evaluated operation. Globalsu8rawEncryptResult - Buffer for the Encryption Process Result. u32rawEncryptResultLength - Length of the Encryption Process Result. Standby_CsH_FfbSkc - FFB SKC variables stored in Standby RAM. Input->Output-CorrelationInput data determines RTE Status return value Activity Diagram evEncryptReq Test MethodSWATT unit test TEST_evEncryptReq TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_542 SWR_ICAS1_L3_CRY_545 SWR_ICAS1_L3_CRY_549 SWR_ICAS1_L3_CRY_550 SWR_ICAS1_L3_CRY_551 SWR_ICAS1_L3_CRY_553 SWR_ICAS1_L3_CRY_938 SWR_ICAS1_L3_CRY_610 This is the server function for handling the Encryption request from Kessy Please find detail information in header file.
References Rte_Call_CsH_KessyEvMngr_setEvRequest, u8rawEncryptResult, CSH_EN_SKC_RAW, CSH_ENCRYPTION_BUFFER_SIZE, KEY_BUFFER_SIZE, u32rawEncryptResultLength, CSH_EN_SKC_FFB, Standby_CsH_FfbSkc, CSH_EN_SKC_RSAD, numrawEncryptStatus.
Referenced by TEST_evEncryptReq.
Std_ReturnType evCalcChallengeReq(void)
This is the server function for handling the Challenge Generation request from Kessy The function triggers the Challenge Generation via the CSM (Crypto Stack) . The result of the Challenge Generation is stored in the rawChallengeResult buffer. Afterwards, Kessy receives the generated Challenge result over the KessyEventMngr. This function attempts to generate the real random number via HW module. In case an access to the HW module is rejected at the time of the request (due to e.g., other function requests), retry mechanism is used - RANDOM_NUMBER_COUNT attempts are possible. Eventually, random number pre-generated during runtime and stored in Standby RAM is used. This mechanism is designed for the purpose of wake-up from deep sleep, when multiple functions try to generate the random numbers and the access to HW crypto module may be limited. reentrant Yes - More in details section context task thread safe No multicore safe No synchronous Received request from Kessy N/A void Std_ReturnType retval - RTE Status for evaluated operation. GlobalsrawChallengeResult - Buffer used for a raw Challenge generation. numCalcChallengeStatus - Status of a raw Challenge generation. Standby_CsH_FfbSkc - FFB SKC variables stored in Standby RAM. randomNumberUsed_counter - Counter of random number usage times. randomGenereted_Standby_Status - Random Generated number status variables stored in Standby RAM. Input->Output-CorrelationInput data determines RTE Status return value. Call Sequence Test MethodSWATT unit test TEST_evCalcChallengeReq TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_613 SWR_ICAS1_L3_CRY_414 SWR_ICAS1_L3_CRY_555 SWR_ICAS1_L3_CRY_554 This is the server function for handling the Challenge Generation request from Kessy Please find detail information in header file.
References Rte_Call_CsH_KessyEvMngr_setEvRequest, rawChallengeResult, numCalcChallengeStatus, Standby_CsH_FfbSkc, CSMPI_RESULT_LENGTH, randomNumberUsed_counter, RANDOM_NUMBER_COUNT, randomGenereted_Standby_Status, randomGenereted_Standby, CSH_ENCRYPTION_NOTPOSSIBLE.
Referenced by TEST_evCalcChallengeReq.
Std_ReturnType evCalcSignatureReq(boolean bMarkerDirection, const uint8 *rawFreshnessValue, const uint8 *rawNutzdaten, uint8 numNutzdatenLength)
This is the server function for handling the Signature Calculation request from Kessy The function triggers the Signature Calculation on the data provided as arguments via the CSM (Crypto Stack) using the FFB_SKC cryptographical key. The result of the Signature Calculation is stored in the rawSignatureResult buffer. Afterwards, Kessy receives the encryption result over the KessyEventMngr. reentrant No context task thread safe No multicore safe No synchronous Received request from Kessy N/A boolean bMarkerDirection - value passed by Kessy [in] pointer of rawFreshnessValue array - value passed by Kessy [in] pointer of rawNutzdaten array - value passed by Kessy [in] uint8 numNutzdatenLength - length of the rawNutzdaten array Std_ReturnType retval - RTE Status for evaluated operation. Globalsu32rawEncryptResultLength - Buffer for a Signature Check result rawSignatureResult - Buffer for a Signature Check result numCalcSignatureStatus - Status of a Signature Check result u8rawEncryptResult - Buffer for the Encryption Process Result u8CalcSignatureReqBuffer - Buffer for CalcSignature Req Input->Output-CorrelationInput data determines RTE Status return value. Call Sequence Test MethodSWATT unit test TEST_evCalcSignatureReq TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_605 SWR_ICAS1_L3_CRY_405 SWR_ICAS1_L3_CRY_406 SWR_ICAS1_L3_CRY_407 SWR_ICAS1_L3_CRY_408 SWR_ICAS1_L3_CRY_409 This is the server function for handling the Signature Calculation request from Kessy Please find detail information in header file.
References numCalcSignatureStatus, CSH_ENCRYPTION_NOTPOSSIBLE, Rte_Call_CsH_KessyEvMngr_setEvRequest, rawSignatureResult, u8CalcSignatureReqBuffer, CSH_INPUTVECTOR_SIZE, Standby_CsH_FfbSkc, CSH_MARKERDIRECTION_SIZE, CSH_REFRESHNESS_BUFFER_SIZE, KEY_BUFFER_SIZE, u32rawEncryptResultLength, CSH_ENCRYPTION_BUFFER_SIZE, u8rawEncryptResult.
Referenced by TEST_evCalcSignatureReq.
Std_ReturnType evCheckRSADSignatureReq(const uint8 *rawInputData, uint8 numInputDataLength, const uint8 *rawSignatureToCheck, uint8 numSignatureLength)
This is the server function for handling the RSAD Signature Check request from Kessy The function triggers the RSAD Signature Calculation on the rawInputData via the CSM (Crypto Stack) using the RSAD_SKC cryptographical key and compares the generated signature with the signature provided by Kessy in rawSignatureToCheck. The result of the signatures comparison is stored in the bRSASignatureValid. Afterwards, Kessy receives the signature check result over the KessyEventMngr. reentrant No context task thread safe No multicore safe No synchronous Function called by Kessy component lib. N/A uint8* rawInputData - pointer to rawInpuData. [in] uint8 numInputDataLength - rawInputData length. [in] uint8* rawSignatureToCheck - pointer to rawSignatureToCheck data. [in] uint8 numSignatureLength - rawSignatureToCheck length. Std_ReturnType retval - RTE Status for evaluated operation. GlobalsbRSASignatureValid - Boolean value denoting RSAD Signature validness numCheckRSASignatureStatus - Status of a RSAD Signature Check result Input->Output-CorrelationInput data determines RTE Status return value. Activity Diagram evCheckRSADSignatureReq Test MethodSWATT unit test TEST_evCheckRSADSignatureReq TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_608 SWR_ICAS1_L3_CRY_538 SWR_ICAS1_L3_CRY_541 SWR_ICAS1_L3_CRY_931 SWR_ICAS1_L3_CRY_539 This is the server function for handling the RSAD Signature Check request from Kessy Please find detail information in header file.
References numCheckRSASignatureStatus, CSH_ENCRYPTION_NOTPOSSIBLE, bRSASignatureValid, CSH_NUM_SIGNATURE_LENGTH_MIN, CSH_NUM_SIGNATURE_LENGTH_MAX, Rte_Call_CsH_KessyEvMngr_setEvRequest.
Referenced by TEST_evCheckRSADSignatureReq.
Std_ReturnType CheckSignature_ZKA(boolean bMarkerDirection, const uint8 *rawFreshnessValue, const uint8 *rawNutzdaten, uint8 numNutzdatenLength, const uint8 *rawSignatureToCheck, uint8 numSignatureLength)
This is the server function for handling the Signature Check request from FDH The function triggers the Signature Calculation on the input vector consisting of function arguments via the CSM (Crypto Stack) using the FFB_SKC cryptographical key and compares the generated signature with the signature provided by FDH in rawSignatureToCheck. The result of the signatures comparison is stored in the bZKASignatureValid. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Request sent from FFB Data Handler N/A boolean bMarkerDirection - component of the input vector used for signature calculation [in] pointer of rawFreshnessValue array - component of the input vector used for signature calculation [in] pointer of rawNutzdaten array - component of the input vector used for signature calculation [in] uint8 numNutzdatenLength - length of rawNutzdaten [in] pointer of rawSignatureToCheck array - pointer to the array containing Signature passed by FDH [in] uint8 umSignatureLength - length of the Signature passed by FDH Std_ReturnType retval - RTE Status for evaluated operation. Globalsu8CheckSignatureReqBuffer - Buffer for CheckSignature Req Input->Output-CorrelationThe result of the signatures comparison is provided to FDH. Call Sequence Test MethodSWATT unit test TEST_CheckSignature_ZKA TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_583 SWR_ICAS1_L3_CRY_584 SWR_ICAS1_L3_CRY_397 SWR_ICAS1_L3_CRY_398 SWR_ICAS1_L3_CRY_399 SWR_ICAS1_L3_CRY_400 SWR_ICAS1_L3_CRY_401 SWR_ICAS1_L3_CRY_558 This is the server function for handling the Signature Check request from FDH Please find detail information in header file.
References CSH_ENCRYPTION_INIT, Standby_CsH_FfbSkc, u8CheckSignatureReqBuffer, CSH_MARKERDIRECTION_SIZE, CSH_REFRESHNESS_BUFFER_SIZE, KEY_BUFFER_SIZE.
Referenced by TEST_CheckSignature_ZKA.
Std_ReturnType evCheckSignatureReq(boolean bMarkerDirection, const uint8 *rawFreshnessValue, const uint8 *rawNutzdaten, uint8 numNutzdatenLength, const uint8 *rawSignatureToCheck, uint8 numSignatureLength)
This is the server function for handling the Signature Check request from Kessy The function triggers the Signature Calculation on the input vector consisting of function arguments via the CSM (Crypto Stack) using the FFB_SKC cryptographical key and compares the generated signature with the signature provided by Kessy in rawSignatureToCheck. The result of the signatures comparison is stored in the bSignatureValid. reentrant No context task thread safe No multicore safe No synchronous Received request from Kessy N/A boolean bMarkerDirection - component of the input vector used for signature calculation [in] pointer of rawFreshnessValue - component of the input vector used for signature calculation [in] pointer of rawNutzdaten - component of the input vector used for signature calculation [in] uint8 numNutzdatenLength - length of rawNutzdaten [in] pointer of rawSignatureToCheck - pointer to the array containing Signature passed by FDH [in] uint8 numSignatureLength - length of the Signature passed by FDH Std_ReturnType retval - RTE Status for evaluated operation. GlobalsbSignatureValid - Boolean value denoting Signature validness numCheckSignatureStatus - Status of a Signature Check result u8CheckSignatureReqBuffer - Buffer for CheckSignature Req Input->Output-CorrelationInput data determines RTE Status return value. Call Sequence Test MethodSWATT unit test TEST_evCheckSignatureReq TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_583 SWR_ICAS1_L3_CRY_584 SWR_ICAS1_L3_CRY_397 SWR_ICAS1_L3_CRY_398 SWR_ICAS1_L3_CRY_399 SWR_ICAS1_L3_CRY_400 SWR_ICAS1_L3_CRY_401 SWR_ICAS1_L3_CRY_558 This is the server function for handling the Signature Check request from Kessy Please find detail information in header file.
References bSignatureValid, numCheckSignatureStatus, CSH_NUM_NUTZDATEN_LENGHT_MAX, CSH_NUM_SIGNATURE_LENGTH_MIN, CSH_NUM_SIGNATURE_LENGTH_MAX, Rte_Call_CsH_KessyEvMngr_setEvRequest, Standby_CsH_FfbSkc, u8CheckSignatureReqBuffer, CSH_MARKERDIRECTION_SIZE, CSH_REFRESHNESS_BUFFER_SIZE, KEY_BUFFER_SIZE.
Referenced by TEST_evCheckSignatureReq.
void CSH_CsmKeyExtractCallback(Std_ReturnType retVal)
Call-back function CSH_CsmKeyExtractCallback of the CsH module This function is called by CsmPi reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by CsmPi N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmKeyExtractCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Key Extraction. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmKeyExtractCallback.
void CSH_CsmRandomCallback(Std_ReturnType retVal)
Call-back function CSH_CsmRandomCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmRandomCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Random. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmRandomCallback.
void CSH_CsmMacVerifyCallback(Std_ReturnType retVal)
Call-back function CSH_CsmMacVerifyCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmMacVerifyCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Mac Verify. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmMacVerifyCallback.
void CSH_CsmMacGenerateCallback(Std_ReturnType retVal)
Call-back function CSH_CsmMacGenerateCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmMacGenerateCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Mac Generate. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmMacGenerateCallback.
void CsH_CsmBlockEncryptCallback(Std_ReturnType retVal)
Call-back function CsH_CsmBlockEncryptCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CsH_CsmBlockEncryptCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Block Encrypt. Function required by Csm. Currently not used.
Referenced by TEST_CsH_CsmBlockEncryptCallback.
void CsH_CryptoOperations_Cyclic(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. one major subtasks is referenced periodically: -getRandomNumber reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globalsnone Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_CsH_CryptoOperations_Cyclic TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_725
References getRandomNumber.
Referenced by TEST_CsH_CryptoOperations_Cyclic, CsH_TaskCyclicEvent.