CsH_CryptoOperations.c
CSH_EN_SKC_RAW
Constant used as a value for Custom Key valueUsed in the switch case in evEncryptReq when determining type of Key used for encryption. Represents Custom Key value. values 0u
CSH_EN_SKC_FFB
Constant used as a value for FFB-SKCUsed in the switch case in evEncryptReq when determining type of Key used for encryption. Represents FFB-SKC value. values 1u
CSH_EN_SKC_RSAD
Constant used as a value for RSAD-SKCUsed in the switch case in evEncryptReq when determining type of Key used for encryption. Represents RSAD-SKC value. values 2u
CSH_ENCRYPTION_NOTPOSSIBLE
Constant used as a value in RSAD Signature and Encryption checkUsed as initial value for: numCalcChallengeStatus numCalcSignatureStatus numCheckRSASignatureStatus numCheckSignatureStatus numrawEncryptStatus Used when checking signatures and encryption in: evCalcChallengeReq evCalcSignatureReq evCheckRSADSignatureReq values 1u
CSH_ENCRYPTION_INIT
Constant used as intial value for ZKA Signature StatusUsed as initial value for ZKA Signature Status in CheckSignature_ZKA values 3u
CSH_ENCRYPTION_BUFFER_SIZE
Constant describing size of a buffer for CsH EncryptionDetermines length of array CSH_ENCRYPTION_BUFFER_SIZE Used in evEncryptReq and evCalcSignatureReq values 16u
CSH_MARKERDIRECTION_SIZE
Constant describes marker direction sizeUsed in : evCalcSignatureReq evCheckSignatureReq CheckSignature_ZKA values 1u
CSH_REFRESHNESS_BUFFER_SIZE
Constant describes refreshness buffer size for CsHUsed in : evCalcSignatureReq evCheckSignatureReq CheckSignature_ZKA values 8u
CSH_INPUTVECTOR_SIZE
Constant used as size of input vectorDetermines length of u8CalcSignatureReqBuffer and u8CheckSignatureReqBuffer Is used in evCalcSignatureReq when clearing buffer for signature calculations. values 128u
KEY_BUFFER_SIZE
Constant describing size of buffer for a keyUsed in : evEncryptReq evCalcSignatureReq CheckSignature_ZKA During Key extraction from Csmpi values 16u
CSMPI_RESULT_LENGTH
Constant describing length of Csmpi resultUsed in getRandomNumber and evCalcChallengeReq when values 3u
CSH_NUM_NUTZDATEN_LENGHT_MAX
Constant describing maximum length of payload for signatureUsed in evCheckSignatureReq when checking the signature values 33u
CSH_NUM_SIGNATURE_LENGTH_MAX
Constant describing maximum length signatureUsed in evCheckRSADSignatureReq when checking the RSAD signature values 6u
CSH_NUM_SIGNATURE_LENGTH_MIN
Constant describing minimal length of payload for signatureUsed in evCheckRSADSignatureReq and evCheckSignatureReq when checking the signature values 4u
const Rte_PimType_CsH_CsH_Ffb Pim_CsH_CsH_Ffb_ROM
CsH ROM BlockStructure for a default NVM Values located in Pim range N/A values N/A unit N/A resolution N/A context {task, used inside evCalcChallengeReq()} protection {static global variable for CsH_Task.c} TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_324 SWR_ICAS1_L3_CRY_325 SWR_ICAS1_L3_CRY_328 SWR_ICAS1_L3_CRY_329 SWR_ICAS1_L3_CRY_636
Referenced by TEST_CsH_CryptoOperations_NvM_Init_Values.
uint32 u32rawEncryptResultLength
Length of the Encryption Process ResultDescribes length of the data stored in the buffers used for Encryption u8rawEncryptResult range {0u - 16u } values N/A unit N/A resolution N/A context {task, used inside evEncryptReq(), evCalcSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by evEncryptReq, evCalcSignatureReq.
IDT_CRYPTO_uint8_DIM6 rawChallengeResult
Buffer used for a raw Challenge generation6 bytes containing the Challenge generated in evCalcChallengeResp range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCalcChallengeResp(), evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCalcChallengeResp, evCalcChallengeReq.
uint8 numCalcChallengeStatus
Status of a raw Challenge generationVariable passed to Kessy informing about a Status of the Challenge generation function. range {0u - 3u } values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCalcChallengeResp(), evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCalcChallengeResp, evCalcChallengeReq, TEST_evCalcChallengeReq.
IDT_CRYPTO_uint8_DIM6 rawSignatureResult
Buffer for a Signature Check resultPointer to the output where CSM returns result of the signature check. range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCalcSignatureResp(), evCalcSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCalcSignatureResp, evCalcSignatureReq.
uint8 numCalcSignatureStatus
Status of a Signature Check resultVariable passed to Kessy informing about a Status of the Signature Check function result. range {0u - 3u } values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCalcSignatureResp(), evCalcSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCalcSignatureResp, evCalcSignatureReq, TEST_evCalcSignatureReq.
boolean bRSASignatureValid
Boolean value denoting RSAD Signature validnessDenotes if Signature received in evCheckRSADSignatureReq is valid. range {0u - 1u } values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp(), evCheckRSADSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp, evCheckRSADSignatureReq, TEST_evCheckRSADSignatureReq.
uint8 numCheckRSASignatureStatus
Status of a RSAD Signature Check resultVariable passed to Kessy as response about the result of checking RSAD Signature. range {0u - 3u } values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp(), evCheckRSADSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp, evCheckRSADSignatureReq.
boolean bSignatureValid
Boolean value denoting Signature validnessDenotes if Signature received in evCheckSignatureReq is valid. range {0u - 1u } values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCheckSignatureResp(), evCheckSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCheckSignatureResp, evCheckSignatureReq, TEST_evCheckSignatureReq.
uint8 numCheckSignatureStatus
Status of a Signature Check resultVariable passed to Kessy as response about the result of Signature check in evCheckSignatureReq. range {0u - 3u } values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evCheckSignatureResp(), evCheckSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evCheckSignatureResp, evCheckSignatureReq, TEST_evCheckSignatureReq.
uint8 numrawEncryptStatus
Status for data encryption requestVariable passed to Kessy informing about a Status of the data encryption function. range {0u - 3u} values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evEncryptResp(), evEncryptReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evEncryptResp, evEncryptReq, TEST_evEncryptReq.
uint8 u8rawEncryptResult[16u][16u]
Buffer for the Encryption Process ResultStores max 16 bytes of the Encryption Process Result. range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_Call_Ev_StCryptoKY_evEncryptResp(), evEncryptReq(), evCalcSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CsH_Call_Ev_StCryptoKY_evEncryptResp, evEncryptReq, evCalcSignatureReq.
uint8 u8CalcSignatureReqBuffer[128u][128u]
Buffer for CalcSignature ReqStores 16 bytes of a signature prepared for a usage in evCalcSignatureReq . range N/A values N/A unit N/A resolution N/A context {task, used inside evCalcSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by evCalcSignatureReq, TEST_evCalcSignatureReq.
uint8 u8CheckSignatureReqBuffer[128u][128u]
Buffer for CheckSignature ReqStores 16 bytes of a signature prepared for a usage in evCheckSignatureReq . range N/A values N/A unit N/A resolution N/A context {task, used inside CheckSignature_ZKA(), evCheckSignatureReq()} protection {static global variable for CsH_Task.c}
Referenced by CheckSignature_ZKA, evCheckSignatureReq, TEST_CheckSignature_ZKA, TEST_evCheckSignatureReq.
const uint8 RANDOM_NUMBER_COUNT
Size of randomGenereted_StandbyUsed in getRandomNumber to limit number of invokes of Rte_Call_CsH_RandomGenerate_CSH_RandomGenerateSync range {2u} values N/A unit N/A resolution N/A context {task, used inside getRandomNumber(), evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by evCalcChallengeReq, getRandomNumber.
uint8 randomNumberUsed_counter
Counter of random number usage timesUsed in evCalcChallengeReq during crypto calculation process. range {0u-2u} values N/A unit N/A resolution N/A context {task, used inside evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by evCalcChallengeReq, TEST_evCalcChallengeReq.
uint8 randomGenereted_Standby[2][6][2][6]
Random Generated number variables stored in Standby RAMStores variables related to Random Generated number in the Standby RAM to enable quick extraction of the data on the wake up. range N/A values N/A unit N/A resolution N/A context {task, used inside evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by evCalcChallengeReq, getRandomNumber.
uint8 randomGenereted_Standby_Status[2][2]
Random Generated number status variables stored in Standby RAMStores variables related to Random Generated number status in the Standby RAM to enable quick extraction of the data on the wake up. range {0u-2u} values N/A unit N/A resolution N/A context {task, used inside evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by evCalcChallengeReq, getRandomNumber, TEST_evCalcChallengeReq, TEST_getRandomNumber.
boolean bIsRandomInitialized
Flag denoting if Standby RAM section for Random Generated number has been initializedStores variables related to FFB SKC in the Standby RAM to enable quick extraction of the data on the wake up. range {0u-2u} values N/A unit N/A resolution N/A context {task, used inside evCalcChallengeReq()} protection {static global variable for CsH_Task.c}
Referenced by getRandomNumber, TEST_getRandomNumber.
static void getRandomNumber(void)
Function responsible for StanbyRAM random numbers storage Function responsible for getting and storage to StanbyRAM random numbers used during wakeup reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous none none void void GlobalsrandomGenereted_Standby - Random Generated number variables stored in Standby RAM randomGenereted_Standby_Status - Random Generated number status variables stored in Standby RAM bIsRandomInitialized - Flag denoting if Standby RAM section for Random Generated number has been initialized RANDOM_NUMBER_COUNT - Size of randomGenereted_Standby Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_getRandomNumber TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function for StanbyRAM random numbers storage. Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References bIsRandomInitialized, randomGenereted_Standby_Status, CSH_ENCRYPTION_NOTPOSSIBLE, RANDOM_NUMBER_COUNT, randomGenereted_Standby, CSMPI_RESULT_LENGTH.
Referenced by CsH_CryptoOperations_Cyclic, TEST_CsH_CryptoOperations_Cyclic, TEST_getRandomNumber.
void CsH_CryptoOperations_Cyclic(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. one major subtasks is referenced periodically: -getRandomNumber reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globalsnone Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_CsH_CryptoOperations_Cyclic TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_725
References getRandomNumber.
Referenced by TEST_CsH_CryptoOperations_Cyclic, CsH_TaskCyclicEvent.
void CsH_Call_Ev_StCryptoKY_evCalcChallengeResp(void)
Event function of the CsH module. The function provides the response to Kessy for Challenge Generation request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the result of challenge generation to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCalcChallengeResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsrawChallengeResult - Buffer used for a raw Challenge generation numCalcChallengeStatus - Status of a raw Challenge generation Input->Output-CorrelationResult of challenge generation gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCalcChallengeResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_554
References rawChallengeResult, numCalcChallengeStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCalcChallengeResp.
void CsH_Call_Ev_StCryptoKY_evCalcSignatureResp(void)
Event function of the CsH module. The function provides the response to Kessy for Signature Calculation request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the result of Signature calculation to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCalcSignatureResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsrawSignatureResult - Buffer for a Signature Check result numCalcSignatureStatus - Status of a Signature Check result Input->Output-CorrelationResult of Signature calculation gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCalcSignatureResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_409
References rawSignatureResult, numCalcSignatureStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCalcSignatureResp.
void CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp(void)
Event function of the CsH module. The function provides the response to Kessy for Checking the RSAD Signature request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the result of checking RSAD Signature to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCheckRSADSignatureResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsbRSASignatureValid - Boolean value denoting RSAD Signature validness numCheckRSASignatureStatus - Status of a RSAD Signature Check result Input->Output-CorrelationResult of checking RSAD Signature gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_539
References bRSASignatureValid, numCheckRSASignatureStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCheckRSADSignatureResp.
void CsH_Call_Ev_StCryptoKY_evCheckSignatureResp(void)
Event function of the CsH module. The function provides the response to Kessy for Checking the Signature request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the Status of checking Signature to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evCheckSignatureResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void GlobalsbSignatureValid - Boolean value denoting Signature validness numCheckSignatureStatus - Status of a Signature Check result Input->Output-CorrelationStatus of checking Signature gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evCheckSignatureResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_401
References bSignatureValid, numCheckSignatureStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evCheckSignatureResp.
void CsH_Call_Ev_StCryptoKY_evEncryptResp(void)
Event function of the CsH module. The function provides the response to Kessy for Encryption request. This function is called by KessyEventMngr to minimize the overhead on reaction for the function call. CryptoHandler shall report the Response for data encryption request to the calling application on the client-server interface by triggering Rte_Call_CsH_KYBCM_Ev_StCryptoKY_evEncryptResp. reentrant No context Rte layer thread safe Yes multicore safe No - All APIs needs to be called from the same core asynchronous Function is called by Kessy SWC N/A void void Globalsu8rawEncryptResult - Buffer for the Encryption Process Result numrawEncryptStatus - Status for data encryption request Input->Output-CorrelationStatus of data encryption request gets provided via RTE to Kessy SWC Call Sequence Test MethodSWATT unit test TEST_CsH_Call_Ev_StCryptoKY_evEncryptResp TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_544
References u8rawEncryptResult, numrawEncryptStatus.
Referenced by TEST_CsH_Call_Ev_StCryptoKY_evEncryptResp.
Std_ReturnType evEncryptReq(const uint8 *rawInputData, uint8 enSKC, const uint8 *rawKey)
This is the server function for handling the Encryption request from Kessy Please find detail information in header file.
References Rte_Call_CsH_KessyEvMngr_setEvRequest, u8rawEncryptResult, CSH_EN_SKC_RAW, CSH_ENCRYPTION_BUFFER_SIZE, KEY_BUFFER_SIZE, u32rawEncryptResultLength, CSH_EN_SKC_FFB, Standby_CsH_FfbSkc, CSH_EN_SKC_RSAD, numrawEncryptStatus.
Referenced by TEST_evEncryptReq.
Std_ReturnType evCalcChallengeReq(void)
This is the server function for handling the Challenge Generation request from Kessy Please find detail information in header file.
References Rte_Call_CsH_KessyEvMngr_setEvRequest, rawChallengeResult, numCalcChallengeStatus, Standby_CsH_FfbSkc, CSMPI_RESULT_LENGTH, randomNumberUsed_counter, RANDOM_NUMBER_COUNT, randomGenereted_Standby_Status, randomGenereted_Standby, CSH_ENCRYPTION_NOTPOSSIBLE.
Referenced by TEST_evCalcChallengeReq.
Std_ReturnType evCalcSignatureReq(boolean bMarkerDirection, const uint8 *rawFreshnessValue, const uint8 *rawNutzdaten, uint8 numNutzdatenLength)
This is the server function for handling the Signature Calculation request from Kessy Please find detail information in header file.
References numCalcSignatureStatus, CSH_ENCRYPTION_NOTPOSSIBLE, Rte_Call_CsH_KessyEvMngr_setEvRequest, rawSignatureResult, u8CalcSignatureReqBuffer, CSH_INPUTVECTOR_SIZE, Standby_CsH_FfbSkc, CSH_MARKERDIRECTION_SIZE, CSH_REFRESHNESS_BUFFER_SIZE, KEY_BUFFER_SIZE, u32rawEncryptResultLength, CSH_ENCRYPTION_BUFFER_SIZE, u8rawEncryptResult.
Referenced by TEST_evCalcSignatureReq.
Std_ReturnType evCheckRSADSignatureReq(const uint8 *rawInputData, uint8 numInputDataLength, const uint8 *rawSignatureToCheck, uint8 numSignatureLength)
This is the server function for handling the RSAD Signature Check request from Kessy Please find detail information in header file.
References numCheckRSASignatureStatus, CSH_ENCRYPTION_NOTPOSSIBLE, bRSASignatureValid, CSH_NUM_SIGNATURE_LENGTH_MIN, CSH_NUM_SIGNATURE_LENGTH_MAX, Rte_Call_CsH_KessyEvMngr_setEvRequest.
Referenced by TEST_evCheckRSADSignatureReq.
Std_ReturnType CheckSignature_ZKA(boolean bMarkerDirection, const uint8 *rawFreshnessValue, const uint8 *rawNutzdaten, uint8 numNutzdatenLength, const uint8 *rawSignatureToCheck, uint8 numSignatureLength)
This is the server function for handling the Signature Check request from FDH Please find detail information in header file.
References CSH_ENCRYPTION_INIT, Standby_CsH_FfbSkc, u8CheckSignatureReqBuffer, CSH_MARKERDIRECTION_SIZE, CSH_REFRESHNESS_BUFFER_SIZE, KEY_BUFFER_SIZE.
Referenced by TEST_CheckSignature_ZKA.
Std_ReturnType evCheckSignatureReq(boolean bMarkerDirection, const uint8 *rawFreshnessValue, const uint8 *rawNutzdaten, uint8 numNutzdatenLength, const uint8 *rawSignatureToCheck, uint8 numSignatureLength)
This is the server function for handling the Signature Check request from Kessy Please find detail information in header file.
References bSignatureValid, numCheckSignatureStatus, CSH_NUM_NUTZDATEN_LENGHT_MAX, CSH_NUM_SIGNATURE_LENGTH_MIN, CSH_NUM_SIGNATURE_LENGTH_MAX, Rte_Call_CsH_KessyEvMngr_setEvRequest, Standby_CsH_FfbSkc, u8CheckSignatureReqBuffer, CSH_MARKERDIRECTION_SIZE, CSH_REFRESHNESS_BUFFER_SIZE, KEY_BUFFER_SIZE.
Referenced by TEST_evCheckSignatureReq.
void CSH_CsmKeyExtractCallback(Std_ReturnType retVal)
Call-back function CSH_CsmKeyExtractCallback of the CsH module This function is called by CsmPi reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by CsmPi N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmKeyExtractCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Key Extraction. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmKeyExtractCallback.
void CSH_CsmRandomCallback(Std_ReturnType retVal)
Call-back function CSH_CsmRandomCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmRandomCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Random. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmRandomCallback.
void CSH_CsmMacVerifyCallback(Std_ReturnType retVal)
Call-back function CSH_CsmMacVerifyCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmMacVerifyCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Mac Verify. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmMacVerifyCallback.
void CSH_CsmMacGenerateCallback(Std_ReturnType retVal)
Call-back function CSH_CsmMacGenerateCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CSH_CsmMacGenerateCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Mac Generate. Function required by Csm. Currently not used.
Referenced by TEST_CSH_CsmMacGenerateCallback.
void CsH_CsmBlockEncryptCallback(Std_ReturnType retVal)
Call-back function CsH_CsmBlockEncryptCallback of the CsH module This function is called by CsmPi in Asyncmode reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core asynchronous Called by CsmPi in Asyncmode N/A Std_ReturnType retVal void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CsH_CsmBlockEncryptCallback TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Required Callback function for Csm Block Encrypt. Function required by Csm. Currently not used.
Referenced by TEST_CsH_CsmBlockEncryptCallback.