CsH_KeyLearning.c
NUMBER_OF_KEYS_RECEIVED
Constant describing amount of keys that can be received.Determines length bFFBSchluessel Used in CsH_Update_StanbyRAM_FfbData when updating RAM Data when clearing WCZInit and during copying of FDH Data in FFBDatenUebertragung In for loop in evFindSlotNumber. values 8u
WCZ_LENGTH
Constant used when preparing rolling counterUsed when preparing rolling counter in CsH_TaskCyclicEvent and FFBDatenUebertragung values 4u
WCZ_TRANSFER_OK
Constant indicating that WCZ was transfered correctly.Used in switch case construction in evFFBDataExchangeResp as status for WCZ transfer. values 0u
WCZ_TRANSFER_N_OK
Constant indicating that WCZ wasn't correctly transfered to FDHUsed in switch case construction in evFFBDataExchangeResp as status for WCZ transfer. values 1u
WCZ_TRANSFER_PENDING
Constant describing status of WCZ Transfer.Used in switch case construction in evFFBDataExchangeResp. Not used for now. values 2u
TRANSPONDER_ID_LENGTH
Constant used when copying transponder ID from PimUsed in CsH_Update_StanbyRAM_FfbData when copying transponder ID from Pim values 4u
FFB_DATEN_PACKET_LENGTH
Constant describing length of FFB DataUsed in checkAllDataPointers values 12u
KEY_FREQ_05
Constant describing key frequency with value of 0x05uUsed in FrequencyCheck when checking key frequency values 0x05u
KEY_FREQ_01
Constant describing key frequency with value of 0x01uUsed in FrequencyCheck when checking key frequency values 0x01u
KEY_FREQ_06
Constant describing key frequency with value of 0x06uUsed in FrequencyCheck when checking key frequency values 0x06u
KEY_FREQ_07
Constant describing key frequency with value of 0x07uUsed in FrequencyCheck when checking key frequency values 0x07u
KEY_FREQ_02
Constant describing key frequency with value of 0x02uUsed in FrequencyCheck when checking key frequency values 0x02u
KEY_FREQ_03
Constant describing key frequency with value of 0x03uUsed in FrequencyCheck when checking key frequency values 0x03u
TRANSPONDER_ID_NUM_01
ID of Transponder number 1Used in sendTransponderIDtoSam when sending ID with value of 1u to SAM values 1u
TRANSPONDER_ID_NUM_02
ID of Transponder number 2Used in sendTransponderIDtoSam when sending ID with value of 2u to SAM values 2u
TRANSPONDER_ID_NUM_03
ID of Transponder number 3Used in sendTransponderIDtoSam when sending ID with value of 3u to SAM values 3u
TRANSPONDER_ID_NUM_04
ID of Transponder number 4Used in sendTransponderIDtoSam when sending ID with value of 4u to SAM values 4u
TRANSPONDER_ID_NUM_05
ID of Transponder number 5Used in sendTransponderIDtoSam when sending ID with value of 5u to SAM values 5u
TRANSPONDER_ID_NUM_06
ID of Transponder number 6Used in sendTransponderIDtoSam when sending ID with value of 6u to SAM values 6u
TRANSPONDER_ID_NUM_07
ID of Transponder number 7Used in sendTransponderIDtoSam when sending ID with value of 7u to SAM values 7u
TRANSPONDER_ID_NUM_08
ID of Transponder number 8Used in sendTransponderIDtoSam when sending ID with value of 8u to SAM values 8u
SCHLUESSEL_KONFIGURATIONS_DATEN_01
Constant describing key configuration data with value of 0x03uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x01u
SCHLUESSEL_KONFIGURATIONS_DATEN_02
Constant describing key configuration data with value of 0x02uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x02u
SCHLUESSEL_KONFIGURATIONS_DATEN_03
Constant describing key configuration data with value of 0x03uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x03u
SCHLUESSEL_KONFIGURATIONS_DATEN_10
Constant describing key configuration data with value of 0x10uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x10u
SCHLUESSEL_KONFIGURATIONS_DATEN_20
Constant describing key configuration data with value of 0x20uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x20u
SCHLUESSEL_KONFIGURATIONS_DATEN_40
Constant describing key configuration data with value of 0x40uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x40u
SCHLUESSEL_KONFIGURATIONS_DATEN_80
Constant describing key configuration data with value of 0x80uUsed in vnumUHFKanalkonfiguration when configurating UHF channel values 0x80u
Rte_PimType_CsH_CsH_FfbSkc Standby_CsH_FfbSkc
FFB SKC variables stored in Standby RAMStores variables related to FFB SKC in the Standby RAM to enable quick extraction of the data on the wake up. range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_Update_StanbyRAM_FFBSKC(), CsH_Clear_StanbyRAM_FFBSKC, evEncryptReq(), evCalcChallengeReq(), evCalcSignatureReq(), CheckSignature_ZKA, evCheckSignatureReq(), CSH_getFFBSKCFlag()} protection {global variable for CsH_Task.c}
Referenced by evEncryptReq, evCalcChallengeReq, evCalcSignatureReq, CheckSignature_ZKA, evCheckSignatureReq, TEST_evEncryptReq, TEST_evCalcChallengeReq, TEST_evCalcSignatureReq, TEST_CheckSignature_ZKA, TEST_evCheckSignatureReq, CSH_getFFBSKCFlag, CsH_Update_StanbyRAM_FFBSKC, CsH_Clear_StanbyRAM_FFBSKC, TEST_FFBDatenUebertragung, TEST_CSH_getFFBSKCFlag, TEST_CsH_Update_StanbyRAM_FFBSKC, TEST_CsH_Clear_StanbyRAM_FFBSKC.
Rte_PimType_CsH_CsH_FfbData Standby_CsH_FfbData
FFB Data variables stored in Standby RAMStores variables related to FFB Data in the Standby RAM to enable quick extraction of the data on the wake up. range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_Update_StanbyRAM_FfbData(), CSH_getFFBDataFlag() CsH_Clear_StanbyRAM_FfbData(), FFBDatenUebertragung() evCheckTransponderID(), evFindSlotNumber()} protection {global variable for CsH_Task.c}
Referenced by evFindSlotNumber, CSH_getFFBDataFlag, evCheckTransponderID, CsH_Update_StanbyRAM_FfbData, CsH_Clear_StanbyRAM_FfbData, TEST_FFBDatenUebertragung, TEST_evFindSlotNumber, TEST_CSH_getFFBDataFlag, TEST_evCheckTransponderID, TEST_CsH_Update_StanbyRAM_FfbData, TEST_CsH_Clear_StanbyRAM_FfbData.
boolean bIsCsH_Stanby_Initializated
Standby RAM Initialization FlagIndicates if Standby RAM has been initialized. range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_InitVarFunc()} protection {global variable for CsH_Task.c}
Referenced by CsH_KeyHandler_Init, TEST_CsH_KeyHandler_Init.
boolean b_FFBSKCUebertragungReq
Flag used to start FFBSKC Key learning processBoolean value informing if WFS requested start of FFBSKC key learning process. Checked Cyclically in CsH_TaskCyclicEvent. range {0u - 1u } values N/A unit N/A resolution N/A context {task, used inside CsH_TaskCyclicEvent(), FFBSKCUebertragung()} protection {static global variable for CsH_Task.c}
Referenced by CsH_KeyHandler_Cyclic, FFBSKCUebertragung, FFBSKCUebertragung_WFS_Response, TEST_CsH_KeyHandler_Cyclic, TEST_FFBSKCUebertragung, TEST_FFBSKCUebertragung_WFS_Response.
uint8 u8_FFBSKCUebertragungResp
Response of FFBSKC Key learning processResponse about the operation result for Key Learning function in FFBDatenUebertragung range {0u, 1u } values N/A unit N/A resolution N/A context {task, used inside CsH_TaskCyclicEvent(), FFBDatenUebertragung()} protection {static global variable for CsH_Task.c}
Referenced by FFBSKCUebertragung, FFBSKCUebertragung_WFS_Response, TEST_FFBSKCUebertragung, TEST_FFBSKCUebertragung_WFS_Response.
boolean b_FFBDatenUebertragungReq
Flag used to start FFBDaten Key learning processBoolean value informing if WFS requested start of FFBDaten key learning process. Checked Cyclically in CsH_TaskCyclicEvent. range {0u - 1u } values N/A unit N/A resolution N/A context {task, used inside CsH_TaskCyclicEvent(), FFBDatenUebertragung()} protection {static global variable for CsH_Task.c}
Referenced by CsH_KeyHandler_Cyclic, FFBDatenUebertragung, FFBDatenUebertragungResp_WFS_Response, TEST_CsH_KeyHandler_Cyclic, TEST_FFBDatenUebertragungResp_WFS_Response.
boolean alreadyReSendWCZtoFDH
Boolean value denoting if Rolling Code Counter has already been sent to FDHDetermines if WCZ wasnt correctly transfered to FDH. is checked cyclically in CsH_TaskCyclicEvent . range {0u - 1u} values N/A unit N/A resolution N/A context {task, used inside CsH_TaskCyclicEvent(), evFFBDataExchangeResp()} protection {static global variable for CsH_Task.c}
Referenced by CsH_KeyHandler_Cyclic, evFFBDataExchangeResp, Resend_WCZ_to_FDH, TEST_CsH_KeyHandler_Cyclic, TEST_evFFBDataExchangeResp, TEST_Resend_WCZ_to_FDH.
boolean bFFBSchluessel[8u][8u]
Boolean Array denoting indexes of learned keysArray is assigned values read from Rte with True values under indexes that correspond to learned keys. range N/A values N/A unit N/A resolution N/A context {task, used inside CsH_TaskCyclicEvent(), FFBDatenUebertragung()} protection {static global variable for CsH_Task.c}
Referenced by FFBDatenUebertragung, Resend_WCZ_to_FDH.
uint8 u8_FFBDatenUebertragungResp
Response of FFBDaten Key learning processResponse about the operation result for Key Learning function in FFBDatenUebertragung range {0u, 1u } values N/A unit N/A resolution N/A context {task, used inside CsH_TaskCyclicEvent(), FFBDatenUebertragung()} protection {static global variable for CsH_Task.c}
Referenced by FFBDatenUebertragung, FFBDatenUebertragungResp_WFS_Response, TEST_FFBDatenUebertragung, TEST_FFBDatenUebertragungResp_WFS_Response.
uint8 s_schluesselkonfigurationsdaten
UHF Channel Configuration provided to WFSKey Configuration provided to WFS. Stores configuration for a key during FFB keylearning process. Contains information about keys frequency and if platform is MEB. range {0u - 255u } values N/A unit N/A resolution N/A context {task, used inside vnumUHFKanalkonfiguration()} protection {static global variable for CsH_Task.c}
Referenced by vnumUHFKanalkonfiguration, TEST_vnumUHFKanalkonfiguration.
static void CSH_SetDTC_035819_IfKeysNotLearned(void)
Set DTC 0x035819 to active if SKC and TransponderID are not learned This function is called in CSH cyclic fuction reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called in CSH cyclic fuction N/A void void Globalsnone Input->Output-CorrelationSets DTC_035819 If Keys are Not Learned Call Sequence Test MethodSWATT unit test TEST_CSH_SetDTC_035819_IfKeysNotLearned TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Satisfies requirementSWR_ICAS1_L3_CRY_339 Set DTC 0x035819 to active if SKC and TransponderID are not learned Please find detail information in the declaration.
References CSH_CheckDtc_035819Status.
Referenced by CsH_KeyHandler_Cyclic, TEST_CsH_KeyHandler_Cyclic, TEST_CSH_SetDTC_035819_IfKeysNotLearned.
static Std_ReturnType CSH_CheckDtc_035819Status(void)
Check if DTC 0x035819 is active This function is called by CSH_SetDTC_035819_IfKeysNotLearned reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by CSH_SetDTC_035819_IfKeysNotLearned N/A void Std_ReturnType retval - RTE Status for evaluated operation. Globalsnone Input->Output-CorrelationRte_Call_CsH_ZV_DemEventId_35819_GetEventStatus data determines RTE Status return value. Call Sequence Test MethodSWATT unit test TEST_CSH_CheckDtc_035819Status TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_330 Check if DTC 0x035819 is active Please find detail information in the declaration.
Referenced by CSH_SetDTC_035819_IfKeysNotLearned, TEST_CSH_CheckDtc_035819Status.
static void CsH_Update_StanbyRAM_FFBSKC(void)
Helper function for storing the FFB_SKC and the corresponding validity flag into Standby RAM reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called in CsH Init and Cyclic functions. N/A void void GlobalsStandby_CsH_FfbSkc - FFBSKC variables stored in Standby RAM Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CsH_Update_StanbyRAM_FFBSKC TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function storing the FFB_SKC data in Standby RAM. Helper function for storing the FFB_SKC and the corresponding validity flag into Standby RAM Please find detail information in the declaration.
References Standby_CsH_FfbSkc.
Referenced by CsH_KeyHandler_Init, FFBSKCUebertragung_WFS_Response, TEST_CsH_KeyHandler_Init, TEST_CsH_Update_StanbyRAM_FFBSKC.
static void CsH_Update_StanbyRAM_FfbData(void)
Helper function for storing the FFB Key data and the corresponding validity flag into Standby RAM reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called in CsH Init and Cyclic functions. N/A void void GlobalsStandby_CsH_FfbData - FFB Data variables stored in Standby RAM Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CsH_Update_StanbyRAM_FfbData TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function storing the FFB Ket data in Standby RAM. Helper function for storing the FFB Key data and the corresponding validity flag into Standby RAM Please find detail information in the declaration.
References NUMBER_OF_KEYS_RECEIVED, Standby_CsH_FfbData, TRANSPONDER_ID_LENGTH.
Referenced by CsH_KeyHandler_Init, FFBDatenUebertragungResp_WFS_Response, TEST_CsH_KeyHandler_Init, TEST_FFBDatenUebertragungResp_WFS_Response, TEST_CsH_Update_StanbyRAM_FfbData.
static void CsH_Clear_StanbyRAM_FFBSKC(void)
Helper function clearing data related to FFB SKC in the Standby RAM Sets CsH_FFBSKC_ValidationFlag to False and fill data in CsH_FFBSKC with zeroes in Standby_CsH_FfbSkc reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Triggered at the start of function FFBSKCUebertragung N/A void void GlobalsStandby_CsH_FfbSkc - FFBSKC variables stored in Standby RAM Input->Output-CorrelationFFBSKC related data stored in Standby RAM is cleared Call Sequence Test MethodSWATT unit test TEST_CsH_Clear_StanbyRAM_FFBSKC TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function clearing the FFB_SKC data in Standby RAM. Helper function clearing data related to FFB SKC in the Standby RAM Please find detail information in the declaration.
References Standby_CsH_FfbSkc.
Referenced by FFBSKCUebertragung, TEST_CsH_Clear_StanbyRAM_FFBSKC.
static void CsH_Clear_StanbyRAM_FfbData(void)
Helper function clearing data related to FFBData in the Standby RAM Sets CsH_FFBData_ValidationFlag to False and fills pFFBTransponderId with zeroes in Standby_CsH_FfbData reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Triggered at the start of function FFBSKCUebertragung N/A void void GlobalsStandby_CsH_FfbData - FFBData variables stored in Standby RAM Input->Output-CorrelationFFBData related data stored in Standby RAM is cleared Call Sequence Test MethodSWATT unit test TEST_CsH_Clear_StanbyRAM_FfbData TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function clearing the FFDData data in Standby RAM. Helper function clearing data related to FFBData in the Standby RAM Please find detail information in the declaration.
References Standby_CsH_FfbData.
Referenced by FFBSKCUebertragung, TEST_CsH_Clear_StanbyRAM_FfbData.
STATIC boolean checkAllDataPointers(const uint8 *rawDataPointer)
This function checks if the Learning Crypt is not equal to 0.This function checks if the Learning Crypt for given key slot received from WFS as part of FFB Key Learning trigger is not equal to 0. If case given Learning Crypt contains zero, then the Key Learning process is skipped for given key slot. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous FFB Key Learning trigger received by CsH N/A pointer of rawDataPointer - pointer to the array containing Learning Crypts for 8 key slots received from WFS. boolean - Status of the operation (ok/processing error) Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_checkAllDataPointers TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: Helper function checking the Learning Crypt. . This function checks if the Learning Crypt is not equal to 0. Please find detail information in the declaration.
References FFB_DATEN_PACKET_LENGTH.
Referenced by FFBDatenUebertragung, TEST_checkAllDataPointers.
STATIC boolean FrequencyCheck(uint8 keyFrequency)
This function checks if the Key Frequency for given key slot is consistent with ICAS1 configuration This function checks if the Key Frequency data included in the Learning Crypt for given key slot received from WFS as part of FFB Key Learning trigger is consistent with ICAS1 configuration. If case the Key Frequency is inconsistent with ICAS1 configuration, then the entire Key Learning process is ceased. reentrant No context task thread safe No multicore safe No synchronous FFB Key Learning triggered N/A uint8 keyFrequency - Key Frequency data included in the Learning Crypt boolean - Determines if frequency is valid/invalid Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_FrequencyCheck TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_702 This function checks if the Key Frequency for given key slot is consistent with ICAS1 configuration. Please find detail information in the declaration.
References KEY_FREQ_05, KEY_FREQ_01, KEY_FREQ_06, KEY_FREQ_07, KEY_FREQ_02, KEY_FREQ_03.
Referenced by FFBDatenUebertragung, TEST_FrequencyCheck.
static void sendTransponderIDtoSam(uint8 transponderID, uint8 *dataToBeSend)
This function provides TransponderID data over CAN to SAM during Key Learning process The function is called sequentially for all 8 key slots during Key Learning process and only after evaluation of the Learning Crypts received from WFS is successful. Based on the key number (i.e., key slot in range 0..7), the function sends the TransponderID data to SAM over CAN. The TransponderID data bytes are sent in reverted order. reentrant No context task thread safe No multicore safe No synchronous Called after evaluation of the Learning Crypts received from WFS is successful N/A uint8 transponderID - key number [in] pointer of dataToBeSend - pointer to the TransponderID data received from WFS void Globalsnone Input->Output-CorrelationTransponderID provided to SAM via RTE Call Sequence Test MethodSWATT unit test TEST_sendTransponderIDtoSam TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_CRY_388 This function provides TransponderID data over CAN to SAM during Key Learning process Please find detail information in the declaration.
References TRANSPONDER_ID_NUM_01, TRANSPONDER_ID_NUM_02, TRANSPONDER_ID_NUM_03, TRANSPONDER_ID_NUM_04, TRANSPONDER_ID_NUM_05, TRANSPONDER_ID_NUM_06, TRANSPONDER_ID_NUM_07, TRANSPONDER_ID_NUM_08.
Referenced by FFBDatenUebertragung, TEST_sendTransponderIDtoSam.
STATIC void vnumUHFKanalkonfiguration(void)
This function provides WFS with the UHF channel configuration for the keys. This function is called by RTE from WFS. The function provides UHF channel configuration to WFS, which will be further stored in the keys during the Key Learning process. The configuration of the UHF channel configuration is based on the coding parameters: c_Kessy_UWB_Frequenzband_[a|b|c]_aktiv. reentrant No context task thread safe No multicore safe No synchronous Function called by WFS N/A void void Globalss_schluesselkonfigurationsdaten - UHF Channel Configuration provided to WFS Input->Output-Correlations_schluesselkonfigurationsdaten provided via RTE Call Sequence Test MethodSWATT unit test TEST_vnumUHFKanalkonfiguration TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_431 SWR_ICAS1_L3_CRY_432 SWR_ICAS1_L3_CRY_433 SWR_ICAS1_L3_CRY_434 SWR_ICAS1_L3_CRY_435 This function provides WFS with the UHF channel configuration for the keys. Please find detail information in the declaration.
References s_schluesselkonfigurationsdaten, FUNK_FREQUENZ_01, SCHLUESSEL_KONFIGURATIONS_DATEN_03, FUNK_FREQUENZ_02, SCHLUESSEL_KONFIGURATIONS_DATEN_01, FUNK_FREQUENZ_03, SCHLUESSEL_KONFIGURATIONS_DATEN_02, SCHLUESSEL_KONFIGURATIONS_DATEN_10, SCHLUESSEL_KONFIGURATIONS_DATEN_20, SCHLUESSEL_KONFIGURATIONS_DATEN_40, SCHLUESSEL_KONFIGURATIONS_DATEN_80.
Referenced by CsH_KeyHandler_Cyclic, TEST_CsH_KeyHandler_Cyclic, TEST_vnumUHFKanalkonfiguration.
static void FFBSKCUebertragung_WFS_Response(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Prepare and send response to WFS during key learning process. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globalsb_FFBSKCUebertragungReq - Flag used to start FFBSKC Key learning process u8_FFBSKCUebertragungResp - Response of FFBSKC Key learning process bFFBSchluessel - Boolean Array denoting indexes of learned keys Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_FFBSKCUebertragung_WFS_Response TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_716 SWR_ICAS1_L3_CRY_717 SWR_ICAS1_L3_CRY_719 SWR_ICAS1_L3_CRY_720 SWR_ICAS1_L3_CRY_721 SWR_ICAS1_L3_CRY_344 SWR_ICAS1_L3_CRY_511 SWR_ICAS1_L3_CRY_429 SWR_ICAS1_L3_CRY_441 SWR_ICAS1_L3_CRY_725 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in the declaration.
References FUNK_FREQUENZ_03, b_FFBSKCUebertragungReq, u8_FFBSKCUebertragungResp, CsH_Update_StanbyRAM_FFBSKC.
Referenced by CsH_KeyHandler_Cyclic, TEST_CsH_KeyHandler_Cyclic, TEST_FFBSKCUebertragung_WFS_Response.
static void FFBDatenUebertragungResp_WFS_Response(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Prepare and send response to WFS during key learning process. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globals b_FFBDatenUebertragungReq - Flag used to start FFBDaten Key learning process u8_FFBDatenUebertragungResp - Response of FFBDaten Key learning process bFFBSchluessel - Boolean Array denoting indexes of learned keys Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_FFBDatenUebertragungResp_WFS_Response TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_392 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in the declaration.
References u8_FFBDatenUebertragungResp, b_FFBDatenUebertragungReq, CsH_Update_StanbyRAM_FfbData.
Referenced by CsH_KeyHandler_Cyclic, TEST_CsH_KeyHandler_Cyclic, TEST_FFBDatenUebertragungResp_WFS_Response.
static void Resend_WCZ_to_FDH(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. If Distributing RollingCodeCounters to ICAS1::FFBDataHandler faild then resend acction required reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globals alreadyReSendWCZtoFDH - Boolean value denoting if Rolling Code Counter has already been sent to FDH Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_Resend_WCZ_to_FDH TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_733 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in the declaration.
References NUMBER_OF_KEYS_RECEIVED, WCZ_LENGTH, bFFBSchluessel, alreadyReSendWCZtoFDH.
Referenced by CsH_KeyHandler_Cyclic, TEST_CsH_KeyHandler_Cyclic, TEST_Resend_WCZ_to_FDH.
void CsH_KeyHandler_Cyclic(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References b_FFBSKCUebertragungReq, FFBSKCUebertragung_WFS_Response, b_FFBDatenUebertragungReq, FFBDatenUebertragungResp_WFS_Response, alreadyReSendWCZtoFDH, Resend_WCZ_to_FDH, CSH_SetDTC_035819_IfKeysNotLearned, vnumUHFKanalkonfiguration.
Referenced by TEST_CsH_KeyHandler_Cyclic, CsH_TaskCyclicEvent.
void CsH_KeyHandler_Init(void)
CsH init function called by scheduler. Please find detail information in header file.
References bIsCsH_Stanby_Initializated, CsH_Update_StanbyRAM_FFBSKC, CsH_Update_StanbyRAM_FfbData.
Referenced by TEST_CsH_KeyHandler_Init, CsH_InitVarFunc.
Std_ReturnType FFBSKCUebertragung(const uint8 *rawFFBSKC)
Server function for FFB_SKC Learning process triggered by WFS Please find detail information in header file.
References CsH_Clear_StanbyRAM_FFBSKC, CsH_Clear_StanbyRAM_FfbData, u8_FFBSKCUebertragungResp, b_FFBSKCUebertragungReq.
Referenced by TEST_FFBSKCUebertragung.
Std_ReturnType FFBDatenUebertragung(boolean bFFBSchluesselNr1, boolean bFFBSchluesselNr2, boolean bFFBSchluesselNr3, boolean bFFBSchluesselNr4, boolean bFFBSchluesselNr5, boolean bFFBSchluesselNr6, boolean bFFBSchluesselNr7, boolean bFFBSchluesselNr8, const uint8 *rawFFBDatenPaket1, const uint8 *rawFFBDatenPaket2, const uint8 *rawFFBDatenPaket3, const uint8 *rawFFBDatenPaket4, const uint8 *rawFFBDatenPaket5, const uint8 *rawFFBDatenPaket6, const uint8 *rawFFBDatenPaket7, const uint8 *rawFFBDatenPaket8)
Server function for FFB_SKC Learning process triggered by WFS Please find detail information in header file.
References u8_FFBDatenUebertragungResp, NUMBER_OF_KEYS_RECEIVED, bFFBSchluessel, b_FFBDatenUebertragungReq, checkAllDataPointers, FrequencyCheck, WCZ_LENGTH, sendTransponderIDtoSam.
Referenced by TEST_FFBDatenUebertragung.
Std_ReturnType evFindSlotNumber(const uint8 *ReceivedTransponderID, uint8 *slotNumber)
This function is used to provide the Key index of the key with given TransponderID Please find detail information in header file.
References NUMBER_OF_KEYS_RECEIVED, Standby_CsH_FfbData.
Referenced by TEST_evFindSlotNumber.
void evFFBDataExchangeResp(uint8 saveWCZStatus)
This function returns a status of storing the Rolling Code Counter by FDH which is part of the FFB Data Learning process. Please find detail information in header file.
References WCZ_TRANSFER_OK, WCZ_TRANSFER_N_OK, alreadyReSendWCZtoFDH, WCZ_TRANSFER_PENDING.
Referenced by TEST_evFFBDataExchangeResp.
boolean CSH_getFFBSKCFlag(void)
Getter Function for FFBSKC Validation Flag Please find detail information in header file.
References Standby_CsH_FfbSkc.
Referenced by TEST_CSH_getFFBSKCFlag.
boolean CSH_getFFBDataFlag(void)
Getter Function for FFBData Validation Flag Please find detail information in header file.
References Standby_CsH_FfbData.
Referenced by TEST_CSH_getFFBDataFlag.
Std_ReturnType evCheckTransponderID(uint8 KeyIndex, const uint8 *ReceivedTransponderID)
This function checks if the TransponderID stored in the Standby RAM for the key number is the same as received in ReceivedTransponderID Please find detail information in header file.
References Standby_CsH_FfbData.
Referenced by TEST_evCheckTransponderID.