CsH_Task.h
void CsH_InitVarFunc(void)
CsH init function called by scheduler. On Entrance calls init function from other unit reentrant No context task thread safe Yes multicore safe No - All APIs needs to be called from the same core synchronous System after wake up/reset, in EnterRUN. N/A void void GlobalsbIsCsH_Stanby_Initializated - Standby RAM Initialization Flag Input->Output-CorrelationIf Standby RAM hadn't been previously initialized - CsH performs initialization with data for FFB SKC and FFB Data Call Sequence Test MethodSWATT unit test TEST_CsH_InitVarFunc TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: component init function to be called by scheduler. CsH init function called by scheduler. Please find detail information in header file.
References CsH_KeyHandler_Init.
Referenced by TEST_CsH_InitVarFunc.
void CsH_Start(void)
Initialization routine, called once on each EnterRun event by scheduler No functionality, required by architecture. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous System after wake up/reset, in EnterRUN. N/A void void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CsH_Start TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: component init function to be called by scheduler.
Referenced by TEST_CsH_Start.
void CsH_Stop(void)
De-Initialization routine, to be called once on each ExitRun event.This function is called by ModelsTask when the StopEv is set (MmDoStop is called). Here is a good place to save data to NvRAM. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous System leaves RUN mode, prepares to sleep. N/A void void Globalsnone Input->Output-CorrelationN/A Call Sequence Test MethodSWATT unit test TEST_CsH_Stop TraceabilitySatisfies following DOORS Requirements or Design Decision: Design Decision - Justification. Design decision: component de-init function called by scheduler, currently not used.
Referenced by TEST_CsH_Stop.
void CsH_TaskCyclicEvent(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Calls CsH_Prepare_RteBuffer and cyclic function from other units reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Called by the Scheduler in a predefined cycle N/A void void Globalsnone Input->Output-CorrelationCommunicates and exchanges Data with UHF and FFB Data Handler during Key learning process Call Sequence Test MethodSWATT unit test TEST_CsH_TaskCyclicEvent TraceabilitySatisfies following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_L3_CRY_725 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References CsH_Prepare_RteBuffer, CsH_KeyHandler_Cyclic, CsH_CryptoOperations_Cyclic.
Referenced by TEST_CsH_TaskCyclicEvent.