FDH_WCZ_Handler.c
USE_WCZ
USE_WCZ_PENDING
NUM_WCZ_LENGTH
Number of NVM blocks for each key to store RollingCodeCounter data. values 3u Satisfies requirementSWR_L3_CRoute_FFB_457
WCZ_INDEX_0
Value for first NVM block to store RollingCodeCounter data. values 0u Satisfies requirementSWR_L3_CRoute_FFB_457
WCZ_INDEX_1
Value for second NVM block to store RollingCodeCounter data. values 1u Satisfies requirementSWR_L3_CRoute_FFB_457
WCZ_INDEX_2
Value for third NVM block to store RollingCodeCounter data. values 2u Satisfies requirementSWR_L3_CRoute_FFB_457
NUM_WCZ_SLOTS
Value reflecting number of NVM blocks to store current and previous/next values of the RollingCodeCounters. values 2u Satisfies requirementSWR_L3_CRoute_FFB_458
SLOT_INDEX_A
Value reflecting first group of blocks containing data for RollingCodeCounterX. values 0u Satisfies requirementSWR_L3_CRoute_FFB_458
SLOT_INDEX_B
Value reflecting second group of blocks containing data for RollingCodeCounterX + 1. values 1u Satisfies requirementSWR_L3_CRoute_FFB_458
KEY_STATUS_UNKNOWN
Init value for sNvmWcz sStatus.u8Backup. values 0xFFu
KEY_STATUS_OK
Value reflecting status of the key - OK status. values 0x01u Satisfies requirementSWR_L3_CRoute_FFB_427
KEY_STATUS_INACTIVE_SELF_SYNC_1
Condition check value for key synchronization and key status validation. values 0x01u Satisfies requirementSWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_465.
KEY_STATUS_INACTIVE_SELF_SYNC_2
Condition check value for key synchronization and key status validation. values 0x02u Satisfies requirementSWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_465.
KEY_STATUS_INACTIVE_SELF_SYNC_3
Condition check value for key synchronization and key status validation. values 0x03u Satisfies requirementSWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_465.
KEY_STATUS_INACTIVE_MECH_KESSY
Value indicating key deactivation. values 0x04u Satisfies requirementSWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_464.
KEY_STATUS_DISABLED
Value indicating inactive key. values 0x05u
DATA_NVM_READY
Value indicating that NVM can be written to. values 0x00u
DATA_NVM_SLOT_A_WR
Value used for setting NVM write flag. values 0x01u
DATA_NVM_SLOT_WR
Function-like macro used to set flag for NVM write on passed bit.
DATA_NVM_STATUS_WR
Bit 4 for flags sNvmWcz sFlags u8Write and u8Exchange. values 0x04u
DATA_NVM_SLOT_A_RD
Value used for setting NVM read flag. values 0x10u
DATA_NVM_SLOT_B_RD
Value used for sNvmWcz sFlags.u8Write initialization. values 0x20u
DATA_NVM_SLOT_RD
Function-like macro used to set flag for NVM read on passed bit.
DATA_NVM_STATUS_RD
Bit 7 for flags sNvmWcz sFlags.u8Write and sFlags.u8Exchange. values 0x40u
TICKS_PER_SECOND
Value reflecting period (incPeriod) after which the RollingCodeCounter is increased by incCnt. 100(const value) * 10ms (one cycle) = 1000ms = 1s values 100u Satisfies requirementSWR_L3_CRoute_FFB_317
COUNTER_MAX_INC
Max. number (maxInc) of RollingCodeCounter increases that follow after a button actuation in a time-triggered way values 10u Satisfies requirementSWR_L3_CRoute_FFB_318
WCZ_INC_COUNT
Increment (incCnt) by which the RollingCodeCounter is increased after incPeriod has elapsed. values 3u Satisfies requirementSWR_L3_CRoute_FFB_315
WCZ_INC_PER_BUTTON
Value used to update the capture ranges (IncreasePerButtonAcutation).Used to calculate offset WCZ_RANGE_1_OFFSET and WCZ_RANGE_2_OFFSET values 4u Satisfies requirementSWR_L3_CRoute_FFB_434
WCZ_RANGE_1_PARAM
Value reflecting 10 button actuations.Used to calculate offset WCZ_RANGE_1_OFFSET. values 10u Satisfies requirementSWR_L3_CRoute_FFB_328
WCZ_RANGE_1_OFFSET
Value reflecting capture range 1, used by WCZ_CalculateRange.WCZ_RANGE_1_PARAM * ( COUNTER_MAX_INC * WCZ_INC_COUNT + WCZ_INC_PER_BUTTON ). values 340u Satisfies requirementSWR_L3_CRoute_FFB_328
WCZ_RANGE_2_PARAM
Value reflecting 300 button actuations.Used to calculate offset WCZ_RANGE_2_OFFSET. values 300u Satisfies requirementSWR_L3_CRoute_FFB_346
WCZ_RANGE_2_OFFSET
Value reflecting capture range 1, used by WCZ_CalculateRange.WCZ_RANGE_2_PARAM * ( COUNTER_MAX_INC * WCZ_INC_COUNT + WCZ_INC_PER_BUTTON ). values 10540u Satisfies requirementSWR_L3_CRoute_FFB_346
WCZ_RANGE_1
Value for Rolling Code Counter capture range number 1.Range 0 - 340. values 1u Satisfies requirementSWR_L3_CRoute_FFB_328
WCZ_RANGE_2
Value for Rolling Code Counter capture range number 2.Range 341 - 10540. values 2u Satisfies requirementSWR_L3_CRoute_FFB_346
WCZ_RANGE_3
Value for Rolling Code Counter capture range number 3.Range 10541 and above. values 3u Satisfies requirementSWR_L3_CRoute_FFB_347
WCZ_EXCHANGE_OK
Value informing that NVM storage was successfully completed.Used by WCZ_DataExchangeResponse. values 0u Satisfies requirementSWR_L3_CRoute_FFB_451
WCZ_EXCHANGE_ERR
Value informing that problem was encountered during NVM storage attempt.Used by WCZ_DataExchangeResponse. values 1u Satisfies requirementSWR_L3_CRoute_FFB_451
WCZ_EXCHANGE_INPROG
Value informing that data exchange/NVM storage is in progress.Used by WCZ_DataExchangeResponse. values 2u Satisfies requirementSWR_L3_CRoute_FFB_451
NVM_OFFSET_3
Value needed for calculation of index of nvm functions, SLOT_INDEX_A and B has 3 elements values 3u
ROLLING_CODE_COUNTERS_COUNT
Value reflecting number of PIMs for rolling code counters with backups. values 6u
S_WCZ_Group sNvmWcz
Variable to store rolling code counter.Structure holds data for slots, flags, timers, counters, statuses and NVM buffers. values N/A unit N/A resolution N/A context {task, used by multiple functions} protection {static global variable for FDH_Task.c}
Referenced by WCZ_KeyStatusValidation, WCZ_CheckKeyActive, WCZ_SetupSlot, WCZ_Synchronization, WCZ_SetStatus, WCZ_StatusReadFromNvm, WCZ_StatusWriteToNvm, WCZ_StatusVerifyNvm, WCZ_SetValue, WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm, WCZ_TimerReset, WCZ_CounterReset, WCZ_Initialization, WCZ_TimerHandle, evFFBDataExchange, WCZ_Validate, TEST_WCZ_KeyStatusValidation, TEST_WCZ_CheckKeyActive, TEST_WCZ_SetupSlot, TEST_WCZ_Synchronization, TEST_WCZ_SetStatus, TEST_WCZ_StatusReadFromNvm, TEST_WCZ_StatusWriteToNvm, TEST_WCZ_StatusVerifyNvm, TEST_WCZ_SetValue, TEST_WCZ_ValueReadFromNvm, TEST_WCZ_ValueWriteToNvm, TEST_WCZ_ValueVerifyNvm, TEST_WCZ_TimerReset, TEST_WCZ_CounterReset, TEST_WCZ_Initialization, TEST_WCZ_TimerHandle, TEST_evFFBDataExchange, TEST_WCZ_Validate.
Std_ReturnType(*const GetErrorStatus[ 6u ])(NvM_RequestResultType *ptr)[6u])(NvM_RequestResultType *ptr)
Const variable holding pointers to RTE call functions.Array elements point to NvM_GetErrorStatusresult calls, returning result of the last asynchronous request for the given block ID. values N/A unit N/A resolution N/A context {task, used by multiple functions} protection {static global variable for FDH_Task.c}
Referenced by WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm.
Std_ReturnType(*const WriteBlock[ 6u ])(const void *ptr)[6u])(const void *ptr)
Const variable holding pointers to RTE call functions.Array elements point to NvM_WriteBlock calls, called to copy the data of the RAM block to its corresponding NV block. values N/A unit N/A resolution N/A context {task, used by multiple functions} protection {static global variable for FDH_Task.c}
Referenced by WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm.
static boolean WCZ_SlotIndexValidation(const uint8 SlotIndex)
Function validating if slot value is in range reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 SlotIndex - 0..1 (i.e. A,B) slots are allowed only. boolean - True if within range. GlobalsN/A Input->Output-CorrelationN/A Activity Diagram WCZ_SlotIndexValidation Test MethodSWATT unit test. The testing method is described in TEST_WCZ_SlotIndexValidation TraceabilityDesign Decision - Justification. Design decision: helper function for value validation. Function validating if slot value is in range Please find detail information in the declaration.
References SWATT_BYPASS, SLOT_INDEX_A, SLOT_INDEX_B, bTrue, bFalse.
Referenced by WCZ_SetValue, WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm, TEST_WCZ_SlotIndexValidation, TEST_WCZ_SetValue, TEST_WCZ_ValueReadFromNvm, TEST_WCZ_ValueWriteToNvm, TEST_WCZ_ValueVerifyNvm.
static uint8 WCZ_CalculateRange(const uint32 u32WczIn, const uint32 u32WczCalc)
Function calculating one of three possible WCZ ranges.Determine the range, basing on the difference between calculated (estimated) and received WCZ. Defined ranges are: 0..340 (1) 341..10540 (2) or >10540 (3). reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_328} {SWR_L3_CRoute_FFB_346} {SWR_L3_CRoute_FFB_347} uint8 u32WczIn - recently received WCZ rolling code in FZV telegram. [in] uint8 u32WczCalc - internally calculated / estimated WCZ value. uint8 - 1..3 - one of these ranges is determined GlobalsN/A Input->Output-CorrelationThe function is called from UHF_CyclicHandle, when WCZ calculation is performed, the result comparison performed in this function causes either confirmation of validity and activating output signals via ButtonCodeReport or discarding telegram and incrementing error counter. Activity Diagram WCZ_CalculateRange Test MethodSWATT unit test. The testing method is described in TEST_WCZ_CalculateRange TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_L3_CRoute_FFB_346. SWR_L3_CRoute_FFB_347 SWR_L3_CRoute_FFB_328. Design Decision - Justification. Helper function to reduce UHF_CyclicHandle code size. Function calculating one of three possible WCZ ranges.Please find detail information in the declaration.
References SWATT_BYPASS, WCZ_RANGE_3, WCZ_RANGE_1_OFFSET, WCZ_RANGE_1, WCZ_RANGE_2_OFFSET, WCZ_RANGE_2.
Referenced by WCZ_Validate, TEST_WCZ_CalculateRange, TEST_WCZ_Validate.
static boolean WCZ_KeyStatusValidation(const uint8 KeyIndex)
Key status validation.Status of the key, stored in NV have allowable values (0..5). reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_427} {SWR_L3_CRoute_FFB_412} {SWR_L3_CRoute_FFB_467} {SWR_L3_CRoute_FFB_478} uint8 KeyIndex - Index pointing out proper key in the table, where status is available for check (sNvmWcz.sStatus.u8Backup) boolean - returns true if passed value is within correct range. GlobalssNvmWcz sStatus.u8Backup - read value. Input->Output-CorrelationIn use during error handling by NVM read to determine status of specific key (index), then Plausibility DTC is called afterwards with prepass/prefailed status. Alternative use case - UHF_CyclicHandle checks through WCZ_CheckKeyActive func if key is disabled or not before processing of incoming UHF telegram. Activity Diagram WCZ_KeyStatusValidation Test MethodSWATT unit test. The testing method is described in TEST_WCZ_KeyStatusValidation Verification criteriaTestcase shall check if function returns true for correct value range. TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_412. SWR_L3_CRoute_FFB_467. SWR_L3_CRoute_FFB_478. Key status validation.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, KeyIndexValidation, sNvmWcz, FDH_KeyIndexToIndex, KEY_STATUS_OK, KEY_STATUS_INACTIVE_SELF_SYNC_1, KEY_STATUS_INACTIVE_SELF_SYNC_2, KEY_STATUS_INACTIVE_SELF_SYNC_3, KEY_STATUS_INACTIVE_MECH_KESSY, KEY_STATUS_DISABLED, bTrue.
Referenced by WCZ_CheckKeyActive, WCZ_StatusReadFromNvm, TEST_WCZ_KeyStatusValidation, TEST_WCZ_CheckKeyActive, TEST_WCZ_StatusReadFromNvm.
static boolean WCZ_CheckKeyActive(const uint8 KeyIndex)
Check if status of the key, stored in NV have "active" values (0..4). reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_427} {SWR_L3_CRoute_FFB_412} {SWR_L3_CRoute_FFB_467} {SWR_L3_CRoute_FFB_478} uint8 KeyIndex - Index pointing out proper key in the table, where status is available for check (sNvmWcz.sStatus.u8Backup) boolean - returns true if passed value is within correct range. GlobalssNvmWcz sStatus.u8Backup - read value. Input->Output-CorrelationUHF_CyclicHandle checks if key is disabled or not before processing of incoming UHF telegram or not before processing of incoming UHF telegram. Activity Diagram WCZ_CheckKeyActive Test MethodSWATT unit test. The testing method is described in TEST_WCZ_CheckKeyActive Verification criteriaTestcase shall check if function returns true for correct value range. TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_412. SWR_L3_CRoute_FFB_467. SWR_L3_CRoute_FFB_478. Check if status of the key, stored in NV have "active" values (0..4).Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, WCZ_KeyStatusValidation, KEY_STATUS_DISABLED, sNvmWcz, FDH_KeyIndexToIndex, bTrue.
Referenced by WCZ_Validate, TEST_WCZ_CheckKeyActive, TEST_WCZ_Validate.
static void WCZ_SetupSlot(const uint8 KeyIndex)
Function for alternative slot setup.On each call of the function alternative NV slot is set up (A->B->A->B... etc), assuming same key is in use, which is then used to store current WCZ/WCZstatus. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_458} uint8 KeyIndex - Index pointing out proper key in the table, where WCZ is available for read out check. void GlobalssNvmWcz sValue.u32Backup - read value. sNvmWcz sSlot.u8Current - write value. sNvmWcz sSlot.u8Current - write value. Input->Output-CorrelationCalled from UHF_CyclicHandle when First telegram is processed to prepare for NVM storage of new WCZ. Activity Diagram WCZ_SetupSlot Test MethodSWATT unit test. The testing method is described in TEST_WCZ_SetupSlot TraceabilitySatisfies following DOORS Requirement and desing decision: Satisfies requirementSWR_L3_CRoute_FFB_458. SWR_L3_CRoute_FFB_459. Design Decision - Justification. Helper function to reduce UHF_CyclicHandle code size. Function for alternative slot setup.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, KeyIndexValidation, sNvmWcz, SLOT_INDEX_A, FDH_KeyIndexToIndex, SLOT_INDEX_B.
Referenced by WCZ_Validate, TEST_WCZ_SetupSlot, TEST_WCZ_Validate.
static boolean WCZ_CheckConsistency(const uint32 valueA, const uint32 valueB, const uint32 valueC, uint32 *valueOut)
Function comparing 3 copies of rolling code counter data.Compares 3 copies of WCZ and determines if at least 2 are the same. If so, the value is transferred to output buffer, otherwise 0. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_117} uint32 valueA, valueB, valueC - 3 copies of WCZ to compare and determine output value. [out] uint32 *valueOut - returns value of at least 2 same copies or 0. boolean - true if at least 2 copies are same. GlobalsN/A Input->Output-CorrelationCalled during read or verification of NVM WCZ triple storage to determine if value is corrupted or is fine to use. Activity Diagram WCZ_CheckConsistency Test MethodSWATT unit test. The testing method is described in TEST_WCZ_CheckConsistency TraceabilitySatisfies following DOORS Requirement: Satisfies requirementSWR_L3_CRoute_FFB_117 Function comparing 3 copies of rolling code counter data.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, bTrue.
Referenced by WCZ_ValueReadFromNvm, WCZ_ValueVerifyNvm, TEST_WCZ_CheckConsistency, TEST_WCZ_ValueReadFromNvm, TEST_WCZ_ValueVerifyNvm.
static void WCZ_PlausibleDTC(const uint8 KeyIndex, const Dem_EventStatusType status)
Function for handling of DEM event interface.Function is handling DEM event interface for all theoretically configurable key indices regarding "Remote Key Plausibility" fault. If all of NVM stored 3 copies of WCZ, when read back, show different values, fault is reported. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 KeyIndex - key index with valid range 1..8 [in] Dem_EventStatusType status - if at least 2 copies are not the same, DTC = DEM_EVENT_STATUS_PREFAILED, otherwise = DEM_EVENT_STATUS_PREPASSED void GlobalsN/A Input->Output-CorrelationCalled during Read/Verify/Write process of NVM WCZ storage, when retrieved value is corrupted or when process is successful. One DTC per key index is defined but due to data organization, all DTCs are tested together either with prepassed or prefailed status. Activity Diagram WCZ_PlausibleDTC Test MethodSWATT unit test. The testing method is described in TEST_WCZ_PlausibleDTC TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_GW_3263. SWR_ICAS1_GW_3268. SWR_ICAS1_GW_3272. SWR_ICAS1_GW_3276. SWR_ICAS1_GW_3280. SWR_ICAS1_GW_3284. SWR_ICAS1_GW_3288. SWR_ICAS1_GW_3292. SWR_L3_CRoute_FFB_118, SWR_L3_CRoute_FFB_132. Function for handling of DEM event interface.Please find detail information in the declaration.
References SWATT_BYPASS, KEY_INDEX_1, UNUSED_RETVAL, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8.
Referenced by WCZ_StatusReadFromNvm, WCZ_StatusWriteToNvm, WCZ_StatusVerifyNvm, WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm, TEST_WCZ_PlausibleDTC, TEST_WCZ_ValueReadFromNvm, TEST_WCZ_ValueWriteToNvm, TEST_WCZ_ValueVerifyNvm.
static void WCZ_Synchronization(void)
Function requests synchronization of last used key to NVM.Function requests immediate synchronization (to NVM) of last used key i.e. of recently received WCZ in first frame (within last FZV burst), if one of following conditions is met: KL15 is active and authorized with last KeyFob OR Entry via Kessy with Last Keyfob is succesfull. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_479} {SWR_L3_CRoute_FFB_482} void void GlobalssNvmWcz sStatus.u8Backup - R access to determine key index status. sNvmWc. sStatus.u8LastKeyIndex - R access to determine last key index status. Input->Output-CorrelationThere are 2 external scenarios, which force last used key re-synchronization if status is not OK due to WCZ received in range 2 or 3. The key transmitted FFB telegrams afterwards are processed again. NVM synchronization of WCZ value/status is triggered. Activity Diagram WCZ_Synchronization Test MethodSWATT unit test. The testing method is described in TEST_WCZ_Synchronization TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_479. SWR_L3_CRoute_FFB_482. Function requests synchronization of last used key to NVM.Please find detail information in the declaration.
References SWATT_BYPASS, KEY_INDEX_UNSET, sNvmWcz, FDH_KeyIndexToIndex, KEY_STATUS_INACTIVE_SELF_SYNC_1, KEY_STATUS_INACTIVE_SELF_SYNC_2, KEY_STATUS_INACTIVE_SELF_SYNC_3, KEY_STATUS_INACTIVE_MECH_KESSY, bFalse, UNUSED_RETVAL, WCZ_SetStatus, KEY_STATUS_OK.
Referenced by WCZ_CyclicHandle, TEST_WCZ_Synchronization, TEST_WCZ_CyclicHandle.
static void WCZ_SetStatus(const uint8 KeyIndex, const uint8 status)
Function setting up specified key status in NVM.Status for specified key is copied to buffer and flags are set to write it to NVM and read back to verify. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_520} uint8 KeyIndex - key index with valid range 1..8. . [in] uint8 status - value to be stored in internal status buffer and written to NVM. void GlobalssNvmWcz sValue.u32Backup - read and write value. sNvmWcz sValue.u8Write - write value. sNvmWcz sValue.u8Read - write value. Input->Output-CorrelationStatus change triggering synchronization with NVM - 3 call scenarios possible: evFFBDataExchange (learning procedure), UHF_CyclicHandle (after First Telegram range determined), WCZ_Synchronization (one of sync conditions fulfilled). As a result, NVM synch W/V procedure of specific key status is requested. Activity Diagram WCZ_SetStatus Test MethodSWATT unit test. The testing method is described in TEST_WCZ_SetStatus TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_520. Function setting up specified key status in NVM.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, KeyIndexValidation, sNvmWcz, FDH_KeyIndexToIndex, CLR_FLAG, DATA_NVM_STATUS_RD, SET_FLAG, DATA_NVM_STATUS_WR.
Referenced by WCZ_Synchronization, evFFBDataExchange, WCZ_Validate, TEST_WCZ_SetStatus.
static void WCZ_StatusReadFromNvm(void)
Status of all keys is transferred from NVM to internal buffers.In "real" use after wake up or reset, otherwise no effect. The simplified flow is: clear all R/W flags set statuses and validity to invalid for all keys, clear last key check status of NVM block --- if block is OK, read NV data to internal buffer (status[], valid[], last key) --- if block is corrupted, rewrite block with values in internal buffers --- if unknown status of NV or unknown status of the key read, then set prefail Key Plausibility DTCs --- if block is busy, skip checks for now reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssNvmWcz sFlags.u8Read - R/W access, trigger for read sNvmWcz sFlags.u8Write - W access, unconditional clear sNvmWcz sFlags.bValid - R/W access, flag set when read process is successful sNvmWcz sStatus.u8Backup - W access, status byte for each WCZ key, working copy mirrored in NVM status bytes sNvmWcz sStatus.sEntry.nvm_id - NV stack block identifier, referenced as parameter to function call sNvmWcz sStatus.pim_ptr->rb_fdh_Retry - R/W access, restored from NVM, reinit in case of corrupted data. sNvmWcz sStatus.u8LastKeyIndex -R/W access, restored from NVM, reinit in case of corrupted data. Input->Output-CorrelationInput: NVM block; NVM block status check via NvM_GetErrorStatus(), trigger for read flag, see Globals Called from WCZ_CyclicHandle periodically (every 10ms). However read from NVM operation is triggered (flag DATA_NVM_STATUS_RD set) only during system wake up initialization WCZ_Initialization. Output: output data is available in Globals, In case of detected corrupted NVM block or invalid state of NVM block, DTCs for all keys (8) "WCZ plausible" is tested as prefail. Activity Diagram WCZ_StatusReadFromNvm Test MethodSWATT unit test. The testing method is described in TEST_WCZ_StatusReadFromNvm TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_118. Status of all keys is transferred from NVM to internal buffers.Please find detail information in the declaration.
References SWATT_BYPASS, DATA_NVM_STATUS_RD, sNvmWcz, CLR_FLAG, DATA_NVM_STATUS_WR, NUM_KEY_LENGTH, bFalse, KEY_STATUS_UNKNOWN, KEY_INDEX_UNSET, RTE_E_OK, bTrue, WCZ_KeyStatusValidation, FDH_IndexToKeyIndex, WCZ_PlausibleDTC, UNUSED_RETVAL.
Referenced by WCZ_CyclicHandle, TEST_WCZ_StatusReadFromNvm, TEST_WCZ_CyclicHandle.
static void WCZ_StatusWriteToNvm(void)
Status of all keys is transferred to NVM from internal buffers.Write in case of status change of any key. The simplified flow is: check status of NVM block --- if block is OK, write NV status[], valid[], last key --- if block is corrupted, but in learning procedure, write NV status[], valid[], last key --- if unknown status of NV block or integrity failed, then set prefail Key Plausibility DTCs in addition, if write to NV during learning procedure is ok, send response to C/S request reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_413} void void GlobalssNvmWcz sFlags.u8Write - R/W access, triggers for write operation, cleared when request processed. sNvmWczs Flags.u8Exchange - R/W access, always set during learning together with u8Write flag to generate C/S response for evFFBDataExchange by calling WCZ_DataExchangeResponse. sNvmWcz sFlags.bValid - R/W access, flag set when unknown status of NVM block. sNvmWcz sStatus.u8Backup - R access, status byte for each WCZ key, copied to NVM status bytes buffer to write to NVM. sNvmWcz sStatus.u8LastKeyIndex -R access, copied to NVM buffer to write to NVM.d sNvmWcz sStatus.pim_ptr->rb_fdh_Retry - R/W access, restored from NVM, reinit in case of corrupted data. Input->Output-CorrelationInput: input data and write trigger is available in Globals, NVM block status check via NvM_GetErrorStatus() Called cyclically from WCZ_CyclicHandle. Requested write operation (by DATA_NVM_STATUS_WR flag set in u8Write byte) from UHF_CyclicHandle via WCZ_SetStatus. Alternatively sporadic request during learning procedure from evFFBDataExchange. Output: NVM block write triggered holding WCZ status information. DTC plausible tested with prefailed status when unknown status of NVM block. During learning procedure response is generated through WCZ_DataExchangeResponse to evFFBDataExchange Activity Diagram WCZ_StatusWriteToNvm Test MethodSWATT unit test. The testing method is described in TEST_WCZ_StatusWriteToNvm TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_118. SWR_L3_CRoute_FFB_413. Status of all keys is transferred to NVM from internal buffers.Please find detail information in the declaration.
References SWATT_BYPASS, IS_SET_FLAG, sNvmWcz, DATA_NVM_STATUS_WR, RTE_E_OK, NUM_KEY_LENGTH, CLR_FLAG, WCZ_DataExchangeResponse, DATA_NVM_READY, bTrue, bFalse, WCZ_PlausibleDTC, FDH_IndexToKeyIndex.
Referenced by WCZ_CyclicHandle, TEST_WCZ_StatusWriteToNvm, TEST_WCZ_CyclicHandle.
static void WCZ_StatusVerifyNvm(void)
Read back after status block write to NVM.The simplified flow is: check status of NVM block --- if block is OK, clear read flag --- if block is "pending", do nothing --- if unknown status of NV block or integrity failed, then set prefail Key Plausibility DTCs in addition, if verification of NV write is performed during learning procedure and is ok/nok, send adequate response to WCZ evFFBDataExchange C/S request reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssNvmWcz sFlags.u8Write - R/W access, trigger for write (DATA_NVM_STATUS_RD) sNvmWcz sFlags.u8Exchange - R/W access, always set during learning together with u8Write flag to generate C/S response for evFFBDataExchange by calling WCZ_DataExchangeResponse sNvmWcz sFlags.bValid - R/W access, flag cleared when verification process is faulty Input->Output-CorrelationInput: NVM block status check via NvM_GetErrorStatus(), trigger for verify flag, see Globals Called from WCZ_CyclicHandle periodically (every 10ms). Requested write operation (by DATA_NVM_STATUS_RD flag set in u8Write byte) from UHF_CyclicHandle via WCZ_SetStatus. Alternatively sporadic request during learning procedure from evFFBDataExchange. Output: updated flags are available in Globals, During learning procedure response is generated through WCZ_DataExchangeResponse to evFFBDataExchange Activity Diagram WCZ_StatusVerifyNvm Test MethodSWATT unit test. The testing method is described in TEST_WCZ_StatusVerifyNvm TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_118. Read back after status block write to NVM.Please find detail information in the declaration.
References SWATT_BYPASS, IS_CLR_FLAG, sNvmWcz, DATA_NVM_STATUS_WR, IS_SET_FLAG, DATA_NVM_STATUS_RD, RTE_E_OK, CLR_FLAG, WCZ_DataExchangeResponse, DATA_NVM_READY, bTrue, bFalse, NUM_KEY_LENGTH, WCZ_PlausibleDTC, FDH_IndexToKeyIndex.
Referenced by WCZ_CyclicHandle, TEST_WCZ_StatusVerifyNvm, TEST_WCZ_CyclicHandle.
static void WCZ_SetValue(const uint8 SlotIndex, const uint8 KeyIndex, const uint32 value, const boolean storeInNvM)
Function to store rolling code counter value.Store WCZ value in internal buffer, under given slot and key index location. There are R/W flags set to perform NVM write and verification. If Flags are set then value will be stored in NVM if not just in RAM. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_520} uint8 SlotIndex - slot index with valid range 0 or 1, alternatively in use. . [in] uint8 KeyIndex - key index with valid range 1..8. . [in] uint32 value - value to be stored in internal status buffer and written to NVM. [in] boolean storeInNvM - flag which is determine if value have to be stored in NvM or not. void GlobalssNvmWcz sValue.u32Backup - read and write value, buffer updated on value change. sNvmWcz sValue.u8Write - write value - clear read request just in case it is set. Not needed for requested operation. sNvmWcz sValue.u8Read - write value, triggers NVM W/V operation by flags DATA_NVM_SLOT_WR() / DATA_NVM_SLOT_RD(). Input->Output-CorrelationWCZ storage triggered from UHF_CyclicHandle for new telegram, when detected that it is "first telegram". Second case - during key learning procedure evFFBDataExchange. WCZ Write and verification is processed in cyclic calls from WCZ_CyclicHandle. Activity Diagram WCZ_SetValue Test MethodSWATT unit test. The testing method is described in TEST_WCZ_SetValue TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_520. Function to store rolling code counter value.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, WCZ_SlotIndexValidation, KeyIndexValidation, sNvmWcz, FDH_KeyIndexToIndex, CLR_FLAG, DATA_NVM_SLOT_RD, SET_FLAG, DATA_NVM_SLOT_WR.
Referenced by WCZ_TimerHandle, evFFBDataExchange, WCZ_Validate, TEST_WCZ_SetValue.
static void WCZ_ValueReadFromNvm(const uint8 SlotIndex)
WCZ for all keys are transferred from NVM to internal buffers.In "real", use after wake up or reset, otherwise no effect. The simplified flow is: clear all R/W flags clear WCZ for all keys - for all 3 blocks from requested slot: --- check status of NVM block --- if block is OK, increase counter of "good" blocks --- if block is corrupted, rewrite block with values in internal buffers, which are 0's --- if unknown status of NV block, then set prefail Key Plausibility DTCs if counter of "good" blocks is 3 (all are ok in specific slot) - restore value to internal buffer if 2 out of 3 hold the same value, set Key Plausibility DTCs to prepassed else set internal buffer to 0, set Key Plausibility DTCs to prefailed reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_321} {SWR_L3_CRoute_FFB_323} {SWR_L3_CRoute_FFB_329} uint8 SlotIndex - 0..1 (i.e. A,B) slots are allowed only. void GlobalssNvmWcz sFlags.u8Write - R/W access, triggers for write operation, cleared when request processed. sNvmWcz sFlags.u8Read - R/W access, trigger for read. sNvmWcz sFlags.u8Write - W access, unconditional clear. sNvmWcz sFlags.bValid - W access, flag cleared on faults. sNvmWcz sValue[SLOT_INDEX_A/B].u32Backup[] - R/W access, 4 byte WCZ internal buffer is initialized / restored from NVM. sNvmWcz sValue[SLOT_INDEX_A/B].pim_ptr[iwcz]->rb_fdh_WCZ[ikey] - R/W access,NVM RAM mirror, restored from NVM, reinit in case of corrupted data. Input->Output-CorrelationInput: NVM blocks in requested slot; NVM blocks status check via NvM_GetErrorStatus(), see Globals Called from WCZ_CyclicHandle periodically (every 10ms). However read from NVM operation is triggered (flag DATA_NVM_SLOT_RD set) only during system wake up initialization WCZ_Initialization. Output: output data is available in Globals, In case of detected corrupted NVM block (none of 2 same blocks) or invalid state of NVM block, DTCs for all keys (8) "WCZ plausible" is tested as prefail. Id 2 or 3 values out of 3 are same, then DTC is prepassed for each key/DTC. Activity Diagram WCZ_ValueReadFromNvm Test MethodSWATT unit test. The testing method is described in TEST_WCZ_ValueReadFromNvm TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_118. SWR_L3_CRoute_FFB_321. SWR_L3_CRoute_FFB_323. SWR_L3_CRoute_FFB_329. WCZ for all keys are transferred from NVM to internal buffers.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, WCZ_SlotIndexValidation, IS_SET_FLAG, sNvmWcz, DATA_NVM_SLOT_RD, CLR_FLAG, DATA_NVM_SLOT_WR, NUM_KEY_LENGTH, NUM_WCZ_LENGTH, RTE_E_OK, GetErrorStatus, NVM_OFFSET_3, UNUSED_RETVAL, WriteBlock, WCZ_PlausibleDTC, FDH_IndexToKeyIndex, WCZ_CheckConsistency, WCZ_INDEX_0, WCZ_INDEX_1, WCZ_INDEX_2.
Referenced by WCZ_CyclicHandle, TEST_WCZ_ValueReadFromNvm, TEST_WCZ_CyclicHandle.
static void WCZ_ValueWriteToNvm(const uint8 SlotIndex)
WCZ for all keys are transferred to NVM from internal buffers.The simplified flow is: for all 3 NV blocks from requested slot: --- check status of NVM block --- if block is OK, increase counter of "good" blocks --- if block is corrupted but key learning is ongoing, ignore it --- if block is corrupted or unknown status, then set prefail Key Plausibility DTCs and send "NOK" response to WCZ evFFBDataExchange C/S request (only if in key learning routine) if counter of "good" blocks is 3 (all are ok in specific slot) --- transfer WCZ value from internal buffer to all 3 blocks in specified slot --- clear write flag and send response to WCZ evFFBDataExchange C/S request (only if in key learning routine) reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_322} {SWR_L3_CRoute_FFB_323} {SWR_L3_CRoute_FFB_457} uint8 SlotIndex - 0..1 (i.e. A,B) slots are allowed only. void GlobalssNvmWcz sFlags.u8Write - R/W access, triggers for write operation, cleared when request processed. sNvmWcz .sFlags.u8Write - R/W access, NVM write trigger flag, cleared when request processed sNvmWcz sFlags.u8Exchange - always set during learning together with u8Write flag to generate C/S response for evFFBDataExchange by calling WCZ_DataExchangeResponse sNvmWcz sFlags.bValid - W access, flag cleared on faults sNvmWcz sValue[SLOT_INDEX_A/B].u32Backup[] - R access, 4 byte WCZ internal buffer is copied to NVM block RAM mirror area sNvmWcz sValue[SLOT_INDEX_A/B].pim_ptr[iwcz]->rb_fdh_WCZ[ikey] - W access,NVM RAM mirror overwritten before NVM write op is triggered. Input->Output-CorrelationInput: NVM blocks in requested slot; NVM blocks status check via NvM_GetErrorStatus(), see Globals Called from WCZ_CyclicHandle periodically (every 10ms). Requested write operation (flag DATA_NVM_SLOT_WR set)- refer to WCZ_SetValue Output: output data in RAM mirror of NVM block In case of invalid state of NVM block, DTCs for all keys (8) "WCZ plausible" is tested as prefail. During learning procedure response is generated through WCZ_DataExchangeResponse to evFFBDataExchange. Activity Diagram WCZ_ValueWriteToNvm Test MethodSWATT unit test. The testing method is described in TEST_WCZ_ValueWriteToNvm TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_118. SWR_L3_CRoute_FFB_322. SWR_L3_CRoute_FFB_323. SWR_L3_CRoute_FFB_457. WCZ for all keys are transferred to NVM from internal buffers.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, WCZ_SlotIndexValidation, IS_SET_FLAG, sNvmWcz, DATA_NVM_SLOT_WR, NUM_WCZ_LENGTH, RTE_E_OK, GetErrorStatus, NVM_OFFSET_3, WCZ_DataExchangeResponse, NUM_KEY_LENGTH, WCZ_PlausibleDTC, FDH_IndexToKeyIndex, CLR_FLAG, WriteBlock, DATA_NVM_READY, bTrue.
Referenced by WCZ_CyclicHandle, TEST_WCZ_ValueWriteToNvm, TEST_WCZ_CyclicHandle.
static void WCZ_ValueVerifyNvm(const uint8 SlotIndex)
Determine status of all NVM blocks in requested slot, which store WCZ for all keys.The simplified flow is: for all 3 NV blocks from requested slot: --- check status of NVM block --- if block is OK, increase counter of "good" blocks --- if block is corrupted or unknown status, then set prefail Key Plausibility DTCs and send "NOK" response to WCZ evFFBDataExchange C/S request (only if in key learning routine) if counter of "good" blocks is 3 (all are ok in specific slot) - check WCZ data plausibility (compare 3 copies) --- if any 2 copies differ, then set prefail Key Plausibility DTCs --- if 2 or 3 copies of WCZ are same, copy it to internal buffer, then set prepassed Key Plausibility DTCs --- clear read flag - if in key learning process, send "OK" response to WCZ evFFBDataExchange C/S request if R/W flags cleared (i.e. write and verification succesfull); "NOK" otherwise reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 SlotIndex - 0..1 (i.e. A,B) slots are allowed only. void GlobalssNvmWcz sFlags.u8Write - R/W access, verification is triggered sNvmWcz sFlags.bValid - W access, flag cleared on faults sNvmWcz sFlags.u8Exchange - R/W, always set during learning together with u8Write flag to generate C/S response for evFFBDataExchange by calling WCZ_DataExchangeResponse sNvmWcz sNvmWcz.sValue[SLOT_INDEX_A/B].u32Backup[] - W access, 4 byte WCZ internal buffer is restored from NVM sNvmWcz sNvmWcz.sValue[SLOT_INDEX_A/B].pim_ptr[iwcz]->rb_fdh_WCZ[ikey] - R access,NVM RAM mirror, restored from NVM. Input->Output-CorrelationInput: NVM blocks in requested slot; NVM blocks status check via NvM_GetErrorStatus(), see Globals Called from WCZ_CyclicHandle periodically (every 10ms). However verify from NVM operation is triggered (flag DATA_NVM_SLOT_RD flag set) together with write operation (verify executed after write "part" is done). Output: output data is available in Globals, In case of detected corrupted NVM block (none of 2 same blcoks) or invalid state of NVM block, DTCs for all keys (8) "WCZ plausible" is tested as prefail. Id 2 or 3 values out of 3 are same, then DTC is prepassed for each key/DTC.. During learning procedure response is generated through WCZ_DataExchangeResponse to evFFBDataExchange Activity Diagram WCZ_ValueVerifyNvm Test MethodSWATT unit test. The testing method is described in TEST_WCZ_ValueVerifyNvm TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_118}. Determine status of all NVM blocks in requested slot, which store WCZ for all keys.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, WCZ_SlotIndexValidation, IS_CLR_FLAG, sNvmWcz, DATA_NVM_SLOT_WR, IS_SET_FLAG, DATA_NVM_SLOT_RD, NUM_WCZ_LENGTH, RTE_E_OK, GetErrorStatus, NVM_OFFSET_3, WCZ_DataExchangeResponse, NUM_KEY_LENGTH, WCZ_PlausibleDTC, FDH_IndexToKeyIndex, CLR_FLAG, WCZ_CheckConsistency, WCZ_INDEX_0, WCZ_INDEX_1, WCZ_INDEX_2, DATA_NVM_READY, bTrue.
Referenced by WCZ_CyclicHandle, TEST_WCZ_ValueVerifyNvm, TEST_WCZ_CyclicHandle.
static void WCZ_TimerReset(const boolean start, const uint8 keyNumber)
Function resets the timer for specified key number. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_345} boolean start - when true, starts timer [in] uint8 keyNumber - range 0..7, corresponding timer will be reset void GlobalssNvmWcz sFZV_Timer[].bRun - R access, flag to run WCZ timer, if true sNvmWcz sFZV_Timer[].u8second, sNvmWcz sFZV_Timer[].u32Value - W access, both cleared sNvmWcz sFZV_Timer[].bRun - W access, start/stop timer Input->Output-CorrelationTimers Initialized from WCZ_Initialization. Timer triggered from UHF_CyclicHandle(). Activity Diagram WCZ_TimerReset Test MethodSWATT unit test. The testing method is described in TEST_WCZ_TimerReset TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_345 Function resets the timer for specified key number.Please find detail information in the declaration.
References SWATT_BYPASS, sNvmWcz, TICKS_PER_SECOND.
Referenced by WCZ_Initialization, WCZ_Validate, TEST_WCZ_TimerReset, TEST_WCZ_Validate.
static void WCZ_CounterReset(const uint8 keyNumber)
Function resets the counter for specified key number. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_344} uint8 keyNumber - 0..7, corresponding counter will be reset. void GlobalssNvmWcz sCounter[keyNumber].u8FzvFrame, sNvmWcz sCounter[keyNumber].u32Value - W access, cleared. Input->Output-CorrelationN/A Activity Diagram WCZ_CounterReset Test MethodSWATT unit test. The testing method is described in TEST_WCZ_CounterReset TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_344
References sNvmWcz.
Referenced by WCZ_Initialization, TEST_WCZ_CounterReset.
static void WCZ_DataExchange(const uint8 KeyIndex, const boolean bEnable, const uint8 u8WczCode[], uint8 u8Status[], uint32 u32Value[])
Function converting WCZ value received during key learning.Converts WCZ value received during key learning from byte oriented table to uint32 for specified key index, assuming key is enabled, otherwise WCZ is set to 0. Output status is transferred to key index position in the status table. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_521} uint8 KeyIndex - key index with valid range 1..8. [in] boolean - bEnable - key is enabled [in] uint8 u8WczCode[] - WCZ in byte oriented form [out] uint8 u8StatusList[] - status out, filled at c-style key position [out] uint32 u32ValueList[] - output u32 WCZ filled to c-style key position void GlobalsN/A Input->Output-CorrelationInternally WCZ is stored as 32 bit uint. Conversion is performed during learning, while storing of initial WCZ. Activity Diagram WCZ_SetupSlot Test MethodSWATT unit test. The testing method is described in TEST_WCZ_DataExchange TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_521 Function converting WCZ value received during key learning.Please find detail information in the declaration.
References SWATT_BYPASS, bFalse, KeyIndexValidation, FDH_KeyIndexToIndex, KEY_STATUS_OK, FDH_tabToU32, KEY_STATUS_DISABLED.
Referenced by evFFBDataExchange, TEST_WCZ_DataExchange, TEST_evFFBDataExchange.
static void WCZ_DataExchangeResponse(const boolean bSaveWCZValid, const uint8 numSaveWCZStatus)
Function handles data exchange C/S response communication ( evFFBDataExchangeResp).Returned statuses are: Pending - data exchange/NVM storage in progress; OK - NVM storage complete and succesfull; ERR - problem encountered during NVM storage attempt. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_522} boolean bSaveWCZValid - true, if WCZ for the keys are stored succesfully during learning process [in] uint8 numSaveWCZStatus - when all flags cleared, NVM storage process is completed void GlobalsN/A Input->Output-CorrelationDuring learning process, when WCZ storage to NVM is performed, response to C/S call evFFBDataExchange is generated, depending on process stage/result OK/ERR/In progress status is responded via evFFBDataExchangeResp interface. Activity Diagram WCZ_DataExchangeResponse Test MethodSWATT unit test. The testing method is described in TEST_WCZ_DataExchangeResponse TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_522. SWR_L3_CRoute_FFB_451. Function handles data exchange C/S response communication ( evFFBDataExchangeResp).Please find detail information in the declaration.
References SWATT_BYPASS, WCZ_EXCHANGE_INPROG, bFalse, WCZ_EXCHANGE_OK, WCZ_EXCHANGE_ERR.
Referenced by WCZ_StatusWriteToNvm, WCZ_StatusVerifyNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm, evFFBDataExchange, TEST_WCZ_ValueWriteToNvm, TEST_WCZ_ValueVerifyNvm, TEST_WCZ_DataExchangeResponse, TEST_evFFBDataExchange.
static void FDH_tabToU32(const uint8 src[], uint32 *val)
Function for copying data of different type. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 src[] - pointer to the 4 byte table holding number [out] uint32 *val - pointer to result in 32 bit variable void GlobalsN/A Input->Output-CorrelationSrc buffer gets copied to target and converted from 4 byte per value table to uint32. Test MethodSWATT unit test. The testing method is described in TEST_FDH_Task_FDH_tabToU32 Verification criteriaTestcase shall verify if data is copied correctly. TraceabilityDesign Decision - Justification. Design decision: helper function to copy data.
Referenced by WCZ_DataExchange, WCZ_Validate, TEST_FDH_Task_FDH_tabToU32.
void WCZ_Initialization(void)
Init function for sNvmWcz and rolling code counter data.Please find detail information in header file.
References sNvmWcz, SLOT_INDEX_A, WCZ_INDEX_0, WCZ_INDEX_1, WCZ_INDEX_2, SLOT_INDEX_B, DATA_NVM_STATUS_RD, DATA_NVM_SLOT_A_RD, DATA_NVM_SLOT_B_RD, DATA_NVM_READY, NUM_KEY_LENGTH, bFalse, KEY_STATUS_UNKNOWN, KEY_INDEX_UNSET, WCZ_TimerReset, WCZ_CounterReset.
Referenced by FDH_Start, TEST_WCZ_Initialization.
void WCZ_CyclicHandle(void)
Cyclic function for rolling code counter.Please find detail information in header file.
References bFalse, NUM_KEY_LENGTH, bTrue, UNUSED_RETVAL, evFFBDataExchange, FDH_KeyIndexToIndex, KEY_INDEX_1, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8, WCZ_StatusReadFromNvm, WCZ_ValueReadFromNvm, SLOT_INDEX_A, SLOT_INDEX_B, WCZ_StatusWriteToNvm, WCZ_ValueWriteToNvm, WCZ_StatusVerifyNvm, WCZ_ValueVerifyNvm, WCZ_Synchronization.
Referenced by FDH_TaskCyclicEvent, TEST_WCZ_CyclicHandle.
void WCZ_TimerHandle(void)
Function executes periodically in 10ms ticks timers used in WCZ internal calculation.Please find detail information in header file.
References NUM_KEY_LENGTH, bFalse, sNvmWcz, TICKS_PER_SECOND, WCZ_INC_COUNT, COUNTER_MAX_INC, bTrue, WCZ_SetValue, FDH_IndexToKeyIndex.
Referenced by FDH_TaskCyclicEvent, TEST_WCZ_TimerHandle.
Std_ReturnType evFFBDataExchange(boolean bFFBStatusNr1, boolean bFFBStatusNr2, boolean bFFBStatusNr3, boolean bFFBStatusNr4, boolean bFFBStatusNr5, boolean bFFBStatusNr6, boolean bFFBStatusNr7, boolean bFFBStatusNr8, const uint8 *numWCZInit1, const uint8 *numWCZInit2, const uint8 *numWCZInit3, const uint8 *numWCZInit4, const uint8 *numWCZInit5, const uint8 *numWCZInit6, const uint8 *numWCZInit7, const uint8 *numWCZInit8)
Function requesting WCZ storage of all learned FFBs in NVM as a C/S service.Please find detail information in header file.
References NUM_KEY_LENGTH, WCZ_DataExchange, KEY_INDEX_1, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8, WCZ_SetStatus, FDH_IndexToKeyIndex, WCZ_SetValue, SLOT_INDEX_A, bTrue, SLOT_INDEX_B, KEY_INDEX_UNSET, KEY_STATUS_OK, sNvmWcz, WCZ_DataExchangeResponse, DATA_NVM_READY, bFalse, RTE_E_OK, RTE_E_INVALID.
Referenced by WCZ_CyclicHandle, TEST_evFFBDataExchange.
boolean WCZ_Validate(S_UHF_Message *p_UHF_Message)
Function check if WCZ is validPlease find detail information in header file.
References bFalse, FDH_KeyIndexToIndex, S_UHF_Message::u8KeyIndex, sNvmWcz, WCZ_RANGE_3, WCZ_CheckKeyActive, NUM_KEY_LENGTH, WCZ_SetupSlot, S_UHF_Message::sFlags, S_FDH_Flags::FirstFzvTelegram, WCZ_TimerReset, bTrue, FDH_tabToU32, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_Payload_FZV::RolingCodeCounter, WCZ_CalculateRange, KEY_STATUS_INACTIVE_MECH_KESSY, WCZ_RANGE_1, WCZ_SetStatus, KEY_STATUS_OK, WCZ_RANGE_2, WCZ_SetValue, S_FDH_Flags::DiscardTelegram, sUHF_Message.
Referenced by UHF_CyclicHandle, TEST_WCZ_Validate.