FDH_WCZ_Handler.h
void WCZ_Initialization(void)
Init function for sNvmWcz and rolling code counter data.On system wake up, internal data structures initialization with default values. NV data read flags are set to request read stored WCZ data+status to internal buffers. Validity and WCZ buffers are set to invalid. Also internal data (counters, timers) used during WCZ processing are cleared. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssNvmWcz - W access Input->Output-CorrelationAfter initialization cyclic processing of WCZ data/status synchronization can start. Activity Diagram WCZ_Initialization Test MethodSWATT unit test. The testing method is described in TEST_WCZ_Initialization TraceabilityDesign Decision - Justification. Design decision: helper function to initialize sNvmWcz and connected data. Init function for sNvmWcz and rolling code counter data. Please find detail information in header file.
References sNvmWcz, SLOT_INDEX_A, WCZ_INDEX_0, WCZ_INDEX_1, WCZ_INDEX_2, SLOT_INDEX_B, DATA_NVM_STATUS_RD, DATA_NVM_SLOT_A_RD, DATA_NVM_SLOT_B_RD, DATA_NVM_READY, NUM_KEY_LENGTH, bFalse, KEY_STATUS_UNKNOWN, KEY_INDEX_UNSET, WCZ_TimerReset, WCZ_CounterReset.
Referenced by FDH_Start, TEST_WCZ_Initialization.
void WCZ_CyclicHandle(void)
Cyclic function for rolling code counter.NVM data storage/retrieve cyclic scheduler. Executed from 10ms FDH cyclic task. Following sequence Read-Write-Verify is executed each cycle for both WCZ Value and Status information. Flags (sNvmWcz.sFlags.u8Read, sNvmWcz.sFlags.u8Write, sNvmWcz.sFlags.u8Exchange) are evaluated in the functions to determine exact actions. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationCyclic execution of Read/Write/Verify sequence to synchronize to NVM WCZ value and status, where requested. Read is requested only at wake up/reset only; Write/Verify is periodic, whenever First Telegram in burst is determined, via UHF_CyclicHandle->WCZ_SetValue/WCZ_SetStatus. Alternative scenario of triggering Write/Verify is through learning process, from callout function evFFBDataExchange->WCZ_SetValue/WCZ_SetStatus. Activity Diagram WCZ_CyclicHandle Test MethodSWATT unit test. The testing method is described in TEST_WCZ_CyclicHandle TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_268. Cyclic function for rolling code counter.Please find detail information in header file.
References bFalse, NUM_KEY_LENGTH, bTrue, UNUSED_RETVAL, evFFBDataExchange, FDH_KeyIndexToIndex, KEY_INDEX_1, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8, WCZ_StatusReadFromNvm, WCZ_ValueReadFromNvm, SLOT_INDEX_A, SLOT_INDEX_B, WCZ_StatusWriteToNvm, WCZ_ValueWriteToNvm, WCZ_StatusVerifyNvm, WCZ_ValueVerifyNvm, WCZ_Synchronization.
Referenced by FDH_TaskCyclicEvent, TEST_WCZ_CyclicHandle.
void WCZ_TimerHandle(void)
Function executes periodically in 10ms ticks timers used in WCZ internal calculation.In addition there are associated counters, one per key incremented every second up to 10s. After counter value increase, WCZ is calculated and value strored in RAM. If counter reach max value = 10 then value is also stored in NvM. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_349} {SWR_L3_CRoute_FFB_345} {SWR_L3_CRoute_FFB_495} void void GlobalssNvmWcz sFZV_Timer[].bRun - R access, flag to run WCZ timer, if true sNvmWcz sFZV_Timer[] - R/W access, timer counts up (u32Value) sNvmWcz sCounter[] - R/W access Input->Output-CorrelationTimer started (via WCZ_TimerReset) when new FZV "first telegram" is detected, from UHF_CyclicHandle. Present value of the timer is utulized to calculate internally expected WCZ. Activity Diagram WCZ_TimerHandle Test MethodSWATT unit test. The testing method is described in TEST_WCZ_TimerHandle TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_345, SWR_L3_CRoute_FFB_350. SWR_L3_CRoute_FFB_495, SWR_L3_CRoute_FFB_349. Function executes periodically in 10ms ticks timers used in WCZ internal calculation.Please find detail information in header file.
References NUM_KEY_LENGTH, bFalse, sNvmWcz, TICKS_PER_SECOND, WCZ_INC_COUNT, COUNTER_MAX_INC, bTrue, WCZ_SetValue, FDH_IndexToKeyIndex.
Referenced by FDH_TaskCyclicEvent, TEST_WCZ_TimerHandle.
boolean WCZ_Validate(S_UHF_Message *p_UHF_Message)
Function check if WCZ is validFunction is handling cyclic processing of WCZ ranges of received and validated FZV telegrams. The simplified flow is: Every 10ms the following flow is executed: If WCZ storage in NVM is valid (completed R/W, no errors) - If Key index of current (new) message is not disabled --- store it as last key index --- If first telegram in burst -> setup slot for NVM write and reset timer used for FZV burst detection --- copy to internal buffer (not nv yet) incoming WCZ value --- calculate WCZ and determine into which range it falls --- trigger storage of WCZ to NVM --- if the present key is not deactivated already (KEY_STATUS_INACTIVE_MECH_KESSY) ----- calculate status of key (based on present range and recent status in NVM) and trigger storage of updated value into NVM ----- -> range 1: -> status = 0 ----- -> range 2: -> increment status by 1 up to 3 times ----- -> range 3: -> deactivate (KEY_STATUS_INACTIVE_MECH_KESSY) --- clear first telegram flag (as all checks processed already) - if in range 1 -> set valid=1 of the present key (=keyIndex od processed telegram) - discard telegram if in range 3 reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_463} {SWR_L3_CRoute_FFB_326} {SWR_L3_CRoute_FFB_344} {SWR_L3_CRoute_FFB_427} {SWR_L3_CRoute_FFB_465} {SWR_L3_CRoute_FFB_466} {SWR_L3_CRoute_FFB_412} {SWR_L3_CRoute_FFB_467} {SWR_L3_CRoute_FFB_478} {SWR_L3_CRoute_FFB_429} {SWR_L3_CRoute_FFB_476} {SWR_L3_CRoute_FFB_414} p_UHF_Message - R access to most of the fields in the structure, W to some like DiscardTelegram. This structure is major input data to this cyclic function, fields like "event/new value/validity" are written when values are "consumed". void Globals sNvmWcz - direct R access to status fields in structure, but also indirect access through used function calls e.g. WCZ_SetValue. Input->Output-CorrelationGeneral flow as follows: Input sUHF_Message, in structure sUHF_Message in this cyclic call are the consumed and output signals are generated over ButtonCodeReport function. Local memory is declared for WCZin, WCZincprev, WCZCalc while telegram burst is processed. Activity Diagram WCZ_Validate Test MethodSWATT unit test. The testing method is described in TEST_WCZ_Validate TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_459. SWR_L3_CRoute_FFB_463. SWR_L3_CRoute_FFB_344. SWR_L3_CRoute_FFB_326. SWR_L3_CRoute_FFB_427. SWR_L3_CRoute_FFB_465. SWR_L3_CRoute_FFB_466. SWR_L3_CRoute_FFB_467. SWR_L3_CRoute_FFB_412. SWR_L3_CRoute_FFB_478. SWR_L3_CRoute_FFB_414. SWR_L3_CRoute_FFB_429. SWR_L3_CRoute_FFB_476. SWR_L3_CRoute_FFB_325. Function check if WCZ is validPlease find detail information in header file.
References bFalse, FDH_KeyIndexToIndex, S_UHF_Message::u8KeyIndex, sNvmWcz, WCZ_RANGE_3, WCZ_CheckKeyActive, NUM_KEY_LENGTH, WCZ_SetupSlot, S_UHF_Message::sFlags, S_FDH_Flags::FirstFzvTelegram, WCZ_TimerReset, bTrue, FDH_tabToU32, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_Payload_FZV::RolingCodeCounter, WCZ_CalculateRange, KEY_STATUS_INACTIVE_MECH_KESSY, WCZ_RANGE_1, WCZ_SetStatus, KEY_STATUS_OK, WCZ_RANGE_2, WCZ_SetValue, S_FDH_Flags::DiscardTelegram, sUHF_Message.
Referenced by UHF_CyclicHandle, TEST_WCZ_Validate.
Std_ReturnType evFFBDataExchange(boolean bFFBStatusNr1, boolean bFFBStatusNr2, boolean bFFBStatusNr3, boolean bFFBStatusNr4, boolean bFFBStatusNr5, boolean bFFBStatusNr6, boolean bFFBStatusNr7, boolean bFFBStatusNr8, const uint8 *numWCZInit1, const uint8 *numWCZInit2, const uint8 *numWCZInit3, const uint8 *numWCZInit4, const uint8 *numWCZInit5, const uint8 *numWCZInit6, const uint8 *numWCZInit7, const uint8 *numWCZInit8)
Function requesting WCZ storage of all learned FFBs in NVM as a C/S service.This is callout function (from CSH module), which is requesting WCZ storage of all learned FFBs in NVM as a C/S service. Also initial statuses are requested to store in separate NVM block. Up to 8 keys are supported. Note: store means write+verify. Also, initial answer to C/S request is sent back. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_519} {SWR_L3_CRoute_FFB_520} {SWR_L3_CRoute_FFB_522} boolean bFFBStatusNr 1-8 (8 parameters) - true, if key is learned. [in] boolean numWCZInit1 1-8 (8 parameters) - pointer to byte oriented WCZ data Std_ReturnType - RTE status. GlobalssNvmWcz sFlags.u8Exchange - R/W sNvmWcz sFlags.u8Write - R Input->Output-CorrelationThe function is called out of CSH context as C/S interface. It is sporadic call only occurring during key learning process. Initial values of WCZ and status (active or disabled) for up to 8 keys are provided. All status and WCZ values are stored in internal NVM structure and NVM write / verification is triggered. Once learning is complete, UHF telegrams may be processed. Activity Diagram evFFBDataExchange Test MethodSWATT unit test. The testing method is described in TEST_evFFBDataExchange TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_519. SWR_L3_CRoute_FFB_520. SWR_L3_CRoute_FFB_522. Function requesting WCZ storage of all learned FFBs in NVM as a C/S service.Please find detail information in header file.
References NUM_KEY_LENGTH, WCZ_DataExchange, KEY_INDEX_1, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8, WCZ_SetStatus, FDH_IndexToKeyIndex, WCZ_SetValue, SLOT_INDEX_A, bTrue, SLOT_INDEX_B, KEY_INDEX_UNSET, KEY_STATUS_OK, sNvmWcz, WCZ_DataExchangeResponse, DATA_NVM_READY, bFalse, RTE_E_OK, RTE_E_INVALID.
Referenced by WCZ_CyclicHandle, TEST_evFFBDataExchange.