FDH_Toolbox.c
boolean KeyIndexValidation(const uint8 KeyIndex)
Checks if key index is within acceptable values/range.Please find detail information in header file.
References SWATT_BYPASS, m_KeyIndexValidation, KEY_INDEX_1, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8, bTrue, bFalse.
Referenced by TEST_KeyIndexValidation, TEST_FDH_IndexToKeyIndex, evUHFEmpfang_FZV, evUHFEmpfang_Comfort, WCZ_KeyStatusValidation, WCZ_SetupSlot, WCZ_SetStatus, WCZ_SetValue, WCZ_DataExchange.
uint8 FDH_KeyIndexToIndex(const uint8 KeyIndex)
Translation of KeyIndex (functional key number 1..8) to internal C-style index to key tables (0..7).Please find detail information in header file.
Referenced by TEST_FDH_KeyIndexToIndex, evUHFEmpfang_FZV, WCZ_KeyStatusValidation, WCZ_CheckKeyActive, WCZ_SetupSlot, WCZ_Synchronization, WCZ_SetStatus, WCZ_SetValue, WCZ_DataExchange, WCZ_CyclicHandle, WCZ_Validate.
uint8 FDH_IndexToKeyIndex(const sint8 Index)
Translation of C-style key index (0..7) to functional key number (1..8)Please find detail information in header file.
Referenced by TEST_FDH_IndexToKeyIndex, WCZ_StatusReadFromNvm, WCZ_StatusWriteToNvm, WCZ_StatusVerifyNvm, WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm, WCZ_TimerHandle, evFFBDataExchange.