FDH_UHF_Handler.h
void UHF_MessageInitialization(void)
Init function for sUHF_Message.Function initializes internal buffer which is utilized during UHF telegram reception and processing. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssUHF_Message - W access Input->Output-CorrelationsUHF_Message structure fields are initialized for cyclic processing in RUN mode. Activity Diagram UHF_MessageInitialization Test MethodSWATT unit test. The testing method is described in TEST_UHF_MessageInitialization Verification criteriaTestcase shall check if structure fields are set to correct init value. TraceabilityDesign Decision - Justification. Design decision: helper function to initialize UHF_Message data. Init function for sUHF_Message. Please find detail information in the header file.
References sUHF_Message, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_UHF_Payload::Comfort, S_UHF_Message::sFlags, S_FDH_Flags::DiscardTelegram, bFalse, S_FDH_Flags::FirstFzvTelegram, S_FDH_Flags::FirstFzvTelegramWasSet, S_FDH_Flags::NewMessage, S_FDH_Flags::TransponderIDValid, S_FDH_Flags::SignatureValid, S_FDH_Flags::ResetButtonAction, S_FDH_Flags::ValidFzv, S_FDH_Flags::LFBit, S_FDH_Flags::LFRangeEntire, S_FDH_Flags::LFRangeTrunk, S_UHF_Message::u8KeyIndex, KEY_INDEX_UNSET, S_UHF_Message::u8RFTransponderID, RAW_UHF_TRANSPONDER_ID_LENGTH, S_UHF_Message::u8RFPortNumber, PORT_UNKNOWN_TELEGRAMM, S_UHF_Message::u8RFFunctionNumber, FUNC_UNKNOWN_FUNC, S_UHF_Message::u8BatteryLevel, BATTERY_VOLTAGE_UNKNOWN, S_UHF_Message::u8SignalStaerke, STAERKE_UNKNOWN.
Referenced by FDH_Start, TEST_UHF_MessageInitialization.
void UHF_TimerInitialization(void)
Function initializes internal timers i.e. timers are stopped. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void Globalsu32FDH_TimerA - initialized with STOP value. u32FDH_TimerB - initialized with STOP value. Input->Output-CorrelationTimers will not run unless intentionally loaded started during UHF telegrams processing flow. Test MethodSWATT unit test. The testing method is described in TEST_UHF_TimerInitialization Verification criteriaTestcase shall check if timers are set to correct init value. TraceabilityDesign Decision - Justification. Design decision: helper function to initialize internal timers. Function initializes internal timers i.e. timers are stopped. Please find detail information in the header file.
References u32FDH_TimerA, FDH_TIMERA_STOP, u32FDH_TimerB, FDH_TIMERB_STOP.
Referenced by FDH_Start, TEST_UHF_TimerInitialization.
void UHF_CyclicHandle(void)
Main cyclic function for UHF message processing.Function is handling cyclic processing of WCZ ranges of received and validated FZV telegrams. The simplified flow is: Every 10ms the following flow is executed: If new message received and validated (signature, transponder) - If button is reset (flag set in evUHFEmpfang) -> clear existing output events; clear new message event for comfort function - Otherwise, switch (telegram function) - CASE FZV --- If WCZ storage in NVM is valid (completed R/W, no errors) ----- If Key index of current (new) message is not disabled ------- store it as last key index ------- If first telegram in burst -> setup slot for NVM write and reset timer used for FZV burst detection ------- copy to internal buffer (not nv yet) incoming WCZ value ------- calculate WCZ and determine into which range it falls ------- trigger storage of WCZ to NVM ------- if the present key is not deactivated already (KEY_STATUS_INACTIVE_MECH_KESSY) --------- calculate status of key (based on present range and recent status in NVM) and trigger storage of updated value into NVM --------- -> range 1: -> status = 0 --------- -> range 2: -> increment status by 1 up to 3 times --------- -> range 3: -> deactivate (KEY_STATUS_INACTIVE_MECH_KESSY) ------- clear first telegram flag (as all checks processed already) ----- if in range 1 -> set valid=1 of the present key (=keyIndex od processed telegram) ----- discard telegram if in range 3 --- if valid key -> report button code (generate event for ZV Lib), reload and start timer A; stop timer B - CASE COMFORT --- if timerA is running and timerB is stopped OR timerA is stopped and timerB is running ----- report comfort event button code (generate event for ZV Lib), reload and start timerB; stop timerA - CASE RELEASE --- stop timerA and timerB --- clear button code report (event) clear validation flag of transponder Id, signature, new message flag reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_464} {SWR_L3_CRoute_FFB_481} {SWR_L3_CRoute_FFB_275} {SWR_L3_CRoute_FFB_297} {SWR_L3_CRoute_FFB_354} {SWR_L3_CRoute_FFB_174} {SWR_L3_CRoute_FFB_273} {SWR_L3_CRoute_FFB_287} {SWR_L3_CRoute_FFB_288} {SWR_L3_CRoute_FFB_263} {SWR_L3_CRoute_FFB_289} {SWR_L3_CRoute_FFB_272} void void GlobalssUHF_Message - R access to most of the fields in the structure, W to some like DiscardTelegram. This structure is major input data to this cyclic function, fields like "event/new value/validity" are written when values are "consumed". sNvmWcz - direct R access to status fields in structure, but also indirect access through used function calls e.g. WCZ_SetValue. u32FDH_TimerA u32FDH_TimerB - R/W access, globally declared timers, directly accessed. Input->Output-CorrelationGeneral flow as follows: Input telegram, initially received and validated/processed (evUHFEmpfang, UHF_MessageValidation) in structure sUHF_Message in this cyclic call are the consumed and output signals are generated over ButtonCodeReport function. Local memory is declared for WCZin, WCZincprev, WCZCalc while telegram burst is processed. Activity Diagram UHF_CyclicHandle Test MethodSWATT unit test. The testing method is described in TEST_UHF_CyclicHandle TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_354. SWR_L3_CRoute_FFB_205. SWR_L3_CRoute_FFB_275. SWR_L3_CRoute_FFB_297. SWR_L3_CRoute_FFB_327. SWR_L3_CRoute_FFB_481. SWR_L3_CRoute_FFB_464. SWR_L3_CRoute_FFB_174. SWR_L3_CRoute_FFB_273. SWR_L3_CRoute_FFB_287. SWR_L3_CRoute_FFB_288. SWR_L3_CRoute_FFB_289. SWR_L3_CRoute_FFB_263. SWR_L3_CRoute_FFB_272. SWR_L3_CRoute_FFB_268. Main cyclic function for UHF message processing.Please find detail information in the header file.
References bFalse, sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::NewMessage, S_FDH_Flags::TransponderIDValid, S_FDH_Flags::SignatureValid, S_FDH_Flags::ResetButtonAction, ButtonCodeReport, PAYLOAD_BUTTONCODE_NO, KEY_INDEX_UNSET, FUNC_NUMMER_COMFORT, S_UHF_Message::u8RFFunctionNumber, PORT_FFB_TELEGRAMM, S_UHF_Message::u8RFPortNumber, S_UHF_Message::u8KeyIndex, FUNC_NUMMER_FZV, WCZ_Validate, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_Payload_FZV::ButtonCode, UNUSED_RETVAL, u32FDH_TimerA, u32FDH_TimerB, FDH_TIMERB_STOP, FDH_TIMERA_STOP, S_UHF_Payload::Comfort, S_Payload_Comfort::ButtonCode, S_FDH_Flags::LFBit, S_FDH_Flags::LFRangeEntire, S_FDH_Flags::LFRangeTrunk, FUNC_NUMMER_RELEASE.
Referenced by FDH_TaskCyclicEvent, TEST_UHF_CyclicHandle.
void UHF_TimerHandle(void)
Function handling UHF timer A and B.Timer A is loaded/started by FZV telegram reception and B is loaded/started by Comfort telegram reception. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_779} {SWR_L3_CRoute_FFB_260} void void Globalsu32FDH_TimerA and u32FDH_TimerB - both timer are modified. Input->Output-CorrelationUHF_CyclicHandle reloads timers when Comfort telegrams are processed, when any timer expire UHF_CyclicHandle consumes the events. In addition direct bypass of clearing output signals when both timers expired via call ButtonCodeReport Activity Diagram UHF_TimerHandle Test MethodSWATT unit test. The testing method is described in TEST_UHF_TimerHandle TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_260. SWR_L3_CRoute_FFB_291. SWR_L3_CRoute_FFB_779. Function handling UHF timer A and B.Please find detail information in the header file.
References FDH_TIMERA_STOP, u32FDH_TimerA, FDH_TIMERB_STOP, u32FDH_TimerB, ButtonCodeReport, PAYLOAD_BUTTONCODE_NO, KEY_INDEX_UNSET, bFalse.
Referenced by FDH_TaskCyclicEvent, TEST_UHF_TimerHandle.
void evCheckSignatureResp(boolean bSignatureValid, uint8 numCheckSignatureStatus)
Function providing result to the C/S service evCheckSignatureReq.This is callout function (from CSH module), which is providing result to the C/S service evCheckSignatureReq, called in UHF_MessageValidation. There is no pending status supported. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {{SWR_L3_CRoute_FFB_220} boolean bSignatureValid - true, if signature correct, otherwise false. uint8 numCheckSignatureStatus - in case of status 0, signature check is complete, otherwise ignore. void sUHF_Message sFlags.SignatureValid - W access. N/A Activity Diagram evCheckSignatureResp SWATT unit test. The testing method is described in TEST_evCheckSignatureResp Satisfies following DOORS Requirements: {SWR_L3_CRoute_FFB_220}. {SWR_L3_CRoute_FFB_222}. Function providing result to the C/S service evCheckSignatureReq. Please find detail information in the header file.
References sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::SignatureValid, bFalse.
Referenced by TEST_evCheckSignatureResp.
void evCheckTransponderIDResp(boolean bTransponderIDValid, uint8 numCheckTransponderIDStatus)
Function providing result to the C/S service evCheckTransponderIDReq.This is callout function (from CSH module), which is providing result to the C/S service evCheckTransponderIDReq, called in UHF_MessageValidation. There is no pending status supported. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous boolean bTransponderIDValid - true, if transponder Id is recognized (learnt), otherwise false. uint8 numCheckTransponderIDStatus - in case of status 0, transponder check is complete, otherwise ignore. void GlobalssUHF_Message sFlags.TransponderIDValid - W access. Input->Output-CorrelationN/A Activity Diagram evCheckSignatureResp Test MethodSWATT unit test. The testing method is described in TEST_evCheckTransponderIDResp TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_207. Function providing result to the C/S service evCheckTransponderIDReq.Please find detail information in the header file.
References sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::TransponderIDValid, bFalse.
Referenced by TEST_evCheckTransponderIDResp.
Std_ReturnType evUHFEmpfang(const uint8 *rawUHFTransponderID, uint8 numUHFPortNumber, uint8 numUHFFunktionsnummer, uint8 numBatteryLevel, const uint8 *rawUHFPayload, boolean bCRCValid, uint8 u8UHFSignalstaerke)
Callout function (from CSH module), which is forwarding new UHF FFB telegram for processing.The simplified flow is: if CRC is correct and telegram is for FFB - store button code / frame counter for next telegram analysis in static variable - CASE FZV telegram --- call evUHFEmpfang_FZV - CASE COMFORT telegram --- call evUHFEmpfang_Comfort - CASE RELEASE telegram --- call evUHFEmpfang_Release - ENDCASE - if function and key index valid --- store other telegram fields: function, port, battery level, signal strength (starke) --- validate message (transponder Id, signature, battery level) --- set new message trigger. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_414} {SWR_L3_CRoute_FFB_354} {SWR_L3_CRoute_FFB_287} {SWR_L3_CRoute_FFB_288} {SWR_L3_CRoute_FFB_284} {SWR_L3_CRoute_FFB_285} {SWR_L3_CRoute_FFB_259} {SWR_L3_CRoute_FFB_283} {SWR_L3_CRoute_FFB_293} uint8 rawUHFTransponderID - pointer to byte oriented transponder Id of received telegram uint8 numUHFPortNumber - only if 1 (FFB telegram) to be processed, otherwise kessy uint8 numUHFFunktionsnummer - function of the telegram: FZV=0, Comfort=1, Release=2 uint8 numBatteryLevel - for further check, stored along with other data from telegram in local buffer uint8 rawUHFPayload[] - raw data of telegram for parsing, includes WCZ, signature,... boolean bCRCValid - true if CRC of the telegram content is valid uint8 u8UHFSignalstaerke - signal strength Std_ReturnType - RTE status. GlobalssUHF_Message sFlags.TransponderIDValid - W access. sUHF_Message sPayload.FZV - R/W access sUHF_Message sPayload.Comfort - R/W access sUHF_Message u8KeyIndex - R/W sUHF_Message u8RFTransponderID - W sUHF_Message u8RFPortNumber - W sUHF_Message u8RFFunctionNumber - W sUHF_Message u8BatteryLevel - W sUHF_Message u8SignalStaerke - W sUHF_Message sFlags.LFBit - W sUHF_Message sFlags.LFRangeEntire - W sUHF_Message sFlags.LFRangeTrunk - W sUHF_Message sFlags.DiscardTelegram - R/W sUHF_Message sFlags.FirstFzvTelegram - W sUHF_Message sFlags.ValidFzv - R/W sUHF_Message sFlags.ResetButtonAction - W sUHF_Message sFlags.NewMessage - W Input->Output-CorrelationCallout from UHF Master on new telegram reception to initiate processing. sUHF internal message attributes/flags are filled in and message validation is next step, then UHF_CyclicHandle will process further the new telegram. Activity Diagram evUHFEmpfang Test MethodSWATT unit test. The testing method is described in TEST_evUHFEmpfang TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_192. SWR_L3_CRoute_FFB_361. SWR_L3_CRoute_FFB_205. SWR_L3_CRoute_FFB_206. SWR_L3_CRoute_FFB_208. SWR_L3_CRoute_FFB_211. SWR_L3_CRoute_FFB_324. SWR_L3_CRoute_FFB_300. SWR_L3_CRoute_FFB_178. SWR_L3_CRoute_FFB_181. SWR_L3_CRoute_FFB_182. SWR_L3_CRoute_FFB_301. SWR_L3_CRoute_FFB_406. SWR_L3_CRoute_FFB_407. SWR_L3_CRoute_FFB_408. SWR_L3_CRoute_FFB_259. SWR_L3_CRoute_FFB_354. SWR_L3_CRoute_FFB_287. SWR_L3_CRoute_FFB_288. SWR_L3_CRoute_FFB_228. SWR_L3_CRoute_FFB_324. SWR_L3_CRoute_FFB_283. SWR_L3_CRoute_FFB_284. SWR_L3_CRoute_FFB_285. SWR_L3_CRoute_FFB_293. SWR_L3_CRoute_FFB_414. Callout function (from CSH module), which is forwarding new UHF FFB telegram for processing.Please find detail information in the header file.
References bFalse, PORT_FFB_TELEGRAMM, TransponderIDComparison, sUHF_Message, S_UHF_Message::u8RFTransponderID, S_UHF_Message::sFlags, S_FDH_Flags::ResetButtonAction, FUNC_NUMMER_FZV, evUHFEmpfang_FZV, FUNC_NUMMER_COMFORT, evUHFEmpfang_Comfort, FUNC_NUMMER_RELEASE, evUHFEmpfang_Release, bTrue, RAW_UHF_TRANSPONDER_ID_LENGTH, S_UHF_Message::u8RFPortNumber, S_UHF_Message::u8RFFunctionNumber, S_UHF_Message::u8BatteryLevel, S_UHF_Message::u8SignalStaerke, UHF_MessageValidation, S_FDH_Flags::DiscardTelegram, S_FDH_Flags::NewMessage, RTE_E_OK.
Referenced by TEST_evUHFEmpfang.