FDH_Task.h
void FDH_InitVarFunc(void)
FDH init function called by scheduler.Maps NVM RAM buffer+blobk_id handles (entries) to S_WCZ_Group internal container structure. There are 6 block/buffers handles assigned (triple storage, 2 slots - A/B) and single block for WCZ status. In each block up to 8 keys WCZ may be stored, depending on the number of learned keys. In status block up to 8 key WCZ statuses are stored and index of last-used-key. Called by scheduler once on each EnterRun. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssNvmWcz sValue[].pim_ptr and sStatus.pim_ptr - write access. Input->Output-CorrelationN/A Activity Diagram FDH_InitVarFunc Test MethodSWATT unit test. The testing method is described in TEST_FDH_InitVarFunc TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. FDH init function called by scheduler. Please find detail information in header file.
References bFDH_Run, bTrue.
Referenced by TEST_FDH_InitVarFunc.
void FDH_Start(void)
Initialization routine, called once on each EnterRun event by scheduler.Three major subtasks contexts (internal data) are initialized: "UHF reception", "WCZ NVM processing" and "WCZ Timer execution". reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram FDH_Start Test MethodSWATT unit test. The testing method is described in TEST_FDH_Start TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. Initialization routine, called once on each EnterRun event by scheduler. Please find detail information in header file.
References UHF_MessageInitialization, UHF_TimerInitialization, WCZ_Initialization.
Referenced by TEST_FDH_Start.
void FDH_Stop(void)
De-Initialization routine, to be called once on each ExitRun event.No functionality, required by architecture. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Test MethodSWATT unit test. The testing method is described in TEST_FDH_Stop TraceabilityDesign Decision - Justification. Design decision: component de-init function called by scheduler, currently not used. De-Initialization routine, to be called once on each ExitRun event. Please find detail information in header file.
Referenced by TEST_FDH_Stop.
void FDH_TaskCyclicEvent(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode.4 major subtasks are referenced periodically: -WCZ processing -UHF message processing -WCZ timers processing -UHF timers processing reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram FDH_TaskCyclicEvent Test MethodSWATT unit test. The testing method is described in TEST_FDH_TaskCyclicEvent TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_268. Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References bFalse, bFDH_Run, WCZ_CyclicHandle, UHF_CyclicHandle, WCZ_TimerHandle, UHF_TimerHandle.
Referenced by TEST_FDH_TaskCyclicEvent.