FDH_Toolbox.h
USE_CUSTOM_MEM_FUNC
boolean KeyIndexValidation(const uint8 KeyIndex)
Key index validation.Checks if key index is within acceptable values/range. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 KeyIndex - key index to check boolean - returns true if index within range <1..8>, otherwise false. GlobalsN/A Input->Output-CorrelationWhen UHF telegram is received, one of fields to validate is key index, based on slot number. Activity Diagram KeyIndexValidation Test MethodSWATT unit test. The testing method is described in TEST_KeyIndexValidation Verification criteriaTestcase shall check if function returns true for correct value range. TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_L3_CRoute_FFB_301 Design Decision - Justification. Helper function for condition check in order not to duplicate code. Checks if key index is within acceptable values/range.Please find detail information in header file.
References SWATT_BYPASS, m_KeyIndexValidation, KEY_INDEX_1, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8, bTrue, bFalse.
Referenced by TEST_KeyIndexValidation, TEST_FDH_IndexToKeyIndex, evUHFEmpfang_FZV, evUHFEmpfang_Comfort, WCZ_KeyStatusValidation, WCZ_SetupSlot, WCZ_SetStatus, WCZ_SetValue, WCZ_DataExchange.
uint8 FDH_KeyIndexToIndex(const uint8 KeyIndex)
Translation of KeyIndex (functional key number 1..8) to internal C-style index to key tables (0..7). reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 KeyIndex - functional key number (as used in SWRs when key number is referenced), value range 1-8. uint8 - c style indexing for range 0-7. GlobalsN/A Input->Output-CorrelationPassed value is decreased by 1 and returned. Test MethodSWATT unit test. The testing method is described in TEST_FDH_KeyIndexToIndex TraceabilityDesign Decision - Justification. Design decision: helper function for value conversion. Translation of KeyIndex (functional key number 1..8) to internal C-style index to key tables (0..7). Please find detail information in header file.
Referenced by TEST_FDH_KeyIndexToIndex, evUHFEmpfang_FZV, WCZ_KeyStatusValidation, WCZ_CheckKeyActive, WCZ_SetupSlot, WCZ_Synchronization, WCZ_SetStatus, WCZ_SetValue, WCZ_DataExchange, WCZ_CyclicHandle, WCZ_Validate.
uint8 FDH_IndexToKeyIndex(const sint8 Index)
Translation of C-style key index (0..7) to functional key number (1..8) reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous sint8 Index- c style indexing for range 0-7. uint8 - functional key number (as used in SWRs when key number is referenced), value range 1-8. GlobalsN/A Input->Output-CorrelationPassed value is increased by 1 and returned. Test MethodSWATT unit test. The testing method is described in TEST_FDH_IndexToKeyIndex TraceabilityDesign Decision - Justification. Design decision: helper function for value conversion. Translation of C-style key index (0..7) to functional key number (1..8) Please find detail information in header file.
Referenced by TEST_FDH_IndexToKeyIndex, WCZ_StatusReadFromNvm, WCZ_StatusWriteToNvm, WCZ_StatusVerifyNvm, WCZ_ValueReadFromNvm, WCZ_ValueWriteToNvm, WCZ_ValueVerifyNvm, WCZ_TimerHandle, evFFBDataExchange.