FDH_UHF_Handler.c
NUM_NUTZDATEN_LENGTH
Length of num Nutzdaten Length data. values 7 Satisfies requirementSWR_L3_CRoute_FFB_226
PAYLOAD_BUTTONCODE_NO
Value for button code received from UHF telegram - no button. values 0u Satisfies requirementSWR_L3_CRoute_FFB_245
PAYLOAD_BUTTONCODE_LOCK
Value for button code received from UHF telegram - lock. values 1u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_162.
PAYLOAD_BUTTONCODE_UNLOCK
Value for button code received from UHF telegram - unlock. values 2u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_150.
PAYLOAD_BUTTONCODE_TRUNC
Value for button code received from UHF telegram - trunk. values 3u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_160. SWR_L3_CRoute_FFB_670.
PAYLOAD_BUTTONCODE_SD_LEFT
Value for button code received from UHF telegram - sliding door left. values 4u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_687. SWR_L3_CRoute_FFB_690.
PAYLOAD_BUTTONCODE_SD_RIGTH
Value for button code received from UHF telegram - sliding door right. values 5u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_688. SWR_L3_CRoute_FFB_691.
PAYLOAD_BUTTONCODE_PANIC
Value for button code received from UHF telegram - panic. values 6u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_161.
PAYLOAD_BUTTONCODE_REMOTESTART
Value for button code received from UHF telegram - remote start. values 7u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_157.
PAYLOAD_BUTTONCODE_CONVERTIBLE_TOP
Value for button code received from UHF telegram - remote start. values 8u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_156.
PAYLOAD_BUTTONCODE_E_TASTE
Value for button code received from UHF telegram - convertible top. values 9u Satisfies requirementSWR_L3_CRoute_FFB_245. SWR_L3_CRoute_FFB_155.
PORT_UNKNOWN_TELEGRAMM
Init value for sUHF_Message u8RFPortNumber. values 255u
PORT_FFB_TELEGRAMM
Value used for sUHF_Message u8RFPortNumber condition check. values 1u Satisfies requirementSWR_L3_CRoute_FFB_205
FUNC_UNKNOWN_FUNC
Init value for sUHF_Message u8RFFunctionNumber. values 255u
FUNC_NUMMER_FZV
Value used for sUHF_Message u8RFFunctionNumber condition check. values 0u Satisfies requirementSWR_L3_CRoute_FFB_208
FUNC_NUMMER_COMFORT
Value used for sUHF_Message u8RFFunctionNumber condition check. values 1u Satisfies requirementSWR_L3_CRoute_FFB_208
FUNC_NUMMER_RELEASE
Value used for sUHF_Message u8RFFunctionNumber condition check. values 2u Satisfies requirementSWR_L3_CRoute_FFB_208
BATTERY_VOLTAGE_UNKNOWN
Init value for sUHF_Message u8BatteryLevel. values 255u
STAERKE_UNKNOWN
Init value for sUHF_Message u8SignalStaerke. values 255u
FDH_TIMERA_STOP
Stop value for u32FDH_TimerA timer. values 0u
FDH_TIMERB_STOP
Stop value for u32FDH_TimerB timer. values 0u
FRAME_COUNTER_MAX
Max value for frame counter. values 7u Satisfies requirementSWR_L3_CRoute_FFB_354
FRAME_COUNTER_MIN
Min value for frame counter. values 7u Satisfies requirementSWR_L3_CRoute_FFB_354
S_UHF_Message sUHF_Message
Variable holding UHF Message data.Structure contains main input data for FDH subcomponent, used for UHF frame validation. values N/A unit N/A resolution N/A context {task, used by multiple functions} protection {static global variable for FDH_Task.c}
Referenced by UHF_MessageValidation, UHF_LFRange, evUHFEmpfang_FZV, evUHFEmpfang_Comfort, evUHFEmpfang_Release, UHF_MessageInitialization, UHF_CyclicHandle, evCheckSignatureResp, evCheckTransponderIDResp, evUHFEmpfang, TEST_UHF_MessageValidation, TEST_UHF_LFRange, TEST_UHF_MessageInitialization, TEST_UHF_CyclicHandle, TEST_evCheckSignatureResp, TEST_evCheckTransponderIDResp, TEST_evUHFEmpfang_FZV, TEST_evUHFEmpfang_Comfort, TEST_evUHFEmpfang_Release, TEST_evUHFEmpfang, WCZ_Validate.
uint32 u32FDH_TimerA
Timer for TimeOut Window A.Timer related to the FZV Telegram reception. values 0 - timer stopped unit N/A resolution N/A context {task, used inside UHF_TimerInitialization(), UHF_CyclicHandle(), UHF_TimerHandle()} protection {static global variable for FDH_Task.c}
Referenced by UHF_TimerInitialization, UHF_CyclicHandle, UHF_TimerHandle, TEST_UHF_TimerInitialization, TEST_UHF_CyclicHandle, TEST_UHF_TimerHandle.
uint32 u32FDH_TimerB
Timer for TimeOut Window B.Timer related to the Comfort Frame reception. values 0 - timer stopped unit N/A resolution N/A context {task, used inside UHF_TimerInitialization(), UHF_CyclicHandle(), UHF_TimerHandle()} protection {static global variable for FDH_Task.c}
Referenced by UHF_TimerInitialization, UHF_CyclicHandle, UHF_TimerHandle, TEST_UHF_TimerInitialization, TEST_UHF_CyclicHandle, TEST_UHF_TimerHandle.
static void UHF_MessageValidation(void)
Function validating UHF message, based on function number.Request validation of: transponderId (for each payload) & signature of raw UHF payload of received payload (only for FZV). Both requests are sent to CSH module using C/S interfaces. In addition battery level check is performed against invalid value. Then respective DTC event call is used. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssUHF_Message - read and write data. Input->Output-CorrelationBattery Level DTCs (for all keys is tested). Signature and TransponderId C/S interface requests started: evCheckSignatureReq, evCheckTransponderID. Responds to be expected via callout functions from CSH module evCheckSignatureResp evCheckTransponderIDResp. Activity Diagram UHF_LFRange Test MethodSWATT unit test. The testing method is described in TEST_UHF_MessageValidation TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_L3_CRoute_FFB_215. SWR_L3_CRoute_FFB_216. SWR_L3_CRoute_FFB_217. SWR_L3_CRoute_FFB_218. SWR_L3_CRoute_FFB_114. SWR_L3_CRoute_FFB_115. SWR_L3_CRoute_FFB_207. SWR_L3_CRoute_FFB_214. SWR_L3_CRoute_FFB_226. SWR_L3_CRoute_FFB_219. Design Decision - Justification. Helper function to reduce evUHFEmpfang code size. Function validating UHF message, based on function number.Please find detail information in the declaration above .
References SWATT_BYPASS, sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::TransponderIDValid, bFalse, UNUSED_RETVAL, S_UHF_Message::u8KeyIndex, S_UHF_Message::u8RFTransponderID, S_UHF_Message::u8RFFunctionNumber, FUNC_NUMMER_FZV, bTrue, NUM_NUTZDATEN_LENGTH, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_Payload_FZV::RolingCodeCounter, RAW_ROLLING_CODE_COUNTER_LENGTH, S_Payload_FZV::Crypto, S_UHF_Message::u8RFPortNumber, S_Payload_FZV::ButtonCode, S_Payload_FZV::FrameCounter, S_Payload_FZV::SlotNumber, S_FDH_Flags::SignatureValid, RAW_SIGNATURE_LENGTH, BATTERY_VOLTAGE_UNKNOWN, S_UHF_Message::u8BatteryLevel, BatteryLevelDTC, FUNC_NUMMER_COMFORT, FUNC_NUMMER_RELEASE.
Referenced by evUHFEmpfang, TEST_UHF_MessageValidation, TEST_evUHFEmpfang.
static void UHF_LFRange(void)
Function setting internal flags based on codings.Range flags mirror respective ANP parameter values into subcomponent UHF message telegram buffer. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalssUHF_Message sFlags.LFRangeEntire - set flag. sUHF_Message sFlags.LFRangeTrunk - set flag. Input->Output-CorrelationCalled from evUHFEmpfang when Comfort telegram is processed. Activity Diagram UHF_LFRange Test MethodSWATT unit test. The testing method is described in TEST_UHF_LFRange TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_181. SWR_L3_CRoute_FFB_182. Function setting internal flags based on codings.Please find detail information in the declaration above .
References SWATT_BYPASS, bFalse, sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::LFRangeEntire, bTrue, S_FDH_Flags::LFRangeTrunk.
Referenced by evUHFEmpfang_Comfort, TEST_UHF_LFRange, TEST_evUHFEmpfang_Comfort.
static void BatteryLevelDTC(const uint8 KeyIndex, const Dem_EventStatusType status)
Function for handling of DEM event interface.Function is handling DEM event interface for all theoretically configurable key indicates regarding "Defective key battery measurement" fault. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 KeyIndex - key index with valid range 1..8 [in] Dem_EventStatusType status - if battery measurement level shows defective value, DTC = DEM_EVENT_STATUS_PREFAILED, otherwise = DEM_EVENT_STATUS_PREPASSED void GlobalsN/A Input->Output-CorrelationFor each key, there is assigned defective key DTC, which shall be tested. DTC is reported to DEM, which is accessible by diagnostic client (workshop, telemetric, HMI). Activity Diagram BatteryLevelDTC Test MethodSWATT unit test. The testing method is described in TEST_BatteryLevelDTC TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_GW_3262. SWR_ICAS1_GW_3267. SWR_ICAS1_GW_3271. SWR_ICAS1_GW_3275. SWR_ICAS1_GW_3279. SWR_ICAS1_GW_3283. SWR_ICAS1_GW_3287. SWR_ICAS1_GW_3291. SWR_L3_CRoute_FFB_114. SWR_L3_CRoute_FFB_115. Design Decision - Justification. Helper function to reduce UHF_MessageValidation code size. Function for handling of DEM event interface.Please find detail information in the declaration above .
References SWATT_BYPASS, KEY_INDEX_1, UNUSED_RETVAL, KEY_INDEX_2, KEY_INDEX_3, KEY_INDEX_4, KEY_INDEX_5, KEY_INDEX_6, KEY_INDEX_7, KEY_INDEX_8.
Referenced by UHF_MessageValidation, TEST_UHF_MessageValidation, TEST_BatteryLevelDTC.
static void ButtonCodeReport(const uint8 ButtonCode, const uint8 KeyIndex, const boolean LFBit, const boolean LFRangeEntire, const boolean LFRangeTrunk)
Function proccessing UHF telegram button code.Button code is mapped to specific logic RTE signal, according to SW requirements, in order to generate events for ZV functionality. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_172} {SWR_L3_CRoute_FFB_255} {SWR_L3_CRoute_FFB_246} {SWR_L3_CRoute_FFB_671} {SWR_L3_CRoute_FFB_675} {SWR_L3_CRoute_FFB_676} {SWR_L3_CRoute_FFB_677} {SWR_L3_CRoute_FFB_250} {SWR_L3_CRoute_FFB_686} {SWR_L3_CRoute_FFB_716} {SWR_L3_CRoute_FFB_718} {SWR_L3_CRoute_FFB_254} {SWR_L3_CRoute_FFB_689} {SWR_L3_CRoute_FFB_717} {SWR_L3_CRoute_FFB_247} {SWR_L3_CRoute_FFB_251} {SWR_L3_CRoute_FFB_253} {SWR_L3_CRoute_FFB_252} uint8 ButtonCode - code received from UHF telegram. [in] uint8 KeyIndex - valid range 1..8. [in] boolean LFBit - valid range 1..8. [in] boolean LFRangeEntire - valid range 1..8. [in] boolean LFRangeTrunk - valid range 1..8. void GlobalsN/A Input->Output-CorrelationInput ButtonCode signal, is mapped to activation (=true) of specific RTE output signal. The signals are connected to and trigger ZV_Lib component to execute vehicle access operations. For few comfort signals (TRUNK, CONVERTIBLE), corresponding LF signals are set (LFBit, LFRange). TRUNK signal is handled in HandleButtonCodeTrunk function. Activity Diagram ButtonCodeReport Test MethodSWATT unit test. The testing method is described in TEST_ButtonCodeReport TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_256. SWR_L3_CRoute_FFB_255. SWR_L3_CRoute_FFB_246. SWR_L3_CRoute_FFB_671. SWR_L3_CRoute_FFB_675. SWR_L3_CRoute_FFB_676. SWR_L3_CRoute_FFB_677. SWR_L3_CRoute_FFB_182. SWR_L3_CRoute_FFB_686. SWR_L3_CRoute_FFB_689. SWR_L3_CRoute_FFB_247. SWR_L3_CRoute_FFB_251. SWR_L3_CRoute_FFB_253. SWR_L3_CRoute_FFB_181. SWR_L3_CRoute_FFB_252. SWR_L3_CRoute_FFB_172. SWR_L3_CRoute_FFB_178. SWR_L3_CRoute_FFB_184. SWR_L3_CRoute_FFB_684. SWR_L3_CRoute_FFB_685. SWR_L3_CRoute_FFB_716. SWR_L3_CRoute_FFB_717. SWR_L3_CRoute_FFB_718. SWR_L3_CRoute_FFB_719. SWR_L3_CRoute_FFB_250. SWR_L3_CRoute_FFB_254. Function proccessing UHF telegram button code.Please find detail information in the declaration above .
References SWATT_BYPASS, bFalse, PAYLOAD_BUTTONCODE_LOCK, bTrue, PAYLOAD_BUTTONCODE_UNLOCK, PAYLOAD_BUTTONCODE_TRUNC, HandleButtonCodeTrunk, PAYLOAD_BUTTONCODE_SD_LEFT, UNUSED_RETVAL, PAYLOAD_BUTTONCODE_SD_RIGTH, PAYLOAD_BUTTONCODE_PANIC, PAYLOAD_BUTTONCODE_REMOTESTART, PAYLOAD_BUTTONCODE_CONVERTIBLE_TOP, PAYLOAD_BUTTONCODE_E_TASTE, PAYLOAD_BUTTONCODE_NO.
Referenced by UHF_CyclicHandle, UHF_TimerHandle, TEST_ButtonCodeReport, TEST_UHF_CyclicHandle, TEST_UHF_TimerHandle.
static boolean FrameCounterVerify(const uint8 pre, const uint8 cur)
New frame counter vs previous received check. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_297} {SWR_L3_CRoute_FFB_354} uint8 pre - previous frame Id [in] uint8 cur - present frame Id boolean - returns true if previous frame counter is smaller than present one or roll over from max to 0. GlobalsN/A Input->Output-CorrelationPositive assumption, according to requirements is, that consecutive frame numbers are received during single button press. Verification allows further processing of present UHF telegram holding same code. Otherwise button press ended and output signals to be cleared in further processing flow. Activity Diagram FrameCounterVerify Test MethodSWATT unit test. The testing method is described in TEST_FrameCounterVerify TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_354. SWR_L3_CRoute_FFB_297. New frame counter vs previous received check.Please find detail information in the declaration above .
References SWATT_BYPASS, bFalse, FRAME_COUNTER_MAX, FRAME_COUNTER_MIN, bTrue.
Referenced by evUHFEmpfang_FZV, TEST_FrameCounterVerify.
static boolean TransponderIDComparison(const uint8 tid_1[], const uint8 tid_2[])
FDH internal mem compare function.Function limited to amount of bytes used for TransponderId identification. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 tid_1[] - pointer to the buffer holding first transponder Id. [in] uint8 tid_2[] - pointer to the buffer holding second transponder Id. boolean - true if both buffers hold same values, otherwise false. GlobalsN/A Input->Output-CorrelationIn use during UHF telegram processing flow, determining change of tke keyfob in consecutive UHF telegrams. If occurs, current Keyfob key press pending event should be ended and new one started. Activity Diagram TransponderIDComparison Test MethodSWATT unit test. The testing method is described in TEST_TransponderIDComparison TraceabilityDesign Decision - Justification. Design decision: helper function to reduce evUHFEmpfang code size. FDH internal mem compare function. Please find detail information in the declaration above .
References SWATT_BYPASS, bTrue, RAW_UHF_TRANSPONDER_ID_LENGTH, bFalse.
Referenced by evUHFEmpfang, TEST_TransponderIDComparison, TEST_evUHFEmpfang.
static void HandleButtonCodeTrunk(boolean *bFFBAnfHDEntr, boolean *bFFBAnfCabinLock)
Function to handle received button code for trunk.Function checks how ButtonCode 'Trunk Unlock trigger' should be interpreted. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_671} {SWR_L3_CRoute_FFB_675} {SWR_L3_CRoute_FFB_676} {SWR_L3_CRoute_FFB_677} boolean *bFFBAnfCabinLock - pointer to flag informing if ButtonCode should be interpreted as Trunk unlock (in case of passenger vehicles). [out] boolean *bFFBAnfHDEntr - pointer to flag informing if ButtonCode should be interpreted as Cargo unlock (in case of cargo vehicles). void GlobalsN/A Input->Output-CorrelationTrunk Unlock trigger can be interpreted as Trunk unlock and Cargo unlock. The selection of the proper trigger is done based on the pa_NFZ_Schliessung adaptation's value. Activity Diagram HandleButtonCodeTrunk Test MethodSWATT unit test. The testing method is described in TEST_HandleButtonCodeTrunk TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_L3_CRoute_FFB_671. SWR_L3_CRoute_FFB_675. SWR_L3_CRoute_FFB_676. SWR_L3_CRoute_FFB_677. Design Decision - Justification. Helper function to reduce ButtonCodeReport code size. Function to handle received button code for trunk.Please find detail information in the declaration above .
References bFalse, UNUSED_RETVAL, bTrue.
Referenced by ButtonCodeReport, TEST_HandleButtonCodeTrunk.
static void evUHFEmpfang_FZV(boolean bTransponderIdComparison, const uint8 *rawUHFPayload, boolean *out_bFunctionNumberValid, boolean *out_bKeyIndexValid)
Helper function for handling FZV telegram inside evUHFEmpfangThe simplified flow is: copy FZV payload to static buffer determine key number (from slot), validate key index (unset if invalid) recognize if FZV first telegram in burst -> set flag needed for WCZ processing recognize if frame counter change measn button code reset or just button code changes -> set button code reset flag reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_354} {SWR_L3_CRoute_FFB_259} boolean bTransponderIdComparison - Transponder ID comparison result uint8 rawUHFPayload[] - raw data of telegram for parsing, includes WCZ, signature,... [out] boolean* out_bFunctionNumberValid - is FZV frame valid [out] boolean* out_bKeyIndexValid - is key index valid void GlobalssUHF_Message sPayload.FZV - R/W access sUHF_Message u8KeyIndex - R/W sUHF_Message sFlags.LFBit - W sUHF_Message sFlags.LFRangeEntire - W sUHF_Message sFlags.LFRangeTrunk - W sUHF_Message sFlags.DiscardTelegram - R/W sUHF_Message sFlags.FirstFzvTelegram - W sUHF_Message sFlags.ValidFzv - R/W sUHF_Message sFlags.ResetButtonAction - W Input->Output-CorrelationCallout from UHF Master on new telegram reception to initiate processing. sUHF internal message attributes/flags are filled in and message validation is next step, then UHF_CyclicHandle will process further the new telegram. Activity Diagram evUHFEmpfang_FZV Test MethodSWATT unit test. The testing method is described in TEST_evUHFEmpfang_FZV TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_206. SWR_L3_CRoute_FFB_211. SWR_L3_CRoute_FFB_324. SWR_L3_CRoute_FFB_300. SWR_L3_CRoute_FFB_178. SWR_L3_CRoute_FFB_181. SWR_L3_CRoute_FFB_182. SWR_L3_CRoute_FFB_301. SWR_L3_CRoute_FFB_406. SWR_L3_CRoute_FFB_407. SWR_L3_CRoute_FFB_408. SWR_L3_CRoute_FFB_259. SWR_L3_CRoute_FFB_354. Helper function for handling FZV telegram inside evUHFEmpfangPlease find detail information in the declaration above .
References SWATT_BYPASS, NUM_KEY_LENGTH, sUHF_Message, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_Payload_FZV::FrameCounter, S_Payload_FZV::ButtonCode, KEY_INDEX_UNSET, S_UHF_Message::u8KeyIndex, FDH_KeyIndexToIndex, S_Payload_FZV::SlotNumber, S_UHF_Message::sFlags, S_FDH_Flags::LFBit, bFalse, S_FDH_Flags::LFRangeEntire, S_FDH_Flags::LFRangeTrunk, KeyIndexValidation, S_FDH_Flags::FirstFzvTelegramWasSet, bTrue, S_FDH_Flags::DiscardTelegram, S_FDH_Flags::FirstFzvTelegram, S_FDH_Flags::ValidFzv, FrameCounterVerify, S_FDH_Flags::ResetButtonAction.
Referenced by evUHFEmpfang, TEST_evUHFEmpfang_FZV, TEST_evUHFEmpfang.
static void evUHFEmpfang_Comfort(boolean bTransponderIdComparison, const uint8 *rawUHFPayload, boolean *out_bFunctionNumberValid, boolean *out_bKeyIndexValid)
Helper function for handling COMFORT telegram inside evUHFEmpfangThe simplified flow is: if valid FZV (must be, comfort is continuation) - copy Comfort payload - copy LF bit, set LF range flags from Anp - determine key number (from slot), validate key index (unset if invalid) - recognize if button code changed or transponder Id is not as previous -> set button code reset flag reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous {SWR_L3_CRoute_FFB_287} {SWR_L3_CRoute_FFB_288} {SWR_L3_CRoute_FFB_283} boolean bTransponderIdComparison - Transponder ID comparison result uint8 rawUHFPayload[] - raw data of telegram for parsing, includes WCZ, signature,... [out] boolean* out_bFunctionNumberValid - is Comfort frame valid [out] boolean* out_bKeyIndexValid - is key index valid void GlobalssUHF_Message sPayload.FZV - R access sUHF_Message sPayload.Comfort - R/W access sUHF_Message u8KeyIndex - R/W sUHF_Message u8RFFunctionNumber - R sUHF_Message sFlags.LFBit - W sUHF_Message sFlags.ValidFzv - R/W sUHF_Message sFlags.ResetButtonAction - W Input->Output-CorrelationCallout from UHF Master on new telegram reception to initiate processing. sUHF internal message attributes/flags are filled in and message validation is next step, then UHF_CyclicHandle will process further the new telegram. Activity Diagram evUHFEmpfang_Comfort Test MethodSWATT unit test. The testing method is described in TEST_evUHFEmpfang_Comfort TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_206. SWR_L3_CRoute_FFB_324. SWR_L3_CRoute_FFB_300. SWR_L3_CRoute_FFB_178. SWR_L3_CRoute_FFB_301. SWR_L3_CRoute_FFB_287. SWR_L3_CRoute_FFB_288. SWR_L3_CRoute_FFB_228. SWR_L3_CRoute_FFB_324. SWR_L3_CRoute_FFB_283. Helper function for handling COMFORT telegram inside evUHFEmpfangPlease find detail information in the declaration above .
References SWATT_BYPASS, sUHF_Message, S_UHF_Message::u8RFFunctionNumber, bFalse, S_UHF_Message::sFlags, S_FDH_Flags::ValidFzv, FUNC_NUMMER_COMFORT, S_UHF_Message::sPayload, S_UHF_Payload::Comfort, S_Payload_Comfort::ButtonCode, S_UHF_Payload::FZV, S_Payload_FZV::ButtonCode, S_UHF_Message::u8KeyIndex, S_Payload_Comfort::SlotNumber, S_Payload_Comfort::LFPing, S_FDH_Flags::LFBit, bTrue, UHF_LFRange, KeyIndexValidation, KEY_INDEX_UNSET, S_FDH_Flags::ResetButtonAction.
Referenced by evUHFEmpfang, TEST_evUHFEmpfang_Comfort, TEST_evUHFEmpfang.
static void evUHFEmpfang_Release(boolean *out_bFunctionNumberValid, boolean *out_bKeyIndexValid)
Helper function for handling RELEASE telegram inside evUHFEmpfangThe simplified flow is: Unset key index, unset VFZ valid flag, clear other flags reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous boolean* out_bFunctionNumberValid - is FZV frame valid [out] boolean* out_bKeyIndexValid - is key index valid void GlobalssUHF_Message u8KeyIndex - R/W sUHF_Message sFlags.LFBit - W sUHF_Message sFlags.LFRangeEntire - W sUHF_Message sFlags.LFRangeTrunk - W sUHF_Message sFlags.ValidFzv - R/W Input->Output-CorrelationCallout from UHF Master on new telegram reception to initiate processing. sUHF internal message attributes/flags are filled in and message validation is next step, then UHF_CyclicHandle will process further the new telegram. Activity Diagram evUHFEmpfang_Release Test MethodSWATT unit test. The testing method is described in TEST_evUHFEmpfang_Release TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_FFB_178. SWR_L3_CRoute_FFB_181. SWR_L3_CRoute_FFB_182. Helper function for handling RELEASE telegram inside evUHFEmpfangPlease find detail information in the declaration above .
References SWATT_BYPASS, sUHF_Message, S_UHF_Message::u8KeyIndex, KEY_INDEX_UNSET, S_UHF_Message::sFlags, S_FDH_Flags::LFBit, bFalse, S_FDH_Flags::LFRangeEntire, S_FDH_Flags::LFRangeTrunk, S_FDH_Flags::ValidFzv, bTrue.
Referenced by evUHFEmpfang, TEST_evUHFEmpfang_Release, TEST_evUHFEmpfang.
void UHF_MessageInitialization(void)
Init function for sUHF_Message.Please find detail information in the header file.
References sUHF_Message, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_UHF_Payload::Comfort, S_UHF_Message::sFlags, S_FDH_Flags::DiscardTelegram, bFalse, S_FDH_Flags::FirstFzvTelegram, S_FDH_Flags::FirstFzvTelegramWasSet, S_FDH_Flags::NewMessage, S_FDH_Flags::TransponderIDValid, S_FDH_Flags::SignatureValid, S_FDH_Flags::ResetButtonAction, S_FDH_Flags::ValidFzv, S_FDH_Flags::LFBit, S_FDH_Flags::LFRangeEntire, S_FDH_Flags::LFRangeTrunk, S_UHF_Message::u8KeyIndex, KEY_INDEX_UNSET, S_UHF_Message::u8RFTransponderID, RAW_UHF_TRANSPONDER_ID_LENGTH, S_UHF_Message::u8RFPortNumber, PORT_UNKNOWN_TELEGRAMM, S_UHF_Message::u8RFFunctionNumber, FUNC_UNKNOWN_FUNC, S_UHF_Message::u8BatteryLevel, BATTERY_VOLTAGE_UNKNOWN, S_UHF_Message::u8SignalStaerke, STAERKE_UNKNOWN.
Referenced by FDH_Start, TEST_UHF_MessageInitialization.
void UHF_TimerInitialization(void)
Function initializes internal timers i.e. timers are stopped.Please find detail information in the header file.
References u32FDH_TimerA, FDH_TIMERA_STOP, u32FDH_TimerB, FDH_TIMERB_STOP.
Referenced by FDH_Start, TEST_UHF_TimerInitialization.
void UHF_CyclicHandle(void)
Main cyclic function for UHF message processing.Please find detail information in the header file.
References bFalse, sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::NewMessage, S_FDH_Flags::TransponderIDValid, S_FDH_Flags::SignatureValid, S_FDH_Flags::ResetButtonAction, ButtonCodeReport, PAYLOAD_BUTTONCODE_NO, KEY_INDEX_UNSET, FUNC_NUMMER_COMFORT, S_UHF_Message::u8RFFunctionNumber, PORT_FFB_TELEGRAMM, S_UHF_Message::u8RFPortNumber, S_UHF_Message::u8KeyIndex, FUNC_NUMMER_FZV, WCZ_Validate, S_UHF_Message::sPayload, S_UHF_Payload::FZV, S_Payload_FZV::ButtonCode, UNUSED_RETVAL, u32FDH_TimerA, u32FDH_TimerB, FDH_TIMERB_STOP, FDH_TIMERA_STOP, S_UHF_Payload::Comfort, S_Payload_Comfort::ButtonCode, S_FDH_Flags::LFBit, S_FDH_Flags::LFRangeEntire, S_FDH_Flags::LFRangeTrunk, FUNC_NUMMER_RELEASE.
Referenced by FDH_TaskCyclicEvent, TEST_UHF_CyclicHandle.
void UHF_TimerHandle(void)
Function handling UHF timer A and B.Please find detail information in the header file.
References FDH_TIMERA_STOP, u32FDH_TimerA, FDH_TIMERB_STOP, u32FDH_TimerB, ButtonCodeReport, PAYLOAD_BUTTONCODE_NO, KEY_INDEX_UNSET, bFalse.
Referenced by FDH_TaskCyclicEvent, TEST_UHF_TimerHandle.
void evCheckSignatureResp(boolean bSignatureValid, uint8 numCheckSignatureStatus)
Function providing result to the C/S service evCheckSignatureReq.Please find detail information in the header file.
References sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::SignatureValid, bFalse.
Referenced by TEST_evCheckSignatureResp.
void evCheckTransponderIDResp(boolean bTransponderIDValid, uint8 numCheckTransponderIDStatus)
Function providing result to the C/S service evCheckTransponderIDReq.Please find detail information in the header file.
References sUHF_Message, S_UHF_Message::sFlags, S_FDH_Flags::TransponderIDValid, bFalse.
Referenced by TEST_evCheckTransponderIDResp.
Std_ReturnType evUHFEmpfang(const uint8 *rawUHFTransponderID, uint8 numUHFPortNumber, uint8 numUHFFunktionsnummer, uint8 numBatteryLevel, const uint8 *rawUHFPayload, boolean bCRCValid, uint8 u8UHFSignalstaerke)
Callout function (from CSH module), which is forwarding new UHF FFB telegram for processing.Please find detail information in the header file.
References bFalse, PORT_FFB_TELEGRAMM, TransponderIDComparison, sUHF_Message, S_UHF_Message::u8RFTransponderID, S_UHF_Message::sFlags, S_FDH_Flags::ResetButtonAction, FUNC_NUMMER_FZV, evUHFEmpfang_FZV, FUNC_NUMMER_COMFORT, evUHFEmpfang_Comfort, FUNC_NUMMER_RELEASE, evUHFEmpfang_Release, bTrue, RAW_UHF_TRANSPONDER_ID_LENGTH, S_UHF_Message::u8RFPortNumber, S_UHF_Message::u8RFFunctionNumber, S_UHF_Message::u8BatteryLevel, S_UHF_Message::u8SignalStaerke, UHF_MessageValidation, S_FDH_Flags::DiscardTelegram, S_FDH_Flags::NewMessage, RTE_E_OK.
Referenced by TEST_evUHFEmpfang.