WFS_dem.c
void WFS_ImmoNoInitCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_ImmoNoInitCallback_EventStatusChanged.
void WFS_EcuDefectCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_EcuDefectCallback_EventStatusChanged.
void WFS_DevModeActiveCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_DevModeActiveCallback_EventStatusChanged.
void WFS_SupplierModeActCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_SupplierModeActCallback_EventStatusChanged.
void WFS_KeyNoSignalCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyNoSignalCallback_EventStatusChanged.
void WFS_KeyLogisticsNoDLCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLogisticsNoDLCallback_EventStatusChanged.
void WFS_KeyLogisticsWrongDataCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLogisticsWrongDataCallback_EventStatusChanged.
void WFS_KeyImplausibleSignalCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyImplausibleSignalCallback_EventStatusChanged.
void WFS_KeyLearnGenFcnCdCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnGenFcnCdCallback_EventStatusChanged.
void WFS_KeyLearnTypeImplausCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnTypeImplausCallback_EventStatusChanged.
void WFS_KeyLearnWrTestFailCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnWrTestFailCallback_EventStatusChanged.
void WFS_KeyLearnAuthProdCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnAuthProdCallback_EventStatusChanged.
void WFS_KeyLearnWrSKC1Callback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnWrSKC1Callback_EventStatusChanged.
void WFS_KeyLearnAuthPairCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnAuthPairCallback_EventStatusChanged.
void WFS_KeyLearnWrSKC3Callback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnWrSKC3Callback_EventStatusChanged.
void WFS_KeyLearnWrongUhfCfgCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnWrongUhfCfgCallback_EventStatusChanged.
void WFS_KeyLearnVerifyFFBCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnVerifyFFBCallback_EventStatusChanged.
void WFS_KeyLearnVerifyCRCCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnVerifyCRCCallback_EventStatusChanged.
void WFS_KeyLearnGenWUPCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnGenWUPCallback_EventStatusChanged.
void WFS_KeyLearnFFBCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnFFBCallback_EventStatusChanged.
void WFS_KeyLearnVerifyUIDCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_KeyLearnVerifyUIDCallback_EventStatusChanged.
void WFS_MSG1UnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_MSG1UnauthorizedCallback_EventStatusChanged.
void WFS_MSG2UnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_MSG2UnauthorizedCallback_EventStatusChanged.
void WFS_MSG3UnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_MSG3UnauthorizedCallback_EventStatusChanged.
void WFS_MSG4UnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_MSG4UnauthorizedCallback_EventStatusChanged.
void WFS_GSGUnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_GSGUnauthorizedCallback_EventStatusChanged.
void WFS_ELVUnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_ELVUnauthorizedCallback_EventStatusChanged.
void WFS_OCUUnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_OCUUnauthorizedCallback_EventStatusChanged.
void WFS_VTSUnauthorizedCallback(Dem_UdsStatusByteType EventStatusByteOld, Dem_UdsStatusByteType EventStatusByteNew)
Referenced by Rte_Call_Dem_WFS_VTSUnauthorizedCallback_EventStatusChanged.
Std_ReturnType Rte_Call_Dem_WFS_ImmoNoInitCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of Immobilizer was not initialized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_ImmoNoInitCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_507
References EventId, WFS_ImmoNoInitCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_EcuDefectCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of ECU defect. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_EcuDefectCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_504
References EventId, WFS_EcuDefectCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_DevModeActiveCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of activation of Development Mode. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_DevModeActiveCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_437
References EventId, WFS_DevModeActiveCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_SupplierModeActCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of activation of Supplier Mode. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_SupplierModeActCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_530
References EventId, WFS_SupplierModeActCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyNoSignalCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of no signal of Key. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyNoSignalCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_524
References EventId, WFS_KeyNoSignalCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLogisticsNoDLCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of no DL of Key Logistics. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLogisticsNoDLCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_522
References EventId, WFS_KeyLogisticsNoDLCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLogisticsWrongDataCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of wrong data of Key Logistics. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLogisticsWrongDataCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_523
References EventId, WFS_KeyLogisticsWrongDataCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyImplausibleSignalCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of implausible signal of Key. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyImplausibleSignalCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_508
References EventId, WFS_KeyImplausibleSignalCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnGenFcnCdCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnGenFcnCd. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnGenFcnCdCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_512
References EventId, WFS_KeyLearnGenFcnCdCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnTypeImplausCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of implausible type of Key Learn. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnTypeImplausCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_514
References EventId, WFS_KeyLearnTypeImplausCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnWrTestFailCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnWrTestFail. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnWrTestFailCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_521
References EventId, WFS_KeyLearnWrTestFailCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnAuthProdCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnAuthProd. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnAuthProdCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_510
References EventId, WFS_KeyLearnAuthProdCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnWrSKC1Callback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnWrSKC1. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnWrSKC1Callback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_519
References EventId, WFS_KeyLearnWrSKC1Callback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnAuthPairCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnAuthPair. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnAuthPairCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_509
References EventId, WFS_KeyLearnAuthPairCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnWrSKC3Callback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnWrSKC3. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnWrSKC3Callback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_520
References EventId, WFS_KeyLearnWrSKC3Callback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnWrongUhfCfgCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of KeyLearnwrongUhfCfg. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnWrongUhfCfgCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_518
References EventId, WFS_KeyLearnWrongUhfCfgCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnVerifyFFBCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of Key Learn Verify FFB. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnVerifyFFBCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_516
References EventId, WFS_KeyLearnVerifyFFBCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnVerifyCRCCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of Key Learn Verify CRC. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnVerifyCRCCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_515
References EventId, WFS_KeyLearnVerifyCRCCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnGenWUPCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of Key Learn Generation of WUP. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnGenWUPCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_513
References EventId, WFS_KeyLearnGenWUPCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnFFBCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of Key Learn FFB. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnFFBCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_511
References EventId, WFS_KeyLearnFFBCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_KeyLearnVerifyUIDCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of Key Learn Verify UID. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_KeyLearnVerifyUIDCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_517
References EventId, WFS_KeyLearnVerifyUIDCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_MSG1UnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of MSG1 unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_MSG1UnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_525
References EventId, WFS_MSG1UnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_MSG2UnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of MSG2 unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_MSG2UnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_526
References EventId, WFS_MSG2UnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_MSG3UnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of MSG3 unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_MSG3UnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_527
References EventId, WFS_MSG3UnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_MSG4UnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of MSG4 unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_MSG4UnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_528
References EventId, WFS_MSG4UnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_GSGUnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of GSG unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_GSGUnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_506
References EventId, WFS_GSGUnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_ELVUnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of ELV unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_ELVUnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_505
References EventId, WFS_ELVUnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_OCUUnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of OCU unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_OCUUnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_529
References EventId, WFS_OCUUnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.
Std_ReturnType Rte_Call_Dem_WFS_VTSUnauthorizedCallback_EventStatusChanged(Dem_EventIdType EventId, Dem_EventStatusExtendedType EventStatusByteOld, Dem_EventStatusExtendedType EventStatusByteNew)
Wrapper for function responsible for changing status in case of VTS unauthorized. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dem_EventIdType EventId - event Id, not used Dem_EventStatusExtendedType EventStatusByteOld - event status to be replaced Dem_EventStatusExtendedType EventStatusByteNew - event status to be set Std_ReturnType E_OK - change of event status was successful (only positive response is returned) GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_Dem_WFS_VTSUnauthorizedCallback_EventStatusChanged TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_ICAS1_L3_WFS_531
References EventId, WFS_VTSUnauthorizedCallback, EventStatusByteOld, EventStatusByteNew.