dt::DummyClass
t_DummyEnum
description
const uint32 dt::DummyClass::u_DummyConstantValue
Description of this variable.
uint32 dt::DummyClass::u_DummyMemberFunction(const void *const p_Param1, uint32 p_Param2)
Short description of this function.
p_Param1 Description of parameter. With [in], [out] and [in,out] the direction of the parameter can be described. Describe range and and unit if applicable. (e.g. unit and range is not applicable for logical (boolean) and complex data types, e.g. enum, struct...) p_Param2 Current vehicle speed in m/s [0-250] Describe which value will be returned and its meaning (incl. error cases). Describe range and unit if applicable. Example 1: 1) returns calculated magic number 2) return 0 if calculation of magic number was not possible 3) return DT_ENUM_VAL1 if no magic number was found Example 2: 1) return calculated magic number if OK, or if error: 0 - calculation of magic number was not possibleDT_ENUM_VAL1 - no magic number was found GlobalsDescribe global input and output data and also its range and unit if applicable. This refers to data that is read or written but declared outside the function (global variables). Indicate if the data is input or output or both. If the data is already described at another location within the SW component, using a reference is sufficient e.g. t_DummyStructure Call Sequence Security Relevance Security-Relevant. Reason: description of reason for relevance Verification Criteria<Describe additional verifcation criteria for the unit testing. For this criteria additional unit tests are derived.> Example: 1) TEST_NS_CLASS_NAME_FUNCTION_NAME_2(): Verify that function returns 42 if the p_Param1 is 0. Test Method<List of unit tests (links) which are derived based on the unit test strategy. The description of the test cases is optional as the test method is mentioned in the header of the unit test implementation. In the rare cases where no unit test is possible, add the tag codereview{justification} (see r_GetInst()) > 1) TEST_NS_CLASS_NAME_FUNCTION_NAME_1(): short description of test case e.g. test if NvM data is written in next cycle if first try fails 2) TEST_NS_CLASS_NAME_FUNCTION_NAME_2(): test order of calls (dynamic module test) 3) TEST_NS_CLASS_NAME_FUNCTION_NAME_3(): test of boundary values 4) TEST_NS_CLASS_NAME_FUNCTION_NAME_4(): equivalence class analysis (test of representative values from input range) TraceabilityUse "designdecision" (see r_GetInst()) if no requiremets can be linked (see guideline for definition of design decision). Use "satisfy" with the corresponding requirements ID. Satisfies requirementSWR_ID_1 Additional description SWR_ID_2 Additional description
Referenced by TEST_NS_CLASS_NAME_FUNCTION_NAME_1, TEST_NS_CLASS_NAME_FUNCTION_NAME_2, TEST_NS_CLASS_NAME_FUNCTION_NAME_3, TEST_NS_CLASS_NAME_FUNCTION_NAME_4.
dt::DummyClass & dt::DummyClass::r_GetInst()
Returns a singleton instance of the class.
Use this function to retrieve a valid instance of the class, since it implements the singleton pattern. The singleton instance of this class. Security Relevance Not Security-Relevant. Verification Criteria<N/A> Test Method Code Reviewdescription of decision/justificationTraceability"designdecision"" in case there are no requirements which need to be satisfied by this function or use "satisfy" with the corresponding requirement ID Design Decisiondescription of decision
Referenced by TEST_NS_CLASS_NAME_FUNCTION_NAME_1, TEST_NS_CLASS_NAME_FUNCTION_NAME_2, TEST_NS_CLASS_NAME_FUNCTION_NAME_3, TEST_NS_CLASS_NAME_FUNCTION_NAME_4, TEST_NS_CLASS_NAME_FUNCTION_R_GETINST_1.
dt::DummyClass::DummyClass()
Constructor is made private to hide it from other modules.
References operator=.
dt::DummyClass::DummyClass(const DummyClass &r_Inst)
Copy-constructor - unimplemented, as it must not be used!
r_Inst Class instance which is used to initialize the new instance.
void dt::DummyClass::operator=(const DummyClass &r_Inst) const
Empty private assignment operator to prevent compiler to generate default one.
r_Inst Instance from which the data will be copied from.
Referenced by DummyClass.