WFS_Task.c
RTE_CAN_MIRROR_OFFSET
Offset from OSEK_Buffer_Start to RTE_Buffer_Start
RTE_LIN_MIRROR_OFFSET
Offset from OSEK_Buffer_Start to RTE_Buffer_Start
RTE_ETH_MIRROR_OFFSET
Offset from OSEK_Buffer_Start to RTE_Buffer_Start
RTE_WFS_CODE
Enable WFS specific code in Rte
Rte_DES_uint8DIM17 WFS_DES_StWegfahrsperre_rawVIN
RTE (EcuM/SchM) WFS Startup: WFS_Init10ms() ------------------------>| EnterRUN: WFS_OnEnterRun() ------------------------>| WFS_Task10ms()[first call] --------------->| | < Rte_Call_WFS_WFS_EcuM_StateRequest_RequestPOSTRUN() Running: WFS_Task10ms() ------------------------>| ...
WFS_Task10ms() ------------------------>| EnterPostRUn: WFS_EnterPostRUN()------------------------>| PostRUN: | < Rte_Call_WFS_WFS_EcuM_StateRequest_ReleasePOSTRUN() Shutdown ***************************************************************************Referrence to rawVin. values struct context task protection none storage class normal ram
Referenced by WFS_InitVarFunc.
Rte_DES_boolean WFS_DES_StFlashfreigabeReq_evAbbruch
Referrence to StFlashfreigabeReq_evAbbruch. values struct context task protection none storage class normal ram
Referenced by WFS_PreCustomHook.
Rte_DES_boolean WFS_DES_StFlashfreigabeReq_evAnforderung
Referrence to StFlashfreigabeReq_evAnforderung. values struct context task protection none storage class normal ram
Referenced by WFS_PreCustomHook.
Rte_ModeType_EcuM_Mode Rte_MdStat_EcuM
Referrence to EcuM CurrentMode. values struct context task protection none storage class normal ram
Referenced by Rte_Mode_WFS_WFS_EcuM_CurrentMode_currentMode.
volatile boolean WFS_EcuM_PostRun_requested
Shows that the library was initialized. Allows the cyclic function to run. Keeps ECUM in post run. values TRUE / FALSE context task protection none storage class normal ram
Referenced by WFS_InitVarFunc, Rte_Call_WFS_WFS_EcuM_StateRequest_RequestPOSTRUN, Rte_Call_WFS_WFS_EcuM_StateRequest_ReleasePOSTRUN.
boolean BSW_StFlashfreigabeReq_evAbbruch
BSW_StFlashfreigabeReq_evAbbruch To be modified by BSW. values TRUE / FALSE context task protection none storage class normal ram
Referenced by WFS_PreCustomHook.
boolean BSW_StFlashfreigabeReq_evAnforderung
BSW_StFlashfreigabeReq_evAnforderung To be modified by BSW. values TRUE / FALSE context task protection none storage class normal ram
Referenced by WFS_PreCustomHook, Rte_Call_WFS_StFlashfreigabeResp_evCallback.
void WFS_OnEnterRUN(void)
Referenced by WFS_Start.
void WFS_OnEnterPostRUN(void)
Referenced by WFS_Stop.
void WFS_preWFS_Task10msHook(void)
Referenced by WFS_TaskCyclicEvent.
void WFS_postWFS_Task10msHook(void)
Referenced by WFS_TaskCyclicEvent.
void WFS_KY_Event_call(void)
Kessy event caller. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_KY_Event_call TraceabilityThis function satisfies no DOORS Requirements. This is a helper function.
Referenced by WFS_TaskCyclicEvent.
void WFS_InitVarFunc(void)
Init the variables for the WFS module. This function is called by ModelsTask before starting the model (MmDoSetup is called). The code here must be short. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: [out] WFS_EcuM_PostRun_requested [out] WFS_DES_StWegfahrsperre_rawVIN Call Sequence Test MethodThe testing method is described on: TEST_WFS_InitVarFunc TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_117
References WFS_EcuM_PostRun_requested, WFS_Init10ms, WFS_DES_StWegfahrsperre_rawVIN.
void WFS_Start(void)
Start-up/init the WFS module. This function is called by modeltask in order to start-up/init the WFS module. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Start TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_114
References WFS_OnEnterRUN.
void WFS_Stop(void)
Stop callback for the WFS module. This function is called by ModelsTask when the StopEv is set (MmDoStop is called). Here is a good place to save data to NvRAM. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Stop TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_113
References WFS_OnEnterPostRUN.
void WFS_TaskCyclicEvent(EventMaskType ev)
Cyclic function of the WFS module. This function is called by ModelsTask when the model's recurrence occurs. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous EventMaskType ev - not used void GlobalsAffected variables: none Call Sequence During test design, following defines should be considered: WFS_ENABLE_RUNNABLE_HOOKS Test MethodThe testing method is described on: TEST_WFS_TaskCyclicEvent TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_154
References WFS_Prepare_RteBuffer, WFS_preWFS_Task10msHook, WFS_PreCustomHook, WFS_Task10ms, WFS_KY_Event_call, WFS_PostStubHook, WFS_postWFS_Task10msHook.
void WFS_PreCustomHook(void)
Manual overwrite of the relevant RTE function. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_PreCustomHook TraceabilityThis function satisfies no DOORS Requirements. This is a helper function.
References WFS_DES_StFlashfreigabeReq_evAbbruch, BSW_StFlashfreigabeReq_evAbbruch, WFS_DES_StFlashfreigabeReq_evAnforderung, BSW_StFlashfreigabeReq_evAnforderung.
Referenced by WFS_TaskCyclicEvent.
Std_ReturnType Rte_Call_WFS_WFS_EcuM_StateRequest_RequestPOSTRUN(void)
Callback for WFS to request PostRUN. WFS needs to be informed when RUN mode has finished and requests to keep the EcuM in PostRUN mode until it releases the mode. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void Std_ReturnType RTE_E_OK - Response is hardcoded. GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_WFS_EcuM_StateRequest_RequestPOSTRUN TraceabilityThis function satisfies no DOORS Requirements. This is a callback for WFS to request PostRUN.
References WFS_EcuM_PostRun_requested.
Std_ReturnType Rte_Call_WFS_WFS_EcuM_StateRequest_ReleasePOSTRUN(void)
Callback for WFS to release PostRUN. WFS needs to be informed when RUN mode has finished and requests to keep the EcuM in PostRUN mode until it releases the mode. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void Std_ReturnType RTE_E_OK - Response is hardcoded. GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_WFS_EcuM_StateRequest_ReleasePOSTRUN TraceabilityThis function satisfies no DOORS Requirements. This is a callback for WFS to release PostRUN.
References WFS_EcuM_PostRun_requested.
Std_ReturnType Rte_Call_WFS_CI_GetData_GetFazitString(IDT_uint8_DIM23 Source)
Used to get the FAZIT string. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous IDT_uint8_DIM23 Source Std_ReturnType RTE_E_OK - Response is hardcoded. GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_CI_GetData_GetFazitString TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_469
uint8 Rte_Mode_WFS_WFS_EcuM_CurrentMode_currentMode(void)
This is a helper function used by WFS to read the EcuM CurrentMode. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void uint8 Globals[in] Rte_MdStat_EcuM Call Sequence Test MethodThe testing method is described on: TEST_Rte_Mode_WFS_WFS_EcuM_CurrentMode_currentMode TraceabilityThis function satisfies no DOORS Requirements. This is a helper function used to read the WFS EcuM CurrentMode.
References Rte_MdStat_EcuM.
Std_ReturnType Rte_Call_WFS_StFlashfreigabeResp_evCallback(boolean bResult)
Function used to verify if Flashing is allowed by WFS. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous boolean bResult - "TRUE" means flashing Allowed By WFS, "FALSE" means flashing is not allowed. Std_ReturnType RTE_E_OK - Harcoded response GlobalsAffected variables: [out] BSW_StFlashfreigabeReq_evAnforderung Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_StFlashfreigabeResp_evCallback TraceabilityThis function satisfies no DOORS Requirements. This is a wrapper function.
References BSW_StFlashfreigabeReq_evAnforderung.
Std_ReturnType Rte_Call_WFS_CI_KsMaster_SetShowroomMode(boolean ShowroomModeActive)
Function used by WFS to set the Showroom mode directly on KS-Master. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous boolean ShowroomModeActive - "TRUE" means that the Showroom mode should be activated, "FALSE" means that the Showroom mode should be deactivated. Std_ReturnType RTE_E_OK - Harcoded response GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_CI_KsMaster_SetShowroomMode TraceabilityThis function satisfies no DOORS Requirements. This is a wrapper function.
Std_ReturnType Rte_Call_WFS_CI_KsMaster_SetShowroomModeIsRunning(boolean *IsRunning)
Function used by WFS to check whether the Showroom mode is set directly. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous boolean* IsRunning - state of the direct setting of the Showroom mode Std_ReturnType RTE_E_OK - Harcoded response GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_CI_KsMaster_SetShowroomModeIsRunning TraceabilityThis function satisfies no DOORS Requirements. This is a wrapper function.