WFS_Stubs.c
RTE_WFS_CODE
Rte_DES_uint8DIM17 WFS_DES_StWegfahrsperre_rawVIN
Referenced by TransmitRawVIN.
Rte_DES_boolean WFS_DES_StDebug_bEntwicklerbotschaften
Referenced by EnableDebugMessages.
Rte_DES_uint8DIM8 WFS_DES_WFS_SwmVersData_SwcoNumber
Referenced by Rte_Call_WFS_val0x1AF_GetVersion.
Rte_DES_uint8DIM2 WFS_DES_WFS_SwmVersData_VendorID
Referenced by Rte_Call_WFS_val0x1AF_GetVersion.
Rte_DES_uint8DIM11 WFS_DES_WFS_SwmVersData_VwSparePartNumber
Referenced by Rte_Call_WFS_val0x1AF_GetVersion.
Rte_DES_uint8DIM4 WFS_DES_WFS_SwmVersData_MajorVersion
Referenced by Rte_Call_WFS_val0x1AF_GetVersion.
Rte_DES_uint8DIM4 WFS_DES_WFS_SwmVersData_MinorVersion
Referenced by Rte_Call_WFS_val0x1AF_GetVersion.
Rte_DES_uint8DIM4 WFS_DES_WFS_SwmVersData_PatchVersion
Referenced by Rte_Call_WFS_val0x1AF_GetVersion.
Rte_DES_IDT_struct_structWfsOcuAntwort WFS_DES_StWfsOcuAntwort_structWfsOcuAntwort
Referenced by WFS_PostStubHook.
Rte_DES_IDT_struct_structWfsElvAntwort WFS_DES_StWfsElvAntwort_structWfsElvAntwort
Referenced by WFS_PostStubHook.
Rte_DES_IDT_struct_structWfsMsg3Antwort WFS_DES_StWfsMsg3Antwort_structWfsMsg3Antwort
Referenced by WFS_PostStubHook.
Rte_DES_IDT_struct_structWfsMsg4Antwort WFS_DES_StWfsMsg4Antwort_structWfsMsg4Antwort
Referenced by WFS_PostStubHook.
void WFS_PostStubHook(void)
Function used to send WFS lib data to WFS Slaves. Since the data format between lib WFS and slave are different, data conversion is required. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous EventMaskType ev - not used void GlobalsAffected variables: none Call Sequence During test design, following defines should be considered: REPLACE_POST_HOOK_WFS_WFS_TASK10MS_STWFSOCUANTWORT_STRUCTWFSOCUANTWORT_NUMRND REPLACE_POST_HOOK_WFS_WFS_TASK10MS_STWFSOCUANTWORT_STRUCTWFSOCUANTWORT_NUMCRC REPLACE_POST_HOOK_WFS_WFS_TASK10MS_STWFSELVANTWORT_STRUCTWFSELVANTWORT_NUMRND REPLACE_POST_HOOK_WFS_WFS_TASK10MS_STWFSELVANTWORT_STRUCTWFSELVANTWORT_NUMCRC REPLACE_POST_HOOK_WFS_WFS_TASK10MS_STWFSMSG3ANTWORT_STRUCTWFSMSG3ANTWORT_NUMCRC REPLACE_POST_HOOK_WFS_WFS_TASK10MS_STWFSMSG4ANTWORT_STRUCTWFSMSG4ANTWORT_NUMCRC Test MethodThe testing method is described on: TEST_WFS_PostStubHook TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_125 SWR_ICAS1_L3_WFS_127
References WFS_DES_StWfsOcuAntwort_structWfsOcuAntwort, WFS_DES_StWfsElvAntwort_structWfsElvAntwort, WFS_DES_StWfsMsg3Antwort_structWfsMsg3Antwort, WFS_DES_StWfsMsg4Antwort_structWfsMsg4Antwort.
Referenced by WFS_TaskCyclicEvent.
static void WFS_TransmitIfCRCIsUpdated(uint8 *lastRteSignalValue, uint8 *rteSignalValue, ReqTxHandle reqTxHandle)
This is helper function used during reading WFS_Uds_EFD1 data. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 lastRteSignalValue uint8 rteSignalValue ReqTxHandle reqTxHandle void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_TransmitIfCRCIsUpdated TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_129
Referenced by WFS_Transmit_StructWfsOcuAntwortNumCrc, WFS_Transmit_StructWfsElvAntwortNumCrc, WFS_Transmit_StructWfsMsg3AntwortNumCrc, WFS_Transmit_StructWfsMsg4AntwortNumCrc.
void WFS_Transmit_StructWfsOcuAntwortNumCrc(uint8 *rteSignalValue)
Function used to add new Tx request for Ocu Slave. Function used as a trigger on new data and adding a new Tx cross core request. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 rteSignalValue void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Transmit_StructWfsOcuAntwortNumCrc TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_129
References WFS_TransmitIfCRCIsUpdated.
void WFS_Transmit_StructWfsElvAntwortNumCrc(uint8 *rteSignalValue)
Function used to add new Tx request for Elv Slave. Function used as a trigger on new data and adding a new Tx cross core request. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 rteSignalValue void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Transmit_StructWfsElvAntwortNumCrc TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_129
References WFS_TransmitIfCRCIsUpdated.
void WFS_Transmit_StructWfsMsg3AntwortNumCrc(uint8 *rteSignalValue)
Function used to add new Tx request for Msg3 Slave. Function used as a trigger on new data and adding a new Tx cross core request. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 rteSignalValue void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Transmit_StructWfsMsg3AntwortNumCrc TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_129
References WFS_TransmitIfCRCIsUpdated.
void WFS_Transmit_StructWfsMsg4AntwortNumCrc(uint8 *rteSignalValue)
Function used to add new Tx request for Msg4 Slave. Function used as a trigger on new data and adding a new Tx cross core request. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 rteSignalValue void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Transmit_StructWfsMsg4AntwortNumCrc TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_129
References WFS_TransmitIfCRCIsUpdated.
void TransmitRawVIN(void)
Used to transmit rawVin. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_TransmitRawVIN TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_330
References WFS_DES_StWegfahrsperre_rawVIN.
void EnableDebugMessages(void)
Used to enable debug messages. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_EnableDebugMessages TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_120
References WFS_DES_StDebug_bEntwicklerbotschaften.
Std_ReturnType Rte_Call_WFS_val0x1AF_GetVersion(T_0x1AF_SwCoIdentification *const pptIdentificationData)
Used to provide information about library version. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous T_0x1AF_SwCoIdentification* const pptIdentificationData Std_ReturnType BAP_RET_OK - function was called with valid parameter E_NOT_OK - function was called with null pointer parameter GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_Rte_Call_WFS_val0x1AF_GetVersion TraceabilityThis function satisfies no DOORS Requirements. This is a helper function providing information about library version.
References WFS_DES_WFS_SwmVersData_SwcoNumber, WFS_DES_WFS_SwmVersData_VendorID, WFS_DES_WFS_SwmVersData_VwSparePartNumber, WFS_DES_WFS_SwmVersData_MajorVersion, WFS_DES_WFS_SwmVersData_MinorVersion, WFS_DES_WFS_SwmVersData_PatchVersion.
Std_ReturnType WFS_Uds_EFD1_ReadData(Dcm_OpStatusType OpStatus, uint8 *Data)
This is a helper function used during reading WFS_Uds_EFD1 data. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous Dcm_OpStatusType OpStatus uint8* Data Std_ReturnType DCM_E_GENERALREJECT - request was rejected by application. Response is hardcoded. GlobalsAffected variables: none Call Sequence During test design, define WFS_STUB_TEST_ACTIVE should be considered. Test MethodThe testing method is described on: TEST_WFS_Uds_EFD1_ReadData TraceabilityThis function satisfies no DOORS Requirements. This is a helper function used during reading WFS_Uds_EFD1 data.
Std_ReturnType WFS_Uds_EFD1_WriteData(const uint8 *Data, Dcm_OpStatusType OpStatus, Dcm_NegativeResponseCodeType *ErrorCode)
This is a helper function used during writing WFS_Uds_EFD1 data. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous const uint8* Data Dcm_OpStatusType OpStatus Dcm_NegativeResponseCodeType* ErrorCode Std_ReturnType DCM_E_GENERALREJECT - request was rejected by application. Response is hardcoded. GlobalsAffected variables: none Call Sequence During test design, define WFS_STUB_TEST_ACTIVE should be considered. Test MethodThe testing method is described on: TEST_WFS_Uds_EFD1_WriteData TraceabilityThis function satisfies no DOORS Requirements. This is a helper function used during writing WFS_Uds_EFD1 data.