WFS_Task.h
boolean BSW_StFlashfreigabeReq_evAbbruch
TBD values boolean unit N/A resolution N/A context task protection none storage class normal ram BSW_StFlashfreigabeReq_evAbbruch To be modified by BSW. values TRUE / FALSE context task protection none storage class normal ram
Referenced by WFS_PreCustomHook.
volatile boolean WFS_EcuM_PostRun_requested
WFS has requested PostRun values boolean unit N/A resolution N/A context task protection none storage class normal ram Shows that the library was initialized. Allows the cyclic function to run. Keeps ECUM in post run. values TRUE / FALSE context task protection none storage class normal ram
Referenced by WFS_InitVarFunc, Rte_Call_WFS_WFS_EcuM_StateRequest_RequestPOSTRUN, Rte_Call_WFS_WFS_EcuM_StateRequest_ReleasePOSTRUN.
uint8 WFS_Status_StWegfahrsperre_bVerbauinfoElv
uint8 WFS_Status_StWegfahrsperre_bKlemmenfreigabeWFS
uint8 WFS_Status_StWegfahrsperre_numLebenszustand
boolean WFS_StWegfahrsperre_bKlemmenfreigabeWFS
boolean WFS_StWegfahrsperre_bVerbauinfoElv
uint8 WFS_StWegfahrsperre_numLebenszustand
boolean BSW_StFlashfreigabeReq_evAnforderung
BSW_StFlashfreigabeReq_evAnforderung To be modified by BSW. values TRUE / FALSE context task protection none storage class normal ram
Referenced by WFS_PreCustomHook, Rte_Call_WFS_StFlashfreigabeResp_evCallback.
void WFS_InitVarFunc(void)
Init the variables for the WFS module. This function is called by ModelsTask before starting the model (MmDoSetup is called). The code here must be short. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: [out] WFS_EcuM_PostRun_requested [out] WFS_DES_StWegfahrsperre_rawVIN Call Sequence Test MethodThe testing method is described on: TEST_WFS_InitVarFunc TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_117
References WFS_EcuM_PostRun_requested, WFS_Init10ms, WFS_DES_StWegfahrsperre_rawVIN.
void WFS_Start(void)
Start-up/init the WFS module. This function is called by modeltask in order to start-up/init the WFS module. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Start TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_114
References WFS_OnEnterRUN.
void WFS_Stop(void)
Stop callback for the WFS module. This function is called by ModelsTask when the StopEv is set (MmDoStop is called). Here is a good place to save data to NvRAM. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_Stop TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_113
References WFS_OnEnterPostRUN.
void WFS_TaskCyclicEvent(EventMaskType ev)
Cyclic function of the WFS module. This function is called by ModelsTask when the model's recurrence occurs. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous EventMaskType ev - not used void GlobalsAffected variables: none Call Sequence During test design, following defines should be considered: WFS_ENABLE_RUNNABLE_HOOKS Test MethodThe testing method is described on: TEST_WFS_TaskCyclicEvent TraceabilitySatisfies following DOORS Requirements and Design Decision: Satisfies requirementSWR_ICAS1_L3_WFS_154
References WFS_Prepare_RteBuffer, WFS_preWFS_Task10msHook, WFS_PreCustomHook, WFS_Task10ms, WFS_KY_Event_call, WFS_PostStubHook, WFS_postWFS_Task10msHook.
void WFS_KY_Event_call(void)
Kessy event caller. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_KY_Event_call TraceabilityThis function satisfies no DOORS Requirements. This is a helper function.
Referenced by WFS_TaskCyclicEvent.
void WFS_PreCustomHook(void)
Manual overwrite of the relevant RTE function. reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void GlobalsAffected variables: none Call Sequence Test MethodThe testing method is described on: TEST_WFS_PreCustomHook TraceabilityThis function satisfies no DOORS Requirements. This is a helper function.
References WFS_DES_StFlashfreigabeReq_evAbbruch, BSW_StFlashfreigabeReq_evAbbruch, WFS_DES_StFlashfreigabeReq_evAnforderung, BSW_StFlashfreigabeReq_evAnforderung.
Referenced by WFS_TaskCyclicEvent.
void WFS_PostCustomHook(void)
void WFS_Init10ms(void)
Referenced by WFS_InitVarFunc.
void WFS_Task10ms(void)
Referenced by WFS_TaskCyclicEvent.
void WFS_Prepare_RteBuffer(void)
Referenced by WFS_TaskCyclicEvent.
void WFS_PreAllRunnablesHook(void)
void WFS_PostAllRunnablesHook(void)