UHF_Task.c
void UHF_InitVarFunc(void)
UHF init function called by scheduler.Please find detail information in header file.
References UHF_BatteryHandler_Init.
Referenced by TEST_UHF_InitVarFunc.
void UHF_Start(void)
Initialization routine, called once on each EnterRun event by scheduler.Please find detail information in header file.
References UHF_Receiver_Init.
Referenced by TEST_UHF_Start.
void UHF_Stop(void)
De-Initialization routine, to be called once on each ExitRun event.Please find detail information in header file.
References UHF_BatteryHandler_Stop.
Referenced by TEST_UHF_Stop.
void UHF_TaskCyclicEvent(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode.Please find detail information in header file.
References UHF_Prepare_RteBuffer, UHF_BatteryHandler_Cyclic.
Referenced by TEST_UHF_TaskCyclicEvent.