UHF_CRC10.c.test
PRIVATE_FCT
PRIVATE_DATA
FAR_FCT
TEST_DESIGN_TECHNIQUE
FUNC
P2CONST
P2VAR
NIBBLESIZE
LowNibbleArray
HighNibbleArray
EmptyNibbleArray
MAX_UHF_RF_MSG_SIZE
typedef unsigned short uint16
typedef unsigned char uint8
uint16 crc_LookUpTableNibble_CRC10(uint16, uint8, const uint8 *const, const uint8 *const)
Function used for bit operations in CRC calculation. Triggered in crc_Update_CRC10 N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 lu16_Checksum - The Current Checksum (or Initial Value for the first Computation) [in] uint8 lu8_DataByte - Data Byte to be added to the Checksum [in] uint8* lpu8_HighNibble - Table of polynom data [in] uint8* lpu8_LowNibble - Table of polynom data uint16 - checksum after bit operations GlobalsN/A Input->Output-CorrelationN/A Activity Diagram crc_LookUpTableNibble_CRC10 Test MethodSWATT unit test. The testing method is described in TEST_crc_LookUpTableNibble_CRC10 TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_186 Function used for bit operations in CRC calculation.Please find detail information in the declaration.
Referenced by crc_Update_CRC10, TEST_crc_LookUpTableNibble_CRC10.
uint16 crc_Update_CRC10(uint16, uint8, uint16, uint16)
Function used to calculate a CRC10 checksum basing on the current checksum (or initial value).Function used to calculate a CRC10 checksum basing on the current checksum (or initial value) the data byte and the number of remaining bits. If the number of the remaining bits is at least 8 bytewise calculation approach is used ( crc_LookUpTableNibble_CRC10 ) otherwise bitwise calculation is used. Is called by CRC_Compute_CRC10 N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 lu16_Checksum - The Current Checksum (or Initial Value for the first Computation) [in] uint8 lu8_DataByte - Data Byte to be added to the Checksum [in] uint16 lu16_RemainingBits - Number of remaining Bits in the lu8_DataByte [in]uint16 lu16_Polynom - Polynom to be used in CRC calculation uint16 - checksum after bit operations GlobalsN/A Input->Output-CorrelationN/A Activity Diagram crc_Update_CRC10 Test MethodSWATT unit test. The testing method is described in TEST_crc_Update_CRC10 TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_186 Function used to calculate a CRC10 checksum basing on the current checksum (or initial value).Please find detail information in the declaration.
References cau8_CRC10_LowNibbleArray, cau8_CRC10_HighNibbleArray, CRC_BITS_PER_BYTE, crc_LookUpTableNibble_CRC10, CRC_MSB_MASK, CRC_MSB_CRC10_MASK.
Referenced by CRC_Compute_CRC10, TEST_crc_Update_CRC10.
uint16 CRC_Compute_CRC10(const uint8 *, uint16, uint16)
Function called to calculate a CRC10 checksum.Please find detail information in header file.
References CRC_UPROUNDING_INCREMENT, CRC_BITS_PER_BYTE, crc_Update_CRC10.
Referenced by TEST_CRC_Compute_CRC10.
void TEST_crc_LookUpTableNibble_CRC10(void)
TestUnit test verifies: crc_LookUpTableNibble_CRC10. N/A N/A DescriptionTests the function for bit operations on CRC checksum The test technique involves: statement testing
References TEST_DESIGN_TECHNIQUE, NIBBLESIZE, HighNibbleArray, LowNibbleArray, EmptyNibbleArray, crc_LookUpTableNibble_CRC10.
void TEST_crc_Update_CRC10(void)
TestUnit test verifies: crc_Update_CRC10. N/A N/A DescriptionTests the function for calculating CRC10 checksum based on input The test technique involves: statement testing, decision testing, decision table
References TEST_DESIGN_TECHNIQUE, crc_Update_CRC10.
void TEST_CRC_Compute_CRC10(void)
TestUnit test verifies: CRC_Compute_CRC10. N/A N/A DescriptionTests the function for calculating a CRC10 checksum over a given data range The test technique involves: statement testing
References TEST_DESIGN_TECHNIQUE, MAX_UHF_RF_MSG_SIZE, CRC_Compute_CRC10.