UHF_Sender.c
EV_UHF_SENDEN_VALUE_1
helper constant used in evUHFSendenused when assigning values from rawUHFTransponderID to u8RawUHF2SAM_Msg values 1u
EV_UHF_SENDEN_VALUE_2
helper constant used in evUHFSendenused when assigning values from rawUHFTransponderID to u8RawUHF2SAM_Msg values 2u
EV_UHF_SENDEN_VALUE_3
helper constant used in evUHFSendenused when assigning values from rawUHFTransponderID to u8RawUHF2SAM_Msg values 3u
EV_UHF_SENDEN_VALUE_4
helper constant used in evUHFSendenused as a helper in preparing value of a 4th cell in u8RawUHF2SAM_Msg values 4u
EV_UHF_SENDEN_VALUE_8
helper constant used in evUHFSendenused as a helper mask in preparing payload in u8RawUHF2SAM_Msg values 8u
UHF_STORE_VALUE_HEX_3
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper mask to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 0x0003u
UHF_STORE_VALUE_HEX_80
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper mask to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 0x0080u
UHF_STORE_VALUE_HEX_FF
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper mask to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 0x00FFu
EV_UHF_SENDEN_VALUE_HEX_6
helper constant used in evUHFSendenIts value is assigned to a byte Counter limit in evUHFSenden values 0x06u
EV_UHF_SENDEN_VALUE_HEX_7
helper constant used in checkByteAndPrepareMessageUHFIts value is assigned to a byte Counter limit in checkByteAndPrepareMessageUHF values 0x07u
EV_UHF_SENDEN_VALUE_HEX_0F
helper constant used in evUHFSendenused as a helper in preparing value of a 4th cell in u8RawUHF2SAM_Msg values 0x0Fu
EV_UHF_SENDEN_VALUE_HEX_F0
helper constant used in evUHFSendenused as a helper in preparing value of a 4th cell in u8RawUHF2SAM_Msg values 0xF0u
EV_UHF_SENDEN_VALUE_HEX_FF
helper constant used in evUHFSendenused as a helper mask in preparing payload in u8RawUHF2SAM_Msg values 0xFFu
CRC10BITLENGTH
constant describing length of CRC10 checksumused in evUHFSenden when calling Rte to write UHF_01_Datenlaenge_can values 10u
BITSPERBYTE
constant describing amount of bits in byte values 8u
UHF_MESSAGE_2_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_2_ADDRESS its UHF_02 message values 6u
UHF_MESSAGE_3_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_3_ADDRESS its UHF_03 message values 13u
UHF_MESSAGE_4_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_4_ADDRESS its UHF_04 message values 20u
UHF_MESSAGE_5_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_5_ADDRESS its UHF_05 message values 27u
UHF_MESSAGE_6_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_6_ADDRESS its UHF_06 message values 34u
UHF_MESSAGE_7_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_7_ADDRESS its UHF_07 message values 41u
UHF_MESSAGE_8_ADDRESS
constant used as an offset in prepareMessageSevenBytesUHFindicates which UHF_message shall be sent to SAM in case of UHF_MESSAGE_8_ADDRESS its UHF_08 message values 48u
UHF_STORE_CRC_CASE0
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE0 no bits are used values 0u
UHF_STORE_CRC_CASE1
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE1 1st bit is used values 1u
UHF_STORE_CRC_CASE2
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE2 2nd bit is used values 2u
UHF_STORE_CRC_CASE3
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE3 3rd bit is used values 3u
UHF_STORE_CRC_CASE4
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE4 4th bit is used values 4u
UHF_STORE_CRC_CASE5
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE5 5th bit is used values 5u
UHF_STORE_CRC_CASE6
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE6 6th bit is used values 6u
UHF_STORE_CRC_CASE7
constant used in storeCrcEnd_UHF of evUHFSendenDetermines where to store CRC in the end of message depending on which bit in byte payload end. In case of UHF_STORE_CRC_CASE7 7th bit is used values 7u
UHF_STORE_VALUE_2
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 2u
UHF_STORE_VALUE_6
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 6u
UHF_STORE_VALUE_7
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 7u
UHF_STORE_VALUE_9
helper constant used in storeCrcEnd_UHF of evUHFSendenused as a helper to determine at which bit CRC shall be stored in u8RawUHF2SAM_Msg values 9u
UHF_MASK_FIRST_BYTE
Constant when a masking bits in 1st byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 1st Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0x000000000000FFu
UHF_MASK_SECOND_BYTE
Constant used when masking bits in 2nd byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 2nd Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0x0000000000FF00u
UHF_MASK_THIRD_BYTE
Constant used when masking bits in 3rd byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 3rd Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0x00000000FF0000u
UHF_MASK_FOURTH_BYTE
Constant used when masking bits in 4th byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 4th Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0x000000FF000000u
UHF_MASK_FIFTH_BYTE
Constant used when masking bits in 5th byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 5th Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0x0000FF00000000u
UHF_MASK_SIXTH_BYTE
Constant used when masking bits in 6th byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 6th Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0x00FF0000000000u
UHF_MASK_SEVENTH_BYTE
Constant used when masking bits in 7th byte of in prepareMessageSixBytesUHFUsed as a bit mask in prepareMessageSixBytesUHF for 7th Byte when masking to proper bits in u8RawUHF2SAM_Msg structure values 0xFF000000000000u
uint8 u8UHF_Zaehler
UHF Telegram Message counterCounter for UHF messages. Is incremented each time after CAN messages is sent to SAM. RAM block is placed in Standby RAM. range {0-255u} context {is assigned to locally declared Telegram message counter in evUHFSenden and incremented after message is sent to SAM} protection {static global variable for UHF_Task.c}
Referenced by evUHFSenden, TEST_evUHFSenden.
uint8 u8RawUHF2SAM_Msg[MAX_UHF_RF_MSG_SIZE][MAX_UHF_RF_MSG_SIZE]
Buffer structure of UHF Message to be send to SAMStructure used as a container for the message that is sent to SAM over CCAN range N/A values N/A unit N/A resolution N/A context {updated in storeCrcEnd_UHF Its values are copied in prepareMessageSixBytesUHF and prepareMessageSevenBytesUHF Its values are updated in evUHFSenden} protection {static global variable for UHF_Task.c}
Referenced by evUHFSenden, storeCrcEnd_UHF, prepareMessageSixBytesUHF, prepareMessageSevenBytesUHF, TEST_evUHFSenden, TEST_storeCrcEnd_UHF, TEST_prepareMessageSixBytesUHF, TEST_prepareMessageSevenBytesUHF.
static Std_ReturnType storeCrcEnd_UHF(uint16 last_Byte_bits_used, uint16 bytecnt, uint16 *crc_result)
Subfunction of evUHFSenden.Function is used to store CRC at the end of the UHF message depending on which bit in last byte of payload is used. Triggerd by evUHFSenden N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 last_Byte_bits_used - indicates how many bits of a last byte were used [in] uint16 bytecnt - byte counter [in] uint16* crc_result - pointer to CRC result Std_ReturnType RTE Status Globalsu8RawUHF2SAM_Msg - Structure to be send to SAM Input->Output-CorrelationCRC result is placed in u8RawUHF2SAM_Msg Activity Diagram storeCrcEnd_UHF Test MethodSWATT unit test. The testing method is described in TEST_storeCrcEnd_UHF TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_335 Subfunction of evUHFSenden.Please find detail information in declaration.
References SWATT_BYPASS, UHF_STORE_CRC_CASE0, u8RawUHF2SAM_Msg, UHF_STORE_VALUE_2, UHF_STORE_VALUE_HEX_FF, UHF_STORE_VALUE_HEX_3, UHF_STORE_CRC_CASE1, UHF_STORE_CRC_CASE2, UHF_STORE_CRC_CASE3, UHF_STORE_CRC_CASE4, UHF_STORE_CRC_CASE5, UHF_STORE_VALUE_6, BITSPERBYTE, UHF_STORE_CRC_CASE6, UHF_STORE_CRC_CASE7, UHF_STORE_VALUE_9, UHF_STORE_VALUE_7, UHF_STORE_VALUE_HEX_80.
Referenced by evUHFSenden, TEST_evUHFSenden, TEST_storeCrcEnd_UHF.
static void prepareMessageSixBytesUHF(uint64 *msg, uint16 offset)
Function used inside evUHFSenden.Function prepares UHF message 1 to send via RTE funtions. Sets pointer and masks proper bits in u8RawUHF2SAM_Msg structure. Triggered in evUHFSenden N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint64* msg - pointer to a message [in] uint16 offset - offset of bytes when choosing a message void Globalsu8RawUHF2SAM_Msg - source of data for prepared message Input->Output-CorrelationPointer to msg is assigned values of properly masked u8RawUHF2SAM_Msg Test MethodSWATT unit test. The testing method is described in TEST_prepareMessageSixBytesUHF TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_335 Function used inside evUHFSenden.Please find detail information in declaration.
References SWATT_BYPASS, u8RawUHF2SAM_Msg, UHF_MASK_FIRST_BYTE, UHF_OFFSET_PLUS_1, UHF_SHIFT_8_BITS, UHF_MASK_SECOND_BYTE, UHF_OFFSET_PLUS_2, UHF_SHIFT_16_BITS, UHF_MASK_THIRD_BYTE, UHF_OFFSET_PLUS_3, UHF_SHIFT_24_BITS, UHF_MASK_FOURTH_BYTE, UHF_OFFSET_PLUS_4, UHF_SHIFT_32_BITS, UHF_MASK_FIFTH_BYTE, UHF_OFFSET_PLUS_5, UHF_SHIFT_40_BITS, UHF_MASK_SIXTH_BYTE.
Referenced by evUHFSenden, TEST_evUHFSenden, TEST_prepareMessageSixBytesUHF.
static void checkByteAndPrepareMessageUHF(uint64 *msg, uint8 *msgcnt, uint16 *byteCntLimit, uint16 bytecnt, uint16 offset)
Function used inside evUHFSenden - checking and preparing UHF Message to SAM.Function checks counter of a bytes. If it is greater than the limit then content of the prepared message is set with zeros otherwise prepareMessageSevenBytesUHF is called. Triggered in evUHFSenden N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint64* msg - pointer to a message [in] uint16* byteCntLimit - given bytes counter limit [in] uint16 bytecn - given bytes counter [in] uint16 offset - offset of bytes when choosing a message void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram checkByteAndPrepareMessageUHF Test MethodSWATT unit test. The testing method is described in TEST_checkByteAndPrepareMessageUHF TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_335 Function used inside evUHFSenden - checking and preparing UHF Message to SAM.Please find detail information in declaration.
References SWATT_BYPASS, EV_UHF_SENDEN_VALUE_HEX_7, prepareMessageSevenBytesUHF.
Referenced by evUHFSenden, TEST_evUHFSenden, TEST_checkByteAndPrepareMessageUHF.
static void prepareMessageSevenBytesUHF(uint64 *msg, uint16 offset)
Function used inside evUHFSenden.Function prepares UHF messages 2-8 to send via RTE funtions. Sets pointer and masks proper bits in u8RawUHF2SAM_Msg structure. Triggered in evUHFSenden N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint64* msg - pointer to a message [in] uint16 offset - offset of bytes when choosing a message void Globalsu8RawUHF2SAM_Msg - source of data for prepared message Input->Output-CorrelationPointer to msg is assigned values of properly masked u8RawUHF2SAM_Msg Test MethodSWATT unit test. The testing method is described in TEST_prepareMessageSevenBytesUHF TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_335 Function used inside evUHFSenden.Please find detail information in declaration.
References SWATT_BYPASS, u8RawUHF2SAM_Msg, UHF_MASK_FIRST_BYTE, UHF_OFFSET_PLUS_1, UHF_SHIFT_8_BITS, UHF_MASK_SECOND_BYTE, UHF_OFFSET_PLUS_2, UHF_SHIFT_16_BITS, UHF_MASK_THIRD_BYTE, UHF_OFFSET_PLUS_3, UHF_SHIFT_24_BITS, UHF_MASK_FOURTH_BYTE, UHF_OFFSET_PLUS_4, UHF_SHIFT_32_BITS, UHF_MASK_FIFTH_BYTE, UHF_OFFSET_PLUS_5, UHF_SHIFT_40_BITS, UHF_MASK_SIXTH_BYTE, UHF_OFFSET_PLUS_6, UHF_SHIFT_48_BITS, UHF_MASK_SEVENTH_BYTE.
Referenced by evUHFSenden, checkByteAndPrepareMessageUHF, TEST_evUHFSenden, TEST_checkByteAndPrepareMessageUHF, TEST_prepareMessageSevenBytesUHF.
Std_ReturnType evUHFSenden(const uint8 *rawUHFTransponderID, uint8 numUHFPortNumber, uint8 numUHFFunktionsnummer, const uint8 *rawUHFPayload, uint16 numUHFPayloadLength, uint8 numPreambleLength, uint8 numChannelSelect, uint8 numNextChannelSelect, uint8 tChannelSwitchTime)
UHF init function called by scheduler.Please find detail information in header file.
References u8UHF_Zaehler, u8RawUHF2SAM_Msg, MAX_UHF_RF_MSG_SIZE, EV_UHF_SENDEN_VALUE_1, EV_UHF_SENDEN_VALUE_2, EV_UHF_SENDEN_VALUE_3, EV_UHF_SENDEN_VALUE_4, EV_UHF_SENDEN_VALUE_HEX_F0, EV_UHF_SENDEN_VALUE_HEX_0F, BITSPERBYTE, UHF_SENSOR_01_DATA_CAN_LEN, EV_UHF_SENDEN_VALUE_HEX_FF, EV_UHF_SENDEN_VALUE_8, CRC_Compute_CRC10, UHF_SENSOR_MIN_LENGTH, RFCOMINT_PASE_CHECKSUM_CRC10_INIT_VAL, storeCrcEnd_UHF, prepareMessageSixBytesUHF, CRC10BITLENGTH, EV_UHF_SENDEN_VALUE_HEX_6, prepareMessageSevenBytesUHF, UHF_MESSAGE_2_ADDRESS, checkByteAndPrepareMessageUHF, UHF_MESSAGE_3_ADDRESS, UHF_MESSAGE_4_ADDRESS, UHF_MESSAGE_5_ADDRESS, UHF_MESSAGE_6_ADDRESS, UHF_MESSAGE_7_ADDRESS, UHF_MESSAGE_8_ADDRESS.
Referenced by TEST_evUHFSenden, TEST_evUHFSenden_nullptr.
void updateUHFConfig(void)
UHF init function called by scheduler.Please find detail information in header file.
Referenced by TEST_updateUHFConfig.