UHF_Sender.h
Std_ReturnType evUHFSenden(const uint8 *rawUHFTransponderID, uint8 numUHFPortNumber, uint8 numUHFFunktionsnummer, const uint8 *rawUHFPayload, uint16 numUHFPayloadLength, uint8 numPreambleLength, uint8 numChannelSelect, uint8 numNextChannelSelect, uint8 tChannelSwitchTime)
Server UHF function used to send messages to SAMUsed to send CAN messages to SAM using Rte functions. It splits merged payload to valid format for CAN messages, then calls proper Rte Calls in order to send messages over CCAN to SAM. UHF-Master receives the StAnfUHFTrigger.evUHFSenden call from KESSY-SW N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous P2CONST(uint8 AUTOMATIC RTE_APPL_DATA) rawUHFTransponderID - pointer to TransponderId array [in] uint8 numUHFPortNumber - UHF Telegram Port number [in] P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) rawUHFPayload - pointer of TransponderId array [in] uint16 numUHFPayloadLength - Payload length [in] uint8 numPreambleLength - length of preamble [in] uint8 numChannelSelect - selected channel [in] uint8 numNextChannelSelect - next selected channel [in] uint8 tChannelSwitchTime - channel switch time Std_ReturnType Rte Status Globalsu8RawUHF2SAM_Msg - Buffer structure of UHF Message to be send to SAM u8UHF_Zaehler - UHF Telegram Message counter Input->Output-CorrelationPayload stored and formatted in UHF is sent to SAM over Rte Activity Diagram evUHFSenden Test MethodSWATT unit test. The testing method is described on: TEST_evUHFSenden TEST_evUHFSenden_nullptr TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_327 SWR_L3_CRoute_UHF_371 SWR_L3_CRoute_UHF_372 SWR_L3_CRoute_UHF_330 SWR_L3_CRoute_UHF_331 SWR_L3_CRoute_UHF_332 SWR_L3_CRoute_UHF_333 SWR_L3_CRoute_UHF_334 SWR_L3_CRoute_UHF_335 SWR_L3_CRoute_UHF_353 SWR_L3_CRoute_UHF_351 SWR_L3_CRoute_UHF_338 SWR_L3_CRoute_UHF_339 SWR_L3_CRoute_UHF_340 SWR_L3_CRoute_UHF_341 SWR_L3_CRoute_UHF_342 SWR_L3_CRoute_UHF_345 SWR_L3_CRoute_UHF_343 SWR_L3_CRoute_UHF_344 SWR_L3_CRoute_UHF_369 SWR_L3_CRoute_UHF_370 SWR_L3_CRoute_UHF_380 SWR_L3_CRoute_UHF_326 SWR_L3_CRoute_UHF_172 SWR_L3_CRoute_UHF_347 UHF init function called by scheduler.Please find detail information in header file.
References u8UHF_Zaehler, u8RawUHF2SAM_Msg, MAX_UHF_RF_MSG_SIZE, EV_UHF_SENDEN_VALUE_1, EV_UHF_SENDEN_VALUE_2, EV_UHF_SENDEN_VALUE_3, EV_UHF_SENDEN_VALUE_4, EV_UHF_SENDEN_VALUE_HEX_F0, EV_UHF_SENDEN_VALUE_HEX_0F, BITSPERBYTE, UHF_SENSOR_01_DATA_CAN_LEN, EV_UHF_SENDEN_VALUE_HEX_FF, EV_UHF_SENDEN_VALUE_8, CRC_Compute_CRC10, UHF_SENSOR_MIN_LENGTH, RFCOMINT_PASE_CHECKSUM_CRC10_INIT_VAL, storeCrcEnd_UHF, prepareMessageSixBytesUHF, CRC10BITLENGTH, EV_UHF_SENDEN_VALUE_HEX_6, prepareMessageSevenBytesUHF, UHF_MESSAGE_2_ADDRESS, checkByteAndPrepareMessageUHF, UHF_MESSAGE_3_ADDRESS, UHF_MESSAGE_4_ADDRESS, UHF_MESSAGE_5_ADDRESS, UHF_MESSAGE_6_ADDRESS, UHF_MESSAGE_7_ADDRESS, UHF_MESSAGE_8_ADDRESS.
Referenced by TEST_evUHFSenden, TEST_evUHFSenden_nullptr.
void updateUHFConfig(void)
Callback function to trigger update Kessy Data on CAN.At first it reads data from ICAS1::KESSY-SW via Rte then it updates UHF Config using Rte calls. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram updateUHFConfig Test MethodSWATT unit test. The testing method is described in TEST_updateUHFConfig TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_338 UHF init function called by scheduler.Please find detail information in header file.
Referenced by TEST_updateUHFConfig.