UHF_Receiver.h
void UHF_Call_Ev_UHFRFMsg1fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_01 in order to read UHF_Sensor_01. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg1fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg1fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_01.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg1fromSAM.
void UHF_Call_Ev_UHFRFMsg2fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_02 in order to read UHF_Sensor_02. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg2fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg2fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_02.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg2fromSAM.
void UHF_Call_Ev_UHFRFMsg3fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_03 in order to read UHF_Sensor_03. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg3fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg3fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_03.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg3fromSAM.
void UHF_Call_Ev_UHFRFMsg4fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_04 in order to read UHF_Sensor_04. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg4fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg4fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_04.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg4fromSAM.
void UHF_Call_Ev_UHFRFMsg5fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_05 in order to read UHF_Sensor_05. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg5fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg5fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_05.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg5fromSAM.
void UHF_Call_Ev_UHFRFMsg6fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_06 in order to read UHF_Sensor_06. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg6fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg6fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_06.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg6fromSAM.
void UHF_Call_Ev_UHFRFMsg7fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_07 in order to read UHF_Sensor_07. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg7fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg7fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_07.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg7fromSAM.
void UHF_Call_Ev_UHFRFMsg8fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_08 in order to read UHF_Sensor_08. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg8fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg8fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_136 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_08.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg8fromSAM.
void UHF_Call_Ev_UHFRFMsg9fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM.It triggers UHF event vread_UHFRFMsgfromSAM with a parameter UHF_SENSOR_09 in order to read UHF_Sensor_09. Called by Kessy EventMngr N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Call_Ev_UHFRFMsg9fromSAM Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_UHFRFMsg9fromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_113 Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_09.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg9fromSAM.
void vread_UHFRFMsgfromSAM(uint16 sensornummer)
Function to merge payload sent over CAN from SAMFunction is called for as long until payload is available in one structure. Called in functions _fromSAM where Message_Number is a number of a UHF_Sensor message in range from 1 to 9 that UHF is about to merge. Once merge process is complete data is sent to FDH or to Kessy via calling proper functions. Called externally when payload is sent from SAM N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 sensornummer - Number of a message processed by function void Globalss_UHF_Sensor_01_buf - Buffer structure for the UHF_Sensor_01 message u8UHF_Sensor_Zaehler - UHF current message number counter u16actual_DataReceived - Sum of data length received from UHF_Sensors u16UHF_SensorDatenlaenge_can - CAN Data length in Bits s_UHF_LogicalHeader_buf - Buffer structure for the Logical header of the UHF message u16UHF_PayloadDatenlaenge_can - Length of payload received in CAN message from SAM s_UHF_Sensor_0n_buf - Buffer structure for the UHF_Sensor_02-UHF_Sensor_08 message u8numUHFPortNumber - UHF Telegram Port number u8numUHFFunktionsnummer - UHF Telegram function number u8numBatteryLevel - Key Battery Level bCRCValid - Result of the CRC10 Check FirstMessageArrived - flag indicating that first UHF message has already arrived Input->Output-CorrelationPayload is merged in UHF structures and It has been sent to FDH or Kessy Activity Diagram vread_UHFRFMsgfromSAM Test MethodSWATT unit test. The testing method is described in TEST_vread_UHFRFMsgfromSAM TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_315 SWR_L3_CRoute_UHF_136 SWR_L3_CRoute_UHF_148 SWR_L3_CRoute_UHF_212 SWR_L3_CRoute_UHF_151 SWR_L3_CRoute_UHF_182 SWR_L3_CRoute_UHF_150 SWR_L3_CRoute_UHF_271 SWR_L3_CRoute_UHF_183 SWR_L3_CRoute_UHF_184 SWR_L3_CRoute_UHF_152 SWR_L3_CRoute_UHF_187 SWR_L3_CRoute_UHF_215 SWR_L3_CRoute_UHF_123 SWR_L3_CRoute_UHF_245 SWR_L3_CRoute_UHF_105 SWR_L3_CRoute_UHF_107 SWR_L3_CRoute_UHF_108 SWR_L3_CRoute_UHF_109 SWR_L3_CRoute_UHF_111 SWR_L3_CRoute_UHF_337 SWR_L3_CRoute_UHF_379 Function to merge payload sent over CAN from SAM Please find detail information in header file.
References SWATT_BYPASS, vRead_UHF_RPort, UHF_SENSOR_01, s_UHF_Sensor_01_buf, UHF_SENSOR_MIN_LENGTH, UHF_SENSOR_MAX_LENGTH, u8UHF_Sensor_Zaehler, u16actual_DataReceived, u16UHF_SensorDatenlaenge_can, s_UHF_LogicalHeader_buf, s_UHF_LogicalHeader::Transponder_ID, UHF_VALUE_7, UHF_VALUE_1, UHF_VALUE_6, UHF_VALUE_2, UHF_VALUE_3, s_UHF_LogicalHeader::Port_Number, UHF_VALUE_4, s_UHF_LogicalHeader::Funktionsnummer, s_UHF_LogicalHeader::BatteryLevel, u16UHF_PayloadDatenlaenge_can, UHF_SENSOR_02, UHF_SENSOR_03, UHF_SENSOR_04, UHF_SENSOR_05, UHF_SENSOR_06, UHF_SENSOR_07, UHF_SENSOR_08, s_UHF_Sensor_0n_buf, UHF_SENSOR_0N_DATASIZE, PAYLOAD_INIT_LENGTH, updateRawUHFPayload, bEvaluateCRC10, u8numUHFPortNumber, u8numUHFFunktionsnummer, u8numBatteryLevel, bCRCValid, u8SchluesselNr, FirstMessageArrived, updateSignalStrength, PORT_WEL_KESSY_TELEGRAMM, PORT_KESSY_TELEGRAMM, PORT_FFB_TELEGRAMM, u8rawUHFPayload, u8UHFSignalstaerke, SENSOR_INIT_COUNTER.
Referenced by UHF_Call_Ev_UHFRFMsg1fromSAM, UHF_Call_Ev_UHFRFMsg2fromSAM, UHF_Call_Ev_UHFRFMsg3fromSAM, UHF_Call_Ev_UHFRFMsg4fromSAM, UHF_Call_Ev_UHFRFMsg5fromSAM, UHF_Call_Ev_UHFRFMsg6fromSAM, UHF_Call_Ev_UHFRFMsg7fromSAM, UHF_Call_Ev_UHFRFMsg8fromSAM, UHF_Call_Ev_UHFRFMsg9fromSAM, TEST_UHF_Call_Ev_UHFRFMsg1fromSAM, TEST_UHF_Call_Ev_UHFRFMsg2fromSAM, TEST_UHF_Call_Ev_UHFRFMsg3fromSAM, TEST_UHF_Call_Ev_UHFRFMsg4fromSAM, TEST_UHF_Call_Ev_UHFRFMsg5fromSAM, TEST_UHF_Call_Ev_UHFRFMsg6fromSAM, TEST_UHF_Call_Ev_UHFRFMsg7fromSAM, TEST_UHF_Call_Ev_UHFRFMsg8fromSAM, TEST_UHF_Call_Ev_UHFRFMsg9fromSAM, TEST_vread_UHFRFMsgfromSAM.
void UHF_Call_Ev_StUHFKY_evUHFEmpfang(void)
Function calls Client-Server Interface to send telegram to Kessy.Function calls Client-Server Interface in order to route the UHF Telegram to the ICAS1::KESSY-SW for keyless unlock / lock and go functions. Function is called by Kessy EventMngr. UHF_Call_Ev_StUHFKY_evUHFEmpfang N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void Globalss_UHF_LogicalHeader_buf.Transponder_ID -Transponder - ID of the ID-transmitter u8numUHFPortNumber - UHF Telegram Port number u8numUHFFunktionsnummer - Function Number u8numBatteryLevel - Key Battery Level u8rawUHFPayload - UHF payload bCRCValid - Result of the CRC10 Check u8UHFSignalstaerke - Signal strength Input->Output-CorrelationUHF Telegram is routed to Kessy Activity Diagram UHF_Call_Ev_StUHFKY_evUHFEmpfang Test MethodSWATT unit test. The testing method is described in TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_107 Function calls Client-Server Interface to send telegram to Kessy. Please find detail information in header file.
References s_UHF_LogicalHeader_buf, s_UHF_LogicalHeader::Transponder_ID, u8numUHFPortNumber, u8numUHFFunktionsnummer, u8numBatteryLevel, u8rawUHFPayload, bCRCValid, u8UHFSignalstaerke.
Referenced by TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang.
void UHF_Receiver_Init(void)
Initialization routine, called once on each EnterRun event by scheduler.Seven global variables for UHF_Receiver_Init.c are initialized with values: "u8UHF_Sensor_Zaehler", "u8rawUHFPayload", "bCRCValid", "u8UHFSignalstaerke", "u16UHF_SensorDatenlaenge_can", "u16actual_DataReceived", "u16UHF_PayloadDatenlaenge_can", System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Receiver_Init Test MethodSWATT unit test. The testing method is described in TEST_UHF_Start TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. Initialization routine, called once on each EnterRun event by scheduler. Please find detail information in header file.
References bCRCValid, u8UHF_Sensor_Zaehler, SENSOR_INIT_COUNTER, u16actual_DataReceived, u16UHF_SensorDatenlaenge_can, u16UHF_PayloadDatenlaenge_can, PAYLOAD_INIT_LENGTH, u8rawUHFPayload, UHF_PAYLOAD_RAW_LENGTH, u8UHFSignalstaerke.
Referenced by TEST_UHF_Receiver_Init, UHF_Start.
uint8 UHF_Receiver_Get_BatteryLevel(void)
Function return BatteryLevel value.Function return BatteryLevel value. System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Receiver_Init Test MethodSWATT unit test. The testing method is described in TEST_UHF_Receiver_Get_BatteryLevel TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. Function return BatteryLevel value. Please find detail information in header file.
References s_UHF_LogicalHeader_buf, s_UHF_LogicalHeader::BatteryLevel.
Referenced by PerformBatteryUpdateOnClamp15, TEST_UHF_Receiver_Get_BatteryLevel.
uint8 UHF_Receiver_Get_SchluesselNr(void)
Function return SchluesselNr value.Function return SchluesselNr value. System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Receiver_Init Test MethodSWATT unit test. The testing method is described in TEST_UHF_Receiver_Get_SchluesselNr TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. Function return SchluesselNr value. Please find detail information in header file.
References u8SchluesselNr.
Referenced by PerformBatteryUpdateOnClamp15, TEST_UHF_Receiver_Get_SchluesselNr.
boolean UHF_Receiver_Is_FirstMessageArrived(void)
Function return true if FirstMessageArrived.Function return true if FirstMessageArrived. System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Receiver_Init Test MethodSWATT unit test. The testing method is described in TEST_UHF_Receiver_Is_FirstMessageArrived TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. Function return true if FirstMessageArrived. Please find detail information in header file.
References FirstMessageArrived.
Referenced by PerformBatteryUpdateOnClamp15, TEST_UHF_Receiver_Is_FirstMessageArrived.