UHF_Task.h
void UHF_InitVarFunc(void)
UHF init function called by scheduler.Call init function in UHF_BatteryHandler Called by scheduler once on each EnterRun. System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_InitVarFunc Test MethodSWATT unit test. The testing method is described in TEST_UHF_InitVarFunc TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. UHF init function called by scheduler. Please find detail information in header file.
References UHF_BatteryHandler_Init.
Referenced by TEST_UHF_InitVarFunc.
void UHF_Start(void)
Initialization routine, called once on each EnterRun event by scheduler.UHF_Receiver_Init called System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Start Test MethodSWATT unit test. The testing method is described in TEST_UHF_Start TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. Initialization routine, called once on each EnterRun event by scheduler. Please find detail information in header file.
References UHF_Receiver_Init.
Referenced by TEST_UHF_Start.
void UHF_Stop(void)
De-Initialization routine, to be called once on each ExitRun event.Call UHF_BatteryHandler_Stop. System leaves RUN mode, prepares to sleep. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_Stop Test MethodSWATT unit test. The testing method is described in TEST_UHF_Stop TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_189 De-Initialization routine, to be called once on each ExitRun event.Please find detail information in header file.
References UHF_BatteryHandler_Stop.
Referenced by TEST_UHF_Stop.
void UHF_TaskCyclicEvent(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode.2 major subtasks are referenced periodically: -UHF_Prepare_RteBuffer -UHF_BatteryHandler_Cyclic N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_TaskCyclicEvent Test MethodSWATT unit test. The testing method is described in TEST_UHF_TaskCyclicEvent TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_229 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode.Please find detail information in header file.
References UHF_Prepare_RteBuffer, UHF_BatteryHandler_Cyclic.
Referenced by TEST_UHF_TaskCyclicEvent.
void UHF_Prepare_RteBuffer(void)
prepares the rte buffers for signals having range check activated. the function needs to be called before any runnable call. its handles the status flags and last valid values. reentrant No context task context thread safe No multicore safe No synchronous N/A SWC's runnable. void void GlobalsAll last valid signal buffers. Input->Output-CorrelationThe buffer are update one after the other. TraceabilityDesign Decision - Justification. Imported function from Rte_UHF.
Referenced by UHF_TaskCyclicEvent.