UHF_CRC10.c
CRC_BITS_PER_BYTE
Constant used as number of Bits in one ByteThis macro defines the Number of Bits in one Byte. values 8u
CRC_UPROUNDING_INCREMENT
Number of Bits to be added for rounding up to next ByteThis macro defines the Number of Bits to be added for rounding up to next Byte. values 7u
CRC_MSB_MASK
Constant used as MSBit MaskThis macro defines the MSBit Mask. values 0x80u
CRC_MSB_CRC10_MASK
Constant used as MSBit Mask for CRC10This macro defines the MSBit Mask for CRC10. values 0x8000u
const uint8 cau8_CRC10_LowNibbleArray[16u][16u]
Array for High nibble CRC10 checksum calculationCRC Polynomial = 0x08F = x^10+x^7+x^3+x^2+x^1+1 <<6 -> polynom 23C0 range N/A values N/A unit N/A resolution N/A context {used in crc_Update_CRC10 as reference for function crc_LookUpTableNibble_CRC10} protection {static global array variable for UHF_CRC10.c}
Referenced by crc_Update_CRC10.
const uint8 cau8_CRC10_HighNibbleArray[16u][16u]
Array for High nibble CRC10 checksum calculationCRC Polynom = 0x08F = x^10+x^7+x^3+x^2+x^1+1 <<6 -> Polynom 0x23C0 range N/A values N/A unit N/A resolution N/A context {used in crc_Update_CRC10 as reference for function crc_LookUpTableNibble_CRC10} protection {static global array variable for UHF_CRC10.c}
Referenced by crc_Update_CRC10.
uint16 crc_LookUpTableNibble_CRC10(uint16 lu16_Checksum, uint8 lu8_DataByte, const uint8 *const lpu8_HighNibble, const uint8 *const lpu8_LowNibble)
Function used for bit operations in CRC calculation. Triggered in crc_Update_CRC10 N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 lu16_Checksum - The Current Checksum (or Initial Value for the first Computation) [in] uint8 lu8_DataByte - Data Byte to be added to the Checksum [in] uint8* lpu8_HighNibble - Table of polynom data [in] uint8* lpu8_LowNibble - Table of polynom data uint16 - checksum after bit operations GlobalsN/A Input->Output-CorrelationN/A Activity Diagram crc_LookUpTableNibble_CRC10 Test MethodSWATT unit test. The testing method is described in TEST_crc_LookUpTableNibble_CRC10 TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_186 Function used for bit operations in CRC calculation.Please find detail information in the declaration.
Referenced by crc_Update_CRC10, TEST_crc_LookUpTableNibble_CRC10.
uint16 crc_Update_CRC10(uint16 lu16_Checksum, uint8 lu8_DataByte, uint16 lu16_RemainingBits, uint16 lu16_Polynom)
Function used to calculate a CRC10 checksum basing on the current checksum (or initial value).Function used to calculate a CRC10 checksum basing on the current checksum (or initial value) the data byte and the number of remaining bits. If the number of the remaining bits is at least 8 bytewise calculation approach is used ( crc_LookUpTableNibble_CRC10 ) otherwise bitwise calculation is used. Is called by CRC_Compute_CRC10 N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 lu16_Checksum - The Current Checksum (or Initial Value for the first Computation) [in] uint8 lu8_DataByte - Data Byte to be added to the Checksum [in] uint16 lu16_RemainingBits - Number of remaining Bits in the lu8_DataByte [in]uint16 lu16_Polynom - Polynom to be used in CRC calculation uint16 - checksum after bit operations GlobalsN/A Input->Output-CorrelationN/A Activity Diagram crc_Update_CRC10 Test MethodSWATT unit test. The testing method is described in TEST_crc_Update_CRC10 TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_186 Function used to calculate a CRC10 checksum basing on the current checksum (or initial value).Please find detail information in the declaration.
References cau8_CRC10_LowNibbleArray, cau8_CRC10_HighNibbleArray, CRC_BITS_PER_BYTE, crc_LookUpTableNibble_CRC10, CRC_MSB_MASK, CRC_MSB_CRC10_MASK.
Referenced by CRC_Compute_CRC10, TEST_crc_Update_CRC10.
uint16 CRC_Compute_CRC10(const uint8 *lpu8_Buffer, uint16 lu16_NbOfBits, uint16 lu16_InitValue)
Function called to calculate a CRC10 checksum.Please find detail information in header file.
References CRC_UPROUNDING_INCREMENT, CRC_BITS_PER_BYTE, crc_Update_CRC10.
Referenced by TEST_CRC_Compute_CRC10, bEvaluateCRC10, evUHFSenden.