UHF_BatteryHandler.c
BATTERIE_VOLTAGE_INVALID
constant describing invalid value of a key battery voltageused in updateBatteryVoltage when comparing batteryvoltage values 0xFFu
NUMBER_OF_KEYS
constant used as maximal value of keys learned by UHF Masterconstant is referenced in functions regarding key processes (e.g. Key learning process). used in fucntions: UHF_Stop updateBatteryVoltage checkErrorFlags values 8u
boolean batteryErrorFlag[8u][8u]
Array of flags for key battery errorsArray indicates if battery voltage in any of learned keys is invalid. range N/A values N/A unit N/A resolution N/A context {Its values are updated in updateBatteryVoltage Its values are checked in checkErrorFlags All its values are set to FALSE in UHF_Stop} protection {static global variable for UHF_Task.c}
Referenced by UHF_BatteryHandler_Stop, updateBatteryVoltage, checkErrorFlags, TEST_UHF_BatteryHandler_Stop, TEST_updateBatteryVoltage, TEST_checkErrorFlags.
Std_ReturnType(*const DemEvent_SetEventStatus[8])(Dem_EventStatusType data)[8])(Dem_EventStatusType data)
Const variable holding pointers to RTE call functions.Array elements point to functions used to set proper DTC values N/A unit N/A resolution N/A context {task, used by updateBatteryVoltage} protection {static global variable for UHF_BatteryHandler.c}
Referenced by updateBatteryVoltage.
static void updateBatteryCounter(uint8_t u8SchluesselNrBattCounter)
Function updates battery error in RAM mirror and NVM.Function is processing Battery error, increases error counter and saves updated counter and date of event occurance in NVM. Is called in cyclic task in checkErrorFlags and in updateBatteryVoltage N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8_t u8SchluesselNrBattCounter - Number of a key which was used void GlobalsN/A Input->Output-CorrelationkeyBatteryDebouncing might be updated in the NVM Activity Diagram updateBatteryCounter Test MethodSWATT unit test. The testing method is described in TEST_updateBatteryCounter TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_217 SWR_L3_CRoute_UHF_175 SWR_L3_CRoute_UHF_216 SWR_L3_CRoute_UHF_174 SWR_L3_CRoute_UHF_192 SWR_L3_CRoute_UHF_193 SWR_L3_CRoute_UHF_96 Function updates battery error in RAM mirror and NVM. Please find detail information in the declaration.
References SWATT_BYPASS, getNvmKey, KeyBatteryDebouncingType::counter, KeyBatteryDebouncingType::year, KeyBatteryDebouncingType::month, KeyBatteryDebouncingType::day, KeyBatteryDebouncingType::hours, dayOfYear, isLeapYear, UHF_VALUE_2.
Referenced by updateBatteryVoltage, checkErrorFlags, TEST_updateBatteryVoltage, TEST_checkErrorFlags, TEST_updateBatteryCounter.
static void checkErrorFlags(void)
Function iterates over table with error flags and processes if any was set.Processed active flag indicates that an update in NvM is needed. Function is a part of a low battery event. If during calculation system time was not available but all conditions were met - proper flag was set. This function is called in UHF_TaskCyclicEvent and if system time is available, counter is increased and the error flag is reset. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsbatteryErrorFlag - Array storing battery error flags Input->Output-CorrelationN/A Activity Diagram checkErrorFlags Test MethodSWATT unit test. The testing method is described in TEST_checkErrorFlags TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_100 SWR_L3_CRoute_UHF_102 Function iterates over table with error flags and processes if any was set. Please find detail information in the declaration.
References SWATT_BYPASS, isSystemTimeAvailable, NUMBER_OF_KEYS, batteryErrorFlag, updateBatteryCounter.
Referenced by UHF_BatteryHandler_Cyclic, TEST_UHF_BatteryHandler_Cyclic, TEST_checkErrorFlags.
static boolean isSystemTimeAvailable(void)
Function is checking if system time is available.In order to check system time availability it reads signal from ECUManager. Function is using enum construction _BasicUTCQualityEnum. If system time is in format BasicUTCQuiality_Source_RTC or BasicUTCQuiality_UTC_Source_GNSS it returns TRUE otherwise it returns FALSE. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A boolean - information if system time is available. GlobalsN/A Input->Output-CorrelationN/A Activity Diagram isSystemTimeAvailable Test MethodSWATT unit test. The testing method is described in TEST_isSystemTimeAvailable TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_217 Function is checking if system time is available. Please find detail information in the declaration.
References SWATT_BYPASS, BasicUTCQuiality_UTC_MAX, BasicUTCQuiality_Source_RTC, BasicUTCQuiality_UTC_Source_GNSS.
Referenced by updateBatteryVoltage, checkErrorFlags, TEST_isSystemTimeAvailable, TEST_updateBatteryVoltage, TEST_checkErrorFlags.
static boolean isLeapYear(const uint16 year)
Function validating if given year value is a leap year.It uses a mathematical method to validate year. If given number is divisible by 4 it is a leap year. There are exceptions: Year divisible by 100 is not a leap year. Year divisible by 400 is a leap year. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 year - 0..65535 boolean - True if given year is a leap year. GlobalsN/A Input->Output-CorrelationN/A Activity Diagram isLeapYear Test MethodSWATT unit test. The testing method is described in TEST_isLeapYear TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_217 Function validating if given year value is a leap year. Please find detail information in the declaration.
References SWATT_BYPASS, UHF_VALUE_4, UHF_VALUE_100, UHF_VALUE_400.
Referenced by daysInMonth, updateBatteryCounter, TEST_isLeapYear, TEST_daysInMonth, TEST_updateBatteryCounter.
static uint8 daysInMonth(const uint16 year, const uint8 month)
Function returns number of days in given month of a given year.Function returns number of days in given month of a given year. Used as a helper function since 2nd month of a leap year has one more day. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 year - 0..65535 [in] uint8 month - 1..12 uint8 - Number of days in the given month. GlobalsN/A Input->Output-CorrelationN/A Activity Diagram daysInMonth Test MethodSWATT unit test. The testing method is described in TEST_daysInMonth TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_217 Function returns number of days in given month of a given year. Please find detail information in the declaration.
References UHF_VALUE_1, UHF_VALUE_3, UHF_VALUE_5, UHF_VALUE_7, UHF_VALUE_8, UHF_VALUE_10, UHF_VALUE_12, UHF_VALUE_31, UHF_VALUE_2, UHF_VALUE_28, isLeapYear, UHF_VALUE_4, UHF_VALUE_6, UHF_VALUE_9, UHF_VALUE_11, UHF_VALUE_30.
Referenced by dayOfYear, TEST_daysInMonth.
static uint16 dayOfYear(const uint16 year, const uint8 month, const uint8 day)
Function returns number of days that passed until today in current year.Function returns number of days that passed until today in current year. It uses daysInMonth function as a helper function. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 year - 0..65535 [in] uint8 month - 1..12 [in] uint8 day - 0..31 uint16 - Day number in a given year. GlobalsN/A Input->Output-CorrelationN/A Activity Diagram dayOfYear Test MethodSWATT unit test. The testing method is described in TEST_dayOfYear TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_217 Function returns number of days that passed until today in current year. Please find detail information in the declaration.
References SWATT_BYPASS, daysInMonth.
Referenced by updateBatteryCounter, TEST_dayOfYear, TEST_updateBatteryCounter.
static IDT_CRYPTO_uint8_DIM6 * getNvmKey(const uint8 u8SchluesselNrBattVolInput)
Functions returns correct key battery data from PIM.Is using switch construction - depending on a key number given in a parameter different pointer to NVM data is returned. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 u8SchluesselNrBattVolInput - Number of a key IDT_CRYPTO_uint8_DIM6 * - Pointer to battery data GlobalsN/A Input->Output-CorrelationN/A Activity Diagram getNvmKey Test MethodSWATT unit test. The testing method is described in TEST_getNvmKey TraceabilityDesign Decision - Justification. Design decision: helper function for pointer extraction. Functions returns correct key battery data from PIM. Please find detail information in the declaration.
References SWATT_BYPASS, UHF_VALUE_1, UHF_VALUE_2, UHF_VALUE_3, UHF_VALUE_4, UHF_VALUE_5, UHF_VALUE_6, UHF_VALUE_7.
Referenced by updateBatteryVoltage, updateBatteryCounter, TEST_updateBatteryVoltage, TEST_updateBatteryCounter, TEST_getNvmKey.
static void ResetFlagsOnClampS(void)
Function used to detect Power Off on Clamp S and to reset a proper signal on CAN.Uses Rte read fucntion to read a state of Clamp and if OFF transition occurs function sets to 0 signal responsible of showing if key battery is on low level. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram ResetFlagsOnClampS Test MethodSWATT unit test. The testing method is described in TEST_ResetFlagsOnClampS TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_101 Function used to detect Power Off on Clamp S and to reset a proper signal on CAN. Please find detail information in the declaration.
References SWATT_BYPASS.
Referenced by UHF_BatteryHandler_Cyclic, TEST_UHF_BatteryHandler_Cyclic, TEST_ResetFlagsOnClampS.
static void PerformBatteryUpdateOnClamp15(void)
Function checks if ignition of the car happened and if so calls updateBatteryVoltage .Uses Rte function to read state of the clamp 15 and if Transition to ON appears it calls function to update battery level. Additional conditions for function to trigger is that SKC and TransonderID were learned and event with sending battery level occurs. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void Globalss_UHF_LogicalHeader_buf.BatteryLevel - battery level of currently evaluated key u8SchluesselNr - number of currently evaluated key Input->Output-Correlations_FBS_Warn_Schluessel_Batt is set on CAN Activity Diagram PerformBatteryUpdateOnClamp15 Test MethodSWATT unit test. The testing method is described in TEST_PerformBatteryUpdateOnClamp15 TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_100 SWR_L3_CRoute_UHF_102 Function checks if ignition of the car happened and if so calls updateBatteryVoltage. Please find detail information in the declaration.
References SWATT_BYPASS, FirstMessageArrived, UHF_Receiver_Is_FirstMessageArrived, updateBatteryVoltage, UHF_Receiver_Get_BatteryLevel, UHF_Receiver_Get_SchluesselNr.
Referenced by UHF_BatteryHandler_Cyclic, TEST_UHF_BatteryHandler_Cyclic, TEST_PerformBatteryUpdateOnClamp15.
STATIC void updateBatteryVoltage(uint8 batteryvoltage, uint8 u8SchluesselNrBattVol)
Function used to update information about Battery voltage and perform action if battery is on low level.Function reads threshold of low levels of voltage, new battery threshold and value of a counter that is a number describing of how many times low level of battery voltage shall occur before setting an DTC for performed key. Function additionally uses mechanism to calculate difference in time between previous and current incident of low battery and increases the counter. Difference of time in a mechanism mentioned should be longer than 24 hours. Is called by PerformBatteryUpdateOnClamp15 if proper conditions are met N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 batteryvoltage - Battery voltage value received with FFB payload [in] uint8 u8SchluesselNrBattVol - Number of a key to perform update void GlobalsbatteryErrorFlag - Array of flags for key battery errors DemEvent_SetEventStatus - Array of pointers to RTE functions Input->Output-CorrelationIn case of voltage issues batteryErrorFlag is updated Activity Diagram updateBatteryVoltage Test MethodSWATT unit test. The testing method is described in TEST_updateBatteryVoltage TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_129 SWR_L3_CRoute_UHF_213 SWR_L3_CRoute_UHF_126 SWR_L3_CRoute_UHF_178 SWR_L3_CRoute_UHF_238 SWR_L3_CRoute_UHF_179 SWR_L3_CRoute_UHF_208 SWR_L3_CRoute_UHF_209 Function used to update information about Battery voltage and perform action if battery is on low level. Please find detail information in the declaration.
References SWATT_BYPASS, BATTERIE_VOLTAGE_INVALID, getNvmKey, isSystemTimeAvailable, updateBatteryCounter, NUMBER_OF_KEYS, batteryErrorFlag, KeyBatteryDebouncingType::counter, UHF_VALUE_1, UHF_VALUE_8, DemEvent_SetEventStatus.
Referenced by PerformBatteryUpdateOnClamp15, TEST_updateBatteryVoltage, TEST_PerformBatteryUpdateOnClamp15.
void clear_KeyfobBatteryStatus(void)
This function triggers UHF-Master to initialize the Error Counter in PIM after CryptoHandler started the Key Learning process. Please find detail information in header file.
Referenced by TEST_clear_KeyfobBatteryStatus.
void UHF_BatteryHandler_Init(void)
UHF_BatteryHandler init function called by scheduler. Please find detail information in header file.
Referenced by TEST_UHF_BatteryHandler_Init, UHF_InitVarFunc.
void UHF_BatteryHandler_Stop(void)
De-Initialization routine, to be called once on each ExitRun event. Please find detail information in header file.
References NUMBER_OF_KEYS, batteryErrorFlag.
Referenced by TEST_UHF_BatteryHandler_Stop, UHF_Stop.
void UHF_BatteryHandler_Cyclic(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References checkErrorFlags, ResetFlagsOnClampS, PerformBatteryUpdateOnClamp15.
Referenced by TEST_UHF_BatteryHandler_Cyclic, UHF_TaskCyclicEvent.