UHF_BatteryHandler.h
void clear_KeyfobBatteryStatus(void)
This function triggers UHF-Master to initialize the Error Counter in PIM after CryptoHandler started the Key Learning process. CryptoHandler started the Key Learning process - triggered via FFBSKCUebertragung N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous N/A void GlobalsN/A Input->Output-CorrelationError Counters in PIM are initialized Activity Diagram clear_KeyfobBatteryStatus Test MethodSWATT unit test. The testing method is described in TEST_clear_KeyfobBatteryStatus TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_203 SWR_L3_CRoute_UHF_98 SWR_L3_CRoute_UHF_205 This function triggers UHF-Master to initialize the Error Counter in PIM after CryptoHandler started the Key Learning process. Please find detail information in header file.
Referenced by TEST_clear_KeyfobBatteryStatus.
void UHF_BatteryHandler_Init(void)
UHF_BatteryHandler init function called by scheduler.Checks the status for the Keyfob Battery in the NVM. If the status is RTE_E_OK and error status is not NVM_REQ_OK clears out Keyfob Battery status in the NVM with value 0u . Called by scheduler once on each EnterRun. System after wake up/reset, in EnterRUN. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_BatteryHandler_Init Test MethodSWATT unit test. The testing method is described in TEST_UHF_InitVarFunc TraceabilityDesign Decision - Justification. Design decision: component init function to be called by scheduler. UHF_BatteryHandler init function called by scheduler. Please find detail information in header file.
Referenced by TEST_UHF_BatteryHandler_Init, UHF_InitVarFunc.
void UHF_BatteryHandler_Stop(void)
De-Initialization routine, to be called once on each ExitRun event.Sets Battery error flags to FALSE. System leaves RUN mode, prepares to sleep. N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_BatteryHandler_Stop Test MethodSWATT unit test. The testing method is described in TEST_UHF_Stop TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_189 De-Initialization routine, to be called once on each ExitRun event. Please find detail information in header file.
References NUMBER_OF_KEYS, batteryErrorFlag.
Referenced by TEST_UHF_BatteryHandler_Stop, UHF_Stop.
void UHF_BatteryHandler_Cyclic(void)
Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode.4 major subtasks are referenced periodically: -checkErrorFlags -ResetFlagsOnClampS -PerformBatteryUpdateOnClamp15 N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous void void GlobalsN/A Input->Output-CorrelationN/A Activity Diagram UHF_BatteryHandler_Cyclic Test MethodSWATT unit test. The testing method is described in TEST_UHF_TaskCyclicEvent TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_229 Cyclically (10ms) executed routine, called by scheduler while system is in RUN mode. Please find detail information in header file.
References checkErrorFlags, ResetFlagsOnClampS, PerformBatteryUpdateOnClamp15.
Referenced by TEST_UHF_BatteryHandler_Cyclic, UHF_TaskCyclicEvent.