UHF_Receiver.c
SENSOR_INIT_COUNTER
constant used as initial counter for u8UHF_Sensor_Zaehlerused as initial value for u8UHF_Sensor_Zaehler in UHF_Start assigned to u8UHF_Sensor_Zaehler after reading SAM Msg in vread_UHFRFMsgfromSAM values 0xFFu
PAYLOAD_INIT_LENGTH
constant used as initial payload length value for u16UHF_PayloadDatenlaenge_canused as initial value for u16UHF_PayloadDatenlaenge_can in UHF_Start assigned to u16UHF_PayloadDatenlaenge_can after reading SAM Msg in vread_UHFRFMsgfromSAM assigned to u16UHF_PayloadDatenlaenge_can after new CAN-Messages was received in vread_UHFRFMsgfromSAM values 0xFFFFu
UHF_PAYLOAD_RAW_LENGTH
constant describing max length for raw UHF Payloadused in UHF_Start and bEvaluateCRC10 when assigning values to u8rawUHFPayload values 58u
PORT_KESSY_TELEGRAMM
constant used in vread_UHFRFMsgfromSAM in switch caseused in vread_UHFRFMsgfromSAM in switch case determining if port number in s_UHF_LogicalHeader_buf.Port_Number belongs to the Kessy values 0u
PORT_FFB_TELEGRAMM
constant used in vread_UHFRFMsgfromSAM in switch caseused in vread_UHFRFMsgfromSAM in switch case determining if port number in s_UHF_LogicalHeader_buf.Port_Number belongs to the FFB values 1u
PORT_WEL_KESSY_TELEGRAMM
constant used in vread_UHFRFMsgfromSAM in switch caseused in vread_UHFRFMsgfromSAM in switch case determining if port number in s_UHF_LogicalHeader_buf.Port_Number belongs to the Kessy values 2u
typedef struct s_UHF_Sensor_01 S_UHF_Sensor_01
Structure to store data from CCAN Message from UHF_Sensor_01
typedef struct s_UHF_Sensor_0n S_UHF_Sensor_0n
Structure to store data from CCAN Messages from UHF_Sensor_02-08
S_UHF_Sensor_01 s_UHF_Sensor_01_buf
Buffer structure for the UHF_Sensor_01 messageBuffer structure used as container to read UHF_Sensor1 message from CCAN range N/A values N/A unit N/A resolution N/A context {Is assigned values after Rte reads in vRead_UHF_RPort Its data is copied in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by vread_UHFRFMsgfromSAM, vRead_UHF_RPort, TEST_vread_UHFRFMsgfromSAM, TEST_vRead_UHF_RPort.
uint8 u8UHF_Sensor_Zaehler
UHF Sensor counterUHF current message number counter. In case its value is 0 it is automatically updated to 1. range {0-31u, 0xFFu} values N/A unit N/A resolution N/A context {Initialized in UHF_Start with value 0u used in vread_UHFRFMsgfromSAM when reading message from SAM} protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, TEST_UHF_Receiver_Init, TEST_vread_UHFRFMsgfromSAM.
uint16 u16actual_DataReceived
Sum of data length received from UHF_SensorsValue is used to store sum of data lengths of received UHF CAN messages. range {0u, 48-440u} values N/A unit N/A resolution N/A context {Is initialized with value 0u in UHF_Start Its value is updated when reading messages in vread_UHFRFMsgfromSAM and afterwards its reset to 0u} protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, TEST_UHF_Receiver_Init.
uint16 u16UHF_SensorDatenlaenge_can
CAN Data length in BitsUsed to store data length after receiving message from SAM range {0-511u} values N/A unit N/A resolution N/A context {Is initialized with value 0u in UHF_Start and assigned value after receiving message in vread_UHFRFMsgfromSAM } protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, TEST_UHF_Receiver_Init.
S_UHF_LogicalHeader s_UHF_LogicalHeader_buf
Buffer structure for the Logical header of the UHF messageBuffer structure for the Logical header of the UHF message that is to be forwarded to the respectively addressed application. range N/A values N/A unit N/A resolution N/A context {Its updated and used in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, UHF_Receiver_Get_BatteryLevel, TEST_vread_UHFRFMsgfromSAM, TEST_UHF_Receiver_Get_BatteryLevel.
uint16 u16UHF_PayloadDatenlaenge_can
Length of payload received in CAN message from SAMUsed to store length of payload received in CAN message from SAM. Calculated using u16UHF_SensorDatenlaenge_can and UHF_SENSOR_MIN_LENGTH range {40-440u and 0xFFFFu} values N/A unit N/A resolution N/A context {Initialized in UHF_Start with value 0xFFFFu used in vread_UHFRFMsgfromSAM when reading message from SAM} protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, TEST_UHF_Receiver_Init, TEST_vread_UHFRFMsgfromSAM.
uint8 u8rawUHFPayload[((uint16)(MAX_UHF_RF_MSG_SIZE-UHF_SENSOR_01_DATA_CAN_LEN))][((uint16)(MAX_UHF_RF_MSG_SIZE-UHF_SENSOR_01_DATA_CAN_LEN))]
UHF Telegram Payload without Logical HeaderPayload from the Logical Header of the received UHF Telegram range N/A values N/A unit N/A resolution N/A context {Initialized with values of 0u in UHF_Start Its value is updated in updateRawUHFPayload and checked in bEvaluateCRC10} protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, updateRawUHFPayload, bEvaluateCRC10, TEST_UHF_Receiver_Init, TEST_updateRawUHFPayload.
S_UHF_Sensor_0n s_UHF_Sensor_0n_buf
Buffer structure for the UHF_Sensor_02-UHF_Sensor_08 messageBuffer structure used as container to read UHF_Sensor_02-UHF_Sensor_08 message from CCAN range N/A values N/A unit N/A resolution N/A context {Is assigned values after Rte reads in vRead_UHF_RPort Its data is copied in updateRawUHFPayload} protection {static global variable for UHF_Task.c}
Referenced by vread_UHFRFMsgfromSAM, vRead_UHF_RPort, updateRawUHFPayload, TEST_vread_UHFRFMsgfromSAM, TEST_vRead_UHF_RPort, TEST_updateRawUHFPayload.
uint8 u8numUHFPortNumber
UHF Telegram Port numberPort Number from the Logical Header of the received UHF Telegram range {0-2u} values N/A unit N/A resolution N/A context {Its value is updated and send in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang.
uint8 u8numUHFFunktionsnummer
UHF Telegram function numberFunction Number from the Logical Header of the received UHF Telegram range {0-5u} values N/A unit N/A resolution N/A context {Its value is updated and send in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang.
uint8 u8numBatteryLevel
UHF Telegram Raw Key Battery LevelRaw Key Battery Level from the Logical Header of the received UHF Telegram range {0-255u} values N/A unit N/A resolution N/A context {Its value is updated and send in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang.
boolean bCRCValid
UHF Telegram Result of the CRC10 CheckResult of the CRC10 Check. If 0 is received error is detected in case its 1 CRC is valid. range {TRUE, FALSE} values N/A unit N/A resolution N/A context {Initialized with FALSE in UHF_Start Is updated and sent in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, TEST_UHF_Receiver_Init, TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang.
uint8 u8SchluesselNr
Slot number of a keyUsed in order to convey currently active key ID. range {0-8u} values N/A unit N/A resolution N/A context {Is assigned value in vread_UHFRFMsgfromSAM and used for update in updateSignalStrength and updateBatteryVoltage} protection {static global variable for UHF_Task.c}
Referenced by TEST_PerformBatteryUpdateOnClamp15, vread_UHFRFMsgfromSAM, UHF_Receiver_Get_SchluesselNr, TEST_UHF_Receiver_Get_SchluesselNr.
boolean FirstMessageArrived
boolean variable indicating that first UHF message has already arrived.Array indicates if battery voltage in any of learned keys is invalid. range {TRUE, FALSE} values N/A unit N/A resolution N/A context {Its value is set in vread_UHFRFMsgfromSAM after first message arrives} protection {static global variable for UHF_Task.c}
Referenced by PerformBatteryUpdateOnClamp15, TEST_PerformBatteryUpdateOnClamp15, vread_UHFRFMsgfromSAM, UHF_Receiver_Is_FirstMessageArrived, TEST_UHF_Receiver_Is_FirstMessageArrived.
uint8 u8UHFSignalstaerke
UHF Telegram Signal strengthNormalized signal strength of the received UFH Telegram range {0-127u} values N/A unit N/A resolution N/A context {Initialized with 0u in UHF_Start Updated in updateSignalStrength Is used in vread_UHFRFMsgfromSAM} protection {static global variable for UHF_Task.c}
Referenced by UHF_Receiver_Init, vread_UHFRFMsgfromSAM, UHF_Call_Ev_StUHFKY_evUHFEmpfang, updateSignalStrength, TEST_UHF_Receiver_Init, TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang, TEST_updateSignalStrength.
uint8 u8RawUHF_Msg[MAX_UHF_RF_MSG_SIZE][MAX_UHF_RF_MSG_SIZE]
Buffer structure for the UHF messageUsed in bEvaluateCRC10 when computing CRC with CRC_Compute_CRC10 range N/A values N/A unit N/A resolution N/A context {updated in bEvaluateCRC10 and used when computing in CRC_Compute_CRC10} protection {static global variable for UHF_Task.c}
Referenced by bEvaluateCRC10.
Std_ReturnType(* const get_Sensor_Zaehler_can[8])(uint8 *data)[8])(uint8 *data)
Const variable holding pointers to RTE call functions.Array elements point to functions used to get data from CAN from messages UHF_Sensor_01_Zaehler ... UHF_Sensor_08_Zaehler values N/A unit N/A resolution N/A context {task, used by vRead_UHF_RPort} protection {static global variable for UHF_Receiver.c}
Referenced by vRead_UHF_RPort.
Std_ReturnType(* const get_Sensor_Data_can[8])(uint64 *data)[8])(uint64 *data)
Const variable holding pointers to RTE call functions.Array elements point to functions used to get data from CAN from messages UHF_Sensor_01_Data ... UHF_Sensor_08_Data values N/A unit N/A resolution N/A context {task, used by vRead_UHF_RPort} protection {static global variable for UHF_Receiver.c}
Referenced by vRead_UHF_RPort.
STATIC void vRead_UHF_RPort(uint16 number)
Function assigns into global structures value of UHF message data.Function assigns into global structures value of UHF message data depending on a chosen with parameter number of the message. Based on switch construction with cases from 1 to 8 reading corresponding UHF_Sensor. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 number - used in switch to determine from which UHF port message shall be read void Globalss_UHF_Sensor_01_buf - Buffer structure for the UHF_Sensor_01 message s_UHF_Sensor_0n_buf - Buffer structure for the UHF_Sensor_02-UHF_Sensor_08 message get_Sensor_Zaehler_can - Array of pointers to RTE functions get_Sensor_Data_can - Array of pointers to RTE functions Input->Output-Correlations_UHF_Sensor_01-s_UHF_Sensor_08 Message is read and saved in buffer Activity Diagram vRead_UHF_RPort Test MethodSWATT unit test. The testing method is described in TEST_vRead_UHF_RPort TraceabilityDesign Decision - Justification. Design decision: helper function for copy message. Function assigns into global structures value of UHF message data. Please find detail information in the declaration.
References SWATT_BYPASS, UHF_SENSOR_01, s_UHF_Sensor_01_buf, UHF_SHIFT_40_BITS, UHF_SHIFT_32_BITS, UHF_SHIFT_24_BITS, UHF_SHIFT_16_BITS, UHF_SHIFT_8_BITS, UHF_SENSOR_08, get_Sensor_Zaehler_can, s_UHF_Sensor_0n_buf, get_Sensor_Data_can, UHF_SHIFT_48_BITS.
Referenced by vread_UHFRFMsgfromSAM, TEST_vread_UHFRFMsgfromSAM, TEST_vRead_UHF_RPort.
static void updateRawUHFPayload(uint16 sensorStep)
Function used to store payload that arrived with KY or FFB action over CCAN.Seven Bytes of payload arrive and then they are put in a proper place in structure prepared for payload. Additionally bytes should be reversed. Payload arrived with KY or FFB action over CCAN N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint16 sensorStep - Number of a message void Globalsu8rawUHFPayload - container to store payload s_UHF_Sensor_0n_buf - container with payload that arrived Input->Output-Correlations_UHF_Sensor_0n_buf.Data_can data is copied to u8rawUHFPayload Activity Diagram updateRawUHFPayload Test MethodSWATT unit test. The testing method is described in TEST_updateRawUHFPayload TraceabilityDesign Decision - Justification. Design decision: helper function to copy data to u8rawUHFPayload Function used to store payload that arrived with KY or FFB action over CCAN. Please find detail information in the declaration.
References SWATT_BYPASS, UHF_VALUE_7, u8rawUHFPayload, s_UHF_Sensor_0n_buf, UHF_OFFSET_PLUS_1, UHF_VALUE_6, UHF_OFFSET_PLUS_2, UHF_VALUE_5, UHF_OFFSET_PLUS_3, UHF_VALUE_3, UHF_OFFSET_PLUS_4, UHF_VALUE_2, UHF_OFFSET_PLUS_5, UHF_VALUE_1, UHF_OFFSET_PLUS_6.
Referenced by vread_UHFRFMsgfromSAM, TEST_vread_UHFRFMsgfromSAM, TEST_updateRawUHFPayload.
STATIC boolean bEvaluateCRC10(const uint8 *pMsg, uint16 msg_bitlength)
This function is called internally. It is used for checking CRC for payload in order to validate its correctness.This function is called internally. It is used for checking CRC for payload in order to validate its correctness. If CRC Result in used CRC_Compute_CRC10 equals 0 - It confirms CRC is correct and returns TRUE. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous P2CONST(uint8 AUTOMATIC RTE_APPL_DATA) pMsg - pointer of incomming message [in] uint16 msg_bitlength - length of message boolean - TRUE, FALSE depending on CRC correctness Globalsu8RawUHF_Msg - Buffer for the message to be checked u8rawUHFPayload - Data used when preparing message to be checked Input->Output-CorrelationN/A Activity Diagram bEvaluateCRC10 Test MethodSWATT unit test. The testing method is described in TEST_bEvaluateCRC10 TraceabilityDesign Decision - Justification. Design decision: helper function for validating message correctness. This function is called internally. It is used for checking CRC for payload in order to validate its correctness. Please find detail information in the declaration.
References SWATT_BYPASS, u8RawUHF_Msg, MAX_UHF_RF_MSG_SIZE, UHF_SENSOR_01_DATA_CAN_LEN, u8rawUHFPayload, UHF_PAYLOAD_RAW_LENGTH, CRC_Compute_CRC10, RFCOMINT_PASE_CHECKSUM_CRC10_INIT_VAL.
Referenced by vread_UHFRFMsgfromSAM, TEST_vread_UHFRFMsgfromSAM, TEST_bEvaluateCRC10.
static void updateSignalStrength(uint8 keyNumber)
Function reads signal strength of a proper key depending on a number given as argument.Function uses switch-case and depending on a key number given as a parameter calls proper Rte Read to store data about signal strength. N/A N/A reentrant No context task context thread safe No - Integration must insure that the function is not interrupted by the other functions of the same module multicore safe No - All APIs needs to be called from the same core synchronous uint8 keyNumber - 1..8 void Globalsu8UHFSignalstaerke - UHF Telegram Signal strength Input->Output-CorrelationN/A Activity Diagram updateSignalStrength Test MethodSWATT unit test. The testing method is described in TEST_updateSignalStrength TraceabilitySatisfies following DOORS Requirements: Satisfies requirementSWR_L3_CRoute_UHF_113 Function reads signal strength of a proper key depending on a number given as argument. Please find detail information in the declaration.
References SWATT_BYPASS, UHF_VALUE_1, u8UHFSignalstaerke, UHF_VALUE_2, UHF_VALUE_3, UHF_VALUE_4, UHF_VALUE_5, UHF_VALUE_6, UHF_VALUE_7, UHF_VALUE_8.
Referenced by vread_UHFRFMsgfromSAM, TEST_vread_UHFRFMsgfromSAM, TEST_updateSignalStrength.
void UHF_Receiver_Init(void)
Initialization routine, called once on each EnterRun event by scheduler. Please find detail information in header file.
References bCRCValid, u8UHF_Sensor_Zaehler, SENSOR_INIT_COUNTER, u16actual_DataReceived, u16UHF_SensorDatenlaenge_can, u16UHF_PayloadDatenlaenge_can, PAYLOAD_INIT_LENGTH, u8rawUHFPayload, UHF_PAYLOAD_RAW_LENGTH, u8UHFSignalstaerke.
Referenced by TEST_UHF_Receiver_Init, UHF_Start.
void UHF_Call_Ev_UHFRFMsg1fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_01.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg1fromSAM.
void UHF_Call_Ev_UHFRFMsg2fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_02.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg2fromSAM.
void UHF_Call_Ev_UHFRFMsg3fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_03.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg3fromSAM.
void UHF_Call_Ev_UHFRFMsg4fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_04.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg4fromSAM.
void UHF_Call_Ev_UHFRFMsg5fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_05.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg5fromSAM.
void UHF_Call_Ev_UHFRFMsg6fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_06.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg6fromSAM.
void UHF_Call_Ev_UHFRFMsg7fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_07.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg7fromSAM.
void UHF_Call_Ev_UHFRFMsg8fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_08.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg8fromSAM.
void UHF_Call_Ev_UHFRFMsg9fromSAM(void)
Function is called by Kessy EventMngr after UHF receives message from SAM. Please find detail information in header file.
References vread_UHFRFMsgfromSAM, UHF_SENSOR_09.
Referenced by TEST_UHF_Call_Ev_UHFRFMsg9fromSAM.
void vread_UHFRFMsgfromSAM(uint16 sensornummer)
Function to merge payload sent over CAN from SAM Please find detail information in header file.
References SWATT_BYPASS, vRead_UHF_RPort, UHF_SENSOR_01, s_UHF_Sensor_01_buf, UHF_SENSOR_MIN_LENGTH, UHF_SENSOR_MAX_LENGTH, u8UHF_Sensor_Zaehler, u16actual_DataReceived, u16UHF_SensorDatenlaenge_can, s_UHF_LogicalHeader_buf, s_UHF_LogicalHeader::Transponder_ID, UHF_VALUE_7, UHF_VALUE_1, UHF_VALUE_6, UHF_VALUE_2, UHF_VALUE_3, s_UHF_LogicalHeader::Port_Number, UHF_VALUE_4, s_UHF_LogicalHeader::Funktionsnummer, s_UHF_LogicalHeader::BatteryLevel, u16UHF_PayloadDatenlaenge_can, UHF_SENSOR_02, UHF_SENSOR_03, UHF_SENSOR_04, UHF_SENSOR_05, UHF_SENSOR_06, UHF_SENSOR_07, UHF_SENSOR_08, s_UHF_Sensor_0n_buf, UHF_SENSOR_0N_DATASIZE, PAYLOAD_INIT_LENGTH, updateRawUHFPayload, bEvaluateCRC10, u8numUHFPortNumber, u8numUHFFunktionsnummer, u8numBatteryLevel, bCRCValid, u8SchluesselNr, FirstMessageArrived, updateSignalStrength, PORT_WEL_KESSY_TELEGRAMM, PORT_KESSY_TELEGRAMM, PORT_FFB_TELEGRAMM, u8rawUHFPayload, u8UHFSignalstaerke, SENSOR_INIT_COUNTER.
Referenced by UHF_Call_Ev_UHFRFMsg1fromSAM, UHF_Call_Ev_UHFRFMsg2fromSAM, UHF_Call_Ev_UHFRFMsg3fromSAM, UHF_Call_Ev_UHFRFMsg4fromSAM, UHF_Call_Ev_UHFRFMsg5fromSAM, UHF_Call_Ev_UHFRFMsg6fromSAM, UHF_Call_Ev_UHFRFMsg7fromSAM, UHF_Call_Ev_UHFRFMsg8fromSAM, UHF_Call_Ev_UHFRFMsg9fromSAM, TEST_UHF_Call_Ev_UHFRFMsg1fromSAM, TEST_UHF_Call_Ev_UHFRFMsg2fromSAM, TEST_UHF_Call_Ev_UHFRFMsg3fromSAM, TEST_UHF_Call_Ev_UHFRFMsg4fromSAM, TEST_UHF_Call_Ev_UHFRFMsg5fromSAM, TEST_UHF_Call_Ev_UHFRFMsg6fromSAM, TEST_UHF_Call_Ev_UHFRFMsg7fromSAM, TEST_UHF_Call_Ev_UHFRFMsg8fromSAM, TEST_UHF_Call_Ev_UHFRFMsg9fromSAM, TEST_vread_UHFRFMsgfromSAM.
void UHF_Call_Ev_StUHFKY_evUHFEmpfang(void)
Function calls Client-Server Interface to send telegram to Kessy. Please find detail information in header file.
References s_UHF_LogicalHeader_buf, s_UHF_LogicalHeader::Transponder_ID, u8numUHFPortNumber, u8numUHFFunktionsnummer, u8numBatteryLevel, u8rawUHFPayload, bCRCValid, u8UHFSignalstaerke.
Referenced by TEST_UHF_Call_Ev_StUHFKY_evUHFEmpfang.
uint8 UHF_Receiver_Get_BatteryLevel(void)
Function return BatteryLevel value. Please find detail information in header file.
References s_UHF_LogicalHeader_buf, s_UHF_LogicalHeader::BatteryLevel.
Referenced by PerformBatteryUpdateOnClamp15, TEST_UHF_Receiver_Get_BatteryLevel.
uint8 UHF_Receiver_Get_SchluesselNr(void)
Function return SchluesselNr value. Please find detail information in header file.
References u8SchluesselNr.
Referenced by PerformBatteryUpdateOnClamp15, TEST_UHF_Receiver_Get_SchluesselNr.
boolean UHF_Receiver_Is_FirstMessageArrived(void)
Function return true if FirstMessageArrived. Please find detail information in header file.
References FirstMessageArrived.
Referenced by PerformBatteryUpdateOnClamp15, TEST_UHF_Receiver_Is_FirstMessageArrived.