Cdd_SOMEIP.h
MESS_NOTIFICATION
MESS_RESPONSE
SOMEIP_PROTOCOL_VERSION
SOMEIP_INTERFACE_VERSION
TYPE_GUARD_ServerServiceInfoType
TYPE_GUARD_LdComIPduRxIndicationType
TYPE_GUARD_LdComIPduRxIndicationRteType
TYPE_GUARD_LdComIPduRxIndicationRteReadPncType
TYPE_GUARD_LdComIPduRxIndicationMiniComServSetterType
TYPE_GUARD_LdComIPduRxIndicationSomeIPDeserializeType
TYPE_GUARD_LdComTriggerTransmitInitialnotificationType
void get_sd_header(const uint32 req_id, const uint8 MessageType, const uint16 service_id, uint8 buffer[], uint32 *const length)
The function generates the header of the SOME/IP notification.
None None req_id - requested ID of the SOME/IP notification MessageType - type of the SOME/IP notification service_id - ID of the service buffer[] - buffer of the SOME/IP notification *length - the lenght of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequence get_sd_header Test MethodThe following function can be verified with following TEST: SWATT test: TEST_get_sd_header_0004 TraceabilityHelperfunction. No requirements are satisfied. The function generates the header of the SOME/IP notification.The function generates the header of the SOME/IP notificationThis function is called by ComServ for generation protocol header. reentrant No context task ComServ Task thread safe Yes void req_id - requested ID of the SOME/IP notification MessageType - type of the SOME/IP notification service_id - ID of the service buffer[] - buffer of the SOME/IP notification length* - the lenght of the buffer
References ProxySerializer_SwapFromUint32, Add_Protocol_Header, SOMEIP_HEADER_SIZE.
Referenced by TEST_get_sd_header.
void ComSer_ExteriorSound_info_EventReleased(void)
void ComSer_GNSS_satelliteInfo_EventReleased(void)
void ComSer_PnCAuth_availabilities_EventAvailable(void)
void ComSer_PnCAuth_availabilities_EventDown(void)
void ComSer_PnCAuth_tlsRootCaCertificateInformations_EventAvailable(void)
void ComSer_PnCAuth_tlsRootCaCertificateInformations_EventDown(void)
void ComSer_PnCAuth_tlsRootCaCertificates_EventAvailable(void)
void ComSer_PnCAuth_tlsRootCaCertificates_EventDown(void)
void ComSer_PnCAuth_moSub1CaCertificates_EventAvailable(void)
void ComSer_PnCAuth_moSub1CaCertificates_EventDown(void)
void ComSer_PnCAuth_moSub2CaCertificates_EventAvailable(void)
void ComSer_PnCAuth_moSub2CaCertificates_EventDown(void)
void ComSer_PnCAuth_contractCertificates_EventAvailable(void)
void ComSer_PnCAuth_contractCertificates_EventDown(void)
void ComSer_PnCAuth_vehicleCertificates_EventAvailable(void)
void ComSer_PnCAuth_vehicleCertificates_EventDown(void)
void ComSer_PnCAuth_signChallenges_EventAvailable(void)
void ComSer_PnCAuth_signChallenges_EventDown(void)
void ComSer_PnCAuth_reportUnknownRootCertificates_EventAvailable(void)
void ComSer_PnCAuth_reportUnknownRootCertificates_EventDown(void)
void Rte_Read_PnCAuth_availabilities(uint8 *array, uint8 MessageType)
void Rte_Read_PnCAuth_tlsRootCaCertificateInformations(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_tlsRootCaCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_moSub1CaCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_moSub2CaCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_contractCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_vehicleCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_signChallenges(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_reportUnknownRootCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.