Cdd_SOMEIP.c
LD_COM_IP_DU_RX_INDICATION_RTE_READ_LIST_SIZE
LD_COM_IP_DU_RX_INDICATION_SOMEIP_DESERIALIZE_LIST_SIZE
LD_COM_IP_DU_RX_INDICATION_RTE_READ_PNC_LIST
LdComIPduRxIndicationRteType LdComIPduRxIndicationRteReadList[13u][13u]
LdComIPdu Rx Indication for rte read listConfiguration list for LdComIPdu Rx Indication and rte read function with message type range LdComIPdu id, fun_ptr to read function, message type (MESS_NOTIFICATION/MESS_RESPONSE) unit LdComIPduRxIndicationRteType context {LdCom_RxIndication} protection {static global}
Referenced by LdCom_RxIndication.
LdComIPduRxIndicationSomeIPDeserializeType LdComIPduRxIndicationSomeIPDeserializeList[2u][2u]
LdComIPdu Rx Indication for SomeIP Deserialize listConfiguration list for LdComIPdu Rx Indication and SomeIP Deserialize PlugAndChargeAuth function range LdComIPdu id, fun_ptr to deserialize function unit LdComIPduRxIndicationSomeIPDeserializeType context {LdCom_RxIndication} protection {static global}
Referenced by LdCom_RxIndication.
LdComIPduRxIndicationRteReadPncType LdComIPduRxIndicationRteReadPncList[16u][16u]
LdComIPdu Rx Indication for rte read PnCAuth listConfiguration list for LdComIPdu Rx Indication and rte read PnCAuth function with message type range LdComIPdu id, fun_ptr to read function, message type (MESS_NOTIFICATION/MESS_RESPONSE) unit LdComIPduRxIndicationRteReadPncType context {LdCom_RxIndication} protection {static global}
Referenced by LdCom_RxIndication.
static void Add_Protocol_Header(uint8 buf[], uint32 *const pos, const uint8 MessageType, const uint16 ServiceId)
The function fills the SOME/IP Header with Protocol Version, Interface Version, Message Type and Return Type.
Create the data buffer to send SOME/IP messages. Add Payload into the buffer. *pos Pointer to the start position of the protocol header MessageType Type of the message to be filled (MESSAGE_TYPE_RESPONSE, MESSAGE_TYPE_NOTIFICATION). ServiceId MACROs of Service Discovery SERVICE IDs. buf[] Data buffer to fill the SOME/IP Header. None Input->Output-CorrelationInput includes the position and values to be filled into the Header. Output contains the data buffer with filled SomeIP Protocol header. Test MethodThe following function can be verified with following TEST: SWATT test: TEST_Add_Protocol_Header_0001 Traceabilitythis function is given by architectural requirments: ID_ArchiteckturalElement and satisfied following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_GW_3760 ; SWR_ICAS1_GW_3765 ; SWR_ICAS1_GW_3766 ; SWR_ICAS1_GW_3767 ; SWR_ICAS1_GW_3782 ; SWR_ICAS1_GW_3788; SWR_ICAS1_GW_3732 ; SWR_ICAS1_GW_3733. The function fills the SOME/IP Header ProtocolThis function is called in get_sd_header() byComServ for generation protocol header. reentrant No context task ComServ Task thread safe Yes void pos* Pointer to the start position of the protocol header MessageType Type of the message to be filled (MESSAGE_TYPE_RESPONSE, MESSAGE_TYPE_NOTIFICATION). ServiceId MACROs of Service Discovery SERVICE IDs. buf[] Data buffer to fill the SOME/IP Header.
References SOMEIP_PROTOCOL_VERSION, ServerServiceInfoList, ServerServiceInfoType::ServerServiceMajorVersion.
Referenced by get_sd_header, TEST_Add_Protocol_Header, TEST_get_sd_header.
void get_sd_header(const uint32 req_id, const uint8 MessageType, const uint16 service_id, uint8 buffer[], uint32 *const length)
The function generates the header of the SOME/IP notification.The function generates the header of the SOME/IP notificationThis function is called by ComServ for generation protocol header. reentrant No context task ComServ Task thread safe Yes void req_id - requested ID of the SOME/IP notification MessageType - type of the SOME/IP notification service_id - ID of the service buffer[] - buffer of the SOME/IP notification length* - the lenght of the buffer
References ProxySerializer_SwapFromUint32, Add_Protocol_Header, SOMEIP_HEADER_SIZE.
Referenced by TEST_get_sd_header.
void LdCom_RxIndication(PduIdType RxPduId, const PduInfoType *PduInfoPtr)
This function indicates a received I-PDU from a lower layer communication interface module.This function indicates a received I-PDU from a lower layer communication interface module. reentrant No thread safe Yes void RxPduId ID of the received I-PDU. PduInfoPtr Contains the length (SduLength) of the received I-PDU and a pointer to a buffer (SduDataPtr) containing the I-PDU.
References LdComIPduRxIndicationList, LdComIPduRxIndicationType::fun_ptr, LdComIPduRxIndicationMiniComServSetterList, LdComIPduRxIndicationMiniComServSetterType::fun_ptr, LdComIPduRxIndicationMiniComServSetterType::SoAdConf_SoAdPduRoute, LdComIPduRxIndicationRteReadList, LdComIPduRxIndicationRteType::fun_ptr, LdComIPduRxIndicationRteType::MessageType, LdComIPduRxIndicationSomeIPDeserializeList, LdComIPduRxIndicationSomeIPDeserializeType::fun_ptr, LdComIPduRxIndicationRteReadPncList, LdComIPduRxIndicationRteReadPncType::fun_ptr, LdComIPduRxIndicationRteReadPncType::MessageType.
Referenced by TEST_LdCom_RxIndication_ACC, TEST_LdCom_RxIndication_AWV, TEST_LdCom_RxIndication_Airbag, TEST_LdCom_RxIndication_CarBody, TEST_LdCom_RxIndication_CentralLocking, TEST_LdCom_RxIndication_ChargingManagementCore, TEST_LdCom_RxIndication_Chassis, TEST_LdCom_RxIndication_ClampControl, TEST_LdCom_RxIndication_ClimateControl, TEST_LdCom_RxIndication_ContiUpdateCoordination, TEST_LdCom_RxIndication_CruiseControl, TEST_LdCom_RxIndication_Damper, TEST_LdCom_RxIndication_DigitalKey, TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_DrivePerformance, TEST_LdCom_RxIndication_DrivingRange, TEST_LdCom_RxIndication_EmergencyAssist, TEST_LdCom_RxIndication_ExteriorLight, TEST_LdCom_RxIndication_ExteriorSound, TEST_LdCom_RxIndication_EnergySystem, TEST_LdCom_RxIndication_FunctionEnabling, TEST_LdCom_RxIndication_GNS, TEST_LdCom_RxIndication_HighVoltageCoordinator, TEST_LdCom_RxIndication_Immobilizer, TEST_LdCom_RxIndication_LaneAssist, TEST_LdCom_RxIndication_LongitudinalCtrlHmiState, TEST_LdCom_RxIndication_OccupantPresence, TEST_LdCom_RxIndication_Odometry, TEST_LdCom_RxIndication_ParkingBrake, TEST_LdCom_RxIndication_PersonalizationSystem, TEST_LdCom_RxIndication_PlugAndChargeAuth, TEST_LdCom_RxIndication_Positioning, TEST_LdCom_RxIndication_Powertrain, TEST_LdCom_RxIndication_PreCrash, TEST_LdCom_RxIndication_SafetyBeltState, TEST_LdCom_RxIndication_SteeringAssist, TEST_LdCom_RxIndication_Temperature, TEST_LdCom_RxIndication_TravelAssist, TEST_LdCom_RxIndication_TripComputer, TEST_LdCom_RxIndication_UnitMaster, TEST_LdCom_RxIndication_VehicleBasicData, TEST_LdCom_RxIndication_VisualOdometry.
void LdCom_TxConfirmation(PduIdType TxPduId)
Std_ReturnType LdCom_TriggerTransmit(PduIdType TxPduId, PduInfoType *PduInfoPtr)
This function is called when an I-PDU shall be transmitted.This function is called when an I-PDU shall be transmitted. reentrant No thread safe Yes Std_ReturnType TxPduId ID of the I-PDU that is requested to be transmitted. PduInfoPtr Pointer to transmit buffer of L-PDU.
References LdComTriggerTransmitInitialnotificationList, LdComTriggerTransmitInitialnotificationType::fun_ptr.
Referenced by TEST_LdCom_TriggerTransmit_ACC, TEST_LdCom_TriggerTransmit_Airbag, TEST_LdCom_TriggerTransmit_AWV, TEST_LdCom_TriggerTransmit_CarBody, TEST_LdCom_TriggerTransmit_CentralLocking, TEST_LdCom_TriggerTransmit_ChargingManagmentCore, TEST_LdCom_TriggerTransmit_Chassis, TEST_LdCom_TriggerTransmit_ClampControl, TEST_LdCom_TriggerTransmit_ClimateControl, TEST_LdCom_TriggerTransmit_ContiUpdateCoordination, TEST_LdCom_TriggerTransmit_CruiseControl, TEST_LdCom_TriggerTransmit_Damper, TEST_LdCom_TriggerTransmit_DigitalKey, TEST_LdCom_TriggerTransmit_Distance, TEST_LdCom_TriggerTransmit_DrivePerformance, TEST_LdCom_TriggerTransmit_DrivingRange, TEST_LdCom_TriggerTransmit_EmergencyAssist, TEST_LdCom_TriggerTransmit_EnergySystem, TEST_LdCom_TriggerTransmit_ExteriorLight, TEST_LdCom_TriggerTransmit_ExteriorSound, TEST_LdCom_TriggerTransmit_FunctionEnabling, TEST_LdCom_TriggerTransmit_GNSS, TEST_LdCom_TriggerTransmit_HighVoltageCoordinator, TEST_LdCom_TriggerTransmit_Immobilizer, TEST_LdCom_TriggerTransmit_LaneAssist, TEST_LdCom_TriggerTransmit_OccupantPresence, TEST_LdCom_TriggerTransmit_Odometry, TEST_LdCom_TriggerTransmit_ParkingBrake, TEST_LdCom_TriggerTransmit_PersonalizationSystem, TEST_LdCom_TriggerTransmit_Powertrain, TEST_LdCom_TriggerTransmit_PreCrash, TEST_LdCom_TriggerTransmit_SafetyBeltState, TEST_LdCom_TriggerTransmit_SteeringAssist, TEST_LdCom_TriggerTransmit_TravelAssist, TEST_LdCom_TriggerTransmit_VehicleBasicData, TEST_LdCom_TriggerTransmit_VisualOdometry.
void ComSer_PnCAuth_availabilities_EventAvailable(void)
void ComSer_PnCAuth_availabilities_EventDown(void)
void ComSer_PnCAuth_tlsRootCaCertificateInformations_EventAvailable(void)
void ComSer_PnCAuth_tlsRootCaCertificateInformations_EventDown(void)
void ComSer_PnCAuth_tlsRootCaCertificates_EventAvailable(void)
void ComSer_PnCAuth_tlsRootCaCertificates_EventDown(void)
void ComSer_PnCAuth_moSub1CaCertificates_EventAvailable(void)
void ComSer_PnCAuth_moSub1CaCertificates_EventDown(void)
void ComSer_PnCAuth_moSub2CaCertificates_EventAvailable(void)
void ComSer_PnCAuth_moSub2CaCertificates_EventDown(void)
void ComSer_PnCAuth_contractCertificates_EventAvailable(void)
void ComSer_PnCAuth_contractCertificates_EventDown(void)
void ComSer_PnCAuth_vehicleCertificates_EventAvailable(void)
void ComSer_PnCAuth_vehicleCertificates_EventDown(void)
void ComSer_PnCAuth_signChallenges_EventAvailable(void)
void ComSer_PnCAuth_signChallenges_EventDown(void)
void ComSer_PnCAuth_reportUnknownRootCertificates_EventAvailable(void)
void ComSer_PnCAuth_reportUnknownRootCertificates_EventDown(void)
void Rte_Read_PnCAuth_availabilities(uint8 *array, uint8 MessageType)
void Rte_Read_PnCAuth_tlsRootCaCertificateInformations(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_tlsRootCaCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_moSub1CaCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_moSub2CaCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_contractCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_vehicleCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_signChallenges(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.
void Rte_Read_PnCAuth_reportUnknownRootCertificates(uint8 *array, uint8 MessageType)
Referenced by TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_PlugAndChargeAuth.