CrossCore_SOMEIP_TxReq.c
SomeIp_FIfoCore1ReducedSize
SomeIp_FIfoCore0Size
S_CC_SOMEIP_TxReq_debug cc_someip_TxReq_debug
Referenced by Process_SomeIpTxReqCore1, Process_SomeIpTxReqCore0, SoAd_IfTransmit_Wrapper, TEST_Process_SomeIpTxReqCore1_0003, TEST_Process_SomeIpTxReqCore0_0005, TEST_SoAd_IfTransmit_Wrapper_0006.
volatile TFiFoMC SomeIp_TxFifo_Core1_Reduced
Referenced by Init_SomeIP_Fifos, Process_SomeIpTxReqCore1, SoAd_IfTransmit_Wrapper, TEST_Init_SomeIP_Fifos_0001, TEST_Process_SomeIpTxReqCore1_0003, TEST_SoAd_IfTransmit_Wrapper_0006.
volatile TFiFoMC SomeIp_TxFifo_Core0
Referenced by Init_SomeIP_Fifos, Process_SomeIpTxReqCore0, SoAd_IfTransmit_Wrapper, TEST_Init_SomeIP_Fifos_0001, TEST_Process_SomeIpTxReqCore0_0005, TEST_SoAd_IfTransmit_Wrapper_0006.
SomeIp_TxPdu_Reduced SomeIp_FifoBufferCore1_Reduced[12]
Referenced by Init_SomeIP_Fifos, TEST_Init_SomeIP_Fifos_0001.
SomeIp_TxPdu SomeIp_FifoBufferCore0[16]
Referenced by Init_SomeIP_Fifos, TEST_Init_SomeIP_Fifos_0001.
static volatile struct INTC_tag* getINTCPtr(void)
this inline function encapsulates the MACRO EDMA_1 to be MISRA clean
volatile struct EDMA_tag *
Referenced by OS_ISR_SomeIpTxReqCore1, OS_ISR_SomeIpTxReqCore0, SoAd_IfTransmit_Wrapper.
static TFiFoMC* getFifoAdr(volatile TFiFoMC *Ptr)
this inline function encapsulates the getting of a TFiFoMC from a volatile TFiFoMC*
TFiFoMC*
Referenced by Init_SomeIP_Fifos, Process_SomeIpTxReqCore1, Process_SomeIpTxReqCore0, SoAd_IfTransmit_Wrapper.
void Init_SomeIP_Fifos(void)
The function initializes the FIFO Transmission buffer.
Initialize Ethernet main task. Activate Comserver task. None None Globals[in] SomeIp_TxFifo_Core0 [in] SomeIp_TxFifo_Core1_Reduced [in] SomeIp_FifoBufferCore1_Backup [in] SomeIp_FifoBufferCore0 [in] SomeIp_FifoBufferCore1_Reduced Input->Output-CorrelationNone Test Method The following function can be verified with following TEST: SWATT test: TEST_Init_SomeIP_Fifos_0001 TraceabilityHelper function. No requirements.
References getFifoAdr, SomeIp_TxFifo_Core0, SomeIp_FifoBufferCore0, SomeIp_FIfoCore0Size, SomeIp_TxFifo_Core1_Reduced, SomeIp_FifoBufferCore1_Reduced, SomeIp_FIfoCore1ReducedSize.
Referenced by TEST_Init_SomeIP_Fifos_0001.
void OS_ISR_SomeIpTxReqCore1(void)
Interrupt Service Routine to set the event Ev_SomeIpTxReqCore1 on Ethernet Task.
None None None None Globals Globals[in] SWInt_SomeIpTxReqCore1 [in] Ev_SomeIpTxReqCore1 Input->Output-CorrelationNone Test MethodThe following function can be verified with following TEST: SWATT test: TEST_OS_ISR_SomeIpTxReqCore1_0002 TraceabilityImplemented as per VWICAS23-14855.
References getINTCPtr.
Referenced by TEST_OS_ISR_SomeIpTxReqCore1_0002.
void Process_SomeIpTxReqCore1(void)
Event triggered Process function to transmit Ethernet messages from Core 1 to 2.
Activate Ethernet Task None None None Globals[in] SomeIp_TxFifo_Core1_Reduced. Input->Output-CorrelationNone Test MethodThe following function can be verified with following TEST: SWATT test: TEST_Process_SomeIpTxReqCore1_0003 TraceabilityImplemented as per VWICAS23-14855.
References SomeIp_TxFifo_Core1_Reduced, getFifoAdr, cc_someip_TxReq_debug.
Referenced by TEST_Process_SomeIpTxReqCore1_0003.
void OS_ISR_SomeIpTxReqCore0(void)
Interrupt Service Routine to set event Ev_SomeIpTxReqCore0 on Ethernet Task.
None None None None Globals[in] SWInt_SomeIpTxReqCore0 [in] Ev_SomeIpTxReqCore0 Input->Output-CorrelationNone Test MethodThe following function can be verified with following TEST: SWATT test: TEST_OS_ISR_SomeIpTxReqCore0_0004 TraceabilityImplemented as per VWICAS23-14855.
References getINTCPtr.
Referenced by TEST_OS_ISR_SomeIpTxReqCore0_0004.
void Process_SomeIpTxReqCore0(void)
Event triggered Process function to transmit Ethernet messages from Core 0 to 2.
Activate Ethernet Task None None None Globals[in] SomeIp_TxFifo_Core0_Reduced. Input->Output-CorrelationNone Test MethodThe following function can be verified with following TEST: SWATT test: TEST_Process_SomeIpTxReqCore0_0005 TraceabilityImplemented as per VWICAS23-14855.
References SomeIp_TxFifo_Core0, getFifoAdr, cc_someip_TxReq_debug.
Referenced by TEST_Process_SomeIpTxReqCore0_0005.
boolean SoAd_IfTransmit_Wrapper(PduIdType SoAdSrcPduId, const PduInfoType *SoAdSrcPduInfoPtr)
Cross core API to request SOME/IP message transmission that is called by SW-C in core 0 and 1.
Build the Service Discovery message for transmit buffer. Transmit the data buffer into the ethernet bus. SoAdSrcPduId ID of the destination PDU. SoAdSrcPduInfoPtr Pointer to the Data to be sent out. TRUE if the data is transmitted successfully. FALSE otherwise GlobalsNone Input->Output-CorrelationNone Test Method The following function can be verified with following TEST: SWATT test: TEST_SoAd_IfTransmit_Wrapper_0006 TraceabilityHelper function. No requirements.
References cc_someip_TxReq_debug, getFifoAdr, SomeIp_TxFifo_Core1_Reduced, getINTCPtr, SomeIp_TxFifo_Core0.
Referenced by TEST_SoAd_IfTransmit_Wrapper_0006.