CrossCore_SomeIp_TxReq.h
SomeIP_ReqTxHandle
boolean SoAd_IfTransmit_Wrapper(PduIdType SoAdSrcPduId, const PduInfoType *SoAdSrcPduInfoPtr)
Cross core API to request SOME/IP message transmission that is called by SW-C in core 0 and 1.
Build the Service Discovery message for transmit buffer. Transmit the data buffer into the ethernet bus. SoAdSrcPduId ID of the destination PDU. SoAdSrcPduInfoPtr Pointer to the Data to be sent out. TRUE if the data is transmitted successfully. FALSE otherwise GlobalsNone Input->Output-CorrelationNone Test Method The following function can be verified with following TEST: SWATT test: TEST_SoAd_IfTransmit_Wrapper_0006 TraceabilityHelper function. No requirements.
References cc_someip_TxReq_debug, getFifoAdr, SomeIp_TxFifo_Core1_Reduced, getINTCPtr, SomeIp_TxFifo_Core0.
Referenced by TEST_SoAd_IfTransmit_Wrapper_0006.
void Init_SomeIP_Fifos(void)
The function initializes the FIFO Transmission buffer.
Initialize Ethernet main task. Activate Comserver task. None None Globals[in] SomeIp_TxFifo_Core0 [in] SomeIp_TxFifo_Core1_Reduced [in] SomeIp_FifoBufferCore1_Backup [in] SomeIp_FifoBufferCore0 [in] SomeIp_FifoBufferCore1_Reduced Input->Output-CorrelationNone Test Method The following function can be verified with following TEST: SWATT test: TEST_Init_SomeIP_Fifos_0001 TraceabilityHelper function. No requirements.
References getFifoAdr, SomeIp_TxFifo_Core0, SomeIp_FifoBufferCore0, SomeIp_FIfoCore0Size, SomeIp_TxFifo_Core1_Reduced, SomeIp_FifoBufferCore1_Reduced, SomeIp_FIfoCore1ReducedSize.
Referenced by TEST_Init_SomeIP_Fifos_0001.
void Process_SomeIpTxReqCore1(void)
Event triggered Process function to transmit Ethernet messages from Core 1 to 2.
Activate Ethernet Task None None None Globals[in] SomeIp_TxFifo_Core1_Reduced. Input->Output-CorrelationNone Test MethodThe following function can be verified with following TEST: SWATT test: TEST_Process_SomeIpTxReqCore1_0003 TraceabilityImplemented as per VWICAS23-14855.
References SomeIp_TxFifo_Core1_Reduced, getFifoAdr, cc_someip_TxReq_debug.
Referenced by TEST_Process_SomeIpTxReqCore1_0003.
void Process_SomeIpTxReqCore0(void)
Event triggered Process function to transmit Ethernet messages from Core 0 to 2.
Activate Ethernet Task None None None Globals[in] SomeIp_TxFifo_Core0_Reduced. Input->Output-CorrelationNone Test MethodThe following function can be verified with following TEST: SWATT test: TEST_Process_SomeIpTxReqCore0_0005 TraceabilityImplemented as per VWICAS23-14855.
References SomeIp_TxFifo_Core0, getFifoAdr, cc_someip_TxReq_debug.
Referenced by TEST_Process_SomeIpTxReqCore0_0005.