CrossCore_SOMEIP_TxReq_variant_FIFO_FULL_TESTING.c.test
static boolean FiFoMCGet_Core1_Mock_Wrapper(TFiFoMC *pFiFoMC, void *pElemData)
Helper function that wraps the mock function for FiFoMCGet.
None Update elements of pElemData with values .SoAdPduId = 0Xffff, .SduLength = 0Xffff, .MessagePayload = {0xff} SomeIp_TxPdu_Reduced : pElemData [out] TFiFoMC:: pFiFoMC boolean
Referenced by TEST_Process_SomeIpTxReqCore1_0003.
static Std_ReturnType SoAd_IfTransmit_Core1_Mock_Wrapper(PduIdType SoAdSrcPduId, const PduInfoType *SoAdSrcPduInfoPtr)
Helper function that wraps the mock function for SoAd_IfTransmit.
It is used to check values of elements in parameter SoAdSrcPduInfoPtr None None PduIdType : SoAdSrcPduId [in] PduInfoType*:: SoAdSrcPduInfoPtr Std_ReturnType
Referenced by TEST_Process_SomeIpTxReqCore1_0003.
static Std_ReturnType SoAd_IfTransmit_Core0_Mock_Wrapper(PduIdType SoAdSrcPduId, const PduInfoType *SoAdSrcPduInfoPtr)
Helper function that wraps the mock function for SoAd_IfTransmit.
It is used to check values of elements in parameter SoAdSrcPduInfoPtr None None PduIdType : SoAdSrcPduId [in] PduInfoType*:: SoAdSrcPduInfoPtr Std_ReturnType
Referenced by TEST_Process_SomeIpTxReqCore0_0005.
static boolean FiFoMCGet_Core0_Mock_Wrapper(TFiFoMC *pFiFoMC, void *pElemData)
Helper function that wraps the mock function for FiFoMCGet.
None Update elements of pElemData with values .SoAdPduId = 0Xffff, .SduLength = 0Xffff, .MessagePayload = {0xff} SomeIp_TxPdu : pElemData [out] TFiFoMC:: pFiFoMC boolean
References SOMEIP_HEADER_SIZE, BUFFER_SIZE.
Referenced by TEST_Process_SomeIpTxReqCore0_0005.
static boolean FiFoMCPut_Core1_Wrapper(TFiFoMC *pFiFoMC, void *pElemData)
Helper function that wraps the mock function for FiFoMCPut.
It is used to check values of elements in parameter pElemData None None TFiFoMC : pFiFoMC [in] void*:: pElemData boolean
Referenced by TEST_SoAd_IfTransmit_Wrapper_0006.
static boolean FiFoMCPut_Core0_Wrapper(TFiFoMC *pFiFoMC, void *pElemData)
Helper function that wraps the mock function for FiFoMCPut.
It is used to check values of elements in parameter pElemData None None TFiFoMC : pFiFoMC [in] void*:: pElemData boolean
Referenced by TEST_SoAd_IfTransmit_Wrapper_0006.
void TEST_Init_SomeIP_Fifos_0001(void)
TestUnit test verifies: Init_SomeIP_Fifos N/A SomeIp_TxFifo_Core0, SomeIp_TxFifo_Core1_Reduced, SomeIp_FifoBufferCore1_Backup, SomeIp_FifoBufferCore1_Reduced and SomeIp_FifoBufferCore0 are globals DescriptionLink to Jenkins build, which contains the SWATT Documentation: ( https://icas1-ci.conti.de/job/VW_MEB_19_ICAS1_CHORUS_DEV_CONAN_SWATT/ ) test types: decision testing Check that FiFoMCInit() called to initilaize buffers SomeIp_FifoBufferCore1_Backup, SomeIp_FifoBufferCore0 and SomeIp_FifoBufferCore1_Reduced
References getFifoAdr_SWATT, SomeIp_TxFifo_Core0, SomeIp_FifoBufferCore0, SomeIp_FIfoCore0Size, SomeIp_TxFifo_Core1_Reduced, SomeIp_FifoBufferCore1_Reduced, SomeIp_FIfoCore1ReducedSize, Init_SomeIP_Fifos.
void TEST_OS_ISR_SomeIpTxReqCore1_0002(void)
TestUnit test verifies: OS_ISR_SomeIpTxReqCore1 INTC_1 is gloabl of type INTC_tag, EthTask has value 2u, and Ev_SomeIpTxReqCore1 has value 0x0080u N/A DescriptionLink to Jenkins build, which contains the SWATT Documentation: ( https://icas1-ci.conti.de/job/VW_MEB_19_ICAS1_CHORUS_DEV_CONAN_SWATT/ ) test types: decision testing Check that the correct bit in INTC_1 is set Check that the event Ev_SomeIpTxReqCore1 on Ethernet Task is set
References OS_ISR_SomeIpTxReqCore1.
void TEST_Process_SomeIpTxReqCore1_0003(void)
TestUnit test verifies: Process_SomeIpTxReqCore1 SomeIp_TxFifo_Core1_Reduced is a global varaible. cc_someip_TxReq_debug is gloal intialized with zeros. N/A DescriptionLink to Jenkins build, which contains the SWATT Documentation: ( https://icas1-ci.conti.de/job/VW_MEB_19_ICAS1_CHORUS_DEV_CONAN_SWATT/ ) test types: decision testing Check that ehternet messeges are transmitted from core 1 to core 2
References SomeIp_TxFifo_Core1_Reduced, Process_SomeIpTxReqCore1, FiFoMCGet_Core1_Mock_Wrapper, getFifoAdr_SWATT, SoAd_IfTransmit_Core1_Mock_Wrapper, cc_someip_TxReq_debug.
void TEST_OS_ISR_SomeIpTxReqCore0_0004(void)
TestUnit test verifies: OS_ISR_SomeIpTxReqCore0 INTC_1 is gloabl of type INTC_tag, EthTask has value 2u, and Ev_SomeIpTxReqCore0 has value 0x0040u N/A DescriptionLink to Jenkins build, which contains the SWATT Documentation: ( https://icas1-ci.conti.de/job/VW_MEB_19_ICAS1_CHORUS_DEV_CONAN_SWATT/ ) test types: decision testing Check that the correct bit in INTC_1 is set Check that the event Ev_SomeIpTxReqCore0 on Ethernet Task is set
References OS_ISR_SomeIpTxReqCore0.
void TEST_Process_SomeIpTxReqCore0_0005(void)
TestUnit test verifies: Process_SomeIpTxReqCore0 N/A SomeIp_TxFifo_Core0 is a global varaible. cc_someip_TxReq_debug is gloal intialized with zeros DescriptionLink to Jenkins build, which contains the SWATT Documentation: ( https://icas1-ci.conti.de/job/VW_MEB_19_ICAS1_CHORUS_DEV_CONAN_SWATT/ ) test types: decision testing Check that ehternet messeges are transmitted from core 0 to core 2
References SomeIp_TxFifo_Core0, Process_SomeIpTxReqCore0, FiFoMCGet_Core0_Mock_Wrapper, getFifoAdr_SWATT, SoAd_IfTransmit_Core0_Mock_Wrapper, cc_someip_TxReq_debug.
void TEST_SoAd_IfTransmit_Wrapper_0006(void)
TestUnit test verifies: SoAd_IfTransmit_Wrapper Define an auxiliaray array aux_MessagePayload[5] as unit8 and initilaized with 0xff. SomeIp_TxFifo_Core1_Reduced, cc_someip_TxReq_debug and INTC_1 are globals N/A Description Link to Jenkins build, which contains the SWATT Documentation: ( https://icas1-ci.conti.de/job/VW_MEB_19_ICAS1_CHORUS_DEV_CONAN_SWATT/ ) test types: decision testing
References FiFoMCPut_Core1_Wrapper, getFifoAdr_SWATT, SomeIp_TxFifo_Core1_Reduced, FiFoMCPut_Core0_Wrapper, SomeIp_TxFifo_Core0, SoAd_IfTransmit_Wrapper, cc_someip_TxReq_debug.