LdCom_GwAdapter.c
LdCom_FifoSize
LdCom_PduSize
LdCom_NoOfTxPdus
LdCom_NoOfRxPdus
LdCom_Min
LdCom_PduInfoType LdCom_TxPdus[(14U)][(14U)]
Referenced by LdCom_Transmit, LdCom_CopyTxData, TEST_LdCom_Transmit_0002, TEST_LdCom_CopyTxData_0003.
LdCom_PduInfoType LdCom_RxPdus[(14U)][(14U)]
Referenced by LdCom_StartOfReception, LdCom_CopyRxData, LdCom_TpRxIndication, TEST_LdCom_StartOfReception_0004, TEST_LdCom_CopyRxData_0005, TEST_LdCom_TpRxIndication_0006.
LdCom_PduInfoType LdCom_RxFifoBuffer[(14U) *(3U)][(14U) *(3U)]
Referenced by LdCom_Init, init_LdCom_RxFifoBuffer, TEST_LdCom_Init_0001.
TFifo LdCom_RxFifo[(14U)][(14U)]
Referenced by LdCom_Init, LdCom_TpRxIndication, LdCom_Receive, init_LdCom_RxFifo, TEST_LdCom_Init_0001, TEST_LdCom_TpRxIndication_0006.
void LdCom_Init(void)
Initialize the LdCom module.
None None None None Globals[out] TFifo LdCom_RxFifo [out] LdCom_PduInfoType LdCom_RxFifoBuffer Input->Output-CorrelationNone Call Sequence Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_Init_0001 Traceability TBD
References LdCom_NoOfRxPdus, LdCom_RxFifo, LdCom_RxFifoBuffer, LdCom_FifoSize.
Referenced by TEST_LdCom_Init_0001.
Std_ReturnType LdCom_Transmit(PduIdType id, const Ks_Ika_Challenge_ImplType *pData)
Transmit function for the slave communication.
None None txId slave handle pData is the data to be sent #E_NOT_OK or return value from CanTp_Transmit() Globals[out] LdCom_PduInfoType LdCom_TxPdus Input->Output-CorrelationNone Call SequenceBased on the given MsgType, CanTp_Transmit() needs to be called. callsequence Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_Transmit_0002 Traceability TBD
References LdCom_NoOfTxPdus, LdCom_Min, LdCom_PduSize, LdCom_TxPdus.
Referenced by TEST_LdCom_Transmit_0002.
BufReq_ReturnType LdCom_CopyTxData(PduIdType id, const PduInfoType *info, RetryInfoType *retry, PduLengthType *availableDataPtr)
Function for copying the data in the given buffer.
It is called to acquire the transmit data for a segmented pdu This is done by CanTp, when the transmission was triggered with CanTp_Transmit() Transmission was started using CanTp_Transmit() None id is the index of the transmission buffer, where the data are stored info contains the information about the datalength to be sent retry is unused availableDataPtr is filled with the number of bytes, that should be sent #BUFREQ_OK #BUFREQ_E_BUSY Globals[out] LdCom_PduInfoType LdCom_TxPdus Input->Output-CorrelationNone Call Sequence callsequence Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_CopyTxData_0003 Traceability TBD
References LdCom_NoOfTxPdus, LdCom_PduSize, LdCom_TxPdus, LdCom_Min.
Referenced by TEST_LdCom_CopyTxData_0003.
BufReq_ReturnType LdCom_StartOfReception(PduIdType id, const PduInfoType *info, PduLengthType TpSduLength, PduLengthType *bufferSizePtr)
Function is called by the PduR/CanTp from Core2 and indicates a received message.
None LdCom_CopyRxData() needs to be called to copy the data in the reception buffer. id is the index of the slave from which the message came from. info is unused TpSduLength is the length of the data, that are going to be received bufferSizePtr is filled with the maximum number of bytes the LdCom impplementation is able to handle. #BUFREQ_OK #BUFREQ_E_OVFL Globals[out] LdCom_PduInfoType LdCom_RxPdus Input->Output-CorrelationNone No callsequence, just the following checks: Is the id is smaller than the number of slaves?Is the length of the received data smaller than the maximum number of bytes, that we can handle? If both checks are ok, the maximum number of bytes is given back as bufferSizePtr. Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_StartOfReception_0004 Traceability TBD
References LdCom_NoOfRxPdus, LdCom_PduSize, LdCom_RxPdus.
Referenced by TEST_LdCom_StartOfReception_0004.
BufReq_ReturnType LdCom_CopyRxData(PduIdType id, const PduInfoType *info, PduLengthType *bufferSizePtr)
Function is copying the received data into the reception array.
If this is the first chunk of data, LdCom_StartOfReception() needs to be called before. If this is a following chunk of data, LdCom_RxPdus[id].arraySize need to have the value from last chunk. LdCom_TpRxIndication() needs to be called after the last chunk by the lower layer, so the data need to be put in the FIFO. id is the index of the slave from which the message came from. info contains the received data bufferSizePtr is the remaining bytes after this copying. #BUFREQ_E_NOT_OK #BUFREQ_OK Globals[out] LdCom_PduInfoType LdCom_RxPdus Input->Output-CorrelationNone Call Sequencecallsequence Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_CopyRxData_0005 Traceability TBD
References LdCom_NoOfRxPdus, LdCom_PduSize, LdCom_RxPdus, LdCom_Min.
Referenced by TEST_LdCom_CopyRxData_0005.
void LdCom_TpRxIndication(PduIdType id, Std_ReturnType result)
Function is putting the received data in the reception FIFO.
All junks need to be copied to the reception array with LdCom_CopyRxData(). The SWC needs to take the element from the FIFO and process it id is the index of the slave from which the message came from. result is the information, whether the reception was OK None Globals[out] TFifo LdCom_RxFifo [out] LdCom_PduInfoType LdCom_RxPdus Input->Output-CorrelationNone Call Sequencecallsequence Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_TpRxIndication_0006 Traceability TBD
References LdCom_NoOfRxPdus, LdCom_RxFifo, LdCom_RxPdus.
Referenced by TEST_LdCom_TpRxIndication_0006.
Std_ReturnType LdCom_Receive(PduIdType id, Ks_Ika_Challenge_ImplType *pData)
Function is checking for received messages for the given slave.
FIFO needs to be intialzed (Done in LdCom_Init()) None id is the index of the slave for which it should be checked for received data pData is the buffer, where the received data should be stored in #RTE_E_NO_DATA #RTE_E_OK #RTE_E_INVALID Globals[out] TFifo LdCom_RxFifo Input->Output-CorrelationNone callsequence callsequence Test Method The following function can be verified with following TEST: SWATT test: TEST_LdCom_Receive_0007 Traceability TBD
References LdCom_NoOfRxPdus, LdCom_RxFifo, LdCom_Min, LdCom_PduSize.
Referenced by TEST_LdCom_Receive_0007.