LdCom_Cbk.h
void LdCom_RxIndication(PduIdType RxPduId, const PduInfoType *PduInfoPtr)
This function indicates a received I-PDU from a lower layer communication interface module.
Check if the socket route is enabled. The I-PDU data is copied from the underlying layer to LdCom. RxPduId ID of the received I-PDU. PduInfoPtr Contains the length (SduLength) of the received I-PDU and a pointer to a buffer (SduDataPtr) containing the I-PDU. None GlobalsNone Input->Output-CorrelationInput include the id of the received Com I-PDU and payload buffer. Respective service handle callbacks are called if the protocol version match. Configured RxPduID in Tresos Servicehandlecallback LdComIPdu_RPC_ACC_notifications_Adaptive_req (void)ComSer_get_ACC_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_notifications_Adaptive) LdComIPdu_RPC_ACC_notifications_ICAS3_IVI_req (void)ComSer_get_ACC_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_notifications_ICAS3_IVI) LdComIPdu_RPC_ACC_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_notifications_Java_req (void)ComSer_get_ACC_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_notifications_Java) LdComIPdu_RPC_ACC_notifications_ZR_TOP_req (void)ComSer_get_ACC_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_notifications_ZR_TOP) LdComIPdu_RPC_ACC_info_Adaptive_req (void)ComSer_get_ACC_info(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_info_Adaptive) LdComIPdu_RPC_ACC_info_ICAS3_IVI_req (void)ComSer_get_ACC_info(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_info_ICAS3_IVI) LdComIPdu_RPC_ACC_info_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_info(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_info_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_info_Java_req (void)ComSer_get_ACC_info(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_info_Java) LdComIPdu_RPC_ACC_info_ZR_TOP_req (void)ComSer_get_ACC_info(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_info_ZR_TOP) LdComIPdu_RPC_ACC_relevantObjects_Adaptive_req (void)ComSer_get_ACC_relevantObjects(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_relevantObjects_Adaptive) LdComIPdu_RPC_ACC_relevantObjects_ICAS3_IVI_req (void)ComSer_get_ACC_relevantObjects(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_relevantObjects_ICAS3_IVI) LdComIPdu_RPC_ACC_relevantObjects_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_relevantObjects(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_relevantObjects_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_relevantObjects_Java_req (void)ComSer_get_ACC_relevantObjects(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_relevantObjects_Java) LdComIPdu_RPC_ACC_relevantObjects_ZR_TOP_req (void)ComSer_get_ACC_relevantObjects(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_relevantObjects_ZR_TOP) LdComIPdu_RPC_ACC_targetDistances_Adaptive_req (void)ComSer_get_ACC_targetDistances(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_targetDistances_Adaptive) LdComIPdu_RPC_ACC_targetDistances_ICAS3_IVI_req (void)ComSer_get_ACC_targetDistances(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_targetDistances_ICAS3_IVI) LdComIPdu_RPC_ACC_targetDistances_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_targetDistances(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_targetDistances_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_targetDistances_Java_req (void)ComSer_get_ACC_targetDistances(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_targetDistances_Java) LdComIPdu_RPC_ACC_targetDistances_ZR_TOP_req (void)ComSer_get_ACC_targetDistances(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_targetDistances_ZR_TOP) LdComIPdu_RPC_ACC_velocities_Adaptive_req (void)ComSer_get_ACC_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_velocities_Adaptive) LdComIPdu_RPC_ACC_velocities_ICAS3_IVI_req (void)ComSer_get_ACC_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_velocities_ICAS3_IVI) LdComIPdu_RPC_ACC_velocities_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_velocities_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_velocities_Java_req (void)ComSer_get_ACC_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_velocities_Java) LdComIPdu_RPC_ACC_velocities_ZR_TOP_req (void)ComSer_get_ACC_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_velocities_ZR_TOP) LdComIPdu_RPC_ACC_additionalInformation_Adaptive_req (void)ComSer_get_ACC_additionalInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalInformation_Adaptive) LdComIPdu_RPC_ACC_additionalInformation_ICAS3_IVI_req (void)ComSer_get_ACC_additionalInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalInformation_ICAS3_IVI) LdComIPdu_RPC_ACC_additionalInformation_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_additionalInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalInformation_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_additionalInformation_Java_req (void)ComSer_get_ACC_additionalInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalInformation_Java) LdComIPdu_RPC_ACC_additionalInformation_ZR_TOP_req (void)ComSer_get_ACC_additionalInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalInformation_ZR_TOP) LdComIPdu_RPC_ACC_additionalRadarInformation_Adaptive_req (void)ComSer_get_ACC_additionalRadarInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalRadarInformation_Adaptive) LdComIPdu_RPC_ACC_additionalRadarInformation_ICAS3_IVI_req (void)ComSer_get_ACC_additionalRadarInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalRadarInformation_ICAS3_IVI) LdComIPdu_RPC_ACC_additionalRadarInformation_ICAS3_ZR_TOP_req (void)ComSer_get_ACC_additionalRadarInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalRadarInformation_ICAS3_ZR_TOP) LdComIPdu_RPC_ACC_additionalRadarInformation_Java_req (void)ComSer_get_ACC_additionalRadarInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalRadarInformation_Java) LdComIPdu_RPC_ACC_additionalRadarInformation_ZR_TOP_req (void)ComSer_get_ACC_additionalRadarInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ACC_additionalRadarInformation_ZR_TOP) LdComIPdu_RPC_Airbag_notifications_Adaptive_req (void)ComSer_get_Airbag_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Airbag_notifications_Adaptive) LdComIPdu_RPC_Airbag_notifications_ICAS3_req (void)ComSer_get_Airbag_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Airbag_notifications_ICAS3) LdComIPdu_RPC_Airbag_notifications_Java_req (void)ComSer_get_Airbag_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Airbag_notifications_Java) LdComIPdu_RPC_Airbag_crashInfo_Adaptive_req (void)ComSer_get_Airbag_crashInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Airbag_crashInfo_Adaptive) LdComIPdu_RPC_Airbag_crashInfo_ICAS3_req (void)ComSer_get_Airbag_crashInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Airbag_crashInfo_ICAS3) LdComIPdu_RPC_Airbag_crashInfo_Java_req (void)ComSer_get_Airbag_crashInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Airbag_crashInfo_Java) LdComIPdu_RPC_CarBody_doors_Adaptive_req (void)ComSer_get_CarBody_doors(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_doors_Adaptive) LdComIPdu_RPC_CarBody_doors_ICAS3_req (void)ComSer_get_CarBody_doors(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_doors_ICAS3) LdComIPdu_RPC_CarBody_doors_ConMod_NAD_req (void)ComSer_get_CarBody_doors(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_doors_ConMod_NAD) LdComIPdu_RPC_CarBody_doors_Java_req (void)ComSer_get_CarBody_doors(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_doors_Java) LdComIPdu_RPC_CarBody_hatchesAndTraps_Adaptive_req (void)ComSer_get_CarBody_hatchesAndTraps(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_hatchesAndTraps_Adaptive) LdComIPdu_RPC_CarBody_hatchesAndTraps_ICAS3_req (void)ComSer_get_CarBody_hatchesAndTraps(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_hatchesAndTraps_ICAS3) LdComIPdu_RPC_CarBody_hatchesAndTraps_ConMod_NAD_req (void)ComSer_get_CarBody_hatchesAndTraps(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_hatchesAndTraps_ConMod_NAD) LdComIPdu_RPC_CarBody_hatchesAndTraps_Java_req (void)ComSer_get_CarBody_hatchesAndTraps(request_id, SoAdConf_SoAdPduRoute_RPC_CarBody_hatchesAndTraps_Java) LdComIPdu_RPC_SteeringAssist_notifications_Adaptive_req (void)ComSer_get_SteeringAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SteeringAssist_notifications_Adaptive) LdComIPdu_RPC_SteeringAssist_notifications_ICAS3_req (void)ComSer_get_SteeringAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SteeringAssist_notifications_ICAS3) LdComIPdu_RPC_SteeringAssist_notifications_ICAS3_IVI_req (void)ComSer_get_SteeringAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SteeringAssist_notifications_ICAS3_IVI) LdComIPdu_RPC_SteeringAssist_notifications_Java_req (void)ComSer_get_SteeringAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SteeringAssist_notifications_Java) LdComIPdu_RPC_Damper_notifications_Adaptive_req (void)ComSer_get_Damper_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Damper_notifications_Adaptive) LdComIPdu_RPC_Damper_notifications_Java_req (void)ComSer_get_Damper_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Damper_notifications_Java) LdComIPdu_RPC_Damper_damperMonitorInfo_Adaptive_req (void)ComSer_get_Damper_damperMonitorInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Damper_damperMonitorInfo_Adaptive) LdComIPdu_RPC_Damper_damperMonitorInfo_Java_req (void)ComSer_get_Damper_damperMonitorInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Damper_damperMonitorInfo_Java) LdComIPdu_RPC_AWV_notifications_Adaptive_req (void)ComSer_get_AWV_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_notifications_Adaptive) LdComIPdu_RPC_AWV_notifications_ICAS3_IVI_req (void)ComSer_get_AWV_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_notifications_ICAS3_IVI) LdComIPdu_RPC_AWV_notifications_ZR_TOP_req (void)ComSer_get_AWV_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_notifications_ZR_TOP) LdComIPdu_RPC_AWV_notifications_Java_req (void)ComSer_get_AWV_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_notifications_Java) LdComIPdu_RPC_AWV_info_Adaptive_req (void)ComSer_get_AWV_info(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_info_Adaptive) LdComIPdu_RPC_AWV_info_ICAS3_IVI_req (void)ComSer_get_AWV_info(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_info_ICAS3_IVI) LdComIPdu_RPC_AWV_info_ZR_TOP_req (void)ComSer_get_AWV_info(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_info_ZR_TOP) LdComIPdu_RPC_AWV_info_Java_req (void)ComSer_get_AWV_info(request_id, SoAdConf_SoAdPduRoute_RPC_AWV_info_Java) LdComIPdu_RPC_LaneAssist_notifications_Adaptive_req (void)ComSer_get_LaneAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_LaneAssist_notifications_Adaptive) LdComIPdu_RPC_LaneAssist_notifications_ICAS3_IVI_req (void)ComSer_get_LaneAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_LaneAssist_notifications_ICAS3_IVI) LdComIPdu_RPC_LaneAssist_notifications_ZR_TOP_req (void)ComSer_get_LaneAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_LaneAssist_notifications_ZR_TOP) LdComIPdu_RPC_LaneAssist_notifications_Java_req (void)ComSer_get_LaneAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_LaneAssist_notifications_Java) LdComIPdu_RPC_CentralLocking_lockStates_Adaptive_req (void)ComSer_get_CentralLocking_lockStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_lockStates_Adaptive) LdComIPdu_RPC_CentralLocking_lockStates_ICAS3_req (void)ComSer_get_CentralLocking_lockStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_lockStates_ICAS3) LdComIPdu_RPC_CentralLocking_lockStates_ConMod_NAD_req (void)ComSer_get_CentralLocking_lockStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_lockStates_ConMod_NAD) LdComIPdu_RPC_CentralLocking_lockStates_Java_req (void)ComSer_get_CentralLocking_lockStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_lockStates_Java) LdComIPdu_RPC_CentralLocking_safeStates_Adaptive_req (void)ComSer_get_CentralLocking_safeStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_safeStates_Adaptive) LdComIPdu_RPC_CentralLocking_safeStates_ICAS3_req (void)ComSer_get_CentralLocking_safeStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_safeStates_ICAS3) LdComIPdu_RPC_CentralLocking_safeStates_ConMod_NAD_req (void)ComSer_get_CentralLocking_safeStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_safeStates_ConMod_NAD) LdComIPdu_RPC_CentralLocking_safeStates_Java_req (void)ComSer_get_CentralLocking_safeStates(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_safeStates_Java) LdComIPdu_RPC_CentralLocking_info_Adaptive_req (void)ComSer_get_CentralLocking_info(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_info_Adaptive) LdComIPdu_RPC_CentralLocking_info_ICAS3_req (void)ComSer_get_CentralLocking_info(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_info_ICAS3) LdComIPdu_RPC_CentralLocking_info_ConMod_NAD_req (void)ComSer_get_CentralLocking_info(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_info_ConMod_NAD) LdComIPdu_RPC_CentralLocking_info_Java_req (void)ComSer_get_CentralLocking_info(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_info_Java) LdComIPdu_RPC_CentralLocking_notifications_Adaptive_req (void)ComSer_get_CentralLocking_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_notifications_Adaptive) LdComIPdu_RPC_CentralLocking_notifications_ICAS3_req (void)ComSer_get_CentralLocking_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_notifications_ICAS3) LdComIPdu_RPC_CentralLocking_notifications_ConMod_NAD_req (void)ComSer_get_CentralLocking_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_notifications_ConMod_NAD) LdComIPdu_RPC_CentralLocking_notifications_Java_req (void)ComSer_get_CentralLocking_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CentralLocking_notifications_Java) LdComIPdu_RPC_Chassis_axes_Adaptive_req (void)ComSer_get_Chassis_axes(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_axes_Adaptive) LdComIPdu_RPC_Chassis_axes_ICAS3_IVI_req (void)ComSer_get_Chassis_axes(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_axes_ICAS3_IVI) LdComIPdu_RPC_Chassis_axes_ICAS3_req (void)ComSer_get_Chassis_axes(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_axes_ICAS3) LdComIPdu_RPC_Chassis_axes_Java_req (void)ComSer_get_Chassis_axes(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_axes_Java) LdComIPdu_RPC_Chassis_axes_ConMod_V2X_req (void)ComSer_get_Chassis_axes(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_axes_ConMod_V2X) LdComIPdu_RPC_Chassis_velocityInfo_Adaptive_req (void)ComSer_get_Chassis_velocityInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_velocityInfo_Adaptive) LdComIPdu_RPC_Chassis_velocityInfo_ICAS3_IVI_req (void)ComSer_get_Chassis_velocityInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_velocityInfo_ICAS3_IVI) LdComIPdu_RPC_Chassis_velocityInfo_ICAS3_req (void)ComSer_get_Chassis_velocityInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_velocityInfo_ICAS3) LdComIPdu_RPC_Chassis_velocityInfo_Java_req (void)ComSer_get_Chassis_velocityInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_velocityInfo_Java) LdComIPdu_RPC_Chassis_velocityInfo_ConMod_V2X_req (void)ComSer_get_Chassis_velocityInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_velocityInfo_ConMod_V2X) LdComIPdu_RPC_Chassis_notifications_Adaptive_req (void)ComSer_get_Chassis_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_notifications_Adaptive) LdComIPdu_RPC_Chassis_notifications_ICAS3_IVI_req (void)ComSer_get_Chassis_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_notifications_ICAS3_IVI) LdComIPdu_RPC_Chassis_notifications_ICAS3_req (void)ComSer_get_Chassis_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_notifications_ICAS3) LdComIPdu_RPC_Chassis_notifications_Java_req (void)ComSer_get_Chassis_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_notifications_Java) LdComIPdu_RPC_Chassis_notifications_ConMod_V2X_req (void)ComSer_get_Chassis_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_notifications_ConMod_V2X) LdComIPdu_RPC_Chassis_wheels_Adaptive_req (void)ComSer_get_Chassis_wheels(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_wheels_Adaptive) LdComIPdu_RPC_Chassis_wheels_ICAS3_IVI_req (void)ComSer_get_Chassis_wheels(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_wheels_ICAS3_IVI) LdComIPdu_RPC_Chassis_wheels_ICAS3_req (void)ComSer_get_Chassis_wheels(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_wheels_ICAS3) LdComIPdu_RPC_Chassis_wheels_Java_req (void)ComSer_get_Chassis_wheels(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_wheels_Java) LdComIPdu_RPC_Chassis_wheels_ConMod_V2X_req (void)ComSer_get_Chassis_wheels(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_wheels_ConMod_V2X) LdComIPdu_RPC_Chassis_espSystemInfo_Adaptive_req (void)ComSer_get_Chassis_espSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_espSystemInfo_Adaptive) LdComIPdu_RPC_Chassis_espSystemInfo_ICAS3_IVI_req (void)ComSer_get_Chassis_espSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_espSystemInfo_ICAS3_IVI) LdComIPdu_RPC_Chassis_espSystemInfo_ICAS3_req (void)ComSer_get_Chassis_espSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_espSystemInfo_ICAS3) LdComIPdu_RPC_Chassis_espSystemInfo_Java_req (void)ComSer_get_Chassis_espSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_espSystemInfo_Java) LdComIPdu_RPC_Chassis_espSystemInfo_ConMod_V2X_req (void)ComSer_get_Chassis_espSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_Chassis_espSystemInfo_ConMod_V2X) LdComIPdu_RPC_ClampControl_clamps_Adaptive_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_Adaptive) LdComIPdu_RPC_ClampControl_clamps_ICAS3_ZR_TOP_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ICAS3_ZR_TOP) LdComIPdu_RPC_ClampControl_clamps_ICAS3_IVI_MIB_TOP_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ICAS3_IVI_MIB_TOP) LdComIPdu_RPC_ClampControl_clamps_ConMod_NAD_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ConMod_NAD) LdComIPdu_RPC_ClampControl_clamps_Java_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_Java) LdComIPdu_RPC_ClampControl_clamps_OCU_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_OCU) LdComIPdu_RPC_ClampControl_notifications_Adaptive_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_Adaptive) LdComIPdu_RPC_ClampControl_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_ClampControl_notifications_ICAS3_IVI_MIB_TOP_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ICAS3_IVI_MIB_TOP) LdComIPdu_RPC_ClampControl_notifications_ConMod_NAD_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ConMod_NAD) LdComIPdu_RPC_ClampControl_notifications_Java_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_Java) LdComIPdu_RPC_ClampControl_notifications_OCU_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_OCU) LdComIPdu_RPC_ClampControl_specialStates_Adaptive_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_Adaptive) LdComIPdu_RPC_ClampControl_specialStates_ICAS3_ZR_TOP_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ICAS3_ZR_TOP) LdComIPdu_RPC_ClampControl_specialStates_ICAS3_IVI_MIB_TOP_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ICAS3_IVI_MIB_TOP) LdComIPdu_RPC_ClampControl_specialStates_ConMod_NAD_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ConMod_NAD) LdComIPdu_RPC_ClampControl_specialStates_Java_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_Java) LdComIPdu_RPC_ClampControl_specialStates_OCU_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_OCU) LdComIPdu_RPC_DrivePerformance_displayParameters_Java_req (void)ComSer_get_DrivePerformance_displayParameters(request_id, SoAdConf_SoAdPduRoute_RPC_DrivePerformance_displayParameters_Java) LdComIPdu_RPC_DrivingRange_ranges_Adaptive_req (void)ComSer_get_DrivingRange_ranges(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_ranges_Adaptive) LdComIPdu_RPC_DrivingRange_ranges_ZR_TOP_req (void)ComSer_get_DrivingRange_ranges(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_ranges_ZR_TOP) LdComIPdu_RPC_DrivingRange_ranges_ConMod_NAD_req (void)ComSer_get_DrivingRange_ranges(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_ranges_ConMod_NAD) LdComIPdu_RPC_DrivingRange_ranges_Java_req (void)ComSer_get_DrivingRange_ranges(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_ranges_Java) LdComIPdu_RPC_DrivingRange_ranges_OCU_req (void)ComSer_get_DrivingRange_ranges(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_ranges_OCU) LdComIPdu_RPC_DrivingRange_status_Adaptive_req (void)ComSer_get_DrivingRange_status(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_status_Adaptive) LdComIPdu_RPC_DrivingRange_status_ZR_TOP_req (void)ComSer_get_DrivingRange_status(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_status_ZR_TOP) LdComIPdu_RPC_DrivingRange_status_ConMod_NAD_req (void)ComSer_get_DrivingRange_status(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_status_ConMod_NAD) LdComIPdu_RPC_DrivingRange_status_Java_req (void)ComSer_get_DrivingRange_status(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_status_Java) LdComIPdu_RPC_DrivingRange_status_OCU_req (void)ComSer_get_DrivingRange_status(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_status_OCU) LdComIPdu_RPC_DrivingRange_notifications_Adaptive_req (void)ComSer_get_DrivingRange_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_notifications_Adaptive) LdComIPdu_RPC_DrivingRange_notifications_ZR_TOP_req (void)ComSer_get_DrivingRange_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_notifications_ZR_TOP) LdComIPdu_RPC_DrivingRange_notifications_ConMod_NAD_req (void)ComSer_get_DrivingRange_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_notifications_ConMod_NAD) LdComIPdu_RPC_DrivingRange_notifications_Java_req (void)ComSer_get_DrivingRange_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_notifications_Java) LdComIPdu_RPC_DrivingRange_notifications_OCU_req (void)ComSer_get_DrivingRange_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_notifications_OCU) LdComIPdu_RPC_DrivingRange_rangeCalcConsumptions_Adaptive_req (void)ComSer_get_DrivingRange_rangeCalcConsumptions(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_rangeCalcConsumptions_Adaptive) LdComIPdu_RPC_DrivingRange_rangeCalcConsumptions_ZR_TOP_req (void)ComSer_get_DrivingRange_rangeCalcConsumptions(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_rangeCalcConsumptions_ZR_TOP) LdComIPdu_RPC_DrivingRange_rangeCalcConsumptions_ConMod_NAD_req (void)ComSer_get_DrivingRange_rangeCalcConsumptions(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_rangeCalcConsumptions_ConMod_NAD) LdComIPdu_RPC_DrivingRange_rangeCalcConsumptions_Java_req (void)ComSer_get_DrivingRange_rangeCalcConsumptions(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_rangeCalcConsumptions_Java) LdComIPdu_RPC_DrivingRange_rangeCalcConsumptions_OCU_req (void)ComSer_get_DrivingRange_rangeCalcConsumptions(request_id, SoAdConf_SoAdPduRoute_RPC_DrivingRange_rangeCalcConsumptions_OCU) LdComIPdu_RPC_EnergySystem_notifications_Adaptive_req (void)ComSer_get_EnergySystem_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_notifications_Adaptive) LdComIPdu_RPC_EnergySystem_notifications_ICAS3_req (void)ComSer_get_EnergySystem_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_notifications_ICAS3) LdComIPdu_RPC_EnergySystem_notifications_ICAS3_IVI_req (void)ComSer_get_EnergySystem_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_notifications_ICAS3_IVI) LdComIPdu_RPC_EnergySystem_notifications_ConMod_NAD_req (void)ComSer_get_EnergySystem_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_notifications_ConMod_NAD) LdComIPdu_RPC_EnergySystem_notifications_Java_req (void)ComSer_get_EnergySystem_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_notifications_Java) LdComIPdu_RPC_EnergySystem_notifications_OCU_req (void)ComSer_get_EnergySystem_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_notifications_OCU) LdComIPdu_RPC_EnergySystem_highVoltageBatteries_Adaptive_req (void)ComSer_get_EnergySystem_highVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_highVoltageBatteries_Adaptive) LdComIPdu_RPC_EnergySystem_highVoltageBatteries_ICAS3_req (void)ComSer_get_EnergySystem_highVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_highVoltageBatteries_ICAS3) LdComIPdu_RPC_EnergySystem_highVoltageBatteries_ICAS3_IVI_req (void)ComSer_get_EnergySystem_highVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_highVoltageBatteries_ICAS3_IVI) LdComIPdu_RPC_EnergySystem_highVoltageBatteries_ConMod_NAD_req (void)ComSer_get_EnergySystem_highVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_highVoltageBatteries_ConMod_NAD) LdComIPdu_RPC_EnergySystem_highVoltageBatteries_Java_req (void)ComSer_get_EnergySystem_highVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_highVoltageBatteries_Java) LdComIPdu_RPC_EnergySystem_highVoltageBatteries_OCU_req (void)ComSer_get_EnergySystem_highVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_highVoltageBatteries_OCU) LdComIPdu_RPC_EnergySystem_lowVoltageBatteries_Adaptive_req (void)ComSer_get_EnergySystem_lowVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageBatteries_Adaptive) LdComIPdu_RPC_EnergySystem_lowVoltageBatteries_ICAS3_req (void)ComSer_get_EnergySystem_lowVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageBatteries_ICAS3) LdComIPdu_RPC_EnergySystem_lowVoltageBatteries_ICAS3_IVI_req (void)ComSer_get_EnergySystem_lowVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageBatteries_ICAS3_IVI) LdComIPdu_RPC_EnergySystem_lowVoltageBatteries_ConMod_NAD_req (void)ComSer_get_EnergySystem_lowVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageBatteries_ConMod_NAD) LdComIPdu_RPC_EnergySystem_lowVoltageBatteries_Java_req (void)ComSer_get_EnergySystem_lowVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageBatteries_Java) LdComIPdu_RPC_EnergySystem_lowVoltageBatteries_OCU_req (void)ComSer_get_EnergySystem_lowVoltageBatteries(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageBatteries_OCU) LdComIPdu_RPC_EnergySystem_lowVoltageSystemInfo_Adaptive_req (void)ComSer_get_EnergySystem_lowVoltageSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageSystemInfo_Adaptive) LdComIPdu_RPC_EnergySystem_lowVoltageSystemInfo_ICAS3_req (void)ComSer_get_EnergySystem_lowVoltageSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageSystemInfo_ICAS3) LdComIPdu_RPC_EnergySystem_lowVoltageSystemInfo_ICAS3_IVI_req (void)ComSer_get_EnergySystem_lowVoltageSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageSystemInfo_ICAS3_IVI) LdComIPdu_RPC_EnergySystem_lowVoltageSystemInfo_ConMod_NAD_req (void)ComSer_get_EnergySystem_lowVoltageSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageSystemInfo_ConMod_NAD) LdComIPdu_RPC_EnergySystem_lowVoltageSystemInfo_Java_req (void)ComSer_get_EnergySystem_lowVoltageSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageSystemInfo_Java) LdComIPdu_RPC_EnergySystem_lowVoltageSystemInfo_OCU_req (void)ComSer_get_EnergySystem_lowVoltageSystemInfo(request_id, SoAdConf_SoAdPduRoute_RPC_EnergySystem_lowVoltageSystemInfo_OCU) LdComIPdu_RPC_ExteriorLight_lightFunctions_Adaptive_req (void)ComSer_get_ExteriorLight_lightFunctions(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightFunctions_Adaptive) LdComIPdu_RPC_ExteriorLight_lightFunctions_ICAS3_IVI_req (void)ComSer_get_ExteriorLight_lightFunctions(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightFunctions_ICAS3_IVI) LdComIPdu_RPC_ExteriorLight_lightFunctions_ICAS3_ZR_TOP_req (void)ComSer_get_ExteriorLight_lightFunctions(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightFunctions_ICAS3_ZR_TOP) LdComIPdu_RPC_ExteriorLight_lightFunctions_ConMod_NAD_req (void)ComSer_get_ExteriorLight_lightFunctions(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightFunctions_ConMod_NAD) LdComIPdu_RPC_ExteriorLight_lightFunctions_Java_req (void)ComSer_get_ExteriorLight_lightFunctions(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightFunctions_Java) LdComIPdu_RPC_ExteriorLight_lamps_Adaptive_req (void)ComSer_get_ExteriorLight_lamps(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lamps_Adaptive) LdComIPdu_RPC_ExteriorLight_lamps_ICAS3_IVI_req (void)ComSer_get_ExteriorLight_lamps(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lamps_ICAS3_IVI) LdComIPdu_RPC_ExteriorLight_lamps_ICAS3_ZR_TOP_req (void)ComSer_get_ExteriorLight_lamps(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lamps_ICAS3_ZR_TOP) LdComIPdu_RPC_ExteriorLight_lamps_ConMod_NAD_req (void)ComSer_get_ExteriorLight_lamps(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lamps_ConMod_NAD) LdComIPdu_RPC_ExteriorLight_lamps_Java_req (void)ComSer_get_ExteriorLight_lamps(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lamps_Java) LdComIPdu_RPC_ExteriorLight_notifications_Adaptive_req (void)ComSer_get_ExteriorLight_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_notifications_Adaptive) LdComIPdu_RPC_ExteriorLight_notifications_ICAS3_IVI_req (void)ComSer_get_ExteriorLight_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_notifications_ICAS3_IVI) LdComIPdu_RPC_ExteriorLight_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_ExteriorLight_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_ExteriorLight_notifications_ConMod_NAD_req (void)ComSer_get_ExteriorLight_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_notifications_ConMod_NAD) LdComIPdu_RPC_ExteriorLight_notifications_Java_req (void)ComSer_get_ExteriorLight_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_notifications_Java) LdComIPdu_RPC_ExteriorLight_info_Adaptive_req (void)ComSer_get_ExteriorLight_info(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_info_Adaptive) LdComIPdu_RPC_ExteriorLight_info_ICAS3_IVI_req (void)ComSer_get_ExteriorLight_info(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_info_ICAS3_IVI) LdComIPdu_RPC_ExteriorLight_info_ICAS3_ZR_TOP_req (void)ComSer_get_ExteriorLight_info(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_info_ICAS3_ZR_TOP) LdComIPdu_RPC_ExteriorLight_info_ConMod_NAD_req (void)ComSer_get_ExteriorLight_info(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_info_ConMod_NAD) LdComIPdu_RPC_ExteriorLight_info_Java_req (void)ComSer_get_ExteriorLight_info(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_info_Java) LdComIPdu_RPC_ExteriorLight_lightButtonModules_Adaptive_req (void)ComSer_get_ExteriorLight_lightButtonModules(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightButtonModules_Adaptive) LdComIPdu_RPC_ExteriorLight_lightButtonModules_ICAS3_IVI_req (void)ComSer_get_ExteriorLight_lightButtonModules(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightButtonModules_ICAS3_IVI) LdComIPdu_RPC_ExteriorLight_lightButtonModules_ICAS3_ZR_TOP_req (void)ComSer_get_ExteriorLight_lightButtonModules(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightButtonModules_ICAS3_ZR_TOP) LdComIPdu_RPC_ExteriorLight_lightButtonModules_ConMod_NAD_req (void)ComSer_get_ExteriorLight_lightButtonModules(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightButtonModules_ConMod_NAD) LdComIPdu_RPC_ExteriorLight_lightButtonModules_Java_req (void)ComSer_get_ExteriorLight_lightButtonModules(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorLight_lightButtonModules_Java) LdComIPdu_RPC_GNSS_positions_Adaptive_req (void)ComSer_get_GNSS_positions(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positions_Adaptive) LdComIPdu_RPC_GNSS_positions_ICAS3_IVI_req (void)ComSer_get_GNSS_positions(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positions_ICAS3_IVI) LdComIPdu_RPC_GNSS_positions_ConMod_NAD_req (void)ComSer_get_GNSS_positions(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positions_ConMod_NAD) LdComIPdu_RPC_GNSS_positions_ConMod_V2X_req (void)ComSer_get_GNSS_positions(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positions_ConMod_V2X) LdComIPdu_RPC_GNSS_positions_Java_req (void)ComSer_get_GNSS_positions(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positions_Java) LdComIPdu_RPC_GNSS_positions_OCU_req (void)ComSer_get_GNSS_positions(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positions_OCU) LdComIPdu_RPC_GNSS_posGnssSatInfos_Adaptive_req (void)ComSer_get_GNSS_posGnssSatInfos(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_posGnssSatInfos_Adaptive) LdComIPdu_RPC_GNSS_posGnssSatInfos_ICAS3_IVI_req (void)ComSer_get_GNSS_posGnssSatInfos(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_posGnssSatInfos_ICAS3_IVI) LdComIPdu_RPC_GNSS_posGnssSatInfos_ConMod_NAD_req (void)ComSer_get_GNSS_posGnssSatInfos(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_posGnssSatInfos_ConMod_NAD) LdComIPdu_RPC_GNSS_posGnssSatInfos_ConMod_V2X_req (void)ComSer_get_GNSS_posGnssSatInfos(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_posGnssSatInfos_ConMod_V2X) LdComIPdu_RPC_GNSS_posGnssSatInfos_Java_req (void)ComSer_get_GNSS_posGnssSatInfos(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_posGnssSatInfos_Java) LdComIPdu_RPC_GNSS_posGnssSatInfos_OCU_req (void)ComSer_get_GNSS_posGnssSatInfos(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_posGnssSatInfos_OCU) LdComIPdu_RPC_GNSS_positionsQuality_Adaptive_req (void)ComSer_get_GNSS_positionsQuality(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positionsQuality_Adaptive) LdComIPdu_RPC_GNSS_positionsQuality_ICAS3_IVI_req (void)ComSer_get_GNSS_positionsQuality(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positionsQuality_ICAS3_IVI) LdComIPdu_RPC_GNSS_positionsQuality_ConMod_NAD_req (void)ComSer_get_GNSS_positionsQuality(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positionsQuality_ConMod_NAD) LdComIPdu_RPC_GNSS_positionsQuality_ConMod_V2X_req (void)ComSer_get_GNSS_positionsQuality(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positionsQuality_ConMod_V2X) LdComIPdu_RPC_GNSS_positionsQuality_Java_req (void)ComSer_get_GNSS_positionsQuality(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positionsQuality_Java) LdComIPdu_RPC_GNSS_positionsQuality_OCU_req (void)ComSer_get_GNSS_positionsQuality(request_id, SoAdConf_SoAdPduRoute_RPC_GNSS_positionsQuality_OCU) LdComIPdu_RPC_HighVoltageCoordinator_notifications_Adaptive_req (void)ComSer_get_HighVoltageCoordinator_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_HighVoltageCoordinator_notifications_Adaptive) LdComIPdu_RPC_HighVoltageCoordinator_notifications_Java_req (void)ComSer_get_HighVoltageCoordinator_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_HighVoltageCoordinator_notifications_Java) LdComIPdu_RPC_Immobilizer_info_Adaptive_req (void)ComSer_get_Immobilizer_info(request_id, SoAdConf_SoAdPduRoute_RPC_Immobilizer_info_Adaptive) LdComIPdu_RPC_Immobilizer_info_ICAS3_req (void)ComSer_get_Immobilizer_info(request_id, SoAdConf_SoAdPduRoute_RPC_Immobilizer_info_ICAS3) LdComIPdu_RPC_Immobilizer_info_Java_req (void)ComSer_get_Immobilizer_info(request_id, SoAdConf_SoAdPduRoute_RPC_Immobilizer_info_Java) LdComIPdu_RPC_Immobilizer_notifications_Adaptive_req (void)ComSer_get_Immobilizer_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Immobilizer_notifications_Adaptive) LdComIPdu_RPC_Immobilizer_notifications_ICAS3_req (void)ComSer_get_Immobilizer_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Immobilizer_notifications_ICAS3) LdComIPdu_RPC_Immobilizer_notifications_Java_req (void)ComSer_get_Immobilizer_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Immobilizer_notifications_Java) LdComIPdu_RPC_ParkingBrake_notifications_Adaptive_req (void)ComSer_get_ParkingBrake_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_notifications_Adaptive) LdComIPdu_RPC_ParkingBrake_notifications_ICAS3_req (void)ComSer_get_ParkingBrake_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_notifications_ICAS3) LdComIPdu_RPC_ParkingBrake_notifications_ConMod_NAD_req (void)ComSer_get_ParkingBrake_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_notifications_ConMod_NAD) LdComIPdu_RPC_ParkingBrake_notifications_Java_req (void)ComSer_get_ParkingBrake_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_notifications_Java) LdComIPdu_RPC_ParkingBrake_status_Adaptive_req (void)ComSer_get_ParkingBrake_status(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_status_Adaptive) LdComIPdu_RPC_ParkingBrake_status_ICAS3_req (void)ComSer_get_ParkingBrake_status(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_status_ICAS3) LdComIPdu_RPC_ParkingBrake_status_ConMod_NAD_req (void)ComSer_get_ParkingBrake_status(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_status_ConMod_NAD) LdComIPdu_RPC_ParkingBrake_status_Java_req (void)ComSer_get_ParkingBrake_status(request_id, SoAdConf_SoAdPduRoute_RPC_ParkingBrake_status_Java) LdComIPdu_RPC_Powertrain_notifications_Adaptive_req (void)ComSer_get_Powertrain_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_notifications_Adaptive) LdComIPdu_RPC_Powertrain_notifications_ICAS3_IVI_req (void)ComSer_get_Powertrain_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_notifications_ICAS3_IVI) LdComIPdu_RPC_Powertrain_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_Powertrain_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_Powertrain_notifications_ConMod_NAD_req (void)ComSer_get_Powertrain_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_notifications_ConMod_NAD) LdComIPdu_RPC_Powertrain_notifications_ConMod_V2X_req (void)ComSer_get_Powertrain_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_notifications_ConMod_V2X) LdComIPdu_RPC_Powertrain_notifications_Java_req (void)ComSer_get_Powertrain_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_notifications_Java) LdComIPdu_RPC_Powertrain_displayValues_Adaptive_req (void)ComSer_get_Powertrain_displayValues(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_displayValues_Adaptive) LdComIPdu_RPC_Powertrain_displayValues_ICAS3_IVI_req (void)ComSer_get_Powertrain_displayValues(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_displayValues_ICAS3_IVI) LdComIPdu_RPC_Powertrain_displayValues_ICAS3_ZR_TOP_req (void)ComSer_get_Powertrain_displayValues(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_displayValues_ICAS3_ZR_TOP) LdComIPdu_RPC_Powertrain_displayValues_ConMod_NAD_req (void)ComSer_get_Powertrain_displayValues(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_displayValues_ConMod_NAD) LdComIPdu_RPC_Powertrain_displayValues_ConMod_V2X_req (void)ComSer_get_Powertrain_displayValues(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_displayValues_ConMod_V2X) LdComIPdu_RPC_Powertrain_displayValues_Java_req (void)ComSer_get_Powertrain_displayValues(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_displayValues_Java) LdComIPdu_RPC_Powertrain_status_Adaptive_req (void)ComSer_get_Powertrain_status(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_status_Adaptive) LdComIPdu_RPC_Powertrain_status_ICAS3_IVI_req (void)ComSer_get_Powertrain_status(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_status_ICAS3_IVI) LdComIPdu_RPC_Powertrain_status_ICAS3_ZR_TOP_req (void)ComSer_get_Powertrain_status(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_status_ICAS3_ZR_TOP) LdComIPdu_RPC_Powertrain_status_ConMod_NAD_req (void)ComSer_get_Powertrain_status(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_status_ConMod_NAD) LdComIPdu_RPC_Powertrain_status_ConMod_V2X_req (void)ComSer_get_Powertrain_status(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_status_ConMod_V2X) LdComIPdu_RPC_Powertrain_status_Java_req (void)ComSer_get_Powertrain_status(request_id, SoAdConf_SoAdPduRoute_RPC_Powertrain_status_Java) LdComIPdu_RPC_VehicleBasicData_installations_ICAS3_ZR_TOP_req (void)ComSer_get_VehicleBasicData_installations(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_installations_ICAS3_ZR_TOP) LdComIPdu_RPC_VehicleBasicData_installations_ConMod_NAD_req (void)ComSer_get_VehicleBasicData_installations(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_installations_ConMod_NAD) LdComIPdu_RPC_VehicleBasicData_installations_Java_req (void)ComSer_get_VehicleBasicData_installations(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_installations_Java) LdComIPdu_RPC_VehicleBasicData_installations_OCU_req (void)ComSer_get_VehicleBasicData_installations(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_installations_OCU) LdComIPdu_RPC_VehicleBasicData_variants_ICAS3_ZR_TOP_req (void)ComSer_get_VehicleBasicData_variants(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_variants_ICAS3_ZR_TOP) LdComIPdu_RPC_VehicleBasicData_variants_ConMod_NAD_req (void)ComSer_get_VehicleBasicData_variants(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_variants_ConMod_NAD) LdComIPdu_RPC_VehicleBasicData_variants_Java_req (void)ComSer_get_VehicleBasicData_variants(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_variants_Java) LdComIPdu_RPC_VehicleBasicData_variants_OCU_req (void)ComSer_get_VehicleBasicData_variants(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_variants_OCU) LdComIPdu_RPC_VehicleBasicData_parameters_ICAS3_ZR_TOP_req (void)ComSer_get_VehicleBasicData_parameters(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_parameters_ICAS3_ZR_TOP) LdComIPdu_RPC_VehicleBasicData_parameters_ConMod_NAD_req (void)ComSer_get_VehicleBasicData_parameters(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_parameters_ConMod_NAD) LdComIPdu_RPC_VehicleBasicData_parameters_Java_req (void)ComSer_get_VehicleBasicData_parameters(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_parameters_Java) LdComIPdu_RPC_VehicleBasicData_parameters_OCU_req (void)ComSer_get_VehicleBasicData_parameters(request_id, SoAdConf_SoAdPduRoute_RPC_VehicleBasicData_parameters_OCU) LdComIPdu_RPC_VisualOdometry_visualPositions_ICAS3_IVI_req (void)ComSer_get_VisualOdometry_visualPositions(request_id, SoAdConf_SoAdPduRoute_RPC_VisualOdometry_visualPositions_ICAS3_IVI) LdComIPdu_RPC_VisualOdometry_visualPositions_ZR_TOP_req (void)ComSer_get_VisualOdometry_visualPositions(request_id, SoAdConf_SoAdPduRoute_RPC_VisualOdometry_visualPositions_ZR_TOP) LdComIPdu_RPC_VisualOdometry_anchorPoints_ICAS3_IVI_req (void)ComSer_get_VisualOdometry_anchorPoints(request_id, SoAdConf_SoAdPduRoute_RPC_VisualOdometry_anchorPoints_ICAS3_IVI) LdComIPdu_RPC_VisualOdometry_anchorPoints_ZR_TOP_req (void)ComSer_get_VisualOdometry_anchorPoints(request_id, SoAdConf_SoAdPduRoute_RPC_VisualOdometry_anchorPoints_ZR_TOP) LdComIPdu_RPC_EmergencyAssist_notifications_Adaptive (void)ComSer_get_EmergencyAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EmergencyAssist_notifications_Adaptive) LdComIPdu_RPC_EmergencyAssist_notifications_ICAS3 (void)ComSer_get_EmergencyAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EmergencyAssist_notifications_ICAS3) LdComIPdu_RPC_EmergencyAssist_notifications_Java (void)ComSer_get_EmergencyAssist_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_EmergencyAssist_notifications_Java) LdComIPdu_UnitMaster_units (void)Rte_Read_UnitMaster_units(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION,request_id) LdComIPdu_Positioning_positions (void)Rte_Read_Positioning_positions(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION,request_id) LdComIPdu_Positioning_posMapInfo (void)Rte_Read_Positioning_posMapInfo(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION,request_id) LdComIPdu_RPC_DigitalKey_notifications_Adaptive_req (void)ComSer_get_DigitalKey_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DigitalKey_notifications_Adaptive) LdComIPdu_RPC_DigitalKey_notifications_Java_req (void)ComSer_get_DigitalKey_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_DigitalKey_notifications_Java) LdComIPdu_RPC_Distance_distances_Adaptive_req (void)ComSer_get_Distance_distances(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_distances_Adaptive) LdComIPdu_RPC_Distance_distances_ICAS3_req (void)ComSer_get_Distance_distances(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_distances_ICAS3) LdComIPdu_RPC_Distance_distances_Kombi_req (void)ComSer_get_Distance_distances(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_distances_Kombi) LdComIPdu_RPC_Distance_distances_ConMod_NAD_req (void)ComSer_get_Distance_distances(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_distances_ConMod_NAD) LdComIPdu_RPC_Distance_distances_Java_req (void)ComSer_get_Distance_distances(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_distances_Java) LdComIPdu_RPC_Distance_distances_OCU_req (void)ComSer_get_Distance_distances(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_distances_OCU) LdComIPdu_RPC_Distance_notifications_Adaptive_req (void)ComSer_get_Distance_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_notifications_Adaptive) LdComIPdu_RPC_Distance_notifications_ICAS3_req (void)ComSer_get_Distance_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_notifications_ICAS3) LdComIPdu_RPC_Distance_notifications_Kombi_req (void)ComSer_get_Distance_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_notifications_Kombi) LdComIPdu_RPC_Distance_notifications_ConMod_NAD_req (void)ComSer_get_Distance_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_notifications_ConMod_NAD) LdComIPdu_RPC_Distance_notifications_Java_req (void)ComSer_get_Distance_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_notifications_Java) LdComIPdu_RPC_Distance_notifications_OCU_req (void)ComSer_get_Distance_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_Distance_notifications_OCU) LdComIPdu_RPC_ExteriorSound_notifications_Adaptive_req (void)ComSer_get_ExteriorSound_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorSound_notifications_Adaptive) LdComIPdu_RPC_ExteriorSound_notifications_Java_req (void)ComSer_get_ExteriorSound_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ExteriorSound_notifications_Java) LdComIPdu_RPC_ClimateControl_notifications_req (void)ComSer_get_ClimateControl_notifications(request_id,SoAdConf_SoAdPduRoute_RPC_ClimateControl_notifications) LdComIPdu_RPC_ClimateControl_status_req (void)ComSer_get_ClimateControl_status(request_id,SoAdConf_SoAdPduRoute_RPC_ClimateControl_status) LdComIPdu_RPC_ClimateControl_notifications_Connect_req (void)ComSer_get_ClimateControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClimateControl_notifications_Connect) LdComIPdu_RPC_ClimateControl_status_Connect_req (void)ComSer_get_ClimateControl_status(request_id, SoAdConf_SoAdPduRoute_RPC_ClimateControl_status_Connect) LdComIPdu_RPC_ClimateControl_consumptions_Connect_req (void)ComSer_get_ClimateControl_consumptions(request_id, SoAdConf_SoAdPduRoute_RPC_ClimateControl_consumptions_Connect) LdComIPdu_RPC_SafetyBeltState_notifications_ICAS3_IVI_req (void)ComSer_get_SafetyBeltState_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_notifications_ICAS3_IVI) LdComIPdu_RPC_SafetyBeltState_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_SafetyBeltState_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_SafetyBeltState_notifications_Java_req (void)ComSer_get_SafetyBeltState_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_notifications_Java) LdComIPdu_RPC_SafetyBeltState_belts_ICAS3_IVI_req (void)ComSer_get_SafetyBeltState_belts(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_belts_ICAS3_IVI) LdComIPdu_RPC_SafetyBeltState_belts_ICAS3_ZR_TOP_req (void)ComSer_get_SafetyBeltState_belts(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_belts_ICAS3_ZR_TOP) LdComIPdu_RPC_SafetyBeltState_belts_Java_req (void)ComSer_get_SafetyBeltState_belts(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_belts_Java) LdComIPdu_RPC_SafetyBeltState_seatOccupancy_ICAS3_IVI_req (void)ComSer_get_SafetyBeltState_seatOccupancy(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_seatOccupancy_ICAS3_IVI) LdComIPdu_RPC_SafetyBeltState_seatOccupancy_ICAS3_ZR_TOP_req (void)ComSer_get_SafetyBeltState_seatOccupancy(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_seatOccupancy_ICAS3_ZR_TOP) LdComIPdu_RPC_SafetyBeltState_seatOccupancy_Java_req (void)ComSer_get_SafetyBeltState_seatOccupancy(request_id, SoAdConf_SoAdPduRoute_RPC_SafetyBeltState_seatOccupancy_Java) LdComIPdu_RPC_ClampControl_clamps_Adaptive_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_Adaptive) LdComIPdu_RPC_ClampControl_clamps_ICAS3_ZR_TOP_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ICAS3_ZR_TOP) LdComIPdu_RPC_ClampControl_clamps_ICAS3_IVI_MIB_TOP_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ICAS3_IVI_MIB_TOP) LdComIPdu_RPC_ClampControl_clamps_ConMod_NAD_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ConMod_NAD) LdComIPdu_RPC_ClampControl_clamps_ConMod_V2X_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_ConMod_V2X) LdComIPdu_RPC_ClampControl_clamps_Java_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_Java) LdComIPdu_RPC_ClampControl_clamps_OCU_req (void)ComSer_get_ClampControl_clamps(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_clamps_OCU) LdComIPdu_RPC_ClampControl_notifications_Adaptive_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_Adaptive) LdComIPdu_RPC_ClampControl_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_ClampControl_notifications_ICAS3_IVI_MIB_TOP_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ICAS3_IVI_MIB_TOP) LdComIPdu_RPC_ClampControl_notifications_ConMod_NAD_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ConMod_NAD) LdComIPdu_RPC_ClampControl_notifications_ConMod_V2X_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_ConMod_V2X) LdComIPdu_RPC_ClampControl_notifications_Java_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_Java) LdComIPdu_RPC_ClampControl_notifications_OCU_req (void)ComSer_get_ClampControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_notifications_OCU) LdComIPdu_RPC_ClampControl_specialStates_Adaptive_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_Adaptive) LdComIPdu_RPC_ClampControl_specialStates_ICAS3_ZR_TOP_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ICAS3_ZR_TOP) LdComIPdu_RPC_ClampControl_specialStates_ICAS3_IVI_MIB_TOP_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ICAS3_IVI_MIB_TOP) LdComIPdu_RPC_ClampControl_specialStates_ConMod_NAD_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ConMod_NAD) LdComIPdu_RPC_ClampControl_specialStates_ConMod_V2X_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_ConMod_V2X) LdComIPdu_RPC_ClampControl_specialStates_Java_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_Java) LdComIPdu_RPC_ClampControl_specialStates_OCU_req (void)ComSer_get_ClampControl_specialStates(request_id, SoAdConf_SoAdPduRoute_RPC_ClampControl_specialStates_OCU) LdComIPdu_RPC_UnitMaster_units_resp (void)Rte_Read_UnitMaster_units(PduInfoPtr->SduDataPtr,MESS_RESPONSE,request_id) LdComIPdu_RPC_Positioning_positions_resp (void)Rte_Read_Positioning_positions(PduInfoPtr->SduDataPtr,MESS_RESPONSE,request_id) LdComIPdu_RPC_Positioning_posMapInfo_resp (void)Rte_Read_Positioning_posMapInfo(PduInfoPtr->SduDataPtr,MESS_RESPONSE,request_id) LdComIPdu_LongitudinalCtrlHmiState_displayStates (void)Rte_Read_LongitudinalCtrlHmiState_displayStates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION,request_id) LdComIPdu_LongitudinalCtrlHmiState_displayStates_Response (void)Rte_Read_LongitudinalCtrlHmiState_displayStates(PduInfoPtr->SduDataPtr,MESS_RESPONSE,request_id) LdComIPdu_LongitudinalCtrlHmiState_functionSelection (void)Rte_Read_LongitudinalCtrlHmiState_functionSelection(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION,request_id) LdComIPdu_LongitudinalCtrlHmiState_functionSelection_Response (void)Rte_Read_LongitudinalCtrlHmiState_functionSelection(PduInfoPtr->SduDataPtr,MESS_RESPONSE,request_id) LdComIPdu_Temperature_temperatures (void)Rte_Read_Temperature_temperatures(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION,request_id) LdComIPdu_RPC_Temperature_temperatures_Response (void)Rte_Read_Temperature_temperatures(PduInfoPtr->SduDataPtr,MESS_RESPONSE,request_id) LdComIPdu_PnCAuth_availabilities (void)SOMEIP_deserialize_PlugAndChargeAuth_availabilities(PduInfoPtr->SduDataPtr, (uint16)PduInfoPtr->SduLength) LdComIPdu_PnCAuth_availabilities_Response (void)SOMEIP_deserialize_PlugAndChargeAuth_availabilities(PduInfoPtr->SduDataPtr, (uint16)PduInfoPtr->SduLength) LdComIPdu_PnCAuth_tlsRootCaCertificateInformations (void)Rte_Read_PnCAuth_tlsRootCaCertificateInformations(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_tlsRootCaCertificateInformations_Resp (void)Rte_Read_PnCAuth_tlsRootCaCertificateInformations(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_tlsRootCaCertificates (void)Rte_Read_PnCAuth_tlsRootCaCertificates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_tlsRootCaCertificates_Resp (void)Rte_Read_PnCAuth_tlsRootCaCertificates(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_moSub1CaCertificates (void)Rte_Read_PnCAuth_moSub1CaCertificates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_moSub1CaCertificates_Resp (void)Rte_Read_PnCAuth_moSub1CaCertificates(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_moSub2CaCertificates (void)Rte_Read_PnCAuth_moSub2CaCertificates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_moSub2CaCertificates_Resp (void)Rte_Read_PnCAuth_moSub2CaCertificates(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_contractCertificates (void)Rte_Read_PnCAuth_contractCertificates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_contractCertificates_Resp (void)Rte_Read_PnCAuth_contractCertificates(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_vehicleCertificates (void)Rte_Read_PnCAuth_vehicleCertificates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_vehicleCertificates_Resp (void)Rte_Read_PnCAuth_vehicleCertificates(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_signChallenges (void)Rte_Read_PnCAuth_signChallenges(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_signChallenges_Resp (void)Rte_Read_PnCAuth_signChallenges(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_PnCAuth_reportUnknownRootCertificates (void)Rte_Read_PnCAuth_reportUnknownRootCertificates(PduInfoPtr->SduDataPtr,MESS_NOTIFICATION) LdComIPdu_PnCAuth_reportUnknownRootCertificates_Resp (void)Rte_Read_PnCAuth_reportUnknownRootCertificates(PduInfoPtr->SduDataPtr,MESS_RESPONSE) LdComIPdu_RPC_PreCrash_notifications_Adaptive_req (void)ComSer_get_PreCrash_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_PreCrash_notifications_Adaptive) LdComIPdu_RPC_PreCrash_notifications_Java_req (void)ComSer_get_PreCrash_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_PreCrash_notifications_Java) LdComIPdu_RPC_CruiseControl_notifications_Adaptive_req (void)ComSer_get_CruiseControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_notifications_Adaptive) LdComIPdu_RPC_CruiseControl_notifications_ICAS3_ZR_TOP_req (void)ComSer_get_CruiseControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_notifications_ICAS3_ZR_TOP) LdComIPdu_RPC_CruiseControl_notifications_ConMod_V2X_req (void)ComSer_get_CruiseControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_notifications_ConMod_V2X) LdComIPdu_RPC_CruiseControl_notifications_Java_req (void)ComSer_get_CruiseControl_notifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_notifications_Java) LdComIPdu_RPC_CruiseControl_speedLimitInfo_Adaptive_req (void)ComSer_get_CruiseControl_speedLimitInfo(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_speedLimitInfo_Adaptive) LdComIPdu_RPC_CruiseControl_speedLimitInfo_ICAS3_ZR_TOP_req (void)ComSer_get_CruiseControl_speedLimitInfo(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_speedLimitInfo_ICAS3_ZR_TOP) LdComIPdu_RPC_CruiseControl_speedLimitInfo_ConMod_V2X_req (void)ComSer_get_CruiseControl_speedLimitInfo(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_speedLimitInfo_ConMod_V2X) LdComIPdu_RPC_CruiseControl_speedLimitInfo_Java_req (void)ComSer_get_CruiseControl_speedLimitInfo(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_speedLimitInfo_Java) LdComIPdu_RPC_CruiseControl_systemStatusForHMI_Adaptive_req (void)ComSer_get_CruiseControl_systemStatusForHMI(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_systemStatusForHMI_Adaptive) LdComIPdu_RPC_CruiseControl_systemStatusForHMI_ICAS3_ZR_TOP_req (void)ComSer_get_CruiseControl_systemStatusForHMI(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_systemStatusForHMI_ICAS3_ZR_TOP) LdComIPdu_RPC_CruiseControl_systemStatusForHMI_ConMod_V2X_req (void)ComSer_get_CruiseControl_systemStatusForHMI(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_systemStatusForHMI_ConMod_V2X) LdComIPdu_RPC_CruiseControl_systemStatusForHMI_Java_req (void)ComSer_get_CruiseControl_systemStatusForHMI(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_systemStatusForHMI_Java) LdComIPdu_RPC_CruiseControl_functionOnDemandStates_Adaptive_req (void)ComSer_get_CruiseControl_functionOnDemandStates(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_functionOnDemandStates_Adaptive) LdComIPdu_RPC_CruiseControl_functionOnDemandStates_ICAS3_ZR_TOP_req (void)ComSer_get_CruiseControl_functionOnDemandStates(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_functionOnDemandStates_ICAS3_ZR_TOP) LdComIPdu_RPC_CruiseControl_functionOnDemandStates_ConMod_V2X_req (void)ComSer_get_CruiseControl_functionOnDemandStates(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_functionOnDemandStates_ConMod_V2X) LdComIPdu_RPC_CruiseControl_functionOnDemandStates_Java_req (void)ComSer_get_CruiseControl_functionOnDemandStates(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_functionOnDemandStates_Java) LdComIPdu_RPC_CruiseControl_parameterizedNotifications_Adaptive_req (void)ComSer_get_CruiseControl_parameterizedNotifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_parameterizedNotifications_Adaptive) LdComIPdu_RPC_CruiseControl_parameterizedNotifications_ICAS3_ZR_TOP_req (void)ComSer_get_CruiseControl_parameterizedNotifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_parameterizedNotifications_ICAS3_ZR_TOP) LdComIPdu_RPC_CruiseControl_parameterizedNotifications_ConMod_V2X_req (void)ComSer_get_CruiseControl_parameterizedNotifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_parameterizedNotifications_ConMod_V2X) LdComIPdu_RPC_CruiseControl_parameterizedNotifications_Java_req (void)ComSer_get_CruiseControl_parameterizedNotifications(request_id, SoAdConf_SoAdPduRoute_RPC_CruiseControl_parameterizedNotifications_Java) LdComIPdu_RPC_FunctionEnabling_functionEnablingCodes_Java_req (void)MiniComServ_get_FunctionEnabling_functionEnablingCodes(request_id, SoAdConf_SoAdPduRoute_RPC_FunctionEnabling_functionEnablingCodes_Java) LdComIPdu_RPC_FunctionEnabling_functionEnablingCodes_Java_setter_req (void)MiniComServ_set_FunctionEnabling_functionEnablingCodes((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_FunctionEnabling_functionEnablingCodes_Java_setter) LdComIPdu_RPC_FunctionEnabling_baseReports_Java_req (void)MiniComServ_get_FunctionEnabling_baseReports(request_id, SoAdConf_SoAdPduRoute_RPC_FunctionEnabling_baseReports_Java) LdComIPdu_RPC_FunctionEnabling_activationResults_Java_req (void)MiniComServ_get_FunctionEnabling_activationResults(request_id, SoAdConf_SoAdPduRoute_RPC_FunctionEnabling_activationResults_Java) LdComIPdu_RPC_FunctionEnabling_functionEnablingStatus_Java_req (void)MiniComServ_get_FunctionEnabling_functionEnablingStatus(request_id, SoAdConf_SoAdPduRoute_RPC_FunctionEnabling_functionEnablingStatus_Java) LdComIPdu_RPC_OccupantPresence_driverPresenceStatus_ICAS3_IVI_req (void)ComSer_get_OccupantPresence_driverPresenceStatus(request_id, SoAdConf_SoAdPduRoute_RPC_OccupantPresence_driverPresenceStatus_ICAS3_IVI) LdComIPdu_RPC_OccupantPresence_driverPresenceStatus_ICAS3_ZR_TOP_req (void)ComSer_get_OccupantPresence_driverPresenceStatus(request_id, SoAdConf_SoAdPduRoute_RPC_OccupantPresence_driverPresenceStatus_ICAS3_ZR_TOP) LdComIPdu_RPC_OccupantPresence_driverPresenceStatus_Java_req (void)ComSer_get_OccupantPresence_driverPresenceStatus(request_id, SoAdConf_SoAdPduRoute_RPC_OccupantPresence_driverPresenceStatus_Java) LdComIPdu_RPC_Odometry_speeds_Adaptive_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_Adaptive) LdComIPdu_RPC_Odometry_speeds_ICAS3_IVI_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_ICAS3_IVI) LdComIPdu_RPC_Odometry_speeds_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_speeds_Kombi_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_Kombi) LdComIPdu_RPC_Odometry_speeds_ConMod_V2X_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_ConMod_V2X) LdComIPdu_RPC_Odometry_speeds_Java_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_Java) LdComIPdu_RPC_Odometry_speeds_DDA_req (void)MiniComServ_get_Odometry_speeds(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_speeds_DDA) LdComIPdu_RPC_Odometry_velocities_Adaptive_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_Adaptive) LdComIPdu_RPC_Odometry_velocities_ICAS3_IVI_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_ICAS3_IVI) LdComIPdu_RPC_Odometry_velocities_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_velocities_Kombi_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_Kombi) LdComIPdu_RPC_Odometry_velocities_ConMod_V2X_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_ConMod_V2X) LdComIPdu_RPC_Odometry_velocities_Java_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_Java) LdComIPdu_RPC_Odometry_velocities_DDA_req (void)MiniComServ_get_Odometry_velocities(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_velocities_DDA) LdComIPdu_RPC_Odometry_pose2D_Adaptive_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_Adaptive) LdComIPdu_RPC_Odometry_pose2D_ICAS3_IVI_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_ICAS3_IVI) LdComIPdu_RPC_Odometry_pose2D_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_pose2D_Kombi_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_Kombi) LdComIPdu_RPC_Odometry_pose2D_ConMod_V2X_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_ConMod_V2X) LdComIPdu_RPC_Odometry_pose2D_Java_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_Java) LdComIPdu_RPC_Odometry_pose2D_DDA_req (void)MiniComServ_get_Odometry_pose2D(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_pose2D_DDA) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_Adaptive_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_Adaptive) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_ICAS3_IVI_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_ICAS3_IVI) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_Kombi_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_Kombi) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_ConMod_V2X_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_ConMod_V2X) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_Java_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_Java) LdComIPdu_RPC_Odometry_additionalVehicleMotionInformations_DDA_req (void)MiniComServ_get_Odometry_additionalVehicleMotionInformations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_additionalVehicleMotionInformations_DDA) LdComIPdu_RPC_Odometry_wheelCorrections_Adaptive_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_Adaptive) LdComIPdu_RPC_Odometry_wheelCorrections_ICAS3_IVI_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_ICAS3_IVI) LdComIPdu_RPC_Odometry_wheelCorrections_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_wheelCorrections_Kombi_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_Kombi) LdComIPdu_RPC_Odometry_wheelCorrections_ConMod_V2X_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_ConMod_V2X) LdComIPdu_RPC_Odometry_wheelCorrections_Java_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_Java) LdComIPdu_RPC_Odometry_wheelCorrections_DDA_req (void)MiniComServ_get_Odometry_wheelCorrections(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_wheelCorrections_DDA) LdComIPdu_RPC_Odometry_accelerations_Adaptive_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_Adaptive) LdComIPdu_RPC_Odometry_accelerations_ICAS3_IVI_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_ICAS3_IVI) LdComIPdu_RPC_Odometry_accelerations_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_accelerations_Kombi_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_Kombi) LdComIPdu_RPC_Odometry_accelerations_ConMod_V2X_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_ConMod_V2X) LdComIPdu_RPC_Odometry_accelerations_Java_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_Java) LdComIPdu_RPC_Odometry_accelerations_DDA_req (void)MiniComServ_get_Odometry_accelerations(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_accelerations_DDA) LdComIPdu_RPC_Odometry_angularRates_Adaptive_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_Adaptive) LdComIPdu_RPC_Odometry_angularRates_ICAS3_IVI_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_ICAS3_IVI) LdComIPdu_RPC_Odometry_angularRates_ICAS3_ZR_TOP_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_ICAS3_ZR_TOP) LdComIPdu_RPC_Odometry_angularRates_Kombi_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_Kombi) LdComIPdu_RPC_Odometry_angularRates_ConMod_V2X_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_ConMod_V2X) LdComIPdu_RPC_Odometry_angularRates_Java_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_Java) LdComIPdu_RPC_Odometry_angularRates_DDA_req (void)MiniComServ_get_Odometry_angularRates(request_id, SoAdConf_SoAdPduRoute_RPC_Odometry_angularRates_DDA) LdComIPdu_RPC_ChargeTimeManager_chargeTimeCalculations_ICAS3_IVI_req (void)ComSer_get_ChargeTimeManager_chargeTimeCalculations(request_id, SoAdConf_SoAdPduRoute_RPC_ChargeTimeManager_chargeTimeCalculations_ICAS3_IVI) LdComIPdu_RPC_ChargeTimeManager_chargeTimeCalculations_ICAS3_IVI_setter_req (void)ComSer_get_ChargeTimeManager_chargeTimeCalculations(request_id, SoAdConf_SoAdPduRoute_RPC_ChargeTimeManager_chargeTimeCalculations_ICAS3_IVI_setter_resp) LdComIPdu_RPC_ChargingManagementCore_batteryCareModes_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_batteryCareModes(request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_batteryCareModes_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_batteryCareModes_Connect_req (void)MiniComServ_get_ChargingManagementCore_batteryCareModes(request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_batteryCareModes_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_batteryCareModes_Kombi_req (void)MiniComServ_get_ChargingManagementCore_batteryCareModes(request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_batteryCareModes_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_bidirectionalChargingModes_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_bidirectionalChargingModes(request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_bidirectionalChargingModes_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_bidirectionalChargingModes_Connect_req (void)MiniComServ_get_ChargingManagementCore_bidirectionalChargingModes(request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_bidirectionalChargingModes_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_bidirectionalChargingModes_Kombi_req (void)MiniComServ_get_ChargingManagementCore_bidirectionalChargingModes(request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_bidirectionalChargingModes_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_immediateChargingOptions_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_immediateChargingOptions(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_immediateChargingOptions_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_immediateChargingOptions_Connect_req (void)MiniComServ_get_ChargingManagementCore_immediateChargingOptions(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_immediateChargingOptions_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_immediateChargingOptions_Kombi_req (void)MiniComServ_get_ChargingManagementCore_immediateChargingOptions(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_immediateChargingOptions_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_chargingProcessInformation_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_chargingProcessInformation(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_chargingProcessInformation_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_chargingProcessInformation_Connect_req (void)MiniComServ_get_ChargingManagementCore_chargingProcessInformation(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_chargingProcessInformation_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_chargingProcessInformation_Kombi_req (void)MiniComServ_get_ChargingManagementCore_chargingProcessInformation(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_chargingProcessInformation_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_chargingPlugs_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_chargingPlugs(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_chargingPlugs_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_chargingPlugs_Connect_req (void)MiniComServ_get_ChargingManagementCore_chargingPlugs(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_chargingPlugs_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_chargingPlugs_Kombi_req (void)MiniComServ_get_ChargingManagementCore_chargingPlugs(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_chargingPlugs_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_immediateActions_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_immediateActions(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_immediateActions_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_immediateActions_Connect_req (void)MiniComServ_get_ChargingManagementCore_immediateActions(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_immediateActions_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_immediateActions_Kombi_req (void)MiniComServ_get_ChargingManagementCore_immediateActions(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_immediateActions_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_notificationMarkers_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_notificationMarkers(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_notificationMarkers_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_notificationMarkers_Connect_req (void)MiniComServ_get_ChargingManagementCore_notificationMarkers(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_notificationMarkers_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_notificationMarkers_Kombi_req (void)MiniComServ_get_ChargingManagementCore_notificationMarkers(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_notificationMarkers_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_notifications_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_notifications(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_notifications_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_notifications_Connect_req (void)MiniComServ_get_ChargingManagementCore_notifications(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_notifications_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_notifications_Kombi_req (void)MiniComServ_get_ChargingManagementCore_notifications(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_notifications_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_pastErrorInformation_Adaptive_Set_req (void)MiniComServ_set_ChargingManagementCore_pastErrorInformation((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_pastErrorInformation_Adaptive_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_pastErrorInformation_Connect_Set_req (void)MiniComServ_set_ChargingManagementCore_pastErrorInformation((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_pastErrorInformation_Connect_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_pastErrorInformation_Kombi_Set_req (void)MiniComServ_set_ChargingManagementCore_pastErrorInformation((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_pastErrorInformation_Kombi_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_pastErrorInformation_Adaptive_Get_req (void)MiniComServ_get_ChargingManagementCore_pastErrorInformation(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_pastErrorInformation_Adaptive_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_pastErrorInformation_Connect_Get_req (void)MiniComServ_get_ChargingManagementCore_pastErrorInformation(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_pastErrorInformation_Connect_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_pastErrorInformation_Kombi_Get_req (void)MiniComServ_get_ChargingManagementCore_pastErrorInformation(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_pastErrorInformation_Kombi_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_views_Adaptive_Set_req (void)MiniComServ_set_ChargingManagementCore_views((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_views_Adaptive_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_views_Connect_Set_req (void)MiniComServ_set_ChargingManagementCore_views((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_views_Connect_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_views_Kombi_Set_req (void)MiniComServ_set_ChargingManagementCore_views((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_views_Kombi_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_views_Adaptive_Get_req (void)MiniComServ_get_ChargingManagementCore_views(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_views_Adaptive_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_views_Connect_Get_req (void)MiniComServ_get_ChargingManagementCore_views(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_views_Connect_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_views_Kombi_Get_req (void)MiniComServ_get_ChargingManagementCore_views(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_views_Kombi_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_oruUpdateApprovals_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_oruUpdateApprovals(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_oruUpdateApprovals_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_oruUpdateApprovals_Connect_req (void)MiniComServ_get_ChargingManagementCore_oruUpdateApprovals(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_oruUpdateApprovals_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_oruUpdateApprovals_Kombi_req (void)MiniComServ_get_ChargingManagementCore_oruUpdateApprovals(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_oruUpdateApprovals_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_switchControls_Adaptive_Set_req (void)MiniComServ_set_ChargingManagementCore_switchControls((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_switchControls_Adaptive_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_switchControls_Connect_Set_req (void)MiniComServ_set_ChargingManagementCore_switchControls((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_switchControls_Connect_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_switchControls_Kombi_Set_req (void)MiniComServ_set_ChargingManagementCore_switchControls((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_switchControls_Kombi_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_switchControls_Adaptive_Get_req (void)MiniComServ_get_ChargingManagementCore_switchControls(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_switchControls_Adaptive_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_switchControls_Connect_Get_req (void)MiniComServ_get_ChargingManagementCore_switchControls(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_switchControls_Connect_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_switchControls_Kombi_Get_req (void)MiniComServ_get_ChargingManagementCore_switchControls(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_switchControls_Kombi_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_valueControls_Adaptive_Set_req (void)MiniComServ_set_ChargingManagementCore_valueControls((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueControls_Adaptive_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_valueControls_Connect_Set_req (void)MiniComServ_set_ChargingManagementCore_valueControls((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueControls_Connect_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_valueControls_Kombi_Set_req (void)MiniComServ_set_ChargingManagementCore_valueControls((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueControls_Kombi_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_valueControls_Adaptive_Get_req (void)MiniComServ_get_ChargingManagementCore_valueControls(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueControls_Adaptive_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_valueControls_Connect_Get_req (void)MiniComServ_get_ChargingManagementCore_valueControls(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueControls_Connect_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_valueControls_Kombi_Get_req (void)MiniComServ_get_ChargingManagementCore_valueControls(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueControls_Kombi_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_valueIndications_Adaptive_req (void)MiniComServ_get_ChargingManagementCore_valueIndications(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueIndications_Adaptive_resp) LdComIPdu_RPC_ChargingManagementCore_valueIndications_Connect_req (void)MiniComServ_get_ChargingManagementCore_valueIndications(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueIndications_Connect_resp) LdComIPdu_RPC_ChargingManagementCore_valueIndications_Kombi_req (void)MiniComServ_get_ChargingManagementCore_valueIndications(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_valueIndications_Kombi_resp) LdComIPdu_RPC_ChargingManagementCore_resetToFactoryData_Adaptive_Set_req (void)MiniComServ_set_ChargingManagementCore_resetToFactoryData((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_resetToFactoryData_Adaptive_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_resetToFactoryData_Connect_Set_req (void)MiniComServ_set_ChargingManagementCore_resetToFactoryData((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_resetToFactoryData_Connect_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_resetToFactoryData_Kombi_Set_req (void)MiniComServ_set_ChargingManagementCore_resetToFactoryData((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_resetToFactoryData_Kombi_Setter_resp) LdComIPdu_RPC_ChargingManagementCore_resetToFactoryData_Adaptive_Get_req (void)MiniComServ_get_ChargingManagementCore_resetToFactoryData(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_resetToFactoryData_Adaptive_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_resetToFactoryData_Connect_Get_req (void)MiniComServ_get_ChargingManagementCore_resetToFactoryData(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_resetToFactoryData_Connect_Getter_resp) LdComIPdu_RPC_ChargingManagementCore_resetToFactoryData_Kombi_Get_req (void)MiniComServ_get_ChargingManagementCore_resetToFactoryData(request_id,SoAdConf_SoAdPduRoute_RPC_ChargingManagementCore_resetToFactoryData_Kombi_Getter_resp) LdComIPdu_RPC_ContiUpdateCoordination_supplyVoltage_Adaptive_req (void)MiniComServ_get_ContiUpdateCoordination_supplyVoltage(request_id, SoAdConf_SoAdPduRoute_RPC_ContiUpdateCoordination_supplyVoltage_Adaptive) LdComIPdu_RPC_ContiUpdateCoordination_supplyVoltage_Java_req (void)MiniComServ_get_ContiUpdateCoordination_supplyVoltage(request_id, SoAdConf_SoAdPduRoute_RPC_ContiUpdateCoordination_supplyVoltage_Java) LdComIPdu_RPC_ContiUpdateCoordination_diagnosticInformation_Adaptive_req (void)MiniComServ_get_ContiUpdateCoordination_diagnosticInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ContiUpdateCoordination_diagnosticInformation_Adaptive) LdComIPdu_RPC_ContiUpdateCoordination_diagnosticInformation_Java_req (void)MiniComServ_get_ContiUpdateCoordination_diagnosticInformation(request_id, SoAdConf_SoAdPduRoute_RPC_ContiUpdateCoordination_diagnosticInformation_Java) LdComIPdu_RPC_PersonalizationSystem_slots_Java_req (void)MiniComServ_get_PersonalizationSystem_slots(request_id, SoAdConf_SoAdPduRoute_RPC_PersonalizationSystem_slots_Java) LdComIPdu_RPC_PersonalizationSystem_slots_Java_setter_req (void)MiniComServ_set_PersonalizationSystem_slots((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_PersonalizationSystem_slots_Java_setter) LdComIPdu_RPC_PersonalizationSystem_display_Java_req (void)MiniComServ_get_PersonalizationSystem_display(request_id, SoAdConf_SoAdPduRoute_RPC_PersonalizationSystem_display_Java) LdComIPdu_RPC_PersonalizationSystem_display_Java_setter_req (void)MiniComServ_set_PersonalizationSystem_display((PduInfoPtr->SduDataPtr), (uint16)PduInfoPtr->SduLength, request_id, SoAdConf_SoAdPduRoute_RPC_PersonalizationSystem_display_Java_setter) LdComIPdu_TripComputer_resets (void)Rte_Read_TripComputer_resets(PduInfoPtr->SduDataPtr, MESS_NOTIFICATION, request_id) Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_LdCom_RxIndication_0002 Traceabilitythis function is given by architectural requirments: ID_ArchiteckturalElement and satisfied following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_GW_18357; SWR_ICAS1_GW_3829. This function indicates a received I-PDU from a lower layer communication interface module.This function indicates a received I-PDU from a lower layer communication interface module. reentrant No thread safe Yes void RxPduId ID of the received I-PDU. PduInfoPtr Contains the length (SduLength) of the received I-PDU and a pointer to a buffer (SduDataPtr) containing the I-PDU.
References LdComIPduRxIndicationList, LdComIPduRxIndicationType::fun_ptr, LdComIPduRxIndicationMiniComServSetterList, LdComIPduRxIndicationMiniComServSetterType::fun_ptr, LdComIPduRxIndicationMiniComServSetterType::SoAdConf_SoAdPduRoute, LdComIPduRxIndicationRteReadList, LdComIPduRxIndicationRteType::fun_ptr, LdComIPduRxIndicationRteType::MessageType, LdComIPduRxIndicationSomeIPDeserializeList, LdComIPduRxIndicationSomeIPDeserializeType::fun_ptr, LdComIPduRxIndicationRteReadPncList, LdComIPduRxIndicationRteReadPncType::fun_ptr, LdComIPduRxIndicationRteReadPncType::MessageType.
Referenced by TEST_LdCom_RxIndication_ACC, TEST_LdCom_RxIndication_AWV, TEST_LdCom_RxIndication_Airbag, TEST_LdCom_RxIndication_CarBody, TEST_LdCom_RxIndication_CentralLocking, TEST_LdCom_RxIndication_ChargingManagementCore, TEST_LdCom_RxIndication_Chassis, TEST_LdCom_RxIndication_ClampControl, TEST_LdCom_RxIndication_ClimateControl, TEST_LdCom_RxIndication_ContiUpdateCoordination, TEST_LdCom_RxIndication_CruiseControl, TEST_LdCom_RxIndication_Damper, TEST_LdCom_RxIndication_DigitalKey, TEST_LdCom_RxIndication_Distance, TEST_LdCom_RxIndication_DrivePerformance, TEST_LdCom_RxIndication_DrivingRange, TEST_LdCom_RxIndication_EmergencyAssist, TEST_LdCom_RxIndication_ExteriorLight, TEST_LdCom_RxIndication_ExteriorSound, TEST_LdCom_RxIndication_EnergySystem, TEST_LdCom_RxIndication_FunctionEnabling, TEST_LdCom_RxIndication_GNS, TEST_LdCom_RxIndication_HighVoltageCoordinator, TEST_LdCom_RxIndication_Immobilizer, TEST_LdCom_RxIndication_LaneAssist, TEST_LdCom_RxIndication_LongitudinalCtrlHmiState, TEST_LdCom_RxIndication_OccupantPresence, TEST_LdCom_RxIndication_Odometry, TEST_LdCom_RxIndication_ParkingBrake, TEST_LdCom_RxIndication_PersonalizationSystem, TEST_LdCom_RxIndication_PlugAndChargeAuth, TEST_LdCom_RxIndication_Positioning, TEST_LdCom_RxIndication_Powertrain, TEST_LdCom_RxIndication_PreCrash, TEST_LdCom_RxIndication_SafetyBeltState, TEST_LdCom_RxIndication_SteeringAssist, TEST_LdCom_RxIndication_Temperature, TEST_LdCom_RxIndication_TravelAssist, TEST_LdCom_RxIndication_TripComputer, TEST_LdCom_RxIndication_UnitMaster, TEST_LdCom_RxIndication_VehicleBasicData, TEST_LdCom_RxIndication_VisualOdometry.
void LdCom_TxConfirmation(PduIdType TxPduId)
Std_ReturnType LdCom_TriggerTransmit(PduIdType TxPduId, PduInfoType *PduInfoPtr)
This function is called when an I-PDU shall be transmitted.
Check if the socket route is enabled. The initial notification for the PDU is requested. TxPduId ID of the I-PDU that is requested to be transmitted. PduInfoPtr Pointer to transmit buffer of L-PDU. Std_ReturnType standard API return type which is shared between the RTE and the BSW modules. GlobalsNone Input->Output-CorrelationInput include the id of the PDU to be transmitted and pointer to the payload buffer. Respective service handle callbacks are called. Configured TxPduId in Tresos Callback function for initial notification LdComIPdu_ACC_notifications ComSer_ACC_notifications_InitialNotificationRequested(); LdComIPdu_ACC_info ComSer_ACC_info_InitialNotificationRequested(); LdComIPdu_ACC_relevantObjects ComSer_ACC_relevantObjects_InitialNotificationRequested(); LdComIPdu_ACC_targetDistances ComSer_ACC_targetDistances_InitialNotificationRequested(); LdComIPdu_ACC_velocities ComSer_ACC_velocities_InitialNotificationRequested(); LdComIPdu_ACC_additionalInformation ComSer_ACC_additionalInformation_InitialNotificationRequested(); LdComIPdu_ACC_additionalRadarInformation ComSer_ACC_additionalRadarInformation_InitialNotificationRequested(); LdComIPdu_Airbag_notifications ComSer_Airbag_notifications_InitialNotificationRequested(); LdComIPdu_Airbag_crashInfo ComSer_Airbag_crashInfo_InitialNotificationRequested(); LdComIPdu_SteeringAssist_notifications ComSer_SteeringAssist_notifications_InitialNotificationRequested(); LdComIPdu_AWV_notifications ComSer_AWV_notifications_InitialNotificationRequested LdComIPdu_AWV_info ComSer_AWV_info_InitialNotificationRequested LdComIPdu_CarBody_doors ComSer_CarBody_doors_InitialNotificationRequested(); LdComIPdu_CarBody_hatchesAndTraps ComSer_CarBody_hatchesAndTraps_InitialNotificationRequested(); LdComIPdu_CentralLocking_lockStates ComSer_CentralLocking_lockStates_InitialNotificationRequested(); LdComIPdu_CentralLocking_safeStates ComSer_CentralLocking_safeStates_InitialNotificationRequested(); LdComIPdu_CentralLocking_info ComSer_CentralLocking_info_InitialNotificationRequested(); LdComIPdu_CentralLocking_notifications ComSer_CentralLocking_notifications_InitialNotificationRequested(); LdComIPdu_ChargeTimeManager_chargeTimeCalculations ComSer_ChargeTimeManager_chargeTimeCalculations_InitialNotificationRequested(); LdComIPdu_ChargingManagementCore_batteryCareModes MiniComServ_ChargingManagementCore_batteryCareModes_LdCom_Callout(); LdComIPdu_ChargingManagementCore_bidirectionalChargingModes MiniComServ_ChargingManagementCore_bidirectionalChargingModes_LdCom_Callout(); LdComIPdu_ChargingManagementCore_chargingPlugs MiniComServ_ChargingManagementCore_chargingPlugs_LdCom_Callout(); LdComIPdu_ChargingManagementCore_chargingProcessInformation MiniComServ_ChargingManagementCore_chargingProcessInformation_LdCom_Callout(); LdComIPdu_ChargingManagementCore_immediateActions MiniComServ_ChargingManagementCore_immediateActions_LdCom_Callout(); LdComIPdu_ChargingManagementCore_immediateChargingOptions MiniComServ_ChargingManagementCore_immediateChargingOptions_LdCom_Callout(); LdComIPdu_ChargingManagementCore_notificationMarkers MiniComServ_ChargingManagementCore_notificationMarkers_LdCom_Callout(); LdComIPdu_ChargingManagementCore_notifications MiniComServ_ChargingManagementCore_notifications_LdCom_Callout(); LdComIPdu_ChargingManagementCore_oruUpdateApprovals MiniComServ_ChargingManagementCore_oruUpdateApprovals_LdCom_Callout(); LdComIPdu_ChargingManagementCore_pastErrorInformation MiniComServ_ChargingManagementCore_pastErrorInformation_LdCom_Callout(); LdComIPdu_ChargingManagementCore_resetToFactoryData MiniComServ_ChargingManagementCore_resetToFactoryData_LdCom_Callout(); LdComIPdu_ChargingManagementCore_switchControls MiniComServ_ChargingManagementCore_switchControls_LdCom_Callout(); LdComIPdu_ChargingManagementCore_valueControls MiniComServ_ChargingManagementCore_valueControls_LdCom_Callout(); LdComIPdu_ChargingManagementCore_valueIndications MiniComServ_ChargingManagementCore_valueIndications_LdCom_Callout(); LdComIPdu_ChargingManagementCore_views MiniComServ_ChargingManagementCore_views_LdCom_Callout(); LdComIPdu_Chassis_axes ComSer_Chassis_axes_InitialNotificationRequested(); LdComIPdu_Chassis_espSystemInfo ComSer_Chassis_espSystemInfo_InitialNotificationRequested(); LdComIPdu_Chassis_notifications ComSer_Chassis_notifications_InitialNotificationRequested(); LdComIPdu_Chassis_velocityInfo ComSer_Chassis_velocityInfo_InitialNotificationRequested(); LdComIPdu_Chassis_wheels ComSer_Chassis_wheels_InitialNotificationRequested(); LdComIPdu_ClampControl_clamps ComSer_ClampControl_clamps_InitialNotificationRequested(); LdComIPdu_ClampControl_notifications ComSer_ClampControl_notifications_InitialNotificationRequested(); LdComIPdu_ClampControl_specialStates ComSer_ClampControl_specialStates_InitialNotificationRequested(); LdComIPdu_ClimateControl_consumptions ComSer_ClimateControl_consumptions_InitialNotificationRequested(); LdComIPdu_ClimateControl_notifications ComSer_ClimateControl_notifications_InitialNotificationRequested(); LdComIPdu_ClimateControl_status ComSer_ClimateControl_status_InitialNotificationRequested(); LdComIPdu_ContiUpdateCoordination_supplyVoltage MiniComServ_ContiUpdateCoordination_supplyVoltage_LdCom_Callout(); LdComIPdu_ContiUpdateCoordination_diagnosticInformation MiniComServ_ContiUpdateCoordination_diagnosticInformation_LdCom_Callout(); LdComIPdu_CruiseControl_notifications ComSer_CruiseControl_notifications_InitialNotificationRequested(); LdComIPdu_CruiseControl_speedLimitInfo ComSer_CruiseControl_speedLimitInfo_InitialNotificationRequested(); LdComIPdu_CruiseControl_systemStatusForHMI ComSer_CruiseControl_systemStatusForHMI_InitialNotificationRequested(); LdComIPdu_CruiseControl_functionOnDemandStates ComSer_CruiseControl_functionOnDemandStates_InitialNotificationRequested(); LdComIPdu_CruiseControl_parameterizedNotifications ComSer_CruiseControl_parameterizedNotifications_InitialNotificationRequested(); LdComIPdu_Damper_notifications ComSer_Damper_notifications_InitialNotificationRequested(); LdComIPdu_Damper_damperMonitorInfo ComSer_Damper_damperMonitorInfo_InitialNotificationRequested(); LdComIPdu_DigitalKey_notifications ComSer_DigitalKey_notifications_InitialNotificationRequested(); LdComIPdu_Distance_distances ComSer_Distance_distances_InitialNotificationRequested(); LdComIPdu_Distance_notifications ComSer_Distance_notifications_InitialNotificationRequested(); LdComIPdu_DrivePerformance_displayParameters ComSer_DrivePerformance_displayParameters_InitialNotificationRequested(); LdComIPdu_DrivingRange_notifications ComSer_DrivingRange_notifications_InitialNotificationRequested(); LdComIPdu_DrivingRange_ranges ComSer_DrivingRange_ranges_InitialNotificationRequested(); LdComIPdu_DrivingRange_status ComSer_DrivingRange_status_InitialNotificationRequested(); LdComIPdu_EmergencyAssist_notifications ComSer_EmergencyAssist_notifications_InitialNotificationRequested(); LdComIPdu_DrivingRange_rangeCalcConsumptions ComSer_DrivingRange_rangeCalcConsumptions_InitialNotificationRequested(); LdComIPdu_EnergySystem_notifications ComSer_EnergySystem_notifications_InitialNotificationRequested(); LdComIPdu_EnergySystem_highVoltageBatteries ComSer_EnergySystem_highVoltageBatteries_InitialNotificationRequested(); LdComIPdu_EnergySystem_lowVoltageBatteries ComSer_EnergySystem_lowVoltageBatteries_InitialNotificationRequested(); LdComIPdu_EnergySystem_lowVoltageSystemInfo ComSer_EnergySystem_lowVoltageSystemInfo_InitialNotificationRequested(); LdComIPdu_ExteriorLight_lightFunctions ComSer_ExteriorLight_lightFunctions_InitialNotificationRequested(); LdComIPdu_ExteriorLight_lamps ComSer_ExteriorLight_lamps_InitialNotificationRequested(); LdComIPdu_ExteriorLight_notifications ComSer_ExteriorLight_notifications_InitialNotificationRequested(); LdComIPdu_ExteriorLight_info ComSer_ExteriorLight_info_InitialNotificationRequested(); LdComIPdu_ExteriorLight_lightButtonModules ComSer_ExteriorLight_lightButtonModules_InitialNotificationRequested(); LdComIPdu_ExteriorSound_notifications ComSer_ExteriorSound_notifications_InitialNotificationRequested(); LdComIPdu_FunctionEnabling_functionEnablingCodes MiniComServ_FunctionEnabling_functionEnablingCodes_LdCom_Callout(); LdComIPdu_FunctionEnabling_baseReports MiniComServ_FunctionEnabling_baseReports_LdCom_Callout(); LdComIPdu_FunctionEnabling_activationResults MiniComServ_FunctionEnabling_activationResults_LdCom_Callout(); LdComIPdu_FunctionEnabling_functionEnablingStatus MiniComServ_FunctionEnabling_functionEnablingStatus_LdCom_Callout(); LdComIPdu_GNSS_positions ComSer_GNSS_positions_InitialNotificationRequested(); LdComIPdu_GNSS_posGnssSatInfos ComSer_GNSS_posGnssSatInfos_InitialNotificationRequested(); LdComIPdu_GNSS_positionsQuality ComSer_GNSS_positionsQuality_InitialNotificationRequested(); LdComIPdu_HighVoltageCoordinator_notifications ComSer_HighVoltageCoordinator_notifications_InitialNotificationRequested(); LdComIPdu_Immobilizer_info ComSer_Immobilizer_info_InitialNotificationRequested(); LdComIPdu_Immobilizer_notifications ComSer_Immobilizer_notifications_InitialNotificationRequested(); LdComIPdu_LaneAssist_notifications ComSer_LaneAssist_notifications_InitialNotificationRequested(); LdComIPdu_OccupantPresence_driverPresenceStatus ComSer_OccupantPresence_driverPresenceStatus_InitialNotificationRequested(); LdComIPdu_Odometry_speeds MiniComServ_Odometry_speeds_LdCom_Callout(); LdComIPdu_Odometry_velocities MiniComServ_Odometry_velocities_LdCom_Callout(); LdComIPdu_Odometry_pose2D MiniComServ_Odometry_pose2D_LdCom_Callout(); LdComIPdu_Odometry_additionalVehicleMotionInformations MiniComServ_Odometry_additionalVehicleMotionInformations_LdCom_Callout(); LdComIPdu_Odometry_wheelCorrections MiniComServ_Odometry_wheelCorrections_LdCom_Callout(); LdComIPdu_Odometry_accelerations MiniComServ_Odometry_accelerations_LdCom_Callout(); LdComIPdu_Odometry_angularRates MiniComServ_Odometry_angularRates_LdCom_Callout(); LdComIPdu_ParkingBrake_notifications ComSer_ParkingBrake_notifications_InitialNotificationRequested(); LdComIPdu_ParkingBrake_status ComSer_ParkingBrake_status_InitialNotificationRequested(); LdComIPdu_PersonalizationSystem_slots MiniComServ_PersonalizationSystem_slots_LdCom_Callout(); LdComIPdu_PersonalizationSystem_display MiniComServ_PersonalizationSystem_display_LdCom_Callout(); LdComIPdu_Powertrain_notifications ComSer_Powertrain_notifications_InitialNotificationRequested(); LdComIPdu_Powertrain_displayValues ComSer_Powertrain_displayValues_InitialNotificationRequested(); LdComIPdu_Powertrain_status ComSer_Powertrain_status_InitialNotificationRequested(); LdComIPdu_PreCrash_notifications ComSer_PreCrash_notifications_InitialNotificationRequested(); LdComIPdu_SafetyBeltState_notifications ComSer_SafetyBeltState_notifications_InitialNotificationRequested(); LdComIPdu_SafetyBeltState_belts ComSer_SafetyBeltState_belts_InitialNotificationRequested(); LdComIPdu_SafetyBeltState_seatOccupancy ComSer_SafetyBeltState_seatOccupancy_InitialNotificationRequested(); LdComIPdu_TravelAssist_notifications ComSer_TravelAssist_notifications_InitialNotificationRequested(); LdComIPdu_TravelAssist_lanes ComSer_TravelAssist_lanes_InitialNotificationRequested(); LdComIPdu_TravelAssist_curveParameters ComSer_TravelAssist_curveParameters_InitialNotificationRequested(); LdComIPdu_TravelAssist_info ComSer_TravelAssist_info_InitialNotificationRequested(); LdComIPdu_TravelAssist_relevantObjects ComSer_TravelAssist_relevantObjects_InitialNotificationRequested(); LdComIPdu_VehicleBasicData_installations ComSer_VehicleBasicData_installations_InitialNotificationRequested(); LdComIPdu_VehicleBasicData_variants ComSer_VehicleBasicData_variants_InitialNotificationRequested(); LdComIPdu_VehicleBasicData_parameters ComSer_VehicleBasicData_parameters_InitialNotificationRequested(); LdComIPdu_VisualOdometry_visualPositions ComSer_VisualOdometry_visualPositions_InitialNotificationRequested(); LdComIPdu_VisualOdometry_anchorPoints ComSer_VisualOdometry_anchorPoints_InitialNotificationRequested(); callsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_LdCom_TriggerTransmit_0003 Traceabilitythis function is given by architectural requirments: ID_ArchiteckturalElement and satisfied following DOORS Requirements or Design Decision: Satisfies requirementSWR_ICAS1_GW_18357; SWR_ICAS1_GW_3829. This function is called when an I-PDU shall be transmitted.This function is called when an I-PDU shall be transmitted. reentrant No thread safe Yes Std_ReturnType TxPduId ID of the I-PDU that is requested to be transmitted. PduInfoPtr Pointer to transmit buffer of L-PDU.
References LdComTriggerTransmitInitialnotificationList, LdComTriggerTransmitInitialnotificationType::fun_ptr.
Referenced by TEST_LdCom_TriggerTransmit_ACC, TEST_LdCom_TriggerTransmit_Airbag, TEST_LdCom_TriggerTransmit_AWV, TEST_LdCom_TriggerTransmit_CarBody, TEST_LdCom_TriggerTransmit_CentralLocking, TEST_LdCom_TriggerTransmit_ChargingManagmentCore, TEST_LdCom_TriggerTransmit_Chassis, TEST_LdCom_TriggerTransmit_ClampControl, TEST_LdCom_TriggerTransmit_ClimateControl, TEST_LdCom_TriggerTransmit_ContiUpdateCoordination, TEST_LdCom_TriggerTransmit_CruiseControl, TEST_LdCom_TriggerTransmit_Damper, TEST_LdCom_TriggerTransmit_DigitalKey, TEST_LdCom_TriggerTransmit_Distance, TEST_LdCom_TriggerTransmit_DrivePerformance, TEST_LdCom_TriggerTransmit_DrivingRange, TEST_LdCom_TriggerTransmit_EmergencyAssist, TEST_LdCom_TriggerTransmit_EnergySystem, TEST_LdCom_TriggerTransmit_ExteriorLight, TEST_LdCom_TriggerTransmit_ExteriorSound, TEST_LdCom_TriggerTransmit_FunctionEnabling, TEST_LdCom_TriggerTransmit_GNSS, TEST_LdCom_TriggerTransmit_HighVoltageCoordinator, TEST_LdCom_TriggerTransmit_Immobilizer, TEST_LdCom_TriggerTransmit_LaneAssist, TEST_LdCom_TriggerTransmit_OccupantPresence, TEST_LdCom_TriggerTransmit_Odometry, TEST_LdCom_TriggerTransmit_ParkingBrake, TEST_LdCom_TriggerTransmit_PersonalizationSystem, TEST_LdCom_TriggerTransmit_Powertrain, TEST_LdCom_TriggerTransmit_PreCrash, TEST_LdCom_TriggerTransmit_SafetyBeltState, TEST_LdCom_TriggerTransmit_SteeringAssist, TEST_LdCom_TriggerTransmit_TravelAssist, TEST_LdCom_TriggerTransmit_VehicleBasicData, TEST_LdCom_TriggerTransmit_VisualOdometry.