serializing_util.h
SOMEIP_HEADER_SIZE
BUFFER_SIZE
SOMEIP_PROTOCOL_VERSION
SOMEIP_INTERFACE_VERSION
PduIdType PduToTransmit
PduInfoType ToBeSentBySoAd
uint8 NotifArray_core0[8u+ 1476u][8u+1476u]
void ProxySerializer_SwapFromUint16(uint16 val, uint8 buffer[], uint32 *pos)
Convert the Uint16 data into Uint8 buffer.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. val Uint16 input data buffer Uint8 output buffer pos The last position of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapFromUint16_0001 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapFromUint16_0001.
void ProxySerializer_SwapFromUint64(uint64 val, uint8 buffer[], uint32 *pos)
Convert the Uint64 data into Uint8 buffer.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. val Uint64 input data buffer Uint8 output buffer pos The last position of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapFromUint64_0004 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapFromUint64_0004.
void ProxySerializer_SwapFromUint32(uint32 val, uint8 buffer[], uint32 *pos)
Convert the Uint32 data into Uint8 buffer.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. val Uint32 input data buffer Uint8 output buffer pos The last position of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapFromUint32_0002 TraceabilityTBD
Referenced by get_sd_header, TEST_ProxySerializer_SwapFromUint32_0002.
uint16 ProxySerializer_SwapToUint16(const uint8 buffer[], uint32 *pos)
Convert the Uint8 buffer into Uint16.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. buffer Uint8 buffer pos The last position of the buffer Uint16 data GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapToUint16_0007 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapToUint16_0007.
uint32 ProxySerializer_SwapToUint32(const uint8 buffer[], uint32 *pos)
Convert the Uint8 buffer into Uint32.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. buffer Uint8 buffer pos The last position of the buffer Uint32 data GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapToUint32_0008 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapToUint32_0008.
sint32 ProxySerializer_SwapToint32(const uint8 buffer[], uint32 *pos)
Convert the Uint8 buffer into sint32.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. buffer Uint8 buffer pos The last position of the buffer sint32 data GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapToint32_0009 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapToint32_0009.
uint64 ProxySerializer_SwapToUint64(const uint8 buffer[], uint32 *pos)
Convert the Uint8 buffer into uint64.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. buffer Uint8 buffer pos The last position of the buffer uint64 data GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapToUint64_0010 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapToUint64_0010.
void ProxySerializer_SwapFromFloat32(float32 val, uint8 buffer[], uint32 *pos)
Convert the Float32 data into Uint8 buffer.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. val Float32 input data buffer Uint8 output buffer pos The last position of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapFromFloat32_0005 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapFromFloat32_0005.
void ProxySerializer_SwapFromFloat64(float64 val, uint8 buffer[], uint32 *pos)
Convert the Float64 data into Uint8 buffer.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. val Float64 input data buffer Uint8 output buffer pos The last position of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapFromFloat64_0006 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapFromFloat64_0006.
float32 ProxySerializer_SwapToFloat32(const uint8 buffer[], uint32 *pos)
Convert the Uint8 buffer into float32.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. buffer Uint8 buffer pos The last position of the buffer float32 data GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapToFloat32_0011 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapToFloat32_0011.
float64 ProxySerializer_SwapToFloat64(const uint8 buffer[], uint32 *pos)
Convert the Uint8 buffer into float64.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. buffer Uint8 buffer pos The last position of the buffer float64 data GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapToFloat64_0012 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapToFloat64_0012.
void ProxySerializer_SwapFromint32(sint32 val, uint8 buffer[], uint32 *pos)
Convert the sint32 data into Uint8 buffer.
Get the SOMEIP payload for an eventgroup. Request SOME/IP message transmission. val sint32 input data buffer Uint8 output buffer pos The last position of the buffer None GlobalsNone Input->Output-CorrelationNone Call Sequencecallsequence Test MethodThe following function can be verified with following TEST: SWATT test: TEST_ProxySerializer_SwapFromint32_0003 TraceabilityTBD
Referenced by TEST_ProxySerializer_SwapFromint32_0003.